require({cache:{
'Sage/Utility/File/nls/xh/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/xh/FallbackFilePicker',{});
},
'Sage/Utility/File/nls/xh-za/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/xh-za/FallbackFilePicker',{});
},
'Sage/UI/nls/xh/Boolean':function(){
define('Sage/UI/nls/xh/Boolean',{});
},
'Sage/UI/nls/xh-za/Boolean':function(){
define('Sage/UI/nls/xh-za/Boolean',{});
},
'Sage/Services/nls/xh/ActivityService':function(){
define('Sage/Services/nls/xh/ActivityService',{});
},
'Sage/Services/nls/xh-za/ActivityService':function(){
define('Sage/Services/nls/xh-za/ActivityService',{});
},
'Sage/UI/Controls/nls/xh/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/xh/CopyToClipboard',{});
},
'Sage/UI/Controls/nls/xh-za/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/xh-za/CopyToClipboard',{});
},
'Sage/Utility/nls/xh/Activity':function(){
define('Sage/Utility/nls/xh/Activity',{});
},
'Sage/Utility/nls/xh-za/Activity':function(){
define('Sage/Utility/nls/xh-za/Activity',{});
},
'Sage/QuickForms/Design/nls/xh/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/xh/DesignPanel',{});
},
'Sage/QuickForms/Design/nls/xh-za/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/xh-za/DesignPanel',{});
},
'Sage/UI/nls/xh/TimelessActivitiesPane':function(){
define('Sage/UI/nls/xh/TimelessActivitiesPane',{});
},
'Sage/UI/nls/xh-za/TimelessActivitiesPane':function(){
define('Sage/UI/nls/xh-za/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/xh/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/xh/ActivityEditor',{});
},
'Sage/MainView/ActivityMgr/nls/xh-za/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/xh-za/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/xh/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/xh/ContactUserAssociationEditor',{});
},
'Sage/TaskPane/User/nls/xh-za/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/xh-za/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/xh/ActivityManager':function(){
define('Sage/MainView/nls/xh/ActivityManager',{});
},
'Sage/MainView/nls/xh-za/ActivityManager':function(){
define('Sage/MainView/nls/xh-za/ActivityManager',{});
},
'Sage/Services/nls/xh/JobService':function(){
define('Sage/Services/nls/xh/JobService',{});
},
'Sage/Services/nls/xh-za/JobService':function(){
define('Sage/Services/nls/xh-za/JobService',{});
},
'Sage/QuickForms/Design/nls/xh/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/xh-za/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh-za/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/_PropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/xh-za/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh-za/_PropertyEditor',{});
},
'Sage/Services/nls/xh/ActivityActionProcessor':function(){
define('Sage/Services/nls/xh/ActivityActionProcessor',{});
},
'Sage/Services/nls/xh-za/ActivityActionProcessor':function(){
define('Sage/Services/nls/xh-za/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/TextBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/xh-za/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh-za/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/xh/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/xh/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/nls/xh-za/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/xh-za/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/templates/nls/xh/UserActivityDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/xh/UserActivityDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/xh-za/UserActivityDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/xh-za/UserActivityDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/xh/ConfirmationDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/xh/ConfirmationDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/xh-za/ConfirmationDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/xh-za/ConfirmationDetailSummary',{});
},
'Sage/Utility/File/nls/xh/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/xh/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/xh-za/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/xh-za/DefaultDropHandler',{});
},
'Sage/UI/nls/xh/TransferBoxWidget':function(){
define('Sage/UI/nls/xh/TransferBoxWidget',{});
},
'Sage/UI/nls/xh-za/TransferBoxWidget':function(){
define('Sage/UI/nls/xh-za/TransferBoxWidget',{});
},
'Sage/Utility/File/nls/xh/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/xh/AttachmentPropertiesEditForm',{});
},
'Sage/Utility/File/nls/xh-za/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/xh-za/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/xh/AlarmPane':function(){
define('Sage/UI/Alarms/nls/xh/AlarmPane',{});
},
'Sage/UI/Alarms/nls/xh-za/AlarmPane':function(){
define('Sage/UI/Alarms/nls/xh-za/AlarmPane',{});
},
'Sage/TaskPane/nls/xh/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/xh/LiteratureManagementTasks',{});
},
'Sage/TaskPane/nls/xh-za/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/xh-za/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/xh/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/xh/DashboardWidget',{});
},
'Sage/UI/Dashboard/nls/xh-za/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/xh-za/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/NumericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/xh-za/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh-za/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/xh/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/xh/CustomerPaymentsRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/xh-za/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/xh-za/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/xh/FilterPanel':function(){
define('Sage/UI/Filters/nls/xh/FilterPanel',{});
},
'Sage/UI/Filters/nls/xh-za/FilterPanel':function(){
define('Sage/UI/Filters/nls/xh-za/FilterPanel',{});
},
'Sage/TaskPane/nls/xh/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/xh/_BaseTaskPaneTasklet',{});
},
'Sage/TaskPane/nls/xh-za/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/xh-za/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/xh/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/xh/ReportManagerFormatter',{});
},
'Sage/MainView/ReportMgr/nls/xh-za/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/xh-za/ReportManagerFormatter',{});
},
'Sage/UI/nls/xh/OwnerType':function(){
define('Sage/UI/nls/xh/OwnerType',{});
},
'Sage/UI/nls/xh-za/OwnerType':function(){
define('Sage/UI/nls/xh-za/OwnerType',{});
},
'Sage/MainView/JobMgr/templates/nls/xh/JobDefinitionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/xh/JobDefinitionsListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/xh-za/JobDefinitionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/xh-za/JobDefinitionsListSummary',{});
},
'Sage/TaskPane/nls/xh/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/xh/LeadTasksTasklet',{});
},
'Sage/TaskPane/nls/xh-za/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/xh-za/LeadTasksTasklet',{});
},
'Sage/MainView/ReportMgr/templates/nls/xh/ReportDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/xh/ReportDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/xh-za/ReportDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/xh-za/ReportDetailSummary',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/xh/_ParameterEditorBase':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/xh/_ParameterEditorBase',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/xh-za/_ParameterEditorBase':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/xh-za/_ParameterEditorBase',{});
},
'Sage/MailMerge/nls/xh/Service':function(){
define('Sage/MailMerge/nls/xh/Service',{});
},
'Sage/MailMerge/nls/xh-za/Service':function(){
define('Sage/MailMerge/nls/xh-za/Service',{});
},
'Sage/MainView/ActivityMgr/templates/nls/xh/ConfirmationListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/xh/ConfirmationListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/xh-za/ConfirmationListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/xh-za/ConfirmationListSummary',{});
},
'Sage/MainView/ActivityMgr/nls/xh/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/xh/SnoozeOptions',{});
},
'Sage/MainView/ActivityMgr/nls/xh-za/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/xh-za/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/xh-za/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh-za/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/xh-za/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh-za/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/xh/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/xh/InvoiceRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/xh-za/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/xh-za/InvoiceRTDV',{});
},
'Sage/UI/nls/xh/SDataLookup':function(){
define('Sage/UI/nls/xh/SDataLookup',{});
},
'Sage/UI/nls/xh-za/SDataLookup':function(){
define('Sage/UI/nls/xh-za/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/xh/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/xh/RowDesigner',{});
},
'Sage/QuickForms/Design/nls/xh-za/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/xh-za/RowDesigner',{});
},
'Sage/Groups/nls/xh/GroupLookup':function(){
define('Sage/Groups/nls/xh/GroupLookup',{});
},
'Sage/Groups/nls/xh-za/GroupLookup':function(){
define('Sage/Groups/nls/xh-za/GroupLookup',{});
},
'Sage/TaskPane/nls/xh/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/xh/OpportunityTasksTasklet',{});
},
'Sage/TaskPane/nls/xh-za/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/xh-za/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/xh/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/xh/CheckBoxFilter',{});
},
'Sage/UI/Filters/nls/xh-za/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/xh-za/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/xh/LibraryDocument':function(){
define('Sage/Utility/File/nls/xh/LibraryDocument',{});
},
'Sage/Utility/File/nls/xh-za/LibraryDocument':function(){
define('Sage/Utility/File/nls/xh-za/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/xh/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/xh/SpeedSearchLookup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/xh-za/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/xh-za/SpeedSearchLookup',{});
},
'Sage/UI/nls/xh/ConditionManager':function(){
define('Sage/UI/nls/xh/ConditionManager',{});
},
'Sage/UI/nls/xh-za/ConditionManager':function(){
define('Sage/UI/nls/xh-za/ConditionManager',{});
},
'Sage/MainView/JobMgr/templates/nls/xh/SchedulesListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/xh/SchedulesListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/xh-za/SchedulesListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/xh-za/SchedulesListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/xh/UserActivityListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/xh/UserActivityListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/xh-za/UserActivityListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/xh-za/UserActivityListSummary',{});
},
'Sage/UI/Dashboard/nls/xh/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/xh/WidgetDefinition',{});
},
'Sage/UI/Dashboard/nls/xh-za/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/xh-za/WidgetDefinition',{});
},
'Sage/MainView/ActivityMgr/templates/nls/xh/AllOpenListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/xh/AllOpenListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/xh-za/AllOpenListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/xh-za/AllOpenListSummary',{});
},
'Sage/UI/nls/xh/SearchConditionWidget':function(){
define('Sage/UI/nls/xh/SearchConditionWidget',{});
},
'Sage/UI/nls/xh-za/SearchConditionWidget':function(){
define('Sage/UI/nls/xh-za/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/xh-za/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh-za/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/xh/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/xh/JobManagerActions',{});
},
'Sage/MainView/JobMgr/nls/xh-za/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/xh-za/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/xh/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/xh/ContactLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/xh-za/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/xh-za/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/xh/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/xh/DataSourcePanel',{});
},
'Sage/QuickForms/Design/nls/xh-za/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/xh-za/DataSourcePanel',{});
},
'Sage/MainView/ReportMgr/templates/nls/xh/SchedulesListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/xh/SchedulesListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/xh-za/SchedulesListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/xh-za/SchedulesListSummary',{});
},
'Sage/Library/nls/xh/Manager':function(){
define('Sage/Library/nls/xh/Manager',{});
},
'Sage/Library/nls/xh-za/Manager':function(){
define('Sage/Library/nls/xh-za/Manager',{});
},
'Sage/UI/nls/xh/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/xh/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/nls/xh-za/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/xh-za/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/xh/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/xh/NonVisibleControlContainer',{});
},
'Sage/QuickForms/Design/nls/xh-za/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/xh-za/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/xh/Name':function(){
define('Sage/UI/Controls/nls/xh/Name',{});
},
'Sage/UI/Controls/nls/xh-za/Name':function(){
define('Sage/UI/Controls/nls/xh-za/Name',{});
},
'Sage/MainView/JobMgr/nls/xh/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/xh/ExecutionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/xh-za/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/xh-za/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/xh/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh/PhoneControlDesigner',{});
},
'Sage/QuickForms/Design/nls/xh-za/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh-za/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/xh/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/xh/UpdateLeads',{});
},
'Sage/MainView/Lead/nls/xh-za/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/xh-za/UpdateLeads',{});
},
'Sage/Library/nls/xh/FileHandler':function(){
define('Sage/Library/nls/xh/FileHandler',{});
},
'Sage/Library/nls/xh-za/FileHandler':function(){
define('Sage/Library/nls/xh-za/FileHandler',{});
},
'Sage/UI/nls/xh/ListPanel':function(){
define('Sage/UI/nls/xh/ListPanel',{});
},
'Sage/UI/nls/xh-za/ListPanel':function(){
define('Sage/UI/nls/xh-za/ListPanel',{});
},
'Sage/Utility/nls/xh/Sql':function(){
define('Sage/Utility/nls/xh/Sql',{});
},
'Sage/Utility/nls/xh-za/Sql':function(){
define('Sage/Utility/nls/xh-za/Sql',{});
},
'Sage/UI/Filters/nls/xh/EditFilters':function(){
define('Sage/UI/Filters/nls/xh/EditFilters',{});
},
'Sage/UI/Filters/nls/xh-za/EditFilters':function(){
define('Sage/UI/Filters/nls/xh-za/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/FormUsagesPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/xh-za/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh-za/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/xh/DurationSelect':function(){
define('Sage/UI/Controls/nls/xh/DurationSelect',{});
},
'Sage/UI/Controls/nls/xh-za/DurationSelect':function(){
define('Sage/UI/Controls/nls/xh-za/DurationSelect',{});
},
'Sage/UI/Alarms/nls/xh/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/xh/AlarmCountDown',{});
},
'Sage/UI/Alarms/nls/xh-za/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/xh-za/AlarmCountDown',{});
},
'Sage/UI/nls/xh/AttachmentList':function(){
define('Sage/UI/nls/xh/AttachmentList',{});
},
'Sage/UI/nls/xh-za/AttachmentList':function(){
define('Sage/UI/nls/xh-za/AttachmentList',{});
},
'Sage/MailMerge/nls/xh/Lookup':function(){
define('Sage/MailMerge/nls/xh/Lookup',{});
},
'Sage/MailMerge/nls/xh-za/Lookup':function(){
define('Sage/MailMerge/nls/xh-za/Lookup',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/xh-za/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh-za/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/xh/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/xh/RunJobDialog',{});
},
'Sage/MainView/JobMgr/nls/xh-za/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/xh-za/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/xh/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/xh-za/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh-za/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/xh/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/xh-za/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh-za/EditableGridControlDesigner',{});
},
'Sage/MainView/Options/nls/xh/OptionsDialog':function(){
define('Sage/MainView/Options/nls/xh/OptionsDialog',{});
},
'Sage/MainView/Options/nls/xh-za/OptionsDialog':function(){
define('Sage/MainView/Options/nls/xh-za/OptionsDialog',{});
},
'Sage/QuickForms/Design/nls/xh/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh/HiddenControlDesigner',{});
},
'Sage/QuickForms/Design/nls/xh-za/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh-za/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/xh/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/xh/DashboardWidgetCell',{});
},
'Sage/UI/Dashboard/nls/xh-za/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/xh-za/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/UserBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/xh-za/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh-za/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/xh/Dialogs':function(){
define('Sage/UI/nls/xh/Dialogs',{});
},
'Sage/UI/nls/xh-za/Dialogs':function(){
define('Sage/UI/nls/xh-za/Dialogs',{});
},
'Sage/MainView/IntegrationContract/nls/xh/SyncResultsHistory':function(){
define('Sage/MainView/IntegrationContract/nls/xh/SyncResultsHistory',{});
},
'Sage/MainView/IntegrationContract/nls/xh-za/SyncResultsHistory':function(){
define('Sage/MainView/IntegrationContract/nls/xh-za/SyncResultsHistory',{});
},
'Sage/TaskPane/nls/xh/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/xh/SecuredActionTasklet',{});
},
'Sage/TaskPane/nls/xh-za/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/xh-za/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/xh/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/xh/DashboardTabController',{});
},
'Sage/UI/Dashboard/nls/xh-za/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/xh-za/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/xh/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/xh/SalesOrderRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/xh-za/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/xh-za/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/xh/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh/UserControlDesigner',{});
},
'Sage/QuickForms/Design/nls/xh-za/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh-za/UserControlDesigner',{});
},
'Sage/Groups/nls/xh/GroupNavigator':function(){
define('Sage/Groups/nls/xh/GroupNavigator',{});
},
'Sage/Groups/nls/xh-za/GroupNavigator':function(){
define('Sage/Groups/nls/xh-za/GroupNavigator',{});
},
'Sage/Utility/File/nls/xh/AddURLAttachment':function(){
define('Sage/Utility/File/nls/xh/AddURLAttachment',{});
},
'Sage/Utility/File/nls/xh-za/AddURLAttachment':function(){
define('Sage/Utility/File/nls/xh-za/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/xh/EditFilterItems':function(){
define('Sage/UI/Filters/nls/xh/EditFilterItems',{});
},
'Sage/UI/Filters/nls/xh-za/EditFilterItems':function(){
define('Sage/UI/Filters/nls/xh-za/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/xh/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/xh/CrystalReportsFormatter',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/xh-za/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/xh-za/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/xh/DragDropWatcher':function(){
define('Sage/Utility/File/nls/xh/DragDropWatcher',{});
},
'Sage/Utility/File/nls/xh-za/DragDropWatcher':function(){
define('Sage/Utility/File/nls/xh-za/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/xh/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/xh/DesignSurface',{});
},
'Sage/QuickForms/Design/nls/xh-za/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/xh-za/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/xh/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/xh/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/xh-za/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/xh-za/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/FormAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/xh-za/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh-za/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/xh/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/xh/EventListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/xh-za/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/xh-za/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/xh/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/xh/AllOpenListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/xh-za/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/xh-za/AllOpenListPanelConfig',{});
},
'Sage/MainView/nls/xh/FormManager':function(){
define('Sage/MainView/nls/xh/FormManager',{});
},
'Sage/MainView/nls/xh-za/FormManager':function(){
define('Sage/MainView/nls/xh-za/FormManager',{});
},
'Sage/UI/nls/xh/ActivityScheduler':function(){
define('Sage/UI/nls/xh/ActivityScheduler',{});
},
'Sage/UI/nls/xh-za/ActivityScheduler':function(){
define('Sage/UI/nls/xh-za/ActivityScheduler',{});
},
'Sage/MainView/nls/xh/SecurityManager':function(){
define('Sage/MainView/nls/xh/SecurityManager',{});
},
'Sage/MainView/nls/xh-za/SecurityManager':function(){
define('Sage/MainView/nls/xh-za/SecurityManager',{});
},
'Sage/TaskPane/nls/xh/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/xh/ActivityTaskConfigurationProvider',{});
},
'Sage/TaskPane/nls/xh-za/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/xh-za/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/xh/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/xh/EntityInfoToolTip',{});
},
'Sage/UI/Controls/nls/xh-za/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/xh-za/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/xh/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/xh/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/xh-za/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/xh-za/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/templates/nls/xh/AllOpenDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/xh/AllOpenDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/xh-za/AllOpenDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/xh-za/AllOpenDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/xh/ReportsListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/xh/ReportsListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/xh-za/ReportsListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/xh-za/ReportsListSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/xh/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/xh/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/Common/nls/xh-za/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/xh-za/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/templates/nls/xh/ScheduleDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/xh/ScheduleDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/xh-za/ScheduleDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/xh-za/ScheduleDetailSummary',{});
},
'Sage/MainView/Opportunity/nls/xh/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/xh/UpdateOpportunities',{});
},
'Sage/MainView/Opportunity/nls/xh-za/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/xh-za/UpdateOpportunities',{});
},
'Sage/UI/nls/xh/EditCalendarUsers':function(){
define('Sage/UI/nls/xh/EditCalendarUsers',{});
},
'Sage/UI/nls/xh-za/EditCalendarUsers':function(){
define('Sage/UI/nls/xh-za/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/xh/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/xh/CrystalReportParametersDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/xh-za/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/xh-za/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/xh/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh/DateTimePickerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/xh-za/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh-za/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/xh/HelpMenu':function(){
define('Sage/UI/Controls/nls/xh/HelpMenu',{});
},
'Sage/UI/Controls/nls/xh-za/HelpMenu':function(){
define('Sage/UI/Controls/nls/xh-za/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/LayoutPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/xh-za/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh-za/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/xh/UserTasklet':function(){
define('Sage/TaskPane/nls/xh/UserTasklet',{});
},
'Sage/TaskPane/nls/xh-za/UserTasklet':function(){
define('Sage/TaskPane/nls/xh-za/UserTasklet',{});
},
'Sage/UI/Alarms/nls/xh/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/xh/ActivityAlarm',{});
},
'Sage/UI/Alarms/nls/xh-za/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/xh-za/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/xh/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/xh/OpportunityStatistics',{});
},
'Sage/MainView/Opportunity/nls/xh-za/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/xh-za/OpportunityStatistics',{});
},
'Sage/TaskPane/nls/xh/GroupListTasklet':function(){
define('Sage/TaskPane/nls/xh/GroupListTasklet',{});
},
'Sage/TaskPane/nls/xh-za/GroupListTasklet':function(){
define('Sage/TaskPane/nls/xh-za/GroupListTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/xh/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/xh/CrystalReportConditionEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/xh-za/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/xh-za/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/xh/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/xh/AdvancedSearchOptions',{});
},
'Sage/MainView/IntegrationContract/nls/xh-za/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/xh-za/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/xh/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/xh/ColumnDesigner',{});
},
'Sage/QuickForms/Design/nls/xh-za/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/xh-za/ColumnDesigner',{});
},
'Sage/MainView/JobMgr/templates/nls/xh/JobDefinitionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/xh/JobDefinitionDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/xh-za/JobDefinitionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/xh-za/JobDefinitionDetailSummary',{});
},
'Sage/UI/nls/xh/SearchMenuItem':function(){
define('Sage/UI/nls/xh/SearchMenuItem',{});
},
'Sage/UI/nls/xh-za/SearchMenuItem':function(){
define('Sage/UI/nls/xh-za/SearchMenuItem',{});
},
'Sage/Library/nls/xh/DocumentProperties':function(){
define('Sage/Library/nls/xh/DocumentProperties',{});
},
'Sage/Library/nls/xh-za/DocumentProperties':function(){
define('Sage/Library/nls/xh-za/DocumentProperties',{});
},
'Sage/UI/nls/xh/NotesHistoryList':function(){
define('Sage/UI/nls/xh/NotesHistoryList',{});
},
'Sage/UI/nls/xh-za/NotesHistoryList':function(){
define('Sage/UI/nls/xh-za/NotesHistoryList',{});
},
'Sage/Utility/nls/xh/File':function(){
define('Sage/Utility/nls/xh/File',{});
},
'Sage/Utility/nls/xh-za/File':function(){
define('Sage/Utility/nls/xh-za/File',{});
},
'Sage/MainView/ReportMgr/nls/xh/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/xh/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/xh-za/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/xh-za/HistoryListPanelConfig',{});
},
'Sage/MainView/JobMgr/templates/nls/xh/ScheduleDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/xh/ScheduleDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/xh-za/ScheduleDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/xh-za/ScheduleDetailSummary',{});
},
'Sage/QuickForms/Design/nls/xh/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh/UrlControlDesigner',{});
},
'Sage/QuickForms/Design/nls/xh-za/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh-za/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/xh/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/xh/ContactTasksTasklet',{});
},
'Sage/TaskPane/nls/xh-za/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/xh-za/ContactTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/templates/nls/xh/EventSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/xh/EventSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/xh-za/EventSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/xh-za/EventSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/xh/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/xh/_WizardDialogBase',{});
},
'Sage/MainView/ReportMgr/Common/nls/xh-za/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/xh-za/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/xh/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/xh/SchedulesListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/xh-za/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/xh-za/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/xh/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/xh/GoogleDocPicker',{});
},
'Sage/Utility/File/nls/xh-za/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/xh-za/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/xh/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh/ComboBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/xh-za/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh-za/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/xh/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/xh/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/xh-za/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/xh-za/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/xh/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/xh/HistoryEditor',{});
},
'Sage/MainView/ActivityMgr/nls/xh-za/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/xh-za/HistoryEditor',{});
},
'Sage/Groups/nls/xh/GroupManager':function(){
define('Sage/Groups/nls/xh/GroupManager',{});
},
'Sage/Groups/nls/xh-za/GroupManager':function(){
define('Sage/Groups/nls/xh-za/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/xh-za/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh-za/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/ComboBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/xh-za/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh-za/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/xh/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/xh/ReportsListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/xh-za/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/xh-za/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/xh/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/xh/JobNotificationButton',{});
},
'Sage/UI/Alarms/nls/xh-za/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/xh-za/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/xh/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/xh/CrystalReportWizardController',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/xh-za/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/xh-za/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/xh/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/xh/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/xh-za/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/xh-za/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/xh/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/xh/RecurringEditor',{});
},
'Sage/MainView/ActivityMgr/nls/xh-za/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/xh-za/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/xh/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/xh/CrystalReportsUtility',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/xh-za/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/xh-za/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/xh-za/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh-za/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/xh/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/xh/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/xh-za/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/xh-za/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/xh/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/xh-za/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh-za/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/xh/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/xh-za/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh-za/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/xh/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/nls/xh-za/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh-za/PickListControlDesigner',{});
},
'Sage/MainView/ActivityMgr/templates/nls/xh/LitRequestSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/xh/LitRequestSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/xh-za/LitRequestSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/xh-za/LitRequestSummary',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/xh-za/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh-za/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/xh/FolderHandler':function(){
define('Sage/Library/nls/xh/FolderHandler',{});
},
'Sage/Library/nls/xh-za/FolderHandler':function(){
define('Sage/Library/nls/xh-za/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/xh-za/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh-za/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/xh/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/xh/ContactSearchForDuplicates',{});
},
'Sage/MainView/Contact/nls/xh-za/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/xh-za/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/DateTimePickerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/xh-za/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh-za/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/xh/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/xh/AccountingTasksTasklet',{});
},
'Sage/TaskPane/nls/xh-za/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/xh-za/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/xh-za/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh-za/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/CurrencyBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/xh-za/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh-za/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/xh/EditableGrid':function(){
define('Sage/UI/nls/xh/EditableGrid',{});
},
'Sage/UI/nls/xh-za/EditableGrid':function(){
define('Sage/UI/nls/xh-za/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/xh/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/xh/SalesQuoteRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/xh-za/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/xh-za/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/xh/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/xh/SecurityProfile',{});
},
'Sage/MainView/SecurityMgr/nls/xh-za/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/xh-za/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/xh/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/xh/ReportWizardController',{});
},
'Sage/MainView/ReportMgr/nls/xh-za/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/xh-za/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/UserAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/xh-za/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh-za/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/xh/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/xh/ReportManagerUtility',{});
},
'Sage/MainView/ReportMgr/nls/xh-za/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/xh-za/ReportManagerUtility',{});
},
'Sage/UI/nls/xh/SpeedSearch':function(){
define('Sage/UI/nls/xh/SpeedSearch',{});
},
'Sage/UI/nls/xh-za/SpeedSearch':function(){
define('Sage/UI/nls/xh-za/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/CurrencyAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/xh-za/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh-za/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/xh/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/xh/ReportManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/xh-za/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/xh-za/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/xh/SLXPreviewGrid':function(){
define('Sage/UI/nls/xh/SLXPreviewGrid',{});
},
'Sage/UI/nls/xh-za/SLXPreviewGrid':function(){
define('Sage/UI/nls/xh-za/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/xh/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/xh/UnconfirmedPane',{});
},
'Sage/UI/Alarms/nls/xh-za/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/xh-za/UnconfirmedPane',{});
},
'Sage/Utility/nls/xh/Utility':function(){
define('Sage/Utility/nls/xh/Utility',{});
},
'Sage/Utility/nls/xh-za/Utility':function(){
define('Sage/Utility/nls/xh-za/Utility',{});
},
'Sage/QuickForms/Design/nls/xh/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh/ControlDesigner',{});
},
'Sage/QuickForms/Design/nls/xh-za/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh-za/ControlDesigner',{});
},
'Sage/UI/Controls/nls/xh/Address':function(){
define('Sage/UI/Controls/nls/xh/Address',{});
},
'Sage/UI/Controls/nls/xh-za/Address':function(){
define('Sage/UI/Controls/nls/xh-za/Address',{});
},
'Sage/MainView/JobMgr/nls/xh/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/xh/JobManagerGroupContextService',{});
},
'Sage/MainView/JobMgr/nls/xh-za/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/xh-za/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/xh/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/xh/BaseListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/xh-za/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/xh-za/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/xh/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh/OwnerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/xh-za/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh-za/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/xh/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/xh/JobManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/xh-za/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/xh-za/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/xh/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/xh/ActivityEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/xh-za/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/xh-za/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/xh/UserType':function(){
define('Sage/UI/nls/xh/UserType',{});
},
'Sage/UI/nls/xh-za/UserType':function(){
define('Sage/UI/nls/xh-za/UserType',{});
},
'Sage/MainView/ReportMgr/templates/nls/xh/HistoryDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/xh/HistoryDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/xh-za/HistoryDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/xh-za/HistoryDetailSummary',{});
},
'Sage/QuickForms/Design/nls/xh/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/xh/FormDesigner',{});
},
'Sage/QuickForms/Design/nls/xh-za/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/xh-za/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/xh/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/xh/ActivityCalendar',{});
},
'Sage/MainView/ActivityMgr/nls/xh-za/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/xh-za/ActivityCalendar',{});
},
'Sage/Utility/nls/xh/Jobs':function(){
define('Sage/Utility/nls/xh/Jobs',{});
},
'Sage/Utility/nls/xh-za/Jobs':function(){
define('Sage/Utility/nls/xh-za/Jobs',{});
},
'Sage/UI/Controls/nls/xh/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/xh/_DialogHelpIconMixin',{});
},
'Sage/UI/Controls/nls/xh-za/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/xh-za/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/PickListAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/xh-za/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh-za/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/xh/ActivityList':function(){
define('Sage/UI/nls/xh/ActivityList',{});
},
'Sage/UI/nls/xh-za/ActivityList':function(){
define('Sage/UI/nls/xh-za/ActivityList',{});
},
'Sage/UI/Alarms/nls/xh/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/xh/JobNotificationPopup',{});
},
'Sage/UI/Alarms/nls/xh-za/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/xh-za/JobNotificationPopup',{});
},
'Sage/MainView/JobMgr/templates/nls/xh/ExecutionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/xh/ExecutionsListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/xh-za/ExecutionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/xh-za/ExecutionsListSummary',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/xh/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/xh/LeadLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/xh-za/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/xh-za/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/xh/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/xh/SchedulesListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/xh-za/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/xh-za/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/GenericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/xh-za/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh-za/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/xh/CalendarUsersListPane':function(){
define('Sage/UI/nls/xh/CalendarUsersListPane',{});
},
'Sage/UI/nls/xh-za/CalendarUsersListPane':function(){
define('Sage/UI/nls/xh-za/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/xh-za/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh-za/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/ColumnBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/xh-za/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh-za/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/templates/nls/xh/ExecutionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/xh/ExecutionDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/xh-za/ExecutionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/xh-za/ExecutionDetailSummary',{});
},
'Sage/MainView/ReportMgr/nls/xh/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/xh/ReportManagerGroupContextService',{});
},
'Sage/MainView/ReportMgr/nls/xh-za/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/xh-za/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/xh/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/xh/MatchingOptionsConfig',{});
},
'Sage/MainView/IntegrationContract/nls/xh-za/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/xh-za/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/FormBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/xh-za/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh-za/FormBasicPropertyEditor',{});
},
'Sage/UI/Alarms/nls/xh/AlarmButton':function(){
define('Sage/UI/Alarms/nls/xh/AlarmButton',{});
},
'Sage/UI/Alarms/nls/xh-za/AlarmButton':function(){
define('Sage/UI/Alarms/nls/xh-za/AlarmButton',{});
},
'Sage/MainView/ActivityMgr/nls/xh/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/xh/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/MainView/ActivityMgr/nls/xh-za/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/xh-za/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/xh/Attachment':function(){
define('Sage/Utility/File/nls/xh/Attachment',{});
},
'Sage/Utility/File/nls/xh-za/Attachment':function(){
define('Sage/Utility/File/nls/xh-za/Attachment',{});
},
'Sage/QuickForms/Design/nls/xh/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/xh-za/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh-za/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/xh/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/xh/PropertyEditorContainer',{});
},
'Sage/QuickForms/Design/nls/xh-za/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/xh-za/PropertyEditorContainer',{});
},
'Sage/Services/nls/xh/ReportingService':function(){
define('Sage/Services/nls/xh/ReportingService',{});
},
'Sage/Services/nls/xh-za/ReportingService':function(){
define('Sage/Services/nls/xh-za/ReportingService',{});
},
'Sage/MailMerge/nls/xh/Helper':function(){
define('Sage/MailMerge/nls/xh/Helper',{});
},
'Sage/MailMerge/nls/xh-za/Helper':function(){
define('Sage/MailMerge/nls/xh-za/Helper',{});
},
'Sage/UI/Dashboard/nls/xh/Dashboard':function(){
define('Sage/UI/Dashboard/nls/xh/Dashboard',{});
},
'Sage/UI/Dashboard/nls/xh-za/Dashboard':function(){
define('Sage/UI/Dashboard/nls/xh-za/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/xh/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/xh/ActivityListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/xh-za/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/xh-za/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/xh/PickList':function(){
define('Sage/UI/Controls/nls/xh/PickList',{});
},
'Sage/UI/Controls/nls/xh-za/PickList':function(){
define('Sage/UI/Controls/nls/xh-za/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/xh/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/xh/HistoryEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/xh-za/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/xh-za/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/xh/Email':function(){
define('Sage/Utility/nls/xh/Email',{});
},
'Sage/Utility/nls/xh-za/Email':function(){
define('Sage/Utility/nls/xh-za/Email',{});
},
'Sage/TaskPane/nls/xh/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/xh/SecurityManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/xh-za/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/xh-za/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/xh/TimeZoneItem':function(){
define('Sage/UI/nls/xh/TimeZoneItem',{});
},
'Sage/UI/nls/xh-za/TimeZoneItem':function(){
define('Sage/UI/nls/xh-za/TimeZoneItem',{});
},
'Sage/MainView/ReportMgr/templates/nls/xh/HistoryListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/xh/HistoryListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/xh-za/HistoryListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/xh-za/HistoryListSummary',{});
},
'Sage/UI/Columns/nls/xh/SlxEdit':function(){
define('Sage/UI/Columns/nls/xh/SlxEdit',{});
},
'Sage/UI/Columns/nls/xh-za/SlxEdit':function(){
define('Sage/UI/Columns/nls/xh-za/SlxEdit',{});
},
'Sage/Reporting/nls/xh/Enumerations':function(){
define('Sage/Reporting/nls/xh/Enumerations',{});
},
'Sage/Reporting/nls/xh-za/Enumerations':function(){
define('Sage/Reporting/nls/xh-za/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/xh-za/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh-za/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/xh/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/xh/CrystalReportConditionsDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/xh-za/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/xh-za/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/xh/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/xh/ActivityListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/xh-za/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/xh-za/ActivityListPanelConfig',{});
},
'Sage/UI/nls/xh/JobSchedulingWidget':function(){
define('Sage/UI/nls/xh/JobSchedulingWidget',{});
},
'Sage/UI/nls/xh-za/JobSchedulingWidget':function(){
define('Sage/UI/nls/xh-za/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/xh/LogOffButton':function(){
define('Sage/UI/Controls/nls/xh/LogOffButton',{});
},
'Sage/UI/Controls/nls/xh-za/LogOffButton':function(){
define('Sage/UI/Controls/nls/xh-za/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/TextBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/xh-za/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh-za/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/xh/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/xh/EditEventEditor',{});
},
'Sage/MainView/ActivityMgr/nls/xh-za/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/xh-za/EditEventEditor',{});
},
'Sage/MailMerge/nls/xh/Loader':function(){
define('Sage/MailMerge/nls/xh/Loader',{});
},
'Sage/MailMerge/nls/xh-za/Loader':function(){
define('Sage/MailMerge/nls/xh-za/Loader',{});
},
'Sage/UI/Controls/nls/xh/DateTimePicker':function(){
define('Sage/UI/Controls/nls/xh/DateTimePicker',{});
},
'Sage/UI/Controls/nls/xh-za/DateTimePicker':function(){
define('Sage/UI/Controls/nls/xh-za/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/xh/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/xh/ReportManagerActions',{});
},
'Sage/MainView/ReportMgr/nls/xh-za/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/xh-za/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/xh/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/xh/AlarmPopup',{});
},
'Sage/UI/Alarms/nls/xh-za/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/xh-za/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/xh/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/xh/ContactUserAssociationEditor',{});
},
'Sage/MainView/Contact/nls/xh-za/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/xh-za/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/xh-za/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh-za/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/xh/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/xh/BaseListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/xh-za/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/xh-za/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/xh/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/xh-za/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh-za/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/xh/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh/EmailControlDesigner',{});
},
'Sage/QuickForms/Design/nls/xh-za/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh-za/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/xh/Lookup':function(){
define('Sage/UI/Controls/nls/xh/Lookup',{});
},
'Sage/UI/Controls/nls/xh-za/Lookup':function(){
define('Sage/UI/Controls/nls/xh-za/Lookup',{});
},
'Sage/Utility/File/nls/xh/DescriptionsForm':function(){
define('Sage/Utility/File/nls/xh/DescriptionsForm',{});
},
'Sage/Utility/File/nls/xh-za/DescriptionsForm':function(){
define('Sage/Utility/File/nls/xh-za/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/NumericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/xh-za/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh-za/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/xh/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/xh/CommonTasksTasklet',{});
},
'Sage/TaskPane/nls/xh-za/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/xh-za/CommonTasksTasklet',{});
},
'Sage/Utility/nls/xh/Dashboard':function(){
define('Sage/Utility/nls/xh/Dashboard',{});
},
'Sage/Utility/nls/xh-za/Dashboard':function(){
define('Sage/Utility/nls/xh-za/Dashboard',{});
}}});
define("Sage/nls/Sage_xh-za", [], 1);
