require({cache:{
'Sage/Utility/File/nls/es/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/es/FallbackFilePicker',{});
},
'Sage/Utility/File/nls/es-do/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/es-do/FallbackFilePicker',{});
},
'Sage/UI/nls/es/Boolean':function(){
define('Sage/UI/nls/es/Boolean',{});
},
'Sage/UI/nls/es-do/Boolean':function(){
define('Sage/UI/nls/es-do/Boolean',{});
},
'Sage/Services/nls/es/ActivityService':function(){
define('Sage/Services/nls/es/ActivityService',{});
},
'Sage/Services/nls/es-do/ActivityService':function(){
define('Sage/Services/nls/es-do/ActivityService',{});
},
'Sage/UI/Controls/nls/es/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/es/CopyToClipboard',{});
},
'Sage/UI/Controls/nls/es-do/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/es-do/CopyToClipboard',{});
},
'Sage/Utility/nls/es/Activity':function(){
define('Sage/Utility/nls/es/Activity',{});
},
'Sage/Utility/nls/es-do/Activity':function(){
define('Sage/Utility/nls/es-do/Activity',{});
},
'Sage/QuickForms/Design/nls/es/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/es/DesignPanel',{});
},
'Sage/QuickForms/Design/nls/es-do/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/es-do/DesignPanel',{});
},
'Sage/UI/nls/es/TimelessActivitiesPane':function(){
define('Sage/UI/nls/es/TimelessActivitiesPane',{});
},
'Sage/UI/nls/es-do/TimelessActivitiesPane':function(){
define('Sage/UI/nls/es-do/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-do/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-do/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/es/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/es/ContactUserAssociationEditor',{});
},
'Sage/TaskPane/User/nls/es-do/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/es-do/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/es/ActivityManager':function(){
define('Sage/MainView/nls/es/ActivityManager',{});
},
'Sage/MainView/nls/es-do/ActivityManager':function(){
define('Sage/MainView/nls/es-do/ActivityManager',{});
},
'Sage/Services/nls/es/JobService':function(){
define('Sage/Services/nls/es/JobService',{});
},
'Sage/Services/nls/es-do/JobService':function(){
define('Sage/Services/nls/es-do/JobService',{});
},
'Sage/QuickForms/Design/nls/es/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-do/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-do/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/es/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/_PropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-do/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-do/_PropertyEditor',{});
},
'Sage/Services/nls/es/ActivityActionProcessor':function(){
define('Sage/Services/nls/es/ActivityActionProcessor',{});
},
'Sage/Services/nls/es-do/ActivityActionProcessor':function(){
define('Sage/Services/nls/es-do/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/TextBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-do/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-do/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-do/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-do/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es/UserActivityDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es/UserActivityDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es-do/UserActivityDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es-do/UserActivityDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es/ConfirmationDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es/ConfirmationDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es-do/ConfirmationDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es-do/ConfirmationDetailSummary',{});
},
'Sage/Utility/File/nls/es/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/es/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/es-do/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/es-do/DefaultDropHandler',{});
},
'Sage/UI/nls/es/TransferBoxWidget':function(){
define('Sage/UI/nls/es/TransferBoxWidget',{});
},
'Sage/UI/nls/es-do/TransferBoxWidget':function(){
define('Sage/UI/nls/es-do/TransferBoxWidget',{});
},
'Sage/Utility/File/nls/es/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/es/AttachmentPropertiesEditForm',{});
},
'Sage/Utility/File/nls/es-do/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/es-do/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/es/AlarmPane':function(){
define('Sage/UI/Alarms/nls/es/AlarmPane',{});
},
'Sage/UI/Alarms/nls/es-do/AlarmPane':function(){
define('Sage/UI/Alarms/nls/es-do/AlarmPane',{});
},
'Sage/TaskPane/nls/es/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/es/LiteratureManagementTasks',{});
},
'Sage/TaskPane/nls/es-do/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/es-do/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/es/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/es/DashboardWidget',{});
},
'Sage/UI/Dashboard/nls/es-do/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/es-do/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/es/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/NumericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-do/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-do/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/es/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es/CustomerPaymentsRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/es-do/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es-do/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/es/FilterPanel':function(){
define('Sage/UI/Filters/nls/es/FilterPanel',{});
},
'Sage/UI/Filters/nls/es-do/FilterPanel':function(){
define('Sage/UI/Filters/nls/es-do/FilterPanel',{});
},
'Sage/TaskPane/nls/es/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/es/_BaseTaskPaneTasklet',{});
},
'Sage/TaskPane/nls/es-do/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/es-do/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportManagerFormatter',{});
},
'Sage/MainView/ReportMgr/nls/es-do/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/es-do/ReportManagerFormatter',{});
},
'Sage/UI/nls/es/OwnerType':function(){
define('Sage/UI/nls/es/OwnerType',{});
},
'Sage/UI/nls/es-do/OwnerType':function(){
define('Sage/UI/nls/es-do/OwnerType',{});
},
'Sage/MainView/JobMgr/templates/nls/es/JobDefinitionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/es/JobDefinitionsListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/es-do/JobDefinitionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/es-do/JobDefinitionsListSummary',{});
},
'Sage/TaskPane/nls/es/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/es/LeadTasksTasklet',{});
},
'Sage/TaskPane/nls/es-do/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/es-do/LeadTasksTasklet',{});
},
'Sage/MainView/ReportMgr/templates/nls/es/ReportDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/es/ReportDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/es-do/ReportDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/es-do/ReportDetailSummary',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/_ParameterEditorBase':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/_ParameterEditorBase',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-do/_ParameterEditorBase':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-do/_ParameterEditorBase',{});
},
'Sage/MailMerge/nls/es/Service':function(){
define('Sage/MailMerge/nls/es/Service',{});
},
'Sage/MailMerge/nls/es-do/Service':function(){
define('Sage/MailMerge/nls/es-do/Service',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es/ConfirmationListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es/ConfirmationListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es-do/ConfirmationListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es-do/ConfirmationListSummary',{});
},
'Sage/MainView/ActivityMgr/nls/es/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/es/SnoozeOptions',{});
},
'Sage/MainView/ActivityMgr/nls/es-do/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/es-do/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/es/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-do/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-do/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-do/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-do/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/es/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es/InvoiceRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/es-do/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es-do/InvoiceRTDV',{});
},
'Sage/UI/nls/es/SDataLookup':function(){
define('Sage/UI/nls/es/SDataLookup',{});
},
'Sage/UI/nls/es-do/SDataLookup':function(){
define('Sage/UI/nls/es-do/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/es/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/es/RowDesigner',{});
},
'Sage/QuickForms/Design/nls/es-do/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/es-do/RowDesigner',{});
},
'Sage/Groups/nls/es/GroupLookup':function(){
define('Sage/Groups/nls/es/GroupLookup',{});
},
'Sage/Groups/nls/es-do/GroupLookup':function(){
define('Sage/Groups/nls/es-do/GroupLookup',{});
},
'Sage/TaskPane/nls/es/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/es/OpportunityTasksTasklet',{});
},
'Sage/TaskPane/nls/es-do/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/es-do/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/es/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/es/CheckBoxFilter',{});
},
'Sage/UI/Filters/nls/es-do/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/es-do/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/es/LibraryDocument':function(){
define('Sage/Utility/File/nls/es/LibraryDocument',{});
},
'Sage/Utility/File/nls/es-do/LibraryDocument':function(){
define('Sage/Utility/File/nls/es-do/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/SpeedSearchLookup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-do/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-do/SpeedSearchLookup',{});
},
'Sage/UI/nls/es/ConditionManager':function(){
define('Sage/UI/nls/es/ConditionManager',{});
},
'Sage/UI/nls/es-do/ConditionManager':function(){
define('Sage/UI/nls/es-do/ConditionManager',{});
},
'Sage/MainView/JobMgr/templates/nls/es/SchedulesListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/es/SchedulesListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/es-do/SchedulesListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/es-do/SchedulesListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es/UserActivityListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es/UserActivityListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es-do/UserActivityListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es-do/UserActivityListSummary',{});
},
'Sage/UI/Dashboard/nls/es/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/es/WidgetDefinition',{});
},
'Sage/UI/Dashboard/nls/es-do/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/es-do/WidgetDefinition',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es/AllOpenListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es/AllOpenListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es-do/AllOpenListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es-do/AllOpenListSummary',{});
},
'Sage/UI/nls/es/SearchConditionWidget':function(){
define('Sage/UI/nls/es/SearchConditionWidget',{});
},
'Sage/UI/nls/es-do/SearchConditionWidget':function(){
define('Sage/UI/nls/es-do/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/es/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-do/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-do/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/es/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/es/JobManagerActions',{});
},
'Sage/MainView/JobMgr/nls/es-do/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/es-do/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/ContactLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-do/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-do/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/es/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/es/DataSourcePanel',{});
},
'Sage/QuickForms/Design/nls/es-do/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/es-do/DataSourcePanel',{});
},
'Sage/MainView/ReportMgr/templates/nls/es/SchedulesListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/es/SchedulesListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/es-do/SchedulesListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/es-do/SchedulesListSummary',{});
},
'Sage/Library/nls/es/Manager':function(){
define('Sage/Library/nls/es/Manager',{});
},
'Sage/Library/nls/es-do/Manager':function(){
define('Sage/Library/nls/es-do/Manager',{});
},
'Sage/UI/nls/es/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/es/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/nls/es-do/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/es-do/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/es/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/es/NonVisibleControlContainer',{});
},
'Sage/QuickForms/Design/nls/es-do/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/es-do/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/es/Name':function(){
define('Sage/UI/Controls/nls/es/Name',{});
},
'Sage/UI/Controls/nls/es-do/Name':function(){
define('Sage/UI/Controls/nls/es-do/Name',{});
},
'Sage/MainView/JobMgr/nls/es/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es/ExecutionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/es-do/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es-do/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/es/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/PhoneControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-do/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-do/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/es/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/es/UpdateLeads',{});
},
'Sage/MainView/Lead/nls/es-do/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/es-do/UpdateLeads',{});
},
'Sage/Library/nls/es/FileHandler':function(){
define('Sage/Library/nls/es/FileHandler',{});
},
'Sage/Library/nls/es-do/FileHandler':function(){
define('Sage/Library/nls/es-do/FileHandler',{});
},
'Sage/UI/nls/es/ListPanel':function(){
define('Sage/UI/nls/es/ListPanel',{});
},
'Sage/UI/nls/es-do/ListPanel':function(){
define('Sage/UI/nls/es-do/ListPanel',{});
},
'Sage/Utility/nls/es/Sql':function(){
define('Sage/Utility/nls/es/Sql',{});
},
'Sage/Utility/nls/es-do/Sql':function(){
define('Sage/Utility/nls/es-do/Sql',{});
},
'Sage/UI/Filters/nls/es/EditFilters':function(){
define('Sage/UI/Filters/nls/es/EditFilters',{});
},
'Sage/UI/Filters/nls/es-do/EditFilters':function(){
define('Sage/UI/Filters/nls/es-do/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/es/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/FormUsagesPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-do/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-do/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/es/DurationSelect':function(){
define('Sage/UI/Controls/nls/es/DurationSelect',{});
},
'Sage/UI/Controls/nls/es-do/DurationSelect':function(){
define('Sage/UI/Controls/nls/es-do/DurationSelect',{});
},
'Sage/UI/Alarms/nls/es/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/es/AlarmCountDown',{});
},
'Sage/UI/Alarms/nls/es-do/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/es-do/AlarmCountDown',{});
},
'Sage/UI/nls/es/AttachmentList':function(){
define('Sage/UI/nls/es/AttachmentList',{});
},
'Sage/UI/nls/es-do/AttachmentList':function(){
define('Sage/UI/nls/es-do/AttachmentList',{});
},
'Sage/MailMerge/nls/es/Lookup':function(){
define('Sage/MailMerge/nls/es/Lookup',{});
},
'Sage/MailMerge/nls/es-do/Lookup':function(){
define('Sage/MailMerge/nls/es-do/Lookup',{});
},
'Sage/QuickForms/Design/Editors/nls/es/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-do/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-do/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/es/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/es/RunJobDialog',{});
},
'Sage/MainView/JobMgr/nls/es-do/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/es-do/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/es/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-do/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-do/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-do/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-do/EditableGridControlDesigner',{});
},
'Sage/MainView/Options/nls/es/OptionsDialog':function(){
define('Sage/MainView/Options/nls/es/OptionsDialog',{});
},
'Sage/MainView/Options/nls/es-do/OptionsDialog':function(){
define('Sage/MainView/Options/nls/es-do/OptionsDialog',{});
},
'Sage/QuickForms/Design/nls/es/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/HiddenControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-do/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-do/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/es/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/es/DashboardWidgetCell',{});
},
'Sage/UI/Dashboard/nls/es-do/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/es-do/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/es/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/UserBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-do/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-do/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/es/Dialogs':function(){
define('Sage/UI/nls/es/Dialogs',{});
},
'Sage/UI/nls/es-do/Dialogs':function(){
define('Sage/UI/nls/es-do/Dialogs',{});
},
'Sage/MainView/IntegrationContract/nls/es/SyncResultsHistory':function(){
define('Sage/MainView/IntegrationContract/nls/es/SyncResultsHistory',{});
},
'Sage/MainView/IntegrationContract/nls/es-do/SyncResultsHistory':function(){
define('Sage/MainView/IntegrationContract/nls/es-do/SyncResultsHistory',{});
},
'Sage/TaskPane/nls/es/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/es/SecuredActionTasklet',{});
},
'Sage/TaskPane/nls/es-do/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/es-do/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/es/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/es/DashboardTabController',{});
},
'Sage/UI/Dashboard/nls/es-do/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/es-do/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/es/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es/SalesOrderRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/es-do/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es-do/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/es/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/UserControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-do/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-do/UserControlDesigner',{});
},
'Sage/Groups/nls/es/GroupNavigator':function(){
define('Sage/Groups/nls/es/GroupNavigator',{});
},
'Sage/Groups/nls/es-do/GroupNavigator':function(){
define('Sage/Groups/nls/es-do/GroupNavigator',{});
},
'Sage/Utility/File/nls/es/AddURLAttachment':function(){
define('Sage/Utility/File/nls/es/AddURLAttachment',{});
},
'Sage/Utility/File/nls/es-do/AddURLAttachment':function(){
define('Sage/Utility/File/nls/es-do/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/es/EditFilterItems':function(){
define('Sage/UI/Filters/nls/es/EditFilterItems',{});
},
'Sage/UI/Filters/nls/es-do/EditFilterItems':function(){
define('Sage/UI/Filters/nls/es-do/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportsFormatter',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-do/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-do/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/es/DragDropWatcher':function(){
define('Sage/Utility/File/nls/es/DragDropWatcher',{});
},
'Sage/Utility/File/nls/es-do/DragDropWatcher':function(){
define('Sage/Utility/File/nls/es-do/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/es/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/es/DesignSurface',{});
},
'Sage/QuickForms/Design/nls/es-do/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/es-do/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/es/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-do/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-do/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/es/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/FormAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-do/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-do/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/EventListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-do/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-do/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/es/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/es/AllOpenListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/es-do/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/es-do/AllOpenListPanelConfig',{});
},
'Sage/MainView/nls/es/FormManager':function(){
define('Sage/MainView/nls/es/FormManager',{});
},
'Sage/MainView/nls/es-do/FormManager':function(){
define('Sage/MainView/nls/es-do/FormManager',{});
},
'Sage/UI/nls/es/ActivityScheduler':function(){
define('Sage/UI/nls/es/ActivityScheduler',{});
},
'Sage/UI/nls/es-do/ActivityScheduler':function(){
define('Sage/UI/nls/es-do/ActivityScheduler',{});
},
'Sage/MainView/nls/es/SecurityManager':function(){
define('Sage/MainView/nls/es/SecurityManager',{});
},
'Sage/MainView/nls/es-do/SecurityManager':function(){
define('Sage/MainView/nls/es-do/SecurityManager',{});
},
'Sage/TaskPane/nls/es/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/es/ActivityTaskConfigurationProvider',{});
},
'Sage/TaskPane/nls/es-do/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/es-do/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/es/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/es/EntityInfoToolTip',{});
},
'Sage/UI/Controls/nls/es-do/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/es-do/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/es-do/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/es-do/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es/AllOpenDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es/AllOpenDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es-do/AllOpenDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es-do/AllOpenDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/es/ReportsListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/es/ReportsListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/es-do/ReportsListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/es-do/ReportsListSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/es/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/es/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/Common/nls/es-do/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/es-do/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/templates/nls/es/ScheduleDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/es/ScheduleDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/es-do/ScheduleDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/es-do/ScheduleDetailSummary',{});
},
'Sage/MainView/Opportunity/nls/es/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/es/UpdateOpportunities',{});
},
'Sage/MainView/Opportunity/nls/es-do/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/es-do/UpdateOpportunities',{});
},
'Sage/UI/nls/es/EditCalendarUsers':function(){
define('Sage/UI/nls/es/EditCalendarUsers',{});
},
'Sage/UI/nls/es-do/EditCalendarUsers':function(){
define('Sage/UI/nls/es-do/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportParametersDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-do/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-do/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/es/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/DateTimePickerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-do/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-do/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/es/HelpMenu':function(){
define('Sage/UI/Controls/nls/es/HelpMenu',{});
},
'Sage/UI/Controls/nls/es-do/HelpMenu':function(){
define('Sage/UI/Controls/nls/es-do/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/es/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/LayoutPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-do/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-do/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/es/UserTasklet':function(){
define('Sage/TaskPane/nls/es/UserTasklet',{});
},
'Sage/TaskPane/nls/es-do/UserTasklet':function(){
define('Sage/TaskPane/nls/es-do/UserTasklet',{});
},
'Sage/UI/Alarms/nls/es/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/es/ActivityAlarm',{});
},
'Sage/UI/Alarms/nls/es-do/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/es-do/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/es/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/es/OpportunityStatistics',{});
},
'Sage/MainView/Opportunity/nls/es-do/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/es-do/OpportunityStatistics',{});
},
'Sage/TaskPane/nls/es/GroupListTasklet':function(){
define('Sage/TaskPane/nls/es/GroupListTasklet',{});
},
'Sage/TaskPane/nls/es-do/GroupListTasklet':function(){
define('Sage/TaskPane/nls/es-do/GroupListTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportConditionEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-do/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-do/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/es/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/es/AdvancedSearchOptions',{});
},
'Sage/MainView/IntegrationContract/nls/es-do/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/es-do/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/es/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/es/ColumnDesigner',{});
},
'Sage/QuickForms/Design/nls/es-do/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/es-do/ColumnDesigner',{});
},
'Sage/MainView/JobMgr/templates/nls/es/JobDefinitionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/es/JobDefinitionDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/es-do/JobDefinitionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/es-do/JobDefinitionDetailSummary',{});
},
'Sage/UI/nls/es/SearchMenuItem':function(){
define('Sage/UI/nls/es/SearchMenuItem',{});
},
'Sage/UI/nls/es-do/SearchMenuItem':function(){
define('Sage/UI/nls/es-do/SearchMenuItem',{});
},
'Sage/Library/nls/es/DocumentProperties':function(){
define('Sage/Library/nls/es/DocumentProperties',{});
},
'Sage/Library/nls/es-do/DocumentProperties':function(){
define('Sage/Library/nls/es-do/DocumentProperties',{});
},
'Sage/UI/nls/es/NotesHistoryList':function(){
define('Sage/UI/nls/es/NotesHistoryList',{});
},
'Sage/UI/nls/es-do/NotesHistoryList':function(){
define('Sage/UI/nls/es-do/NotesHistoryList',{});
},
'Sage/Utility/nls/es/File':function(){
define('Sage/Utility/nls/es/File',{});
},
'Sage/Utility/nls/es-do/File':function(){
define('Sage/Utility/nls/es-do/File',{});
},
'Sage/MainView/ReportMgr/nls/es/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/es-do/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es-do/HistoryListPanelConfig',{});
},
'Sage/MainView/JobMgr/templates/nls/es/ScheduleDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/es/ScheduleDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/es-do/ScheduleDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/es-do/ScheduleDetailSummary',{});
},
'Sage/QuickForms/Design/nls/es/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/UrlControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-do/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-do/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/es/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/es/ContactTasksTasklet',{});
},
'Sage/TaskPane/nls/es-do/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/es-do/ContactTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es/EventSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es/EventSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es-do/EventSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es-do/EventSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/es/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/es/_WizardDialogBase',{});
},
'Sage/MainView/ReportMgr/Common/nls/es-do/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/es-do/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/es/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es/SchedulesListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/es-do/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es-do/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/es/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/es/GoogleDocPicker',{});
},
'Sage/Utility/File/nls/es-do/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/es-do/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/es/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/ComboBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-do/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-do/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/es/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-do/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-do/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/HistoryEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-do/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-do/HistoryEditor',{});
},
'Sage/Groups/nls/es/GroupManager':function(){
define('Sage/Groups/nls/es/GroupManager',{});
},
'Sage/Groups/nls/es-do/GroupManager':function(){
define('Sage/Groups/nls/es-do/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/es/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-do/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-do/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/ComboBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-do/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-do/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportsListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/es-do/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es-do/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/es/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/es/JobNotificationButton',{});
},
'Sage/UI/Alarms/nls/es-do/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/es-do/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportWizardController',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-do/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-do/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/es/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/es-do/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es-do/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/RecurringEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-do/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-do/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportsUtility',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-do/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-do/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/es/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-do/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-do/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/es/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/es-do/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es-do/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/es/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-do/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-do/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-do/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-do/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-do/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-do/PickListControlDesigner',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es/LitRequestSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es/LitRequestSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es-do/LitRequestSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es-do/LitRequestSummary',{});
},
'Sage/QuickForms/Design/Editors/nls/es/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-do/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-do/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/es/FolderHandler':function(){
define('Sage/Library/nls/es/FolderHandler',{});
},
'Sage/Library/nls/es-do/FolderHandler':function(){
define('Sage/Library/nls/es-do/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/es/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-do/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-do/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/es/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/es/ContactSearchForDuplicates',{});
},
'Sage/MainView/Contact/nls/es-do/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/es-do/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/es/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/DateTimePickerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-do/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-do/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/es/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/es/AccountingTasksTasklet',{});
},
'Sage/TaskPane/nls/es-do/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/es-do/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/es/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-do/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-do/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/CurrencyBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-do/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-do/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/es/EditableGrid':function(){
define('Sage/UI/nls/es/EditableGrid',{});
},
'Sage/UI/nls/es-do/EditableGrid':function(){
define('Sage/UI/nls/es-do/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/es/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es/SalesQuoteRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/es-do/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es-do/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/es/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/es/SecurityProfile',{});
},
'Sage/MainView/SecurityMgr/nls/es-do/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/es-do/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportWizardController',{});
},
'Sage/MainView/ReportMgr/nls/es-do/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/es-do/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/es/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/UserAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-do/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-do/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportManagerUtility',{});
},
'Sage/MainView/ReportMgr/nls/es-do/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/es-do/ReportManagerUtility',{});
},
'Sage/UI/nls/es/SpeedSearch':function(){
define('Sage/UI/nls/es/SpeedSearch',{});
},
'Sage/UI/nls/es-do/SpeedSearch':function(){
define('Sage/UI/nls/es-do/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/es/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/CurrencyAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-do/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-do/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/es/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es/ReportManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/es-do/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es-do/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/es/SLXPreviewGrid':function(){
define('Sage/UI/nls/es/SLXPreviewGrid',{});
},
'Sage/UI/nls/es-do/SLXPreviewGrid':function(){
define('Sage/UI/nls/es-do/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/es/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/es/UnconfirmedPane',{});
},
'Sage/UI/Alarms/nls/es-do/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/es-do/UnconfirmedPane',{});
},
'Sage/Utility/nls/es/Utility':function(){
define('Sage/Utility/nls/es/Utility',{});
},
'Sage/Utility/nls/es-do/Utility':function(){
define('Sage/Utility/nls/es-do/Utility',{});
},
'Sage/QuickForms/Design/nls/es/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/ControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-do/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-do/ControlDesigner',{});
},
'Sage/UI/Controls/nls/es/Address':function(){
define('Sage/UI/Controls/nls/es/Address',{});
},
'Sage/UI/Controls/nls/es-do/Address':function(){
define('Sage/UI/Controls/nls/es-do/Address',{});
},
'Sage/MainView/JobMgr/nls/es/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/es/JobManagerGroupContextService',{});
},
'Sage/MainView/JobMgr/nls/es-do/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/es-do/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/es/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/BaseListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-do/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-do/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/es/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/OwnerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-do/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-do/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/es/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es/JobManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/es-do/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es-do/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/es-do/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/es-do/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/es/UserType':function(){
define('Sage/UI/nls/es/UserType',{});
},
'Sage/UI/nls/es-do/UserType':function(){
define('Sage/UI/nls/es-do/UserType',{});
},
'Sage/MainView/ReportMgr/templates/nls/es/HistoryDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/es/HistoryDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/es-do/HistoryDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/es-do/HistoryDetailSummary',{});
},
'Sage/QuickForms/Design/nls/es/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/es/FormDesigner',{});
},
'Sage/QuickForms/Design/nls/es-do/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/es-do/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityCalendar',{});
},
'Sage/MainView/ActivityMgr/nls/es-do/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/es-do/ActivityCalendar',{});
},
'Sage/Utility/nls/es/Jobs':function(){
define('Sage/Utility/nls/es/Jobs',{});
},
'Sage/Utility/nls/es-do/Jobs':function(){
define('Sage/Utility/nls/es-do/Jobs',{});
},
'Sage/UI/Controls/nls/es/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/es/_DialogHelpIconMixin',{});
},
'Sage/UI/Controls/nls/es-do/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/es-do/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/es/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/PickListAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-do/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-do/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/es/ActivityList':function(){
define('Sage/UI/nls/es/ActivityList',{});
},
'Sage/UI/nls/es-do/ActivityList':function(){
define('Sage/UI/nls/es-do/ActivityList',{});
},
'Sage/UI/Alarms/nls/es/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/es/JobNotificationPopup',{});
},
'Sage/UI/Alarms/nls/es-do/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/es-do/JobNotificationPopup',{});
},
'Sage/MainView/JobMgr/templates/nls/es/ExecutionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/es/ExecutionsListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/es-do/ExecutionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/es-do/ExecutionsListSummary',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/LeadLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-do/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-do/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/es/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es/SchedulesListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/es-do/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es-do/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/es/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/GenericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-do/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-do/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/es/CalendarUsersListPane':function(){
define('Sage/UI/nls/es/CalendarUsersListPane',{});
},
'Sage/UI/nls/es-do/CalendarUsersListPane':function(){
define('Sage/UI/nls/es-do/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/es/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-do/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-do/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/ColumnBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-do/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-do/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/templates/nls/es/ExecutionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/es/ExecutionDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/es-do/ExecutionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/es-do/ExecutionDetailSummary',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportManagerGroupContextService',{});
},
'Sage/MainView/ReportMgr/nls/es-do/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/es-do/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/es/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/es/MatchingOptionsConfig',{});
},
'Sage/MainView/IntegrationContract/nls/es-do/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/es-do/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/es/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/FormBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-do/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-do/FormBasicPropertyEditor',{});
},
'Sage/UI/Alarms/nls/es/AlarmButton':function(){
define('Sage/UI/Alarms/nls/es/AlarmButton',{});
},
'Sage/UI/Alarms/nls/es-do/AlarmButton':function(){
define('Sage/UI/Alarms/nls/es-do/AlarmButton',{});
},
'Sage/MainView/ActivityMgr/nls/es/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/es/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/MainView/ActivityMgr/nls/es-do/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/es-do/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/es/Attachment':function(){
define('Sage/Utility/File/nls/es/Attachment',{});
},
'Sage/Utility/File/nls/es-do/Attachment':function(){
define('Sage/Utility/File/nls/es-do/Attachment',{});
},
'Sage/QuickForms/Design/nls/es/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-do/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-do/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/es/PropertyEditorContainer',{});
},
'Sage/QuickForms/Design/nls/es-do/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/es-do/PropertyEditorContainer',{});
},
'Sage/Services/nls/es/ReportingService':function(){
define('Sage/Services/nls/es/ReportingService',{});
},
'Sage/Services/nls/es-do/ReportingService':function(){
define('Sage/Services/nls/es-do/ReportingService',{});
},
'Sage/MailMerge/nls/es/Helper':function(){
define('Sage/MailMerge/nls/es/Helper',{});
},
'Sage/MailMerge/nls/es-do/Helper':function(){
define('Sage/MailMerge/nls/es-do/Helper',{});
},
'Sage/UI/Dashboard/nls/es/Dashboard':function(){
define('Sage/UI/Dashboard/nls/es/Dashboard',{});
},
'Sage/UI/Dashboard/nls/es-do/Dashboard':function(){
define('Sage/UI/Dashboard/nls/es-do/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-do/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-do/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/es/PickList':function(){
define('Sage/UI/Controls/nls/es/PickList',{});
},
'Sage/UI/Controls/nls/es-do/PickList':function(){
define('Sage/UI/Controls/nls/es-do/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/es/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/es/HistoryEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/es-do/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/es-do/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/es/Email':function(){
define('Sage/Utility/nls/es/Email',{});
},
'Sage/Utility/nls/es-do/Email':function(){
define('Sage/Utility/nls/es-do/Email',{});
},
'Sage/TaskPane/nls/es/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es/SecurityManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/es-do/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es-do/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/es/TimeZoneItem':function(){
define('Sage/UI/nls/es/TimeZoneItem',{});
},
'Sage/UI/nls/es-do/TimeZoneItem':function(){
define('Sage/UI/nls/es-do/TimeZoneItem',{});
},
'Sage/MainView/ReportMgr/templates/nls/es/HistoryListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/es/HistoryListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/es-do/HistoryListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/es-do/HistoryListSummary',{});
},
'Sage/UI/Columns/nls/es/SlxEdit':function(){
define('Sage/UI/Columns/nls/es/SlxEdit',{});
},
'Sage/UI/Columns/nls/es-do/SlxEdit':function(){
define('Sage/UI/Columns/nls/es-do/SlxEdit',{});
},
'Sage/Reporting/nls/es/Enumerations':function(){
define('Sage/Reporting/nls/es/Enumerations',{});
},
'Sage/Reporting/nls/es-do/Enumerations':function(){
define('Sage/Reporting/nls/es-do/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/es/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-do/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-do/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportConditionsDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-do/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-do/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/es/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/es/ActivityListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/es-do/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/es-do/ActivityListPanelConfig',{});
},
'Sage/UI/nls/es/JobSchedulingWidget':function(){
define('Sage/UI/nls/es/JobSchedulingWidget',{});
},
'Sage/UI/nls/es-do/JobSchedulingWidget':function(){
define('Sage/UI/nls/es-do/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/es/LogOffButton':function(){
define('Sage/UI/Controls/nls/es/LogOffButton',{});
},
'Sage/UI/Controls/nls/es-do/LogOffButton':function(){
define('Sage/UI/Controls/nls/es-do/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/es/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/TextBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-do/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-do/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/EditEventEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-do/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-do/EditEventEditor',{});
},
'Sage/MailMerge/nls/es/Loader':function(){
define('Sage/MailMerge/nls/es/Loader',{});
},
'Sage/MailMerge/nls/es-do/Loader':function(){
define('Sage/MailMerge/nls/es-do/Loader',{});
},
'Sage/UI/Controls/nls/es/DateTimePicker':function(){
define('Sage/UI/Controls/nls/es/DateTimePicker',{});
},
'Sage/UI/Controls/nls/es-do/DateTimePicker':function(){
define('Sage/UI/Controls/nls/es-do/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportManagerActions',{});
},
'Sage/MainView/ReportMgr/nls/es-do/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/es-do/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/es/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/es/AlarmPopup',{});
},
'Sage/UI/Alarms/nls/es-do/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/es-do/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/es/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/es/ContactUserAssociationEditor',{});
},
'Sage/MainView/Contact/nls/es-do/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/es-do/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-do/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-do/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/es/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es/BaseListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/es-do/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es-do/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/es/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-do/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-do/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/EmailControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-do/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-do/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/es/Lookup':function(){
define('Sage/UI/Controls/nls/es/Lookup',{});
},
'Sage/UI/Controls/nls/es-do/Lookup':function(){
define('Sage/UI/Controls/nls/es-do/Lookup',{});
},
'Sage/Utility/File/nls/es/DescriptionsForm':function(){
define('Sage/Utility/File/nls/es/DescriptionsForm',{});
},
'Sage/Utility/File/nls/es-do/DescriptionsForm':function(){
define('Sage/Utility/File/nls/es-do/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/es/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/NumericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-do/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-do/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/es/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/es/CommonTasksTasklet',{});
},
'Sage/TaskPane/nls/es-do/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/es-do/CommonTasksTasklet',{});
},
'Sage/Utility/nls/es/Dashboard':function(){
define('Sage/Utility/nls/es/Dashboard',{});
},
'Sage/Utility/nls/es-do/Dashboard':function(){
define('Sage/Utility/nls/es-do/Dashboard',{});
}}});
define("Sage/nls/Sage_es-do", [], 1);
