require({cache:{
'Sage/Utility/File/nls/es/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/es/FallbackFilePicker',{});
},
'Sage/Utility/File/nls/es-ni/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/es-ni/FallbackFilePicker',{});
},
'Sage/UI/nls/es/Boolean':function(){
define('Sage/UI/nls/es/Boolean',{});
},
'Sage/UI/nls/es-ni/Boolean':function(){
define('Sage/UI/nls/es-ni/Boolean',{});
},
'Sage/Services/nls/es/ActivityService':function(){
define('Sage/Services/nls/es/ActivityService',{});
},
'Sage/Services/nls/es-ni/ActivityService':function(){
define('Sage/Services/nls/es-ni/ActivityService',{});
},
'Sage/UI/Controls/nls/es/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/es/CopyToClipboard',{});
},
'Sage/UI/Controls/nls/es-ni/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/es-ni/CopyToClipboard',{});
},
'Sage/Utility/nls/es/Activity':function(){
define('Sage/Utility/nls/es/Activity',{});
},
'Sage/Utility/nls/es-ni/Activity':function(){
define('Sage/Utility/nls/es-ni/Activity',{});
},
'Sage/QuickForms/Design/nls/es/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/es/DesignPanel',{});
},
'Sage/QuickForms/Design/nls/es-ni/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/es-ni/DesignPanel',{});
},
'Sage/UI/nls/es/TimelessActivitiesPane':function(){
define('Sage/UI/nls/es/TimelessActivitiesPane',{});
},
'Sage/UI/nls/es-ni/TimelessActivitiesPane':function(){
define('Sage/UI/nls/es-ni/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-ni/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-ni/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/es/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/es/ContactUserAssociationEditor',{});
},
'Sage/TaskPane/User/nls/es-ni/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/es-ni/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/es/ActivityManager':function(){
define('Sage/MainView/nls/es/ActivityManager',{});
},
'Sage/MainView/nls/es-ni/ActivityManager':function(){
define('Sage/MainView/nls/es-ni/ActivityManager',{});
},
'Sage/Services/nls/es/JobService':function(){
define('Sage/Services/nls/es/JobService',{});
},
'Sage/Services/nls/es-ni/JobService':function(){
define('Sage/Services/nls/es-ni/JobService',{});
},
'Sage/QuickForms/Design/nls/es/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ni/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ni/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/es/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/_PropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ni/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ni/_PropertyEditor',{});
},
'Sage/Services/nls/es/ActivityActionProcessor':function(){
define('Sage/Services/nls/es/ActivityActionProcessor',{});
},
'Sage/Services/nls/es-ni/ActivityActionProcessor':function(){
define('Sage/Services/nls/es-ni/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/TextBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ni/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ni/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-ni/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-ni/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es/UserActivityDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es/UserActivityDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es-ni/UserActivityDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es-ni/UserActivityDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es/ConfirmationDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es/ConfirmationDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es-ni/ConfirmationDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es-ni/ConfirmationDetailSummary',{});
},
'Sage/Utility/File/nls/es/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/es/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/es-ni/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/es-ni/DefaultDropHandler',{});
},
'Sage/UI/nls/es/TransferBoxWidget':function(){
define('Sage/UI/nls/es/TransferBoxWidget',{});
},
'Sage/UI/nls/es-ni/TransferBoxWidget':function(){
define('Sage/UI/nls/es-ni/TransferBoxWidget',{});
},
'Sage/Utility/File/nls/es/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/es/AttachmentPropertiesEditForm',{});
},
'Sage/Utility/File/nls/es-ni/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/es-ni/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/es/AlarmPane':function(){
define('Sage/UI/Alarms/nls/es/AlarmPane',{});
},
'Sage/UI/Alarms/nls/es-ni/AlarmPane':function(){
define('Sage/UI/Alarms/nls/es-ni/AlarmPane',{});
},
'Sage/TaskPane/nls/es/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/es/LiteratureManagementTasks',{});
},
'Sage/TaskPane/nls/es-ni/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/es-ni/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/es/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/es/DashboardWidget',{});
},
'Sage/UI/Dashboard/nls/es-ni/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/es-ni/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/es/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/NumericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ni/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ni/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/es/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es/CustomerPaymentsRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/es-ni/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es-ni/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/es/FilterPanel':function(){
define('Sage/UI/Filters/nls/es/FilterPanel',{});
},
'Sage/UI/Filters/nls/es-ni/FilterPanel':function(){
define('Sage/UI/Filters/nls/es-ni/FilterPanel',{});
},
'Sage/TaskPane/nls/es/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/es/_BaseTaskPaneTasklet',{});
},
'Sage/TaskPane/nls/es-ni/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/es-ni/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportManagerFormatter',{});
},
'Sage/MainView/ReportMgr/nls/es-ni/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/es-ni/ReportManagerFormatter',{});
},
'Sage/UI/nls/es/OwnerType':function(){
define('Sage/UI/nls/es/OwnerType',{});
},
'Sage/UI/nls/es-ni/OwnerType':function(){
define('Sage/UI/nls/es-ni/OwnerType',{});
},
'Sage/MainView/JobMgr/templates/nls/es/JobDefinitionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/es/JobDefinitionsListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/es-ni/JobDefinitionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/es-ni/JobDefinitionsListSummary',{});
},
'Sage/TaskPane/nls/es/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/es/LeadTasksTasklet',{});
},
'Sage/TaskPane/nls/es-ni/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/es-ni/LeadTasksTasklet',{});
},
'Sage/MainView/ReportMgr/templates/nls/es/ReportDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/es/ReportDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/es-ni/ReportDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/es-ni/ReportDetailSummary',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/_ParameterEditorBase':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/_ParameterEditorBase',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ni/_ParameterEditorBase':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ni/_ParameterEditorBase',{});
},
'Sage/MailMerge/nls/es/Service':function(){
define('Sage/MailMerge/nls/es/Service',{});
},
'Sage/MailMerge/nls/es-ni/Service':function(){
define('Sage/MailMerge/nls/es-ni/Service',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es/ConfirmationListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es/ConfirmationListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es-ni/ConfirmationListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es-ni/ConfirmationListSummary',{});
},
'Sage/MainView/ActivityMgr/nls/es/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/es/SnoozeOptions',{});
},
'Sage/MainView/ActivityMgr/nls/es-ni/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/es-ni/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/es/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ni/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ni/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ni/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ni/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/es/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es/InvoiceRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/es-ni/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es-ni/InvoiceRTDV',{});
},
'Sage/UI/nls/es/SDataLookup':function(){
define('Sage/UI/nls/es/SDataLookup',{});
},
'Sage/UI/nls/es-ni/SDataLookup':function(){
define('Sage/UI/nls/es-ni/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/es/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/es/RowDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ni/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ni/RowDesigner',{});
},
'Sage/Groups/nls/es/GroupLookup':function(){
define('Sage/Groups/nls/es/GroupLookup',{});
},
'Sage/Groups/nls/es-ni/GroupLookup':function(){
define('Sage/Groups/nls/es-ni/GroupLookup',{});
},
'Sage/TaskPane/nls/es/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/es/OpportunityTasksTasklet',{});
},
'Sage/TaskPane/nls/es-ni/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/es-ni/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/es/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/es/CheckBoxFilter',{});
},
'Sage/UI/Filters/nls/es-ni/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/es-ni/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/es/LibraryDocument':function(){
define('Sage/Utility/File/nls/es/LibraryDocument',{});
},
'Sage/Utility/File/nls/es-ni/LibraryDocument':function(){
define('Sage/Utility/File/nls/es-ni/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/SpeedSearchLookup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-ni/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-ni/SpeedSearchLookup',{});
},
'Sage/UI/nls/es/ConditionManager':function(){
define('Sage/UI/nls/es/ConditionManager',{});
},
'Sage/UI/nls/es-ni/ConditionManager':function(){
define('Sage/UI/nls/es-ni/ConditionManager',{});
},
'Sage/MainView/JobMgr/templates/nls/es/SchedulesListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/es/SchedulesListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/es-ni/SchedulesListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/es-ni/SchedulesListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es/UserActivityListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es/UserActivityListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es-ni/UserActivityListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es-ni/UserActivityListSummary',{});
},
'Sage/UI/Dashboard/nls/es/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/es/WidgetDefinition',{});
},
'Sage/UI/Dashboard/nls/es-ni/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/es-ni/WidgetDefinition',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es/AllOpenListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es/AllOpenListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es-ni/AllOpenListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es-ni/AllOpenListSummary',{});
},
'Sage/UI/nls/es/SearchConditionWidget':function(){
define('Sage/UI/nls/es/SearchConditionWidget',{});
},
'Sage/UI/nls/es-ni/SearchConditionWidget':function(){
define('Sage/UI/nls/es-ni/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/es/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ni/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ni/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/es/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/es/JobManagerActions',{});
},
'Sage/MainView/JobMgr/nls/es-ni/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/es-ni/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/ContactLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-ni/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-ni/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/es/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/es/DataSourcePanel',{});
},
'Sage/QuickForms/Design/nls/es-ni/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/es-ni/DataSourcePanel',{});
},
'Sage/MainView/ReportMgr/templates/nls/es/SchedulesListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/es/SchedulesListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/es-ni/SchedulesListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/es-ni/SchedulesListSummary',{});
},
'Sage/Library/nls/es/Manager':function(){
define('Sage/Library/nls/es/Manager',{});
},
'Sage/Library/nls/es-ni/Manager':function(){
define('Sage/Library/nls/es-ni/Manager',{});
},
'Sage/UI/nls/es/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/es/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/nls/es-ni/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/es-ni/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/es/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/es/NonVisibleControlContainer',{});
},
'Sage/QuickForms/Design/nls/es-ni/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/es-ni/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/es/Name':function(){
define('Sage/UI/Controls/nls/es/Name',{});
},
'Sage/UI/Controls/nls/es-ni/Name':function(){
define('Sage/UI/Controls/nls/es-ni/Name',{});
},
'Sage/MainView/JobMgr/nls/es/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es/ExecutionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/es-ni/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es-ni/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/es/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/PhoneControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ni/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ni/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/es/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/es/UpdateLeads',{});
},
'Sage/MainView/Lead/nls/es-ni/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/es-ni/UpdateLeads',{});
},
'Sage/Library/nls/es/FileHandler':function(){
define('Sage/Library/nls/es/FileHandler',{});
},
'Sage/Library/nls/es-ni/FileHandler':function(){
define('Sage/Library/nls/es-ni/FileHandler',{});
},
'Sage/UI/nls/es/ListPanel':function(){
define('Sage/UI/nls/es/ListPanel',{});
},
'Sage/UI/nls/es-ni/ListPanel':function(){
define('Sage/UI/nls/es-ni/ListPanel',{});
},
'Sage/Utility/nls/es/Sql':function(){
define('Sage/Utility/nls/es/Sql',{});
},
'Sage/Utility/nls/es-ni/Sql':function(){
define('Sage/Utility/nls/es-ni/Sql',{});
},
'Sage/UI/Filters/nls/es/EditFilters':function(){
define('Sage/UI/Filters/nls/es/EditFilters',{});
},
'Sage/UI/Filters/nls/es-ni/EditFilters':function(){
define('Sage/UI/Filters/nls/es-ni/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/es/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/FormUsagesPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ni/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ni/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/es/DurationSelect':function(){
define('Sage/UI/Controls/nls/es/DurationSelect',{});
},
'Sage/UI/Controls/nls/es-ni/DurationSelect':function(){
define('Sage/UI/Controls/nls/es-ni/DurationSelect',{});
},
'Sage/UI/Alarms/nls/es/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/es/AlarmCountDown',{});
},
'Sage/UI/Alarms/nls/es-ni/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/es-ni/AlarmCountDown',{});
},
'Sage/UI/nls/es/AttachmentList':function(){
define('Sage/UI/nls/es/AttachmentList',{});
},
'Sage/UI/nls/es-ni/AttachmentList':function(){
define('Sage/UI/nls/es-ni/AttachmentList',{});
},
'Sage/MailMerge/nls/es/Lookup':function(){
define('Sage/MailMerge/nls/es/Lookup',{});
},
'Sage/MailMerge/nls/es-ni/Lookup':function(){
define('Sage/MailMerge/nls/es-ni/Lookup',{});
},
'Sage/QuickForms/Design/Editors/nls/es/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ni/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ni/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/es/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/es/RunJobDialog',{});
},
'Sage/MainView/JobMgr/nls/es-ni/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/es-ni/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/es/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ni/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ni/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ni/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ni/EditableGridControlDesigner',{});
},
'Sage/MainView/Options/nls/es/OptionsDialog':function(){
define('Sage/MainView/Options/nls/es/OptionsDialog',{});
},
'Sage/MainView/Options/nls/es-ni/OptionsDialog':function(){
define('Sage/MainView/Options/nls/es-ni/OptionsDialog',{});
},
'Sage/QuickForms/Design/nls/es/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/HiddenControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ni/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ni/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/es/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/es/DashboardWidgetCell',{});
},
'Sage/UI/Dashboard/nls/es-ni/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/es-ni/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/es/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/UserBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ni/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ni/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/es/Dialogs':function(){
define('Sage/UI/nls/es/Dialogs',{});
},
'Sage/UI/nls/es-ni/Dialogs':function(){
define('Sage/UI/nls/es-ni/Dialogs',{});
},
'Sage/MainView/IntegrationContract/nls/es/SyncResultsHistory':function(){
define('Sage/MainView/IntegrationContract/nls/es/SyncResultsHistory',{});
},
'Sage/MainView/IntegrationContract/nls/es-ni/SyncResultsHistory':function(){
define('Sage/MainView/IntegrationContract/nls/es-ni/SyncResultsHistory',{});
},
'Sage/TaskPane/nls/es/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/es/SecuredActionTasklet',{});
},
'Sage/TaskPane/nls/es-ni/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/es-ni/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/es/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/es/DashboardTabController',{});
},
'Sage/UI/Dashboard/nls/es-ni/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/es-ni/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/es/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es/SalesOrderRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/es-ni/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es-ni/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/es/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/UserControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ni/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ni/UserControlDesigner',{});
},
'Sage/Groups/nls/es/GroupNavigator':function(){
define('Sage/Groups/nls/es/GroupNavigator',{});
},
'Sage/Groups/nls/es-ni/GroupNavigator':function(){
define('Sage/Groups/nls/es-ni/GroupNavigator',{});
},
'Sage/Utility/File/nls/es/AddURLAttachment':function(){
define('Sage/Utility/File/nls/es/AddURLAttachment',{});
},
'Sage/Utility/File/nls/es-ni/AddURLAttachment':function(){
define('Sage/Utility/File/nls/es-ni/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/es/EditFilterItems':function(){
define('Sage/UI/Filters/nls/es/EditFilterItems',{});
},
'Sage/UI/Filters/nls/es-ni/EditFilterItems':function(){
define('Sage/UI/Filters/nls/es-ni/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportsFormatter',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ni/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ni/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/es/DragDropWatcher':function(){
define('Sage/Utility/File/nls/es/DragDropWatcher',{});
},
'Sage/Utility/File/nls/es-ni/DragDropWatcher':function(){
define('Sage/Utility/File/nls/es-ni/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/es/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/es/DesignSurface',{});
},
'Sage/QuickForms/Design/nls/es-ni/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/es-ni/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/es/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-ni/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-ni/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/es/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/FormAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ni/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ni/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/EventListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-ni/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-ni/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/es/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/es/AllOpenListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/es-ni/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/es-ni/AllOpenListPanelConfig',{});
},
'Sage/MainView/nls/es/FormManager':function(){
define('Sage/MainView/nls/es/FormManager',{});
},
'Sage/MainView/nls/es-ni/FormManager':function(){
define('Sage/MainView/nls/es-ni/FormManager',{});
},
'Sage/UI/nls/es/ActivityScheduler':function(){
define('Sage/UI/nls/es/ActivityScheduler',{});
},
'Sage/UI/nls/es-ni/ActivityScheduler':function(){
define('Sage/UI/nls/es-ni/ActivityScheduler',{});
},
'Sage/MainView/nls/es/SecurityManager':function(){
define('Sage/MainView/nls/es/SecurityManager',{});
},
'Sage/MainView/nls/es-ni/SecurityManager':function(){
define('Sage/MainView/nls/es-ni/SecurityManager',{});
},
'Sage/TaskPane/nls/es/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/es/ActivityTaskConfigurationProvider',{});
},
'Sage/TaskPane/nls/es-ni/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/es-ni/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/es/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/es/EntityInfoToolTip',{});
},
'Sage/UI/Controls/nls/es-ni/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/es-ni/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/es-ni/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/es-ni/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es/AllOpenDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es/AllOpenDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es-ni/AllOpenDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es-ni/AllOpenDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/es/ReportsListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/es/ReportsListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/es-ni/ReportsListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/es-ni/ReportsListSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/es/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/es/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/Common/nls/es-ni/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/es-ni/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/templates/nls/es/ScheduleDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/es/ScheduleDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/es-ni/ScheduleDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/es-ni/ScheduleDetailSummary',{});
},
'Sage/MainView/Opportunity/nls/es/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/es/UpdateOpportunities',{});
},
'Sage/MainView/Opportunity/nls/es-ni/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/es-ni/UpdateOpportunities',{});
},
'Sage/UI/nls/es/EditCalendarUsers':function(){
define('Sage/UI/nls/es/EditCalendarUsers',{});
},
'Sage/UI/nls/es-ni/EditCalendarUsers':function(){
define('Sage/UI/nls/es-ni/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportParametersDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ni/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ni/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/es/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/DateTimePickerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ni/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ni/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/es/HelpMenu':function(){
define('Sage/UI/Controls/nls/es/HelpMenu',{});
},
'Sage/UI/Controls/nls/es-ni/HelpMenu':function(){
define('Sage/UI/Controls/nls/es-ni/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/es/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/LayoutPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ni/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ni/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/es/UserTasklet':function(){
define('Sage/TaskPane/nls/es/UserTasklet',{});
},
'Sage/TaskPane/nls/es-ni/UserTasklet':function(){
define('Sage/TaskPane/nls/es-ni/UserTasklet',{});
},
'Sage/UI/Alarms/nls/es/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/es/ActivityAlarm',{});
},
'Sage/UI/Alarms/nls/es-ni/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/es-ni/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/es/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/es/OpportunityStatistics',{});
},
'Sage/MainView/Opportunity/nls/es-ni/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/es-ni/OpportunityStatistics',{});
},
'Sage/TaskPane/nls/es/GroupListTasklet':function(){
define('Sage/TaskPane/nls/es/GroupListTasklet',{});
},
'Sage/TaskPane/nls/es-ni/GroupListTasklet':function(){
define('Sage/TaskPane/nls/es-ni/GroupListTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportConditionEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ni/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ni/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/es/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/es/AdvancedSearchOptions',{});
},
'Sage/MainView/IntegrationContract/nls/es-ni/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/es-ni/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/es/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/es/ColumnDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ni/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ni/ColumnDesigner',{});
},
'Sage/MainView/JobMgr/templates/nls/es/JobDefinitionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/es/JobDefinitionDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/es-ni/JobDefinitionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/es-ni/JobDefinitionDetailSummary',{});
},
'Sage/UI/nls/es/SearchMenuItem':function(){
define('Sage/UI/nls/es/SearchMenuItem',{});
},
'Sage/UI/nls/es-ni/SearchMenuItem':function(){
define('Sage/UI/nls/es-ni/SearchMenuItem',{});
},
'Sage/Library/nls/es/DocumentProperties':function(){
define('Sage/Library/nls/es/DocumentProperties',{});
},
'Sage/Library/nls/es-ni/DocumentProperties':function(){
define('Sage/Library/nls/es-ni/DocumentProperties',{});
},
'Sage/UI/nls/es/NotesHistoryList':function(){
define('Sage/UI/nls/es/NotesHistoryList',{});
},
'Sage/UI/nls/es-ni/NotesHistoryList':function(){
define('Sage/UI/nls/es-ni/NotesHistoryList',{});
},
'Sage/Utility/nls/es/File':function(){
define('Sage/Utility/nls/es/File',{});
},
'Sage/Utility/nls/es-ni/File':function(){
define('Sage/Utility/nls/es-ni/File',{});
},
'Sage/MainView/ReportMgr/nls/es/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/es-ni/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es-ni/HistoryListPanelConfig',{});
},
'Sage/MainView/JobMgr/templates/nls/es/ScheduleDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/es/ScheduleDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/es-ni/ScheduleDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/es-ni/ScheduleDetailSummary',{});
},
'Sage/QuickForms/Design/nls/es/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/UrlControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ni/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ni/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/es/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/es/ContactTasksTasklet',{});
},
'Sage/TaskPane/nls/es-ni/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/es-ni/ContactTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es/EventSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es/EventSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es-ni/EventSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es-ni/EventSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/es/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/es/_WizardDialogBase',{});
},
'Sage/MainView/ReportMgr/Common/nls/es-ni/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/es-ni/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/es/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es/SchedulesListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/es-ni/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es-ni/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/es/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/es/GoogleDocPicker',{});
},
'Sage/Utility/File/nls/es-ni/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/es-ni/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/es/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/ComboBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ni/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ni/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/es/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-ni/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-ni/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/HistoryEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-ni/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-ni/HistoryEditor',{});
},
'Sage/Groups/nls/es/GroupManager':function(){
define('Sage/Groups/nls/es/GroupManager',{});
},
'Sage/Groups/nls/es-ni/GroupManager':function(){
define('Sage/Groups/nls/es-ni/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/es/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ni/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ni/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/ComboBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ni/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ni/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportsListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/es-ni/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es-ni/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/es/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/es/JobNotificationButton',{});
},
'Sage/UI/Alarms/nls/es-ni/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/es-ni/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportWizardController',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ni/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ni/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/es/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/es-ni/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es-ni/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/RecurringEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-ni/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-ni/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportsUtility',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ni/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ni/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/es/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ni/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ni/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/es/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/es-ni/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es-ni/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/es/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ni/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ni/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ni/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ni/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ni/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ni/PickListControlDesigner',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es/LitRequestSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es/LitRequestSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es-ni/LitRequestSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es-ni/LitRequestSummary',{});
},
'Sage/QuickForms/Design/Editors/nls/es/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ni/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ni/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/es/FolderHandler':function(){
define('Sage/Library/nls/es/FolderHandler',{});
},
'Sage/Library/nls/es-ni/FolderHandler':function(){
define('Sage/Library/nls/es-ni/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/es/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ni/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ni/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/es/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/es/ContactSearchForDuplicates',{});
},
'Sage/MainView/Contact/nls/es-ni/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/es-ni/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/es/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/DateTimePickerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ni/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ni/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/es/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/es/AccountingTasksTasklet',{});
},
'Sage/TaskPane/nls/es-ni/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/es-ni/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/es/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ni/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ni/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/CurrencyBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ni/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ni/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/es/EditableGrid':function(){
define('Sage/UI/nls/es/EditableGrid',{});
},
'Sage/UI/nls/es-ni/EditableGrid':function(){
define('Sage/UI/nls/es-ni/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/es/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es/SalesQuoteRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/es-ni/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es-ni/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/es/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/es/SecurityProfile',{});
},
'Sage/MainView/SecurityMgr/nls/es-ni/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/es-ni/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportWizardController',{});
},
'Sage/MainView/ReportMgr/nls/es-ni/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/es-ni/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/es/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/UserAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ni/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ni/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportManagerUtility',{});
},
'Sage/MainView/ReportMgr/nls/es-ni/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/es-ni/ReportManagerUtility',{});
},
'Sage/UI/nls/es/SpeedSearch':function(){
define('Sage/UI/nls/es/SpeedSearch',{});
},
'Sage/UI/nls/es-ni/SpeedSearch':function(){
define('Sage/UI/nls/es-ni/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/es/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/CurrencyAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ni/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ni/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/es/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es/ReportManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/es-ni/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es-ni/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/es/SLXPreviewGrid':function(){
define('Sage/UI/nls/es/SLXPreviewGrid',{});
},
'Sage/UI/nls/es-ni/SLXPreviewGrid':function(){
define('Sage/UI/nls/es-ni/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/es/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/es/UnconfirmedPane',{});
},
'Sage/UI/Alarms/nls/es-ni/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/es-ni/UnconfirmedPane',{});
},
'Sage/Utility/nls/es/Utility':function(){
define('Sage/Utility/nls/es/Utility',{});
},
'Sage/Utility/nls/es-ni/Utility':function(){
define('Sage/Utility/nls/es-ni/Utility',{});
},
'Sage/QuickForms/Design/nls/es/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/ControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ni/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ni/ControlDesigner',{});
},
'Sage/UI/Controls/nls/es/Address':function(){
define('Sage/UI/Controls/nls/es/Address',{});
},
'Sage/UI/Controls/nls/es-ni/Address':function(){
define('Sage/UI/Controls/nls/es-ni/Address',{});
},
'Sage/MainView/JobMgr/nls/es/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/es/JobManagerGroupContextService',{});
},
'Sage/MainView/JobMgr/nls/es-ni/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/es-ni/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/es/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/BaseListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-ni/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-ni/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/es/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/OwnerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ni/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ni/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/es/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es/JobManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/es-ni/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es-ni/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/es-ni/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/es-ni/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/es/UserType':function(){
define('Sage/UI/nls/es/UserType',{});
},
'Sage/UI/nls/es-ni/UserType':function(){
define('Sage/UI/nls/es-ni/UserType',{});
},
'Sage/MainView/ReportMgr/templates/nls/es/HistoryDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/es/HistoryDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/es-ni/HistoryDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/es-ni/HistoryDetailSummary',{});
},
'Sage/QuickForms/Design/nls/es/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/es/FormDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ni/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ni/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityCalendar',{});
},
'Sage/MainView/ActivityMgr/nls/es-ni/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/es-ni/ActivityCalendar',{});
},
'Sage/Utility/nls/es/Jobs':function(){
define('Sage/Utility/nls/es/Jobs',{});
},
'Sage/Utility/nls/es-ni/Jobs':function(){
define('Sage/Utility/nls/es-ni/Jobs',{});
},
'Sage/UI/Controls/nls/es/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/es/_DialogHelpIconMixin',{});
},
'Sage/UI/Controls/nls/es-ni/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/es-ni/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/es/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/PickListAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ni/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ni/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/es/ActivityList':function(){
define('Sage/UI/nls/es/ActivityList',{});
},
'Sage/UI/nls/es-ni/ActivityList':function(){
define('Sage/UI/nls/es-ni/ActivityList',{});
},
'Sage/UI/Alarms/nls/es/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/es/JobNotificationPopup',{});
},
'Sage/UI/Alarms/nls/es-ni/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/es-ni/JobNotificationPopup',{});
},
'Sage/MainView/JobMgr/templates/nls/es/ExecutionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/es/ExecutionsListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/es-ni/ExecutionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/es-ni/ExecutionsListSummary',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/LeadLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-ni/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-ni/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/es/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es/SchedulesListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/es-ni/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es-ni/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/es/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/GenericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ni/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ni/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/es/CalendarUsersListPane':function(){
define('Sage/UI/nls/es/CalendarUsersListPane',{});
},
'Sage/UI/nls/es-ni/CalendarUsersListPane':function(){
define('Sage/UI/nls/es-ni/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/es/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ni/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ni/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/ColumnBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ni/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ni/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/templates/nls/es/ExecutionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/es/ExecutionDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/es-ni/ExecutionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/es-ni/ExecutionDetailSummary',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportManagerGroupContextService',{});
},
'Sage/MainView/ReportMgr/nls/es-ni/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/es-ni/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/es/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/es/MatchingOptionsConfig',{});
},
'Sage/MainView/IntegrationContract/nls/es-ni/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/es-ni/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/es/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/FormBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ni/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ni/FormBasicPropertyEditor',{});
},
'Sage/UI/Alarms/nls/es/AlarmButton':function(){
define('Sage/UI/Alarms/nls/es/AlarmButton',{});
},
'Sage/UI/Alarms/nls/es-ni/AlarmButton':function(){
define('Sage/UI/Alarms/nls/es-ni/AlarmButton',{});
},
'Sage/MainView/ActivityMgr/nls/es/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/es/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/MainView/ActivityMgr/nls/es-ni/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/es-ni/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/es/Attachment':function(){
define('Sage/Utility/File/nls/es/Attachment',{});
},
'Sage/Utility/File/nls/es-ni/Attachment':function(){
define('Sage/Utility/File/nls/es-ni/Attachment',{});
},
'Sage/QuickForms/Design/nls/es/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ni/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ni/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/es/PropertyEditorContainer',{});
},
'Sage/QuickForms/Design/nls/es-ni/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/es-ni/PropertyEditorContainer',{});
},
'Sage/Services/nls/es/ReportingService':function(){
define('Sage/Services/nls/es/ReportingService',{});
},
'Sage/Services/nls/es-ni/ReportingService':function(){
define('Sage/Services/nls/es-ni/ReportingService',{});
},
'Sage/MailMerge/nls/es/Helper':function(){
define('Sage/MailMerge/nls/es/Helper',{});
},
'Sage/MailMerge/nls/es-ni/Helper':function(){
define('Sage/MailMerge/nls/es-ni/Helper',{});
},
'Sage/UI/Dashboard/nls/es/Dashboard':function(){
define('Sage/UI/Dashboard/nls/es/Dashboard',{});
},
'Sage/UI/Dashboard/nls/es-ni/Dashboard':function(){
define('Sage/UI/Dashboard/nls/es-ni/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-ni/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-ni/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/es/PickList':function(){
define('Sage/UI/Controls/nls/es/PickList',{});
},
'Sage/UI/Controls/nls/es-ni/PickList':function(){
define('Sage/UI/Controls/nls/es-ni/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/es/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/es/HistoryEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/es-ni/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/es-ni/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/es/Email':function(){
define('Sage/Utility/nls/es/Email',{});
},
'Sage/Utility/nls/es-ni/Email':function(){
define('Sage/Utility/nls/es-ni/Email',{});
},
'Sage/TaskPane/nls/es/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es/SecurityManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/es-ni/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es-ni/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/es/TimeZoneItem':function(){
define('Sage/UI/nls/es/TimeZoneItem',{});
},
'Sage/UI/nls/es-ni/TimeZoneItem':function(){
define('Sage/UI/nls/es-ni/TimeZoneItem',{});
},
'Sage/MainView/ReportMgr/templates/nls/es/HistoryListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/es/HistoryListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/es-ni/HistoryListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/es-ni/HistoryListSummary',{});
},
'Sage/UI/Columns/nls/es/SlxEdit':function(){
define('Sage/UI/Columns/nls/es/SlxEdit',{});
},
'Sage/UI/Columns/nls/es-ni/SlxEdit':function(){
define('Sage/UI/Columns/nls/es-ni/SlxEdit',{});
},
'Sage/Reporting/nls/es/Enumerations':function(){
define('Sage/Reporting/nls/es/Enumerations',{});
},
'Sage/Reporting/nls/es-ni/Enumerations':function(){
define('Sage/Reporting/nls/es-ni/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/es/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ni/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ni/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportConditionsDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ni/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ni/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/es/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/es/ActivityListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/es-ni/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/es-ni/ActivityListPanelConfig',{});
},
'Sage/UI/nls/es/JobSchedulingWidget':function(){
define('Sage/UI/nls/es/JobSchedulingWidget',{});
},
'Sage/UI/nls/es-ni/JobSchedulingWidget':function(){
define('Sage/UI/nls/es-ni/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/es/LogOffButton':function(){
define('Sage/UI/Controls/nls/es/LogOffButton',{});
},
'Sage/UI/Controls/nls/es-ni/LogOffButton':function(){
define('Sage/UI/Controls/nls/es-ni/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/es/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/TextBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ni/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ni/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/EditEventEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-ni/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-ni/EditEventEditor',{});
},
'Sage/MailMerge/nls/es/Loader':function(){
define('Sage/MailMerge/nls/es/Loader',{});
},
'Sage/MailMerge/nls/es-ni/Loader':function(){
define('Sage/MailMerge/nls/es-ni/Loader',{});
},
'Sage/UI/Controls/nls/es/DateTimePicker':function(){
define('Sage/UI/Controls/nls/es/DateTimePicker',{});
},
'Sage/UI/Controls/nls/es-ni/DateTimePicker':function(){
define('Sage/UI/Controls/nls/es-ni/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportManagerActions',{});
},
'Sage/MainView/ReportMgr/nls/es-ni/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/es-ni/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/es/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/es/AlarmPopup',{});
},
'Sage/UI/Alarms/nls/es-ni/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/es-ni/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/es/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/es/ContactUserAssociationEditor',{});
},
'Sage/MainView/Contact/nls/es-ni/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/es-ni/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ni/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ni/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/es/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es/BaseListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/es-ni/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es-ni/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/es/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ni/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ni/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/EmailControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ni/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ni/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/es/Lookup':function(){
define('Sage/UI/Controls/nls/es/Lookup',{});
},
'Sage/UI/Controls/nls/es-ni/Lookup':function(){
define('Sage/UI/Controls/nls/es-ni/Lookup',{});
},
'Sage/Utility/File/nls/es/DescriptionsForm':function(){
define('Sage/Utility/File/nls/es/DescriptionsForm',{});
},
'Sage/Utility/File/nls/es-ni/DescriptionsForm':function(){
define('Sage/Utility/File/nls/es-ni/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/es/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/NumericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ni/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ni/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/es/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/es/CommonTasksTasklet',{});
},
'Sage/TaskPane/nls/es-ni/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/es-ni/CommonTasksTasklet',{});
},
'Sage/Utility/nls/es/Dashboard':function(){
define('Sage/Utility/nls/es/Dashboard',{});
},
'Sage/Utility/nls/es-ni/Dashboard':function(){
define('Sage/Utility/nls/es-ni/Dashboard',{});
}}});
define("Sage/nls/Sage_es-ni", [], 1);
