require({cache:{
'Sage/Utility/File/nls/ar/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/ar/FallbackFilePicker',{});
},
'Sage/Utility/File/nls/ar-bh/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/ar-bh/FallbackFilePicker',{});
},
'Sage/UI/nls/ar/Boolean':function(){
define('Sage/UI/nls/ar/Boolean',{});
},
'Sage/UI/nls/ar-bh/Boolean':function(){
define('Sage/UI/nls/ar-bh/Boolean',{});
},
'Sage/Services/nls/ar/ActivityService':function(){
define('Sage/Services/nls/ar/ActivityService',{});
},
'Sage/Services/nls/ar-bh/ActivityService':function(){
define('Sage/Services/nls/ar-bh/ActivityService',{});
},
'Sage/UI/Controls/nls/ar/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/ar/CopyToClipboard',{});
},
'Sage/UI/Controls/nls/ar-bh/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/ar-bh/CopyToClipboard',{});
},
'Sage/Utility/nls/ar/Activity':function(){
define('Sage/Utility/nls/ar/Activity',{});
},
'Sage/Utility/nls/ar-bh/Activity':function(){
define('Sage/Utility/nls/ar-bh/Activity',{});
},
'Sage/QuickForms/Design/nls/ar/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/ar/DesignPanel',{});
},
'Sage/QuickForms/Design/nls/ar-bh/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/ar-bh/DesignPanel',{});
},
'Sage/UI/nls/ar/TimelessActivitiesPane':function(){
define('Sage/UI/nls/ar/TimelessActivitiesPane',{});
},
'Sage/UI/nls/ar-bh/TimelessActivitiesPane':function(){
define('Sage/UI/nls/ar-bh/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-bh/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-bh/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/ar/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/ar/ContactUserAssociationEditor',{});
},
'Sage/TaskPane/User/nls/ar-bh/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/ar-bh/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/ar/ActivityManager':function(){
define('Sage/MainView/nls/ar/ActivityManager',{});
},
'Sage/MainView/nls/ar-bh/ActivityManager':function(){
define('Sage/MainView/nls/ar-bh/ActivityManager',{});
},
'Sage/Services/nls/ar/JobService':function(){
define('Sage/Services/nls/ar/JobService',{});
},
'Sage/Services/nls/ar-bh/JobService':function(){
define('Sage/Services/nls/ar-bh/JobService',{});
},
'Sage/QuickForms/Design/nls/ar/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-bh/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-bh/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/_PropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-bh/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-bh/_PropertyEditor',{});
},
'Sage/Services/nls/ar/ActivityActionProcessor':function(){
define('Sage/Services/nls/ar/ActivityActionProcessor',{});
},
'Sage/Services/nls/ar-bh/ActivityActionProcessor':function(){
define('Sage/Services/nls/ar-bh/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/TextBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-bh/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-bh/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-bh/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-bh/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar/UserActivityDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar/UserActivityDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar-bh/UserActivityDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar-bh/UserActivityDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar/ConfirmationDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar/ConfirmationDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar-bh/ConfirmationDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar-bh/ConfirmationDetailSummary',{});
},
'Sage/Utility/File/nls/ar/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/ar/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/ar-bh/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/ar-bh/DefaultDropHandler',{});
},
'Sage/UI/nls/ar/TransferBoxWidget':function(){
define('Sage/UI/nls/ar/TransferBoxWidget',{});
},
'Sage/UI/nls/ar-bh/TransferBoxWidget':function(){
define('Sage/UI/nls/ar-bh/TransferBoxWidget',{});
},
'Sage/Utility/File/nls/ar/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/ar/AttachmentPropertiesEditForm',{});
},
'Sage/Utility/File/nls/ar-bh/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/ar-bh/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/ar/AlarmPane':function(){
define('Sage/UI/Alarms/nls/ar/AlarmPane',{});
},
'Sage/UI/Alarms/nls/ar-bh/AlarmPane':function(){
define('Sage/UI/Alarms/nls/ar-bh/AlarmPane',{});
},
'Sage/TaskPane/nls/ar/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/ar/LiteratureManagementTasks',{});
},
'Sage/TaskPane/nls/ar-bh/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/ar-bh/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/ar/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/ar/DashboardWidget',{});
},
'Sage/UI/Dashboard/nls/ar-bh/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/ar-bh/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/NumericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-bh/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-bh/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ar/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar/CustomerPaymentsRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/ar-bh/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar-bh/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/ar/FilterPanel':function(){
define('Sage/UI/Filters/nls/ar/FilterPanel',{});
},
'Sage/UI/Filters/nls/ar-bh/FilterPanel':function(){
define('Sage/UI/Filters/nls/ar-bh/FilterPanel',{});
},
'Sage/TaskPane/nls/ar/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/ar/_BaseTaskPaneTasklet',{});
},
'Sage/TaskPane/nls/ar-bh/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/ar-bh/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/ar/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/ar/ReportManagerFormatter',{});
},
'Sage/MainView/ReportMgr/nls/ar-bh/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/ar-bh/ReportManagerFormatter',{});
},
'Sage/UI/nls/ar/OwnerType':function(){
define('Sage/UI/nls/ar/OwnerType',{});
},
'Sage/UI/nls/ar-bh/OwnerType':function(){
define('Sage/UI/nls/ar-bh/OwnerType',{});
},
'Sage/MainView/JobMgr/templates/nls/ar/JobDefinitionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar/JobDefinitionsListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/ar-bh/JobDefinitionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar-bh/JobDefinitionsListSummary',{});
},
'Sage/TaskPane/nls/ar/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/LeadTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-bh/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-bh/LeadTasksTasklet',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar/ReportDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar/ReportDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar-bh/ReportDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar-bh/ReportDetailSummary',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/_ParameterEditorBase':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/_ParameterEditorBase',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-bh/_ParameterEditorBase':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-bh/_ParameterEditorBase',{});
},
'Sage/MailMerge/nls/ar/Service':function(){
define('Sage/MailMerge/nls/ar/Service',{});
},
'Sage/MailMerge/nls/ar-bh/Service':function(){
define('Sage/MailMerge/nls/ar-bh/Service',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar/ConfirmationListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar/ConfirmationListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar-bh/ConfirmationListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar-bh/ConfirmationListSummary',{});
},
'Sage/MainView/ActivityMgr/nls/ar/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/ar/SnoozeOptions',{});
},
'Sage/MainView/ActivityMgr/nls/ar-bh/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/ar-bh/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-bh/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-bh/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-bh/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-bh/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ar/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar/InvoiceRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/ar-bh/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar-bh/InvoiceRTDV',{});
},
'Sage/UI/nls/ar/SDataLookup':function(){
define('Sage/UI/nls/ar/SDataLookup',{});
},
'Sage/UI/nls/ar-bh/SDataLookup':function(){
define('Sage/UI/nls/ar-bh/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/ar/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/RowDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-bh/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-bh/RowDesigner',{});
},
'Sage/Groups/nls/ar/GroupLookup':function(){
define('Sage/Groups/nls/ar/GroupLookup',{});
},
'Sage/Groups/nls/ar-bh/GroupLookup':function(){
define('Sage/Groups/nls/ar-bh/GroupLookup',{});
},
'Sage/TaskPane/nls/ar/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/OpportunityTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-bh/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-bh/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/ar/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/ar/CheckBoxFilter',{});
},
'Sage/UI/Filters/nls/ar-bh/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/ar-bh/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/ar/LibraryDocument':function(){
define('Sage/Utility/File/nls/ar/LibraryDocument',{});
},
'Sage/Utility/File/nls/ar-bh/LibraryDocument':function(){
define('Sage/Utility/File/nls/ar-bh/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar/SpeedSearchLookup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar-bh/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar-bh/SpeedSearchLookup',{});
},
'Sage/UI/nls/ar/ConditionManager':function(){
define('Sage/UI/nls/ar/ConditionManager',{});
},
'Sage/UI/nls/ar-bh/ConditionManager':function(){
define('Sage/UI/nls/ar-bh/ConditionManager',{});
},
'Sage/MainView/JobMgr/templates/nls/ar/SchedulesListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar/SchedulesListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/ar-bh/SchedulesListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar-bh/SchedulesListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar/UserActivityListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar/UserActivityListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar-bh/UserActivityListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar-bh/UserActivityListSummary',{});
},
'Sage/UI/Dashboard/nls/ar/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/ar/WidgetDefinition',{});
},
'Sage/UI/Dashboard/nls/ar-bh/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/ar-bh/WidgetDefinition',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar/AllOpenListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar/AllOpenListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar-bh/AllOpenListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar-bh/AllOpenListSummary',{});
},
'Sage/UI/nls/ar/SearchConditionWidget':function(){
define('Sage/UI/nls/ar/SearchConditionWidget',{});
},
'Sage/UI/nls/ar-bh/SearchConditionWidget':function(){
define('Sage/UI/nls/ar-bh/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-bh/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-bh/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ar/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/ar/JobManagerActions',{});
},
'Sage/MainView/JobMgr/nls/ar-bh/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/ar-bh/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar/ContactLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar-bh/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar-bh/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/ar/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/ar/DataSourcePanel',{});
},
'Sage/QuickForms/Design/nls/ar-bh/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/ar-bh/DataSourcePanel',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar/SchedulesListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar/SchedulesListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar-bh/SchedulesListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar-bh/SchedulesListSummary',{});
},
'Sage/Library/nls/ar/Manager':function(){
define('Sage/Library/nls/ar/Manager',{});
},
'Sage/Library/nls/ar-bh/Manager':function(){
define('Sage/Library/nls/ar-bh/Manager',{});
},
'Sage/UI/nls/ar/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/ar/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/nls/ar-bh/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/ar-bh/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/ar/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/ar/NonVisibleControlContainer',{});
},
'Sage/QuickForms/Design/nls/ar-bh/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/ar-bh/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/ar/Name':function(){
define('Sage/UI/Controls/nls/ar/Name',{});
},
'Sage/UI/Controls/nls/ar-bh/Name':function(){
define('Sage/UI/Controls/nls/ar-bh/Name',{});
},
'Sage/MainView/JobMgr/nls/ar/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar/ExecutionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/ar-bh/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar-bh/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ar/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/PhoneControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-bh/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-bh/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/ar/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/ar/UpdateLeads',{});
},
'Sage/MainView/Lead/nls/ar-bh/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/ar-bh/UpdateLeads',{});
},
'Sage/Library/nls/ar/FileHandler':function(){
define('Sage/Library/nls/ar/FileHandler',{});
},
'Sage/Library/nls/ar-bh/FileHandler':function(){
define('Sage/Library/nls/ar-bh/FileHandler',{});
},
'Sage/UI/nls/ar/ListPanel':function(){
define('Sage/UI/nls/ar/ListPanel',{});
},
'Sage/UI/nls/ar-bh/ListPanel':function(){
define('Sage/UI/nls/ar-bh/ListPanel',{});
},
'Sage/Utility/nls/ar/Sql':function(){
define('Sage/Utility/nls/ar/Sql',{});
},
'Sage/Utility/nls/ar-bh/Sql':function(){
define('Sage/Utility/nls/ar-bh/Sql',{});
},
'Sage/UI/Filters/nls/ar/EditFilters':function(){
define('Sage/UI/Filters/nls/ar/EditFilters',{});
},
'Sage/UI/Filters/nls/ar-bh/EditFilters':function(){
define('Sage/UI/Filters/nls/ar-bh/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/FormUsagesPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-bh/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-bh/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/ar/DurationSelect':function(){
define('Sage/UI/Controls/nls/ar/DurationSelect',{});
},
'Sage/UI/Controls/nls/ar-bh/DurationSelect':function(){
define('Sage/UI/Controls/nls/ar-bh/DurationSelect',{});
},
'Sage/UI/Alarms/nls/ar/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/ar/AlarmCountDown',{});
},
'Sage/UI/Alarms/nls/ar-bh/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/ar-bh/AlarmCountDown',{});
},
'Sage/UI/nls/ar/AttachmentList':function(){
define('Sage/UI/nls/ar/AttachmentList',{});
},
'Sage/UI/nls/ar-bh/AttachmentList':function(){
define('Sage/UI/nls/ar-bh/AttachmentList',{});
},
'Sage/MailMerge/nls/ar/Lookup':function(){
define('Sage/MailMerge/nls/ar/Lookup',{});
},
'Sage/MailMerge/nls/ar-bh/Lookup':function(){
define('Sage/MailMerge/nls/ar-bh/Lookup',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-bh/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-bh/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ar/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/ar/RunJobDialog',{});
},
'Sage/MainView/JobMgr/nls/ar-bh/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/ar-bh/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/ar/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-bh/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-bh/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-bh/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-bh/EditableGridControlDesigner',{});
},
'Sage/MainView/Options/nls/ar/OptionsDialog':function(){
define('Sage/MainView/Options/nls/ar/OptionsDialog',{});
},
'Sage/MainView/Options/nls/ar-bh/OptionsDialog':function(){
define('Sage/MainView/Options/nls/ar-bh/OptionsDialog',{});
},
'Sage/QuickForms/Design/nls/ar/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/HiddenControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-bh/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-bh/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/ar/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/ar/DashboardWidgetCell',{});
},
'Sage/UI/Dashboard/nls/ar-bh/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/ar-bh/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/UserBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-bh/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-bh/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/ar/Dialogs':function(){
define('Sage/UI/nls/ar/Dialogs',{});
},
'Sage/UI/nls/ar-bh/Dialogs':function(){
define('Sage/UI/nls/ar-bh/Dialogs',{});
},
'Sage/MainView/IntegrationContract/nls/ar/SyncResultsHistory':function(){
define('Sage/MainView/IntegrationContract/nls/ar/SyncResultsHistory',{});
},
'Sage/MainView/IntegrationContract/nls/ar-bh/SyncResultsHistory':function(){
define('Sage/MainView/IntegrationContract/nls/ar-bh/SyncResultsHistory',{});
},
'Sage/TaskPane/nls/ar/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/ar/SecuredActionTasklet',{});
},
'Sage/TaskPane/nls/ar-bh/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/ar-bh/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/ar/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/ar/DashboardTabController',{});
},
'Sage/UI/Dashboard/nls/ar-bh/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/ar-bh/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/ar/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar/SalesOrderRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/ar-bh/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar-bh/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/ar/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/UserControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-bh/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-bh/UserControlDesigner',{});
},
'Sage/Groups/nls/ar/GroupNavigator':function(){
define('Sage/Groups/nls/ar/GroupNavigator',{});
},
'Sage/Groups/nls/ar-bh/GroupNavigator':function(){
define('Sage/Groups/nls/ar-bh/GroupNavigator',{});
},
'Sage/Utility/File/nls/ar/AddURLAttachment':function(){
define('Sage/Utility/File/nls/ar/AddURLAttachment',{});
},
'Sage/Utility/File/nls/ar-bh/AddURLAttachment':function(){
define('Sage/Utility/File/nls/ar-bh/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/ar/EditFilterItems':function(){
define('Sage/UI/Filters/nls/ar/EditFilterItems',{});
},
'Sage/UI/Filters/nls/ar-bh/EditFilterItems':function(){
define('Sage/UI/Filters/nls/ar-bh/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportsFormatter',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-bh/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-bh/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/ar/DragDropWatcher':function(){
define('Sage/Utility/File/nls/ar/DragDropWatcher',{});
},
'Sage/Utility/File/nls/ar-bh/DragDropWatcher':function(){
define('Sage/Utility/File/nls/ar-bh/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/ar/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/ar/DesignSurface',{});
},
'Sage/QuickForms/Design/nls/ar-bh/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/ar-bh/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-bh/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-bh/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/FormAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-bh/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-bh/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/EventListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-bh/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-bh/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ar/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ar/AllOpenListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ar-bh/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ar-bh/AllOpenListPanelConfig',{});
},
'Sage/MainView/nls/ar/FormManager':function(){
define('Sage/MainView/nls/ar/FormManager',{});
},
'Sage/MainView/nls/ar-bh/FormManager':function(){
define('Sage/MainView/nls/ar-bh/FormManager',{});
},
'Sage/UI/nls/ar/ActivityScheduler':function(){
define('Sage/UI/nls/ar/ActivityScheduler',{});
},
'Sage/UI/nls/ar-bh/ActivityScheduler':function(){
define('Sage/UI/nls/ar-bh/ActivityScheduler',{});
},
'Sage/MainView/nls/ar/SecurityManager':function(){
define('Sage/MainView/nls/ar/SecurityManager',{});
},
'Sage/MainView/nls/ar-bh/SecurityManager':function(){
define('Sage/MainView/nls/ar-bh/SecurityManager',{});
},
'Sage/TaskPane/nls/ar/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/ar/ActivityTaskConfigurationProvider',{});
},
'Sage/TaskPane/nls/ar-bh/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/ar-bh/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/ar/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/ar/EntityInfoToolTip',{});
},
'Sage/UI/Controls/nls/ar-bh/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/ar-bh/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/ar-bh/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/ar-bh/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar/AllOpenDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar/AllOpenDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar-bh/AllOpenDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar-bh/AllOpenDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar/ReportsListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar/ReportsListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar-bh/ReportsListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar-bh/ReportsListSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/ar/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/ar/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/Common/nls/ar-bh/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/ar-bh/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar/ScheduleDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar/ScheduleDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar-bh/ScheduleDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar-bh/ScheduleDetailSummary',{});
},
'Sage/MainView/Opportunity/nls/ar/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/ar/UpdateOpportunities',{});
},
'Sage/MainView/Opportunity/nls/ar-bh/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/ar-bh/UpdateOpportunities',{});
},
'Sage/UI/nls/ar/EditCalendarUsers':function(){
define('Sage/UI/nls/ar/EditCalendarUsers',{});
},
'Sage/UI/nls/ar-bh/EditCalendarUsers':function(){
define('Sage/UI/nls/ar-bh/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportParametersDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-bh/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-bh/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/ar/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/DateTimePickerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-bh/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-bh/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/ar/HelpMenu':function(){
define('Sage/UI/Controls/nls/ar/HelpMenu',{});
},
'Sage/UI/Controls/nls/ar-bh/HelpMenu':function(){
define('Sage/UI/Controls/nls/ar-bh/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/LayoutPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-bh/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-bh/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/ar/UserTasklet':function(){
define('Sage/TaskPane/nls/ar/UserTasklet',{});
},
'Sage/TaskPane/nls/ar-bh/UserTasklet':function(){
define('Sage/TaskPane/nls/ar-bh/UserTasklet',{});
},
'Sage/UI/Alarms/nls/ar/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/ar/ActivityAlarm',{});
},
'Sage/UI/Alarms/nls/ar-bh/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/ar-bh/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/ar/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/ar/OpportunityStatistics',{});
},
'Sage/MainView/Opportunity/nls/ar-bh/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/ar-bh/OpportunityStatistics',{});
},
'Sage/TaskPane/nls/ar/GroupListTasklet':function(){
define('Sage/TaskPane/nls/ar/GroupListTasklet',{});
},
'Sage/TaskPane/nls/ar-bh/GroupListTasklet':function(){
define('Sage/TaskPane/nls/ar-bh/GroupListTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportConditionEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-bh/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-bh/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ar/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/ar/AdvancedSearchOptions',{});
},
'Sage/MainView/IntegrationContract/nls/ar-bh/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/ar-bh/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/ar/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/ColumnDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-bh/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-bh/ColumnDesigner',{});
},
'Sage/MainView/JobMgr/templates/nls/ar/JobDefinitionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar/JobDefinitionDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/ar-bh/JobDefinitionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar-bh/JobDefinitionDetailSummary',{});
},
'Sage/UI/nls/ar/SearchMenuItem':function(){
define('Sage/UI/nls/ar/SearchMenuItem',{});
},
'Sage/UI/nls/ar-bh/SearchMenuItem':function(){
define('Sage/UI/nls/ar-bh/SearchMenuItem',{});
},
'Sage/Library/nls/ar/DocumentProperties':function(){
define('Sage/Library/nls/ar/DocumentProperties',{});
},
'Sage/Library/nls/ar-bh/DocumentProperties':function(){
define('Sage/Library/nls/ar-bh/DocumentProperties',{});
},
'Sage/UI/nls/ar/NotesHistoryList':function(){
define('Sage/UI/nls/ar/NotesHistoryList',{});
},
'Sage/UI/nls/ar-bh/NotesHistoryList':function(){
define('Sage/UI/nls/ar-bh/NotesHistoryList',{});
},
'Sage/Utility/nls/ar/File':function(){
define('Sage/Utility/nls/ar/File',{});
},
'Sage/Utility/nls/ar-bh/File':function(){
define('Sage/Utility/nls/ar-bh/File',{});
},
'Sage/MainView/ReportMgr/nls/ar/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/ar-bh/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar-bh/HistoryListPanelConfig',{});
},
'Sage/MainView/JobMgr/templates/nls/ar/ScheduleDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar/ScheduleDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/ar-bh/ScheduleDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar-bh/ScheduleDetailSummary',{});
},
'Sage/QuickForms/Design/nls/ar/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/UrlControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-bh/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-bh/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/ar/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/ContactTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-bh/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-bh/ContactTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar/EventSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar/EventSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar-bh/EventSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar-bh/EventSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/ar/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/ar/_WizardDialogBase',{});
},
'Sage/MainView/ReportMgr/Common/nls/ar-bh/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/ar-bh/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/ar/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar/SchedulesListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/ar-bh/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar-bh/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/ar/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/ar/GoogleDocPicker',{});
},
'Sage/Utility/File/nls/ar-bh/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/ar-bh/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/ar/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/ComboBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-bh/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-bh/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/ar/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-bh/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-bh/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/HistoryEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-bh/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-bh/HistoryEditor',{});
},
'Sage/Groups/nls/ar/GroupManager':function(){
define('Sage/Groups/nls/ar/GroupManager',{});
},
'Sage/Groups/nls/ar-bh/GroupManager':function(){
define('Sage/Groups/nls/ar-bh/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-bh/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-bh/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/ComboBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-bh/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-bh/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ar/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar/ReportsListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/ar-bh/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar-bh/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/ar/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/ar/JobNotificationButton',{});
},
'Sage/UI/Alarms/nls/ar-bh/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/ar-bh/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportWizardController',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-bh/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-bh/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/ar/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/ar-bh/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar-bh/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/RecurringEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-bh/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-bh/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportsUtility',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-bh/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-bh/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-bh/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-bh/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ar/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/ar-bh/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar-bh/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ar/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-bh/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-bh/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-bh/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-bh/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-bh/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-bh/PickListControlDesigner',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar/LitRequestSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar/LitRequestSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar-bh/LitRequestSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar-bh/LitRequestSummary',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-bh/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-bh/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/ar/FolderHandler':function(){
define('Sage/Library/nls/ar/FolderHandler',{});
},
'Sage/Library/nls/ar-bh/FolderHandler':function(){
define('Sage/Library/nls/ar-bh/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-bh/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-bh/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/ar/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/ar/ContactSearchForDuplicates',{});
},
'Sage/MainView/Contact/nls/ar-bh/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/ar-bh/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/DateTimePickerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-bh/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-bh/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/ar/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/AccountingTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-bh/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-bh/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-bh/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-bh/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/CurrencyBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-bh/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-bh/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/ar/EditableGrid':function(){
define('Sage/UI/nls/ar/EditableGrid',{});
},
'Sage/UI/nls/ar-bh/EditableGrid':function(){
define('Sage/UI/nls/ar-bh/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/ar/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar/SalesQuoteRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/ar-bh/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar-bh/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/ar/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/ar/SecurityProfile',{});
},
'Sage/MainView/SecurityMgr/nls/ar-bh/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/ar-bh/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/ar/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/ar/ReportWizardController',{});
},
'Sage/MainView/ReportMgr/nls/ar-bh/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/ar-bh/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/UserAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-bh/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-bh/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ar/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/ar/ReportManagerUtility',{});
},
'Sage/MainView/ReportMgr/nls/ar-bh/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/ar-bh/ReportManagerUtility',{});
},
'Sage/UI/nls/ar/SpeedSearch':function(){
define('Sage/UI/nls/ar/SpeedSearch',{});
},
'Sage/UI/nls/ar-bh/SpeedSearch':function(){
define('Sage/UI/nls/ar-bh/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/CurrencyAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-bh/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-bh/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/ar/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/ReportManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-bh/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-bh/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/ar/SLXPreviewGrid':function(){
define('Sage/UI/nls/ar/SLXPreviewGrid',{});
},
'Sage/UI/nls/ar-bh/SLXPreviewGrid':function(){
define('Sage/UI/nls/ar-bh/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/ar/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/ar/UnconfirmedPane',{});
},
'Sage/UI/Alarms/nls/ar-bh/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/ar-bh/UnconfirmedPane',{});
},
'Sage/Utility/nls/ar/Utility':function(){
define('Sage/Utility/nls/ar/Utility',{});
},
'Sage/Utility/nls/ar-bh/Utility':function(){
define('Sage/Utility/nls/ar-bh/Utility',{});
},
'Sage/QuickForms/Design/nls/ar/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/ControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-bh/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-bh/ControlDesigner',{});
},
'Sage/UI/Controls/nls/ar/Address':function(){
define('Sage/UI/Controls/nls/ar/Address',{});
},
'Sage/UI/Controls/nls/ar-bh/Address':function(){
define('Sage/UI/Controls/nls/ar-bh/Address',{});
},
'Sage/MainView/JobMgr/nls/ar/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/ar/JobManagerGroupContextService',{});
},
'Sage/MainView/JobMgr/nls/ar-bh/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/ar-bh/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/ar/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/BaseListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-bh/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-bh/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ar/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/OwnerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-bh/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-bh/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/ar/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/JobManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-bh/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-bh/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/ar-bh/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ar-bh/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/ar/UserType':function(){
define('Sage/UI/nls/ar/UserType',{});
},
'Sage/UI/nls/ar-bh/UserType':function(){
define('Sage/UI/nls/ar-bh/UserType',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar/HistoryDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar/HistoryDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar-bh/HistoryDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar-bh/HistoryDetailSummary',{});
},
'Sage/QuickForms/Design/nls/ar/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/FormDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-bh/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-bh/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityCalendar',{});
},
'Sage/MainView/ActivityMgr/nls/ar-bh/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/ar-bh/ActivityCalendar',{});
},
'Sage/Utility/nls/ar/Jobs':function(){
define('Sage/Utility/nls/ar/Jobs',{});
},
'Sage/Utility/nls/ar-bh/Jobs':function(){
define('Sage/Utility/nls/ar-bh/Jobs',{});
},
'Sage/UI/Controls/nls/ar/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/ar/_DialogHelpIconMixin',{});
},
'Sage/UI/Controls/nls/ar-bh/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/ar-bh/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/PickListAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-bh/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-bh/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/ar/ActivityList':function(){
define('Sage/UI/nls/ar/ActivityList',{});
},
'Sage/UI/nls/ar-bh/ActivityList':function(){
define('Sage/UI/nls/ar-bh/ActivityList',{});
},
'Sage/UI/Alarms/nls/ar/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/ar/JobNotificationPopup',{});
},
'Sage/UI/Alarms/nls/ar-bh/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/ar-bh/JobNotificationPopup',{});
},
'Sage/MainView/JobMgr/templates/nls/ar/ExecutionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar/ExecutionsListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/ar-bh/ExecutionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar-bh/ExecutionsListSummary',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar/LeadLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar-bh/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar-bh/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/ar/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar/SchedulesListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/ar-bh/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar-bh/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/GenericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-bh/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-bh/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/ar/CalendarUsersListPane':function(){
define('Sage/UI/nls/ar/CalendarUsersListPane',{});
},
'Sage/UI/nls/ar-bh/CalendarUsersListPane':function(){
define('Sage/UI/nls/ar-bh/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-bh/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-bh/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/ColumnBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-bh/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-bh/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/templates/nls/ar/ExecutionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar/ExecutionDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/ar-bh/ExecutionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar-bh/ExecutionDetailSummary',{});
},
'Sage/MainView/ReportMgr/nls/ar/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/ar/ReportManagerGroupContextService',{});
},
'Sage/MainView/ReportMgr/nls/ar-bh/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/ar-bh/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/ar/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/ar/MatchingOptionsConfig',{});
},
'Sage/MainView/IntegrationContract/nls/ar-bh/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/ar-bh/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/FormBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-bh/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-bh/FormBasicPropertyEditor',{});
},
'Sage/UI/Alarms/nls/ar/AlarmButton':function(){
define('Sage/UI/Alarms/nls/ar/AlarmButton',{});
},
'Sage/UI/Alarms/nls/ar-bh/AlarmButton':function(){
define('Sage/UI/Alarms/nls/ar-bh/AlarmButton',{});
},
'Sage/MainView/ActivityMgr/nls/ar/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/ar/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/MainView/ActivityMgr/nls/ar-bh/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/ar-bh/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/ar/Attachment':function(){
define('Sage/Utility/File/nls/ar/Attachment',{});
},
'Sage/Utility/File/nls/ar-bh/Attachment':function(){
define('Sage/Utility/File/nls/ar-bh/Attachment',{});
},
'Sage/QuickForms/Design/nls/ar/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-bh/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-bh/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/ar/PropertyEditorContainer',{});
},
'Sage/QuickForms/Design/nls/ar-bh/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/ar-bh/PropertyEditorContainer',{});
},
'Sage/Services/nls/ar/ReportingService':function(){
define('Sage/Services/nls/ar/ReportingService',{});
},
'Sage/Services/nls/ar-bh/ReportingService':function(){
define('Sage/Services/nls/ar-bh/ReportingService',{});
},
'Sage/MailMerge/nls/ar/Helper':function(){
define('Sage/MailMerge/nls/ar/Helper',{});
},
'Sage/MailMerge/nls/ar-bh/Helper':function(){
define('Sage/MailMerge/nls/ar-bh/Helper',{});
},
'Sage/UI/Dashboard/nls/ar/Dashboard':function(){
define('Sage/UI/Dashboard/nls/ar/Dashboard',{});
},
'Sage/UI/Dashboard/nls/ar-bh/Dashboard':function(){
define('Sage/UI/Dashboard/nls/ar-bh/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-bh/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-bh/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/ar/PickList':function(){
define('Sage/UI/Controls/nls/ar/PickList',{});
},
'Sage/UI/Controls/nls/ar-bh/PickList':function(){
define('Sage/UI/Controls/nls/ar-bh/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/ar/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ar/HistoryEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/ar-bh/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ar-bh/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/ar/Email':function(){
define('Sage/Utility/nls/ar/Email',{});
},
'Sage/Utility/nls/ar-bh/Email':function(){
define('Sage/Utility/nls/ar-bh/Email',{});
},
'Sage/TaskPane/nls/ar/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/SecurityManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-bh/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-bh/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/ar/TimeZoneItem':function(){
define('Sage/UI/nls/ar/TimeZoneItem',{});
},
'Sage/UI/nls/ar-bh/TimeZoneItem':function(){
define('Sage/UI/nls/ar-bh/TimeZoneItem',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar/HistoryListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar/HistoryListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar-bh/HistoryListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar-bh/HistoryListSummary',{});
},
'Sage/UI/Columns/nls/ar/SlxEdit':function(){
define('Sage/UI/Columns/nls/ar/SlxEdit',{});
},
'Sage/UI/Columns/nls/ar-bh/SlxEdit':function(){
define('Sage/UI/Columns/nls/ar-bh/SlxEdit',{});
},
'Sage/Reporting/nls/ar/Enumerations':function(){
define('Sage/Reporting/nls/ar/Enumerations',{});
},
'Sage/Reporting/nls/ar-bh/Enumerations':function(){
define('Sage/Reporting/nls/ar-bh/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-bh/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-bh/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportConditionsDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-bh/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-bh/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ar/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ar/ActivityListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ar-bh/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ar-bh/ActivityListPanelConfig',{});
},
'Sage/UI/nls/ar/JobSchedulingWidget':function(){
define('Sage/UI/nls/ar/JobSchedulingWidget',{});
},
'Sage/UI/nls/ar-bh/JobSchedulingWidget':function(){
define('Sage/UI/nls/ar-bh/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/ar/LogOffButton':function(){
define('Sage/UI/Controls/nls/ar/LogOffButton',{});
},
'Sage/UI/Controls/nls/ar-bh/LogOffButton':function(){
define('Sage/UI/Controls/nls/ar-bh/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/TextBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-bh/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-bh/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/EditEventEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-bh/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-bh/EditEventEditor',{});
},
'Sage/MailMerge/nls/ar/Loader':function(){
define('Sage/MailMerge/nls/ar/Loader',{});
},
'Sage/MailMerge/nls/ar-bh/Loader':function(){
define('Sage/MailMerge/nls/ar-bh/Loader',{});
},
'Sage/UI/Controls/nls/ar/DateTimePicker':function(){
define('Sage/UI/Controls/nls/ar/DateTimePicker',{});
},
'Sage/UI/Controls/nls/ar-bh/DateTimePicker':function(){
define('Sage/UI/Controls/nls/ar-bh/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/ar/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/ar/ReportManagerActions',{});
},
'Sage/MainView/ReportMgr/nls/ar-bh/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/ar-bh/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/ar/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/ar/AlarmPopup',{});
},
'Sage/UI/Alarms/nls/ar-bh/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/ar-bh/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/ar/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/ar/ContactUserAssociationEditor',{});
},
'Sage/MainView/Contact/nls/ar-bh/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/ar-bh/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-bh/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-bh/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ar/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar/BaseListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/ar-bh/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar-bh/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ar/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-bh/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-bh/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/EmailControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-bh/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-bh/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/ar/Lookup':function(){
define('Sage/UI/Controls/nls/ar/Lookup',{});
},
'Sage/UI/Controls/nls/ar-bh/Lookup':function(){
define('Sage/UI/Controls/nls/ar-bh/Lookup',{});
},
'Sage/Utility/File/nls/ar/DescriptionsForm':function(){
define('Sage/Utility/File/nls/ar/DescriptionsForm',{});
},
'Sage/Utility/File/nls/ar-bh/DescriptionsForm':function(){
define('Sage/Utility/File/nls/ar-bh/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/NumericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-bh/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-bh/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/ar/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/CommonTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-bh/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-bh/CommonTasksTasklet',{});
},
'Sage/Utility/nls/ar/Dashboard':function(){
define('Sage/Utility/nls/ar/Dashboard',{});
},
'Sage/Utility/nls/ar-bh/Dashboard':function(){
define('Sage/Utility/nls/ar-bh/Dashboard',{});
}}});
define("Sage/nls/Sage_ar-bh", [], 1);
