require({cache:{
'Sage/Utility/File/nls/ar/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/ar/FallbackFilePicker',{});
},
'Sage/Utility/File/nls/ar-ae/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/ar-ae/FallbackFilePicker',{});
},
'Sage/UI/nls/ar/Boolean':function(){
define('Sage/UI/nls/ar/Boolean',{});
},
'Sage/UI/nls/ar-ae/Boolean':function(){
define('Sage/UI/nls/ar-ae/Boolean',{});
},
'Sage/Services/nls/ar/ActivityService':function(){
define('Sage/Services/nls/ar/ActivityService',{});
},
'Sage/Services/nls/ar-ae/ActivityService':function(){
define('Sage/Services/nls/ar-ae/ActivityService',{});
},
'Sage/UI/Controls/nls/ar/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/ar/CopyToClipboard',{});
},
'Sage/UI/Controls/nls/ar-ae/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/ar-ae/CopyToClipboard',{});
},
'Sage/Utility/nls/ar/Activity':function(){
define('Sage/Utility/nls/ar/Activity',{});
},
'Sage/Utility/nls/ar-ae/Activity':function(){
define('Sage/Utility/nls/ar-ae/Activity',{});
},
'Sage/QuickForms/Design/nls/ar/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/ar/DesignPanel',{});
},
'Sage/QuickForms/Design/nls/ar-ae/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/ar-ae/DesignPanel',{});
},
'Sage/UI/nls/ar/TimelessActivitiesPane':function(){
define('Sage/UI/nls/ar/TimelessActivitiesPane',{});
},
'Sage/UI/nls/ar-ae/TimelessActivitiesPane':function(){
define('Sage/UI/nls/ar-ae/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ae/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ae/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/ar/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/ar/ContactUserAssociationEditor',{});
},
'Sage/TaskPane/User/nls/ar-ae/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/ar-ae/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/ar/ActivityManager':function(){
define('Sage/MainView/nls/ar/ActivityManager',{});
},
'Sage/MainView/nls/ar-ae/ActivityManager':function(){
define('Sage/MainView/nls/ar-ae/ActivityManager',{});
},
'Sage/Services/nls/ar/JobService':function(){
define('Sage/Services/nls/ar/JobService',{});
},
'Sage/Services/nls/ar-ae/JobService':function(){
define('Sage/Services/nls/ar-ae/JobService',{});
},
'Sage/QuickForms/Design/nls/ar/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-ae/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-ae/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/_PropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ae/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ae/_PropertyEditor',{});
},
'Sage/Services/nls/ar/ActivityActionProcessor':function(){
define('Sage/Services/nls/ar/ActivityActionProcessor',{});
},
'Sage/Services/nls/ar-ae/ActivityActionProcessor':function(){
define('Sage/Services/nls/ar-ae/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/TextBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ae/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ae/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ae/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ae/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar/UserActivityDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar/UserActivityDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar-ae/UserActivityDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar-ae/UserActivityDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar/ConfirmationDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar/ConfirmationDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar-ae/ConfirmationDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar-ae/ConfirmationDetailSummary',{});
},
'Sage/Utility/File/nls/ar/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/ar/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/ar-ae/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/ar-ae/DefaultDropHandler',{});
},
'Sage/UI/nls/ar/TransferBoxWidget':function(){
define('Sage/UI/nls/ar/TransferBoxWidget',{});
},
'Sage/UI/nls/ar-ae/TransferBoxWidget':function(){
define('Sage/UI/nls/ar-ae/TransferBoxWidget',{});
},
'Sage/Utility/File/nls/ar/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/ar/AttachmentPropertiesEditForm',{});
},
'Sage/Utility/File/nls/ar-ae/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/ar-ae/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/ar/AlarmPane':function(){
define('Sage/UI/Alarms/nls/ar/AlarmPane',{});
},
'Sage/UI/Alarms/nls/ar-ae/AlarmPane':function(){
define('Sage/UI/Alarms/nls/ar-ae/AlarmPane',{});
},
'Sage/TaskPane/nls/ar/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/ar/LiteratureManagementTasks',{});
},
'Sage/TaskPane/nls/ar-ae/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/ar-ae/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/ar/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/ar/DashboardWidget',{});
},
'Sage/UI/Dashboard/nls/ar-ae/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/ar-ae/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/NumericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ae/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ae/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ar/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar/CustomerPaymentsRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/ar-ae/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar-ae/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/ar/FilterPanel':function(){
define('Sage/UI/Filters/nls/ar/FilterPanel',{});
},
'Sage/UI/Filters/nls/ar-ae/FilterPanel':function(){
define('Sage/UI/Filters/nls/ar-ae/FilterPanel',{});
},
'Sage/TaskPane/nls/ar/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/ar/_BaseTaskPaneTasklet',{});
},
'Sage/TaskPane/nls/ar-ae/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/ar-ae/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/ar/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/ar/ReportManagerFormatter',{});
},
'Sage/MainView/ReportMgr/nls/ar-ae/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/ar-ae/ReportManagerFormatter',{});
},
'Sage/UI/nls/ar/OwnerType':function(){
define('Sage/UI/nls/ar/OwnerType',{});
},
'Sage/UI/nls/ar-ae/OwnerType':function(){
define('Sage/UI/nls/ar-ae/OwnerType',{});
},
'Sage/MainView/JobMgr/templates/nls/ar/JobDefinitionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar/JobDefinitionsListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/ar-ae/JobDefinitionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar-ae/JobDefinitionsListSummary',{});
},
'Sage/TaskPane/nls/ar/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/LeadTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-ae/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-ae/LeadTasksTasklet',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar/ReportDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar/ReportDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar-ae/ReportDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar-ae/ReportDetailSummary',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/_ParameterEditorBase':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/_ParameterEditorBase',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-ae/_ParameterEditorBase':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-ae/_ParameterEditorBase',{});
},
'Sage/MailMerge/nls/ar/Service':function(){
define('Sage/MailMerge/nls/ar/Service',{});
},
'Sage/MailMerge/nls/ar-ae/Service':function(){
define('Sage/MailMerge/nls/ar-ae/Service',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar/ConfirmationListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar/ConfirmationListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar-ae/ConfirmationListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar-ae/ConfirmationListSummary',{});
},
'Sage/MainView/ActivityMgr/nls/ar/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/ar/SnoozeOptions',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ae/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ae/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ae/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ae/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ae/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ae/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ar/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar/InvoiceRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/ar-ae/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar-ae/InvoiceRTDV',{});
},
'Sage/UI/nls/ar/SDataLookup':function(){
define('Sage/UI/nls/ar/SDataLookup',{});
},
'Sage/UI/nls/ar-ae/SDataLookup':function(){
define('Sage/UI/nls/ar-ae/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/ar/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/RowDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-ae/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-ae/RowDesigner',{});
},
'Sage/Groups/nls/ar/GroupLookup':function(){
define('Sage/Groups/nls/ar/GroupLookup',{});
},
'Sage/Groups/nls/ar-ae/GroupLookup':function(){
define('Sage/Groups/nls/ar-ae/GroupLookup',{});
},
'Sage/TaskPane/nls/ar/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/OpportunityTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-ae/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-ae/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/ar/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/ar/CheckBoxFilter',{});
},
'Sage/UI/Filters/nls/ar-ae/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/ar-ae/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/ar/LibraryDocument':function(){
define('Sage/Utility/File/nls/ar/LibraryDocument',{});
},
'Sage/Utility/File/nls/ar-ae/LibraryDocument':function(){
define('Sage/Utility/File/nls/ar-ae/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar/SpeedSearchLookup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar-ae/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar-ae/SpeedSearchLookup',{});
},
'Sage/UI/nls/ar/ConditionManager':function(){
define('Sage/UI/nls/ar/ConditionManager',{});
},
'Sage/UI/nls/ar-ae/ConditionManager':function(){
define('Sage/UI/nls/ar-ae/ConditionManager',{});
},
'Sage/MainView/JobMgr/templates/nls/ar/SchedulesListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar/SchedulesListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/ar-ae/SchedulesListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar-ae/SchedulesListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar/UserActivityListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar/UserActivityListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar-ae/UserActivityListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar-ae/UserActivityListSummary',{});
},
'Sage/UI/Dashboard/nls/ar/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/ar/WidgetDefinition',{});
},
'Sage/UI/Dashboard/nls/ar-ae/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/ar-ae/WidgetDefinition',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar/AllOpenListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar/AllOpenListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar-ae/AllOpenListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar-ae/AllOpenListSummary',{});
},
'Sage/UI/nls/ar/SearchConditionWidget':function(){
define('Sage/UI/nls/ar/SearchConditionWidget',{});
},
'Sage/UI/nls/ar-ae/SearchConditionWidget':function(){
define('Sage/UI/nls/ar-ae/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ae/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ae/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ar/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/ar/JobManagerActions',{});
},
'Sage/MainView/JobMgr/nls/ar-ae/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/ar-ae/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar/ContactLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar-ae/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar-ae/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/ar/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/ar/DataSourcePanel',{});
},
'Sage/QuickForms/Design/nls/ar-ae/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/ar-ae/DataSourcePanel',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar/SchedulesListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar/SchedulesListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar-ae/SchedulesListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar-ae/SchedulesListSummary',{});
},
'Sage/Library/nls/ar/Manager':function(){
define('Sage/Library/nls/ar/Manager',{});
},
'Sage/Library/nls/ar-ae/Manager':function(){
define('Sage/Library/nls/ar-ae/Manager',{});
},
'Sage/UI/nls/ar/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/ar/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/nls/ar-ae/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/ar-ae/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/ar/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/ar/NonVisibleControlContainer',{});
},
'Sage/QuickForms/Design/nls/ar-ae/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/ar-ae/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/ar/Name':function(){
define('Sage/UI/Controls/nls/ar/Name',{});
},
'Sage/UI/Controls/nls/ar-ae/Name':function(){
define('Sage/UI/Controls/nls/ar-ae/Name',{});
},
'Sage/MainView/JobMgr/nls/ar/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar/ExecutionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/ar-ae/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar-ae/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ar/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/PhoneControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-ae/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-ae/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/ar/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/ar/UpdateLeads',{});
},
'Sage/MainView/Lead/nls/ar-ae/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/ar-ae/UpdateLeads',{});
},
'Sage/Library/nls/ar/FileHandler':function(){
define('Sage/Library/nls/ar/FileHandler',{});
},
'Sage/Library/nls/ar-ae/FileHandler':function(){
define('Sage/Library/nls/ar-ae/FileHandler',{});
},
'Sage/UI/nls/ar/ListPanel':function(){
define('Sage/UI/nls/ar/ListPanel',{});
},
'Sage/UI/nls/ar-ae/ListPanel':function(){
define('Sage/UI/nls/ar-ae/ListPanel',{});
},
'Sage/Utility/nls/ar/Sql':function(){
define('Sage/Utility/nls/ar/Sql',{});
},
'Sage/Utility/nls/ar-ae/Sql':function(){
define('Sage/Utility/nls/ar-ae/Sql',{});
},
'Sage/UI/Filters/nls/ar/EditFilters':function(){
define('Sage/UI/Filters/nls/ar/EditFilters',{});
},
'Sage/UI/Filters/nls/ar-ae/EditFilters':function(){
define('Sage/UI/Filters/nls/ar-ae/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/FormUsagesPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ae/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ae/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/ar/DurationSelect':function(){
define('Sage/UI/Controls/nls/ar/DurationSelect',{});
},
'Sage/UI/Controls/nls/ar-ae/DurationSelect':function(){
define('Sage/UI/Controls/nls/ar-ae/DurationSelect',{});
},
'Sage/UI/Alarms/nls/ar/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/ar/AlarmCountDown',{});
},
'Sage/UI/Alarms/nls/ar-ae/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/ar-ae/AlarmCountDown',{});
},
'Sage/UI/nls/ar/AttachmentList':function(){
define('Sage/UI/nls/ar/AttachmentList',{});
},
'Sage/UI/nls/ar-ae/AttachmentList':function(){
define('Sage/UI/nls/ar-ae/AttachmentList',{});
},
'Sage/MailMerge/nls/ar/Lookup':function(){
define('Sage/MailMerge/nls/ar/Lookup',{});
},
'Sage/MailMerge/nls/ar-ae/Lookup':function(){
define('Sage/MailMerge/nls/ar-ae/Lookup',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ae/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ae/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ar/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/ar/RunJobDialog',{});
},
'Sage/MainView/JobMgr/nls/ar-ae/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/ar-ae/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/ar/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-ae/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-ae/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-ae/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-ae/EditableGridControlDesigner',{});
},
'Sage/MainView/Options/nls/ar/OptionsDialog':function(){
define('Sage/MainView/Options/nls/ar/OptionsDialog',{});
},
'Sage/MainView/Options/nls/ar-ae/OptionsDialog':function(){
define('Sage/MainView/Options/nls/ar-ae/OptionsDialog',{});
},
'Sage/QuickForms/Design/nls/ar/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/HiddenControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-ae/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-ae/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/ar/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/ar/DashboardWidgetCell',{});
},
'Sage/UI/Dashboard/nls/ar-ae/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/ar-ae/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/UserBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ae/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ae/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/ar/Dialogs':function(){
define('Sage/UI/nls/ar/Dialogs',{});
},
'Sage/UI/nls/ar-ae/Dialogs':function(){
define('Sage/UI/nls/ar-ae/Dialogs',{});
},
'Sage/MainView/IntegrationContract/nls/ar/SyncResultsHistory':function(){
define('Sage/MainView/IntegrationContract/nls/ar/SyncResultsHistory',{});
},
'Sage/MainView/IntegrationContract/nls/ar-ae/SyncResultsHistory':function(){
define('Sage/MainView/IntegrationContract/nls/ar-ae/SyncResultsHistory',{});
},
'Sage/TaskPane/nls/ar/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/ar/SecuredActionTasklet',{});
},
'Sage/TaskPane/nls/ar-ae/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/ar-ae/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/ar/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/ar/DashboardTabController',{});
},
'Sage/UI/Dashboard/nls/ar-ae/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/ar-ae/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/ar/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar/SalesOrderRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/ar-ae/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar-ae/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/ar/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/UserControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-ae/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-ae/UserControlDesigner',{});
},
'Sage/Groups/nls/ar/GroupNavigator':function(){
define('Sage/Groups/nls/ar/GroupNavigator',{});
},
'Sage/Groups/nls/ar-ae/GroupNavigator':function(){
define('Sage/Groups/nls/ar-ae/GroupNavigator',{});
},
'Sage/Utility/File/nls/ar/AddURLAttachment':function(){
define('Sage/Utility/File/nls/ar/AddURLAttachment',{});
},
'Sage/Utility/File/nls/ar-ae/AddURLAttachment':function(){
define('Sage/Utility/File/nls/ar-ae/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/ar/EditFilterItems':function(){
define('Sage/UI/Filters/nls/ar/EditFilterItems',{});
},
'Sage/UI/Filters/nls/ar-ae/EditFilterItems':function(){
define('Sage/UI/Filters/nls/ar-ae/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportsFormatter',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-ae/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-ae/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/ar/DragDropWatcher':function(){
define('Sage/Utility/File/nls/ar/DragDropWatcher',{});
},
'Sage/Utility/File/nls/ar-ae/DragDropWatcher':function(){
define('Sage/Utility/File/nls/ar-ae/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/ar/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/ar/DesignSurface',{});
},
'Sage/QuickForms/Design/nls/ar-ae/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/ar-ae/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ae/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ae/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/FormAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ae/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ae/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/EventListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ae/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ae/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ar/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ar/AllOpenListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ar-ae/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ar-ae/AllOpenListPanelConfig',{});
},
'Sage/MainView/nls/ar/FormManager':function(){
define('Sage/MainView/nls/ar/FormManager',{});
},
'Sage/MainView/nls/ar-ae/FormManager':function(){
define('Sage/MainView/nls/ar-ae/FormManager',{});
},
'Sage/UI/nls/ar/ActivityScheduler':function(){
define('Sage/UI/nls/ar/ActivityScheduler',{});
},
'Sage/UI/nls/ar-ae/ActivityScheduler':function(){
define('Sage/UI/nls/ar-ae/ActivityScheduler',{});
},
'Sage/MainView/nls/ar/SecurityManager':function(){
define('Sage/MainView/nls/ar/SecurityManager',{});
},
'Sage/MainView/nls/ar-ae/SecurityManager':function(){
define('Sage/MainView/nls/ar-ae/SecurityManager',{});
},
'Sage/TaskPane/nls/ar/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/ar/ActivityTaskConfigurationProvider',{});
},
'Sage/TaskPane/nls/ar-ae/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/ar-ae/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/ar/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/ar/EntityInfoToolTip',{});
},
'Sage/UI/Controls/nls/ar-ae/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/ar-ae/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ae/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ae/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar/AllOpenDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar/AllOpenDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar-ae/AllOpenDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar-ae/AllOpenDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar/ReportsListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar/ReportsListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar-ae/ReportsListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar-ae/ReportsListSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/ar/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/ar/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/Common/nls/ar-ae/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/ar-ae/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar/ScheduleDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar/ScheduleDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar-ae/ScheduleDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar-ae/ScheduleDetailSummary',{});
},
'Sage/MainView/Opportunity/nls/ar/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/ar/UpdateOpportunities',{});
},
'Sage/MainView/Opportunity/nls/ar-ae/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/ar-ae/UpdateOpportunities',{});
},
'Sage/UI/nls/ar/EditCalendarUsers':function(){
define('Sage/UI/nls/ar/EditCalendarUsers',{});
},
'Sage/UI/nls/ar-ae/EditCalendarUsers':function(){
define('Sage/UI/nls/ar-ae/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportParametersDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-ae/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-ae/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/ar/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/DateTimePickerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-ae/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-ae/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/ar/HelpMenu':function(){
define('Sage/UI/Controls/nls/ar/HelpMenu',{});
},
'Sage/UI/Controls/nls/ar-ae/HelpMenu':function(){
define('Sage/UI/Controls/nls/ar-ae/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/LayoutPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ae/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ae/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/ar/UserTasklet':function(){
define('Sage/TaskPane/nls/ar/UserTasklet',{});
},
'Sage/TaskPane/nls/ar-ae/UserTasklet':function(){
define('Sage/TaskPane/nls/ar-ae/UserTasklet',{});
},
'Sage/UI/Alarms/nls/ar/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/ar/ActivityAlarm',{});
},
'Sage/UI/Alarms/nls/ar-ae/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/ar-ae/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/ar/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/ar/OpportunityStatistics',{});
},
'Sage/MainView/Opportunity/nls/ar-ae/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/ar-ae/OpportunityStatistics',{});
},
'Sage/TaskPane/nls/ar/GroupListTasklet':function(){
define('Sage/TaskPane/nls/ar/GroupListTasklet',{});
},
'Sage/TaskPane/nls/ar-ae/GroupListTasklet':function(){
define('Sage/TaskPane/nls/ar-ae/GroupListTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportConditionEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-ae/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-ae/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ar/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/ar/AdvancedSearchOptions',{});
},
'Sage/MainView/IntegrationContract/nls/ar-ae/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/ar-ae/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/ar/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/ColumnDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-ae/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-ae/ColumnDesigner',{});
},
'Sage/MainView/JobMgr/templates/nls/ar/JobDefinitionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar/JobDefinitionDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/ar-ae/JobDefinitionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar-ae/JobDefinitionDetailSummary',{});
},
'Sage/UI/nls/ar/SearchMenuItem':function(){
define('Sage/UI/nls/ar/SearchMenuItem',{});
},
'Sage/UI/nls/ar-ae/SearchMenuItem':function(){
define('Sage/UI/nls/ar-ae/SearchMenuItem',{});
},
'Sage/Library/nls/ar/DocumentProperties':function(){
define('Sage/Library/nls/ar/DocumentProperties',{});
},
'Sage/Library/nls/ar-ae/DocumentProperties':function(){
define('Sage/Library/nls/ar-ae/DocumentProperties',{});
},
'Sage/UI/nls/ar/NotesHistoryList':function(){
define('Sage/UI/nls/ar/NotesHistoryList',{});
},
'Sage/UI/nls/ar-ae/NotesHistoryList':function(){
define('Sage/UI/nls/ar-ae/NotesHistoryList',{});
},
'Sage/Utility/nls/ar/File':function(){
define('Sage/Utility/nls/ar/File',{});
},
'Sage/Utility/nls/ar-ae/File':function(){
define('Sage/Utility/nls/ar-ae/File',{});
},
'Sage/MainView/ReportMgr/nls/ar/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/ar-ae/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar-ae/HistoryListPanelConfig',{});
},
'Sage/MainView/JobMgr/templates/nls/ar/ScheduleDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar/ScheduleDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/ar-ae/ScheduleDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar-ae/ScheduleDetailSummary',{});
},
'Sage/QuickForms/Design/nls/ar/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/UrlControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-ae/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-ae/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/ar/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/ContactTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-ae/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-ae/ContactTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar/EventSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar/EventSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar-ae/EventSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar-ae/EventSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/ar/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/ar/_WizardDialogBase',{});
},
'Sage/MainView/ReportMgr/Common/nls/ar-ae/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/ar-ae/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/ar/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar/SchedulesListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/ar-ae/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar-ae/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/ar/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/ar/GoogleDocPicker',{});
},
'Sage/Utility/File/nls/ar-ae/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/ar-ae/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/ar/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/ComboBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-ae/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-ae/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/ar/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ae/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ae/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/HistoryEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ae/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ae/HistoryEditor',{});
},
'Sage/Groups/nls/ar/GroupManager':function(){
define('Sage/Groups/nls/ar/GroupManager',{});
},
'Sage/Groups/nls/ar-ae/GroupManager':function(){
define('Sage/Groups/nls/ar-ae/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ae/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ae/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/ComboBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ae/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ae/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ar/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar/ReportsListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/ar-ae/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar-ae/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/ar/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/ar/JobNotificationButton',{});
},
'Sage/UI/Alarms/nls/ar-ae/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/ar-ae/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportWizardController',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-ae/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-ae/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/ar/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/ar-ae/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar-ae/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/RecurringEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ae/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ae/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportsUtility',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-ae/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-ae/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ae/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ae/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ar/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/ar-ae/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar-ae/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ar/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-ae/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-ae/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-ae/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-ae/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-ae/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-ae/PickListControlDesigner',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar/LitRequestSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar/LitRequestSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar-ae/LitRequestSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar-ae/LitRequestSummary',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ae/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ae/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/ar/FolderHandler':function(){
define('Sage/Library/nls/ar/FolderHandler',{});
},
'Sage/Library/nls/ar-ae/FolderHandler':function(){
define('Sage/Library/nls/ar-ae/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ae/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ae/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/ar/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/ar/ContactSearchForDuplicates',{});
},
'Sage/MainView/Contact/nls/ar-ae/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/ar-ae/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/DateTimePickerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ae/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ae/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/ar/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/AccountingTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-ae/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-ae/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ae/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ae/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/CurrencyBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ae/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ae/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/ar/EditableGrid':function(){
define('Sage/UI/nls/ar/EditableGrid',{});
},
'Sage/UI/nls/ar-ae/EditableGrid':function(){
define('Sage/UI/nls/ar-ae/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/ar/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar/SalesQuoteRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/ar-ae/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar-ae/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/ar/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/ar/SecurityProfile',{});
},
'Sage/MainView/SecurityMgr/nls/ar-ae/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/ar-ae/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/ar/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/ar/ReportWizardController',{});
},
'Sage/MainView/ReportMgr/nls/ar-ae/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/ar-ae/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/UserAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ae/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ae/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ar/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/ar/ReportManagerUtility',{});
},
'Sage/MainView/ReportMgr/nls/ar-ae/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/ar-ae/ReportManagerUtility',{});
},
'Sage/UI/nls/ar/SpeedSearch':function(){
define('Sage/UI/nls/ar/SpeedSearch',{});
},
'Sage/UI/nls/ar-ae/SpeedSearch':function(){
define('Sage/UI/nls/ar-ae/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/CurrencyAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ae/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ae/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/ar/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/ReportManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-ae/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-ae/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/ar/SLXPreviewGrid':function(){
define('Sage/UI/nls/ar/SLXPreviewGrid',{});
},
'Sage/UI/nls/ar-ae/SLXPreviewGrid':function(){
define('Sage/UI/nls/ar-ae/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/ar/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/ar/UnconfirmedPane',{});
},
'Sage/UI/Alarms/nls/ar-ae/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/ar-ae/UnconfirmedPane',{});
},
'Sage/Utility/nls/ar/Utility':function(){
define('Sage/Utility/nls/ar/Utility',{});
},
'Sage/Utility/nls/ar-ae/Utility':function(){
define('Sage/Utility/nls/ar-ae/Utility',{});
},
'Sage/QuickForms/Design/nls/ar/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/ControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-ae/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-ae/ControlDesigner',{});
},
'Sage/UI/Controls/nls/ar/Address':function(){
define('Sage/UI/Controls/nls/ar/Address',{});
},
'Sage/UI/Controls/nls/ar-ae/Address':function(){
define('Sage/UI/Controls/nls/ar-ae/Address',{});
},
'Sage/MainView/JobMgr/nls/ar/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/ar/JobManagerGroupContextService',{});
},
'Sage/MainView/JobMgr/nls/ar-ae/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/ar-ae/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/ar/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/BaseListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ae/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ae/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ar/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/OwnerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-ae/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-ae/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/ar/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/JobManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-ae/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-ae/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ae/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ae/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/ar/UserType':function(){
define('Sage/UI/nls/ar/UserType',{});
},
'Sage/UI/nls/ar-ae/UserType':function(){
define('Sage/UI/nls/ar-ae/UserType',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar/HistoryDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar/HistoryDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar-ae/HistoryDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar-ae/HistoryDetailSummary',{});
},
'Sage/QuickForms/Design/nls/ar/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/FormDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-ae/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-ae/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityCalendar',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ae/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ae/ActivityCalendar',{});
},
'Sage/Utility/nls/ar/Jobs':function(){
define('Sage/Utility/nls/ar/Jobs',{});
},
'Sage/Utility/nls/ar-ae/Jobs':function(){
define('Sage/Utility/nls/ar-ae/Jobs',{});
},
'Sage/UI/Controls/nls/ar/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/ar/_DialogHelpIconMixin',{});
},
'Sage/UI/Controls/nls/ar-ae/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/ar-ae/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/PickListAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ae/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ae/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/ar/ActivityList':function(){
define('Sage/UI/nls/ar/ActivityList',{});
},
'Sage/UI/nls/ar-ae/ActivityList':function(){
define('Sage/UI/nls/ar-ae/ActivityList',{});
},
'Sage/UI/Alarms/nls/ar/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/ar/JobNotificationPopup',{});
},
'Sage/UI/Alarms/nls/ar-ae/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/ar-ae/JobNotificationPopup',{});
},
'Sage/MainView/JobMgr/templates/nls/ar/ExecutionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar/ExecutionsListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/ar-ae/ExecutionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar-ae/ExecutionsListSummary',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar/LeadLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar-ae/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar-ae/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/ar/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar/SchedulesListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/ar-ae/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar-ae/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/GenericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ae/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ae/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/ar/CalendarUsersListPane':function(){
define('Sage/UI/nls/ar/CalendarUsersListPane',{});
},
'Sage/UI/nls/ar-ae/CalendarUsersListPane':function(){
define('Sage/UI/nls/ar-ae/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ae/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ae/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/ColumnBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ae/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ae/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/templates/nls/ar/ExecutionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar/ExecutionDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/ar-ae/ExecutionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar-ae/ExecutionDetailSummary',{});
},
'Sage/MainView/ReportMgr/nls/ar/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/ar/ReportManagerGroupContextService',{});
},
'Sage/MainView/ReportMgr/nls/ar-ae/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/ar-ae/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/ar/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/ar/MatchingOptionsConfig',{});
},
'Sage/MainView/IntegrationContract/nls/ar-ae/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/ar-ae/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/FormBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ae/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ae/FormBasicPropertyEditor',{});
},
'Sage/UI/Alarms/nls/ar/AlarmButton':function(){
define('Sage/UI/Alarms/nls/ar/AlarmButton',{});
},
'Sage/UI/Alarms/nls/ar-ae/AlarmButton':function(){
define('Sage/UI/Alarms/nls/ar-ae/AlarmButton',{});
},
'Sage/MainView/ActivityMgr/nls/ar/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/ar/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ae/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ae/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/ar/Attachment':function(){
define('Sage/Utility/File/nls/ar/Attachment',{});
},
'Sage/Utility/File/nls/ar-ae/Attachment':function(){
define('Sage/Utility/File/nls/ar-ae/Attachment',{});
},
'Sage/QuickForms/Design/nls/ar/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-ae/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-ae/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/ar/PropertyEditorContainer',{});
},
'Sage/QuickForms/Design/nls/ar-ae/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/ar-ae/PropertyEditorContainer',{});
},
'Sage/Services/nls/ar/ReportingService':function(){
define('Sage/Services/nls/ar/ReportingService',{});
},
'Sage/Services/nls/ar-ae/ReportingService':function(){
define('Sage/Services/nls/ar-ae/ReportingService',{});
},
'Sage/MailMerge/nls/ar/Helper':function(){
define('Sage/MailMerge/nls/ar/Helper',{});
},
'Sage/MailMerge/nls/ar-ae/Helper':function(){
define('Sage/MailMerge/nls/ar-ae/Helper',{});
},
'Sage/UI/Dashboard/nls/ar/Dashboard':function(){
define('Sage/UI/Dashboard/nls/ar/Dashboard',{});
},
'Sage/UI/Dashboard/nls/ar-ae/Dashboard':function(){
define('Sage/UI/Dashboard/nls/ar-ae/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ae/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ae/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/ar/PickList':function(){
define('Sage/UI/Controls/nls/ar/PickList',{});
},
'Sage/UI/Controls/nls/ar-ae/PickList':function(){
define('Sage/UI/Controls/nls/ar-ae/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/ar/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ar/HistoryEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ae/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ae/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/ar/Email':function(){
define('Sage/Utility/nls/ar/Email',{});
},
'Sage/Utility/nls/ar-ae/Email':function(){
define('Sage/Utility/nls/ar-ae/Email',{});
},
'Sage/TaskPane/nls/ar/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/SecurityManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-ae/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-ae/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/ar/TimeZoneItem':function(){
define('Sage/UI/nls/ar/TimeZoneItem',{});
},
'Sage/UI/nls/ar-ae/TimeZoneItem':function(){
define('Sage/UI/nls/ar-ae/TimeZoneItem',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar/HistoryListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar/HistoryListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar-ae/HistoryListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar-ae/HistoryListSummary',{});
},
'Sage/UI/Columns/nls/ar/SlxEdit':function(){
define('Sage/UI/Columns/nls/ar/SlxEdit',{});
},
'Sage/UI/Columns/nls/ar-ae/SlxEdit':function(){
define('Sage/UI/Columns/nls/ar-ae/SlxEdit',{});
},
'Sage/Reporting/nls/ar/Enumerations':function(){
define('Sage/Reporting/nls/ar/Enumerations',{});
},
'Sage/Reporting/nls/ar-ae/Enumerations':function(){
define('Sage/Reporting/nls/ar-ae/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ae/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ae/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportConditionsDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-ae/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-ae/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ar/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ar/ActivityListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ar-ae/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ar-ae/ActivityListPanelConfig',{});
},
'Sage/UI/nls/ar/JobSchedulingWidget':function(){
define('Sage/UI/nls/ar/JobSchedulingWidget',{});
},
'Sage/UI/nls/ar-ae/JobSchedulingWidget':function(){
define('Sage/UI/nls/ar-ae/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/ar/LogOffButton':function(){
define('Sage/UI/Controls/nls/ar/LogOffButton',{});
},
'Sage/UI/Controls/nls/ar-ae/LogOffButton':function(){
define('Sage/UI/Controls/nls/ar-ae/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/TextBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ae/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ae/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/EditEventEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ae/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ae/EditEventEditor',{});
},
'Sage/MailMerge/nls/ar/Loader':function(){
define('Sage/MailMerge/nls/ar/Loader',{});
},
'Sage/MailMerge/nls/ar-ae/Loader':function(){
define('Sage/MailMerge/nls/ar-ae/Loader',{});
},
'Sage/UI/Controls/nls/ar/DateTimePicker':function(){
define('Sage/UI/Controls/nls/ar/DateTimePicker',{});
},
'Sage/UI/Controls/nls/ar-ae/DateTimePicker':function(){
define('Sage/UI/Controls/nls/ar-ae/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/ar/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/ar/ReportManagerActions',{});
},
'Sage/MainView/ReportMgr/nls/ar-ae/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/ar-ae/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/ar/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/ar/AlarmPopup',{});
},
'Sage/UI/Alarms/nls/ar-ae/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/ar-ae/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/ar/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/ar/ContactUserAssociationEditor',{});
},
'Sage/MainView/Contact/nls/ar-ae/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/ar-ae/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ae/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ae/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ar/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar/BaseListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/ar-ae/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar-ae/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ar/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-ae/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-ae/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/EmailControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-ae/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-ae/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/ar/Lookup':function(){
define('Sage/UI/Controls/nls/ar/Lookup',{});
},
'Sage/UI/Controls/nls/ar-ae/Lookup':function(){
define('Sage/UI/Controls/nls/ar-ae/Lookup',{});
},
'Sage/Utility/File/nls/ar/DescriptionsForm':function(){
define('Sage/Utility/File/nls/ar/DescriptionsForm',{});
},
'Sage/Utility/File/nls/ar-ae/DescriptionsForm':function(){
define('Sage/Utility/File/nls/ar-ae/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/NumericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ae/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ae/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/ar/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/CommonTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-ae/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-ae/CommonTasksTasklet',{});
},
'Sage/Utility/nls/ar/Dashboard':function(){
define('Sage/Utility/nls/ar/Dashboard',{});
},
'Sage/Utility/nls/ar-ae/Dashboard':function(){
define('Sage/Utility/nls/ar-ae/Dashboard',{});
}}});
define("Sage/nls/Sage_ar-ae", [], 1);
