require({cache:{
'Sage/Utility/File/nls/sz/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/sz/FallbackFilePicker',{});
},
'Sage/UI/nls/sz/Boolean':function(){
define('Sage/UI/nls/sz/Boolean',{});
},
'Sage/Services/nls/sz/ActivityService':function(){
define('Sage/Services/nls/sz/ActivityService',{});
},
'Sage/UI/Controls/nls/sz/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/sz/CopyToClipboard',{});
},
'Sage/Utility/nls/sz/Activity':function(){
define('Sage/Utility/nls/sz/Activity',{});
},
'Sage/QuickForms/Design/nls/sz/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/sz/DesignPanel',{});
},
'Sage/UI/nls/sz/TimelessActivitiesPane':function(){
define('Sage/UI/nls/sz/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/sz/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sz/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/sz/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/sz/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/sz/ActivityManager':function(){
define('Sage/MainView/nls/sz/ActivityManager',{});
},
'Sage/Services/nls/sz/JobService':function(){
define('Sage/Services/nls/sz/JobService',{});
},
'Sage/QuickForms/Design/nls/sz/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sz/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/sz/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sz/_PropertyEditor',{});
},
'Sage/Services/nls/sz/ActivityActionProcessor':function(){
define('Sage/Services/nls/sz/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/sz/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sz/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sz/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sz/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/templates/nls/sz/UserActivityDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/sz/UserActivityDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/sz/ConfirmationDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/sz/ConfirmationDetailSummary',{});
},
'Sage/Utility/File/nls/sz/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/sz/DefaultDropHandler',{});
},
'Sage/UI/nls/sz/TransferBoxWidget':function(){
define('Sage/UI/nls/sz/TransferBoxWidget',{});
},
'Sage/Utility/File/nls/sz/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/sz/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/sz/AlarmPane':function(){
define('Sage/UI/Alarms/nls/sz/AlarmPane',{});
},
'Sage/TaskPane/nls/sz/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/sz/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/sz/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/sz/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/sz/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sz/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/sz/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/sz/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/sz/FilterPanel':function(){
define('Sage/UI/Filters/nls/sz/FilterPanel',{});
},
'Sage/TaskPane/nls/sz/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/sz/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/sz/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/sz/ReportManagerFormatter',{});
},
'Sage/UI/nls/sz/OwnerType':function(){
define('Sage/UI/nls/sz/OwnerType',{});
},
'Sage/MainView/JobMgr/templates/nls/sz/JobDefinitionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/sz/JobDefinitionsListSummary',{});
},
'Sage/TaskPane/nls/sz/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/sz/LeadTasksTasklet',{});
},
'Sage/MainView/ReportMgr/templates/nls/sz/ReportDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/sz/ReportDetailSummary',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sz/_ParameterEditorBase':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sz/_ParameterEditorBase',{});
},
'Sage/MailMerge/nls/sz/Service':function(){
define('Sage/MailMerge/nls/sz/Service',{});
},
'Sage/MainView/ActivityMgr/templates/nls/sz/ConfirmationListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/sz/ConfirmationListSummary',{});
},
'Sage/MainView/ActivityMgr/nls/sz/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/sz/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/sz/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sz/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sz/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sz/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/sz/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/sz/InvoiceRTDV',{});
},
'Sage/UI/nls/sz/SDataLookup':function(){
define('Sage/UI/nls/sz/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/sz/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/sz/RowDesigner',{});
},
'Sage/Groups/nls/sz/GroupLookup':function(){
define('Sage/Groups/nls/sz/GroupLookup',{});
},
'Sage/TaskPane/nls/sz/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/sz/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/sz/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/sz/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/sz/LibraryDocument':function(){
define('Sage/Utility/File/nls/sz/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/sz/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/sz/SpeedSearchLookup',{});
},
'Sage/UI/nls/sz/ConditionManager':function(){
define('Sage/UI/nls/sz/ConditionManager',{});
},
'Sage/MainView/JobMgr/templates/nls/sz/SchedulesListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/sz/SchedulesListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/sz/UserActivityListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/sz/UserActivityListSummary',{});
},
'Sage/UI/Dashboard/nls/sz/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/sz/WidgetDefinition',{});
},
'Sage/MainView/ActivityMgr/templates/nls/sz/AllOpenListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/sz/AllOpenListSummary',{});
},
'Sage/UI/nls/sz/SearchConditionWidget':function(){
define('Sage/UI/nls/sz/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/sz/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sz/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/sz/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/sz/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/sz/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/sz/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/sz/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/sz/DataSourcePanel',{});
},
'Sage/MainView/ReportMgr/templates/nls/sz/SchedulesListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/sz/SchedulesListSummary',{});
},
'Sage/Library/nls/sz/Manager':function(){
define('Sage/Library/nls/sz/Manager',{});
},
'Sage/UI/nls/sz/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/sz/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/sz/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/sz/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/sz/Name':function(){
define('Sage/UI/Controls/nls/sz/Name',{});
},
'Sage/MainView/JobMgr/nls/sz/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/sz/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/sz/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sz/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/sz/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/sz/UpdateLeads',{});
},
'Sage/Library/nls/sz/FileHandler':function(){
define('Sage/Library/nls/sz/FileHandler',{});
},
'Sage/UI/nls/sz/ListPanel':function(){
define('Sage/UI/nls/sz/ListPanel',{});
},
'Sage/Utility/nls/sz/Sql':function(){
define('Sage/Utility/nls/sz/Sql',{});
},
'Sage/UI/Filters/nls/sz/EditFilters':function(){
define('Sage/UI/Filters/nls/sz/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/sz/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sz/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/sz/DurationSelect':function(){
define('Sage/UI/Controls/nls/sz/DurationSelect',{});
},
'Sage/UI/Alarms/nls/sz/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/sz/AlarmCountDown',{});
},
'Sage/UI/nls/sz/AttachmentList':function(){
define('Sage/UI/nls/sz/AttachmentList',{});
},
'Sage/MailMerge/nls/sz/Lookup':function(){
define('Sage/MailMerge/nls/sz/Lookup',{});
},
'Sage/QuickForms/Design/Editors/nls/sz/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sz/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/sz/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/sz/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/sz/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sz/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sz/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sz/EditableGridControlDesigner',{});
},
'Sage/MainView/Options/nls/sz/OptionsDialog':function(){
define('Sage/MainView/Options/nls/sz/OptionsDialog',{});
},
'Sage/QuickForms/Design/nls/sz/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sz/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/sz/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/sz/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/sz/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sz/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/sz/Dialogs':function(){
define('Sage/UI/nls/sz/Dialogs',{});
},
'Sage/MainView/IntegrationContract/nls/sz/SyncResultsHistory':function(){
define('Sage/MainView/IntegrationContract/nls/sz/SyncResultsHistory',{});
},
'Sage/TaskPane/nls/sz/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/sz/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/sz/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/sz/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/sz/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/sz/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/sz/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sz/UserControlDesigner',{});
},
'Sage/Groups/nls/sz/GroupNavigator':function(){
define('Sage/Groups/nls/sz/GroupNavigator',{});
},
'Sage/Utility/File/nls/sz/AddURLAttachment':function(){
define('Sage/Utility/File/nls/sz/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/sz/EditFilterItems':function(){
define('Sage/UI/Filters/nls/sz/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sz/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sz/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/sz/DragDropWatcher':function(){
define('Sage/Utility/File/nls/sz/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/sz/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/sz/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/sz/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sz/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/sz/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sz/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sz/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sz/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/sz/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/sz/AllOpenListPanelConfig',{});
},
'Sage/MainView/nls/sz/FormManager':function(){
define('Sage/MainView/nls/sz/FormManager',{});
},
'Sage/UI/nls/sz/ActivityScheduler':function(){
define('Sage/UI/nls/sz/ActivityScheduler',{});
},
'Sage/MainView/nls/sz/SecurityManager':function(){
define('Sage/MainView/nls/sz/SecurityManager',{});
},
'Sage/TaskPane/nls/sz/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/sz/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/sz/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/sz/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/sz/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/sz/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/templates/nls/sz/AllOpenDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/sz/AllOpenDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/sz/ReportsListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/sz/ReportsListSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/sz/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/sz/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/templates/nls/sz/ScheduleDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/sz/ScheduleDetailSummary',{});
},
'Sage/MainView/Opportunity/nls/sz/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/sz/UpdateOpportunities',{});
},
'Sage/UI/nls/sz/EditCalendarUsers':function(){
define('Sage/UI/nls/sz/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sz/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sz/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/sz/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sz/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/sz/HelpMenu':function(){
define('Sage/UI/Controls/nls/sz/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/sz/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sz/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/sz/UserTasklet':function(){
define('Sage/TaskPane/nls/sz/UserTasklet',{});
},
'Sage/UI/Alarms/nls/sz/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/sz/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/sz/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/sz/OpportunityStatistics',{});
},
'Sage/TaskPane/nls/sz/GroupListTasklet':function(){
define('Sage/TaskPane/nls/sz/GroupListTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sz/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sz/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/sz/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/sz/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/sz/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/sz/ColumnDesigner',{});
},
'Sage/MainView/JobMgr/templates/nls/sz/JobDefinitionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/sz/JobDefinitionDetailSummary',{});
},
'Sage/UI/nls/sz/SearchMenuItem':function(){
define('Sage/UI/nls/sz/SearchMenuItem',{});
},
'Sage/Library/nls/sz/DocumentProperties':function(){
define('Sage/Library/nls/sz/DocumentProperties',{});
},
'Sage/UI/nls/sz/NotesHistoryList':function(){
define('Sage/UI/nls/sz/NotesHistoryList',{});
},
'Sage/Utility/nls/sz/File':function(){
define('Sage/Utility/nls/sz/File',{});
},
'Sage/MainView/ReportMgr/nls/sz/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/sz/HistoryListPanelConfig',{});
},
'Sage/MainView/JobMgr/templates/nls/sz/ScheduleDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/sz/ScheduleDetailSummary',{});
},
'Sage/QuickForms/Design/nls/sz/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sz/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/sz/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/sz/ContactTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/templates/nls/sz/EventSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/sz/EventSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/sz/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/sz/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/sz/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/sz/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/sz/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/sz/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/sz/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sz/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/sz/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sz/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/sz/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sz/HistoryEditor',{});
},
'Sage/Groups/nls/sz/GroupManager':function(){
define('Sage/Groups/nls/sz/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/sz/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sz/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sz/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sz/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/sz/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/sz/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/sz/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/sz/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sz/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sz/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/sz/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/sz/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/sz/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sz/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sz/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sz/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/sz/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sz/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/sz/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/sz/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/sz/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sz/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sz/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sz/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sz/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sz/PickListControlDesigner',{});
},
'Sage/MainView/ActivityMgr/templates/nls/sz/LitRequestSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/sz/LitRequestSummary',{});
},
'Sage/QuickForms/Design/Editors/nls/sz/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sz/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/sz/FolderHandler':function(){
define('Sage/Library/nls/sz/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/sz/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sz/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/sz/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/sz/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/sz/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sz/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/sz/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/sz/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/sz/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sz/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sz/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sz/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/sz/EditableGrid':function(){
define('Sage/UI/nls/sz/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/sz/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/sz/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/sz/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/sz/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/sz/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/sz/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/sz/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sz/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/sz/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/sz/ReportManagerUtility',{});
},
'Sage/UI/nls/sz/SpeedSearch':function(){
define('Sage/UI/nls/sz/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/sz/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sz/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/sz/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/sz/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/sz/SLXPreviewGrid':function(){
define('Sage/UI/nls/sz/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/sz/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/sz/UnconfirmedPane',{});
},
'Sage/Utility/nls/sz/Utility':function(){
define('Sage/Utility/nls/sz/Utility',{});
},
'Sage/QuickForms/Design/nls/sz/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sz/ControlDesigner',{});
},
'Sage/UI/Controls/nls/sz/Address':function(){
define('Sage/UI/Controls/nls/sz/Address',{});
},
'Sage/MainView/JobMgr/nls/sz/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/sz/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/sz/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sz/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/sz/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sz/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/sz/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/sz/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/sz/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/sz/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/sz/UserType':function(){
define('Sage/UI/nls/sz/UserType',{});
},
'Sage/MainView/ReportMgr/templates/nls/sz/HistoryDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/sz/HistoryDetailSummary',{});
},
'Sage/QuickForms/Design/nls/sz/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/sz/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/sz/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/sz/ActivityCalendar',{});
},
'Sage/Utility/nls/sz/Jobs':function(){
define('Sage/Utility/nls/sz/Jobs',{});
},
'Sage/UI/Controls/nls/sz/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/sz/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/sz/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sz/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/sz/ActivityList':function(){
define('Sage/UI/nls/sz/ActivityList',{});
},
'Sage/UI/Alarms/nls/sz/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/sz/JobNotificationPopup',{});
},
'Sage/MainView/JobMgr/templates/nls/sz/ExecutionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/sz/ExecutionsListSummary',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/sz/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/sz/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/sz/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/sz/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/sz/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sz/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/sz/CalendarUsersListPane':function(){
define('Sage/UI/nls/sz/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/sz/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sz/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sz/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sz/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/templates/nls/sz/ExecutionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/sz/ExecutionDetailSummary',{});
},
'Sage/MainView/ReportMgr/nls/sz/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/sz/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/sz/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/sz/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/sz/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sz/FormBasicPropertyEditor',{});
},
'Sage/UI/Alarms/nls/sz/AlarmButton':function(){
define('Sage/UI/Alarms/nls/sz/AlarmButton',{});
},
'Sage/MainView/ActivityMgr/nls/sz/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/sz/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/sz/Attachment':function(){
define('Sage/Utility/File/nls/sz/Attachment',{});
},
'Sage/QuickForms/Design/nls/sz/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sz/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sz/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/sz/PropertyEditorContainer',{});
},
'Sage/Services/nls/sz/ReportingService':function(){
define('Sage/Services/nls/sz/ReportingService',{});
},
'Sage/MailMerge/nls/sz/Helper':function(){
define('Sage/MailMerge/nls/sz/Helper',{});
},
'Sage/UI/Dashboard/nls/sz/Dashboard':function(){
define('Sage/UI/Dashboard/nls/sz/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/sz/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sz/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/sz/PickList':function(){
define('Sage/UI/Controls/nls/sz/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/sz/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/sz/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/sz/Email':function(){
define('Sage/Utility/nls/sz/Email',{});
},
'Sage/TaskPane/nls/sz/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/sz/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/sz/TimeZoneItem':function(){
define('Sage/UI/nls/sz/TimeZoneItem',{});
},
'Sage/MainView/ReportMgr/templates/nls/sz/HistoryListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/sz/HistoryListSummary',{});
},
'Sage/UI/Columns/nls/sz/SlxEdit':function(){
define('Sage/UI/Columns/nls/sz/SlxEdit',{});
},
'Sage/Reporting/nls/sz/Enumerations':function(){
define('Sage/Reporting/nls/sz/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/sz/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sz/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sz/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sz/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/sz/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/sz/ActivityListPanelConfig',{});
},
'Sage/UI/nls/sz/JobSchedulingWidget':function(){
define('Sage/UI/nls/sz/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/sz/LogOffButton':function(){
define('Sage/UI/Controls/nls/sz/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/sz/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sz/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sz/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sz/EditEventEditor',{});
},
'Sage/MailMerge/nls/sz/Loader':function(){
define('Sage/MailMerge/nls/sz/Loader',{});
},
'Sage/UI/Controls/nls/sz/DateTimePicker':function(){
define('Sage/UI/Controls/nls/sz/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/sz/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/sz/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/sz/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/sz/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/sz/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/sz/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sz/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sz/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/sz/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/sz/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/sz/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sz/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sz/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sz/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/sz/Lookup':function(){
define('Sage/UI/Controls/nls/sz/Lookup',{});
},
'Sage/Utility/File/nls/sz/DescriptionsForm':function(){
define('Sage/Utility/File/nls/sz/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/sz/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sz/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/sz/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/sz/CommonTasksTasklet',{});
},
'Sage/Utility/nls/sz/Dashboard':function(){
define('Sage/Utility/nls/sz/Dashboard',{});
}}});
define("Sage/nls/Sage_sz", [], 1);
