require({cache:{
'Sage/Utility/File/nls/ji/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/ji/FallbackFilePicker',{});
},
'Sage/UI/nls/ji/Boolean':function(){
define('Sage/UI/nls/ji/Boolean',{});
},
'Sage/Services/nls/ji/ActivityService':function(){
define('Sage/Services/nls/ji/ActivityService',{});
},
'Sage/UI/Controls/nls/ji/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/ji/CopyToClipboard',{});
},
'Sage/Utility/nls/ji/Activity':function(){
define('Sage/Utility/nls/ji/Activity',{});
},
'Sage/QuickForms/Design/nls/ji/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/ji/DesignPanel',{});
},
'Sage/UI/nls/ji/TimelessActivitiesPane':function(){
define('Sage/UI/nls/ji/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/ji/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ji/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/ji/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/ji/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/ji/ActivityManager':function(){
define('Sage/MainView/nls/ji/ActivityManager',{});
},
'Sage/Services/nls/ji/JobService':function(){
define('Sage/Services/nls/ji/JobService',{});
},
'Sage/QuickForms/Design/nls/ji/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ji/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/ji/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ji/_PropertyEditor',{});
},
'Sage/Services/nls/ji/ActivityActionProcessor':function(){
define('Sage/Services/nls/ji/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/ji/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ji/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ji/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ji/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ji/UserActivityDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ji/UserActivityDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ji/ConfirmationDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ji/ConfirmationDetailSummary',{});
},
'Sage/Utility/File/nls/ji/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/ji/DefaultDropHandler',{});
},
'Sage/UI/nls/ji/TransferBoxWidget':function(){
define('Sage/UI/nls/ji/TransferBoxWidget',{});
},
'Sage/Utility/File/nls/ji/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/ji/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/ji/AlarmPane':function(){
define('Sage/UI/Alarms/nls/ji/AlarmPane',{});
},
'Sage/TaskPane/nls/ji/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/ji/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/ji/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/ji/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/ji/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ji/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ji/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ji/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/ji/FilterPanel':function(){
define('Sage/UI/Filters/nls/ji/FilterPanel',{});
},
'Sage/TaskPane/nls/ji/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/ji/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/ji/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/ji/ReportManagerFormatter',{});
},
'Sage/UI/nls/ji/OwnerType':function(){
define('Sage/UI/nls/ji/OwnerType',{});
},
'Sage/MainView/JobMgr/templates/nls/ji/JobDefinitionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ji/JobDefinitionsListSummary',{});
},
'Sage/TaskPane/nls/ji/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/ji/LeadTasksTasklet',{});
},
'Sage/MainView/ReportMgr/templates/nls/ji/ReportDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ji/ReportDetailSummary',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ji/_ParameterEditorBase':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ji/_ParameterEditorBase',{});
},
'Sage/MailMerge/nls/ji/Service':function(){
define('Sage/MailMerge/nls/ji/Service',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ji/ConfirmationListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ji/ConfirmationListSummary',{});
},
'Sage/MainView/ActivityMgr/nls/ji/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/ji/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/ji/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ji/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ji/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ji/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ji/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ji/InvoiceRTDV',{});
},
'Sage/UI/nls/ji/SDataLookup':function(){
define('Sage/UI/nls/ji/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/ji/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/ji/RowDesigner',{});
},
'Sage/Groups/nls/ji/GroupLookup':function(){
define('Sage/Groups/nls/ji/GroupLookup',{});
},
'Sage/TaskPane/nls/ji/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/ji/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/ji/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/ji/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/ji/LibraryDocument':function(){
define('Sage/Utility/File/nls/ji/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ji/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ji/SpeedSearchLookup',{});
},
'Sage/UI/nls/ji/ConditionManager':function(){
define('Sage/UI/nls/ji/ConditionManager',{});
},
'Sage/MainView/JobMgr/templates/nls/ji/SchedulesListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ji/SchedulesListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ji/UserActivityListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ji/UserActivityListSummary',{});
},
'Sage/UI/Dashboard/nls/ji/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/ji/WidgetDefinition',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ji/AllOpenListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ji/AllOpenListSummary',{});
},
'Sage/UI/nls/ji/SearchConditionWidget':function(){
define('Sage/UI/nls/ji/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/ji/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ji/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ji/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/ji/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ji/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ji/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/ji/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/ji/DataSourcePanel',{});
},
'Sage/MainView/ReportMgr/templates/nls/ji/SchedulesListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ji/SchedulesListSummary',{});
},
'Sage/Library/nls/ji/Manager':function(){
define('Sage/Library/nls/ji/Manager',{});
},
'Sage/UI/nls/ji/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/ji/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/ji/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/ji/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/ji/Name':function(){
define('Sage/UI/Controls/nls/ji/Name',{});
},
'Sage/MainView/JobMgr/nls/ji/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ji/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ji/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ji/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/ji/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/ji/UpdateLeads',{});
},
'Sage/Library/nls/ji/FileHandler':function(){
define('Sage/Library/nls/ji/FileHandler',{});
},
'Sage/UI/nls/ji/ListPanel':function(){
define('Sage/UI/nls/ji/ListPanel',{});
},
'Sage/Utility/nls/ji/Sql':function(){
define('Sage/Utility/nls/ji/Sql',{});
},
'Sage/UI/Filters/nls/ji/EditFilters':function(){
define('Sage/UI/Filters/nls/ji/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/ji/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ji/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/ji/DurationSelect':function(){
define('Sage/UI/Controls/nls/ji/DurationSelect',{});
},
'Sage/UI/Alarms/nls/ji/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/ji/AlarmCountDown',{});
},
'Sage/UI/nls/ji/AttachmentList':function(){
define('Sage/UI/nls/ji/AttachmentList',{});
},
'Sage/MailMerge/nls/ji/Lookup':function(){
define('Sage/MailMerge/nls/ji/Lookup',{});
},
'Sage/QuickForms/Design/Editors/nls/ji/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ji/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ji/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/ji/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/ji/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ji/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ji/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ji/EditableGridControlDesigner',{});
},
'Sage/MainView/Options/nls/ji/OptionsDialog':function(){
define('Sage/MainView/Options/nls/ji/OptionsDialog',{});
},
'Sage/QuickForms/Design/nls/ji/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ji/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/ji/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/ji/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/ji/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ji/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/ji/Dialogs':function(){
define('Sage/UI/nls/ji/Dialogs',{});
},
'Sage/MainView/IntegrationContract/nls/ji/SyncResultsHistory':function(){
define('Sage/MainView/IntegrationContract/nls/ji/SyncResultsHistory',{});
},
'Sage/TaskPane/nls/ji/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/ji/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/ji/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/ji/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/ji/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ji/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/ji/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ji/UserControlDesigner',{});
},
'Sage/Groups/nls/ji/GroupNavigator':function(){
define('Sage/Groups/nls/ji/GroupNavigator',{});
},
'Sage/Utility/File/nls/ji/AddURLAttachment':function(){
define('Sage/Utility/File/nls/ji/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/ji/EditFilterItems':function(){
define('Sage/UI/Filters/nls/ji/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ji/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ji/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/ji/DragDropWatcher':function(){
define('Sage/Utility/File/nls/ji/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/ji/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/ji/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/ji/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ji/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ji/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ji/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ji/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ji/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ji/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ji/AllOpenListPanelConfig',{});
},
'Sage/MainView/nls/ji/FormManager':function(){
define('Sage/MainView/nls/ji/FormManager',{});
},
'Sage/UI/nls/ji/ActivityScheduler':function(){
define('Sage/UI/nls/ji/ActivityScheduler',{});
},
'Sage/MainView/nls/ji/SecurityManager':function(){
define('Sage/MainView/nls/ji/SecurityManager',{});
},
'Sage/TaskPane/nls/ji/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/ji/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/ji/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/ji/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/ji/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/ji/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ji/AllOpenDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ji/AllOpenDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ji/ReportsListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ji/ReportsListSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/ji/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/ji/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/templates/nls/ji/ScheduleDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ji/ScheduleDetailSummary',{});
},
'Sage/MainView/Opportunity/nls/ji/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/ji/UpdateOpportunities',{});
},
'Sage/UI/nls/ji/EditCalendarUsers':function(){
define('Sage/UI/nls/ji/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ji/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ji/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/ji/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ji/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/ji/HelpMenu':function(){
define('Sage/UI/Controls/nls/ji/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/ji/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ji/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/ji/UserTasklet':function(){
define('Sage/TaskPane/nls/ji/UserTasklet',{});
},
'Sage/UI/Alarms/nls/ji/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/ji/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/ji/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/ji/OpportunityStatistics',{});
},
'Sage/TaskPane/nls/ji/GroupListTasklet':function(){
define('Sage/TaskPane/nls/ji/GroupListTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ji/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ji/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ji/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/ji/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/ji/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/ji/ColumnDesigner',{});
},
'Sage/MainView/JobMgr/templates/nls/ji/JobDefinitionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ji/JobDefinitionDetailSummary',{});
},
'Sage/UI/nls/ji/SearchMenuItem':function(){
define('Sage/UI/nls/ji/SearchMenuItem',{});
},
'Sage/Library/nls/ji/DocumentProperties':function(){
define('Sage/Library/nls/ji/DocumentProperties',{});
},
'Sage/UI/nls/ji/NotesHistoryList':function(){
define('Sage/UI/nls/ji/NotesHistoryList',{});
},
'Sage/Utility/nls/ji/File':function(){
define('Sage/Utility/nls/ji/File',{});
},
'Sage/MainView/ReportMgr/nls/ji/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ji/HistoryListPanelConfig',{});
},
'Sage/MainView/JobMgr/templates/nls/ji/ScheduleDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ji/ScheduleDetailSummary',{});
},
'Sage/QuickForms/Design/nls/ji/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ji/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/ji/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/ji/ContactTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ji/EventSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ji/EventSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/ji/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/ji/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/ji/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ji/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/ji/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/ji/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/ji/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ji/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/ji/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ji/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ji/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ji/HistoryEditor',{});
},
'Sage/Groups/nls/ji/GroupManager':function(){
define('Sage/Groups/nls/ji/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/ji/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ji/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ji/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ji/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ji/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ji/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/ji/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/ji/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ji/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ji/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/ji/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ji/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ji/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ji/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ji/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ji/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/ji/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ji/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ji/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ji/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ji/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ji/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ji/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ji/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ji/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ji/PickListControlDesigner',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ji/LitRequestSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ji/LitRequestSummary',{});
},
'Sage/QuickForms/Design/Editors/nls/ji/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ji/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/ji/FolderHandler':function(){
define('Sage/Library/nls/ji/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/ji/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ji/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/ji/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/ji/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/ji/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ji/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/ji/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/ji/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/ji/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ji/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ji/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ji/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/ji/EditableGrid':function(){
define('Sage/UI/nls/ji/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/ji/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ji/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/ji/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/ji/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/ji/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/ji/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/ji/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ji/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ji/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/ji/ReportManagerUtility',{});
},
'Sage/UI/nls/ji/SpeedSearch':function(){
define('Sage/UI/nls/ji/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/ji/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ji/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/ji/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ji/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/ji/SLXPreviewGrid':function(){
define('Sage/UI/nls/ji/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/ji/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/ji/UnconfirmedPane',{});
},
'Sage/Utility/nls/ji/Utility':function(){
define('Sage/Utility/nls/ji/Utility',{});
},
'Sage/QuickForms/Design/nls/ji/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ji/ControlDesigner',{});
},
'Sage/UI/Controls/nls/ji/Address':function(){
define('Sage/UI/Controls/nls/ji/Address',{});
},
'Sage/MainView/JobMgr/nls/ji/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/ji/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/ji/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ji/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ji/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ji/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/ji/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ji/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/ji/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ji/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/ji/UserType':function(){
define('Sage/UI/nls/ji/UserType',{});
},
'Sage/MainView/ReportMgr/templates/nls/ji/HistoryDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ji/HistoryDetailSummary',{});
},
'Sage/QuickForms/Design/nls/ji/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/ji/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/ji/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/ji/ActivityCalendar',{});
},
'Sage/Utility/nls/ji/Jobs':function(){
define('Sage/Utility/nls/ji/Jobs',{});
},
'Sage/UI/Controls/nls/ji/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/ji/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/ji/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ji/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/ji/ActivityList':function(){
define('Sage/UI/nls/ji/ActivityList',{});
},
'Sage/UI/Alarms/nls/ji/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/ji/JobNotificationPopup',{});
},
'Sage/MainView/JobMgr/templates/nls/ji/ExecutionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ji/ExecutionsListSummary',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ji/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ji/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/ji/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ji/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ji/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ji/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/ji/CalendarUsersListPane':function(){
define('Sage/UI/nls/ji/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/ji/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ji/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ji/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ji/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/templates/nls/ji/ExecutionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ji/ExecutionDetailSummary',{});
},
'Sage/MainView/ReportMgr/nls/ji/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/ji/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/ji/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/ji/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ji/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ji/FormBasicPropertyEditor',{});
},
'Sage/UI/Alarms/nls/ji/AlarmButton':function(){
define('Sage/UI/Alarms/nls/ji/AlarmButton',{});
},
'Sage/MainView/ActivityMgr/nls/ji/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/ji/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/ji/Attachment':function(){
define('Sage/Utility/File/nls/ji/Attachment',{});
},
'Sage/QuickForms/Design/nls/ji/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ji/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ji/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/ji/PropertyEditorContainer',{});
},
'Sage/Services/nls/ji/ReportingService':function(){
define('Sage/Services/nls/ji/ReportingService',{});
},
'Sage/MailMerge/nls/ji/Helper':function(){
define('Sage/MailMerge/nls/ji/Helper',{});
},
'Sage/UI/Dashboard/nls/ji/Dashboard':function(){
define('Sage/UI/Dashboard/nls/ji/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/ji/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ji/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/ji/PickList':function(){
define('Sage/UI/Controls/nls/ji/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/ji/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ji/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/ji/Email':function(){
define('Sage/Utility/nls/ji/Email',{});
},
'Sage/TaskPane/nls/ji/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ji/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/ji/TimeZoneItem':function(){
define('Sage/UI/nls/ji/TimeZoneItem',{});
},
'Sage/MainView/ReportMgr/templates/nls/ji/HistoryListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ji/HistoryListSummary',{});
},
'Sage/UI/Columns/nls/ji/SlxEdit':function(){
define('Sage/UI/Columns/nls/ji/SlxEdit',{});
},
'Sage/Reporting/nls/ji/Enumerations':function(){
define('Sage/Reporting/nls/ji/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/ji/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ji/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ji/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ji/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ji/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ji/ActivityListPanelConfig',{});
},
'Sage/UI/nls/ji/JobSchedulingWidget':function(){
define('Sage/UI/nls/ji/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/ji/LogOffButton':function(){
define('Sage/UI/Controls/nls/ji/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/ji/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ji/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ji/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ji/EditEventEditor',{});
},
'Sage/MailMerge/nls/ji/Loader':function(){
define('Sage/MailMerge/nls/ji/Loader',{});
},
'Sage/UI/Controls/nls/ji/DateTimePicker':function(){
define('Sage/UI/Controls/nls/ji/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/ji/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/ji/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/ji/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/ji/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/ji/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/ji/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ji/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ji/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ji/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ji/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ji/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ji/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ji/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ji/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/ji/Lookup':function(){
define('Sage/UI/Controls/nls/ji/Lookup',{});
},
'Sage/Utility/File/nls/ji/DescriptionsForm':function(){
define('Sage/Utility/File/nls/ji/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/ji/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ji/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/ji/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/ji/CommonTasksTasklet',{});
},
'Sage/Utility/nls/ji/Dashboard':function(){
define('Sage/Utility/nls/ji/Dashboard',{});
}}});
define("Sage/nls/Sage_ji", [], 1);
