require({cache:{
'Sage/Utility/File/nls/ar/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/ar/FallbackFilePicker',{});
},
'Sage/Utility/File/nls/ar-qa/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/ar-qa/FallbackFilePicker',{});
},
'Sage/UI/nls/ar/Boolean':function(){
define('Sage/UI/nls/ar/Boolean',{});
},
'Sage/UI/nls/ar-qa/Boolean':function(){
define('Sage/UI/nls/ar-qa/Boolean',{});
},
'Sage/Services/nls/ar/ActivityService':function(){
define('Sage/Services/nls/ar/ActivityService',{});
},
'Sage/Services/nls/ar-qa/ActivityService':function(){
define('Sage/Services/nls/ar-qa/ActivityService',{});
},
'Sage/UI/Controls/nls/ar/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/ar/CopyToClipboard',{});
},
'Sage/UI/Controls/nls/ar-qa/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/ar-qa/CopyToClipboard',{});
},
'Sage/Utility/nls/ar/Activity':function(){
define('Sage/Utility/nls/ar/Activity',{});
},
'Sage/Utility/nls/ar-qa/Activity':function(){
define('Sage/Utility/nls/ar-qa/Activity',{});
},
'Sage/QuickForms/Design/nls/ar/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/ar/DesignPanel',{});
},
'Sage/QuickForms/Design/nls/ar-qa/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/ar-qa/DesignPanel',{});
},
'Sage/UI/nls/ar/TimelessActivitiesPane':function(){
define('Sage/UI/nls/ar/TimelessActivitiesPane',{});
},
'Sage/UI/nls/ar-qa/TimelessActivitiesPane':function(){
define('Sage/UI/nls/ar-qa/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-qa/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-qa/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/ar/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/ar/ContactUserAssociationEditor',{});
},
'Sage/TaskPane/User/nls/ar-qa/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/ar-qa/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/ar/ActivityManager':function(){
define('Sage/MainView/nls/ar/ActivityManager',{});
},
'Sage/MainView/nls/ar-qa/ActivityManager':function(){
define('Sage/MainView/nls/ar-qa/ActivityManager',{});
},
'Sage/Services/nls/ar/JobService':function(){
define('Sage/Services/nls/ar/JobService',{});
},
'Sage/Services/nls/ar-qa/JobService':function(){
define('Sage/Services/nls/ar-qa/JobService',{});
},
'Sage/QuickForms/Design/nls/ar/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-qa/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-qa/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/_PropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-qa/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-qa/_PropertyEditor',{});
},
'Sage/Services/nls/ar/ActivityActionProcessor':function(){
define('Sage/Services/nls/ar/ActivityActionProcessor',{});
},
'Sage/Services/nls/ar-qa/ActivityActionProcessor':function(){
define('Sage/Services/nls/ar-qa/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/TextBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-qa/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-qa/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-qa/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-qa/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar/UserActivityDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar/UserActivityDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar-qa/UserActivityDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar-qa/UserActivityDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar/ConfirmationDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar/ConfirmationDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar-qa/ConfirmationDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar-qa/ConfirmationDetailSummary',{});
},
'Sage/Utility/File/nls/ar/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/ar/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/ar-qa/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/ar-qa/DefaultDropHandler',{});
},
'Sage/UI/nls/ar/TransferBoxWidget':function(){
define('Sage/UI/nls/ar/TransferBoxWidget',{});
},
'Sage/UI/nls/ar-qa/TransferBoxWidget':function(){
define('Sage/UI/nls/ar-qa/TransferBoxWidget',{});
},
'Sage/Utility/File/nls/ar/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/ar/AttachmentPropertiesEditForm',{});
},
'Sage/Utility/File/nls/ar-qa/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/ar-qa/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/ar/AlarmPane':function(){
define('Sage/UI/Alarms/nls/ar/AlarmPane',{});
},
'Sage/UI/Alarms/nls/ar-qa/AlarmPane':function(){
define('Sage/UI/Alarms/nls/ar-qa/AlarmPane',{});
},
'Sage/TaskPane/nls/ar/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/ar/LiteratureManagementTasks',{});
},
'Sage/TaskPane/nls/ar-qa/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/ar-qa/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/ar/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/ar/DashboardWidget',{});
},
'Sage/UI/Dashboard/nls/ar-qa/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/ar-qa/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/NumericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-qa/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-qa/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ar/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar/CustomerPaymentsRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/ar-qa/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar-qa/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/ar/FilterPanel':function(){
define('Sage/UI/Filters/nls/ar/FilterPanel',{});
},
'Sage/UI/Filters/nls/ar-qa/FilterPanel':function(){
define('Sage/UI/Filters/nls/ar-qa/FilterPanel',{});
},
'Sage/TaskPane/nls/ar/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/ar/_BaseTaskPaneTasklet',{});
},
'Sage/TaskPane/nls/ar-qa/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/ar-qa/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/ar/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/ar/ReportManagerFormatter',{});
},
'Sage/MainView/ReportMgr/nls/ar-qa/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/ar-qa/ReportManagerFormatter',{});
},
'Sage/UI/nls/ar/OwnerType':function(){
define('Sage/UI/nls/ar/OwnerType',{});
},
'Sage/UI/nls/ar-qa/OwnerType':function(){
define('Sage/UI/nls/ar-qa/OwnerType',{});
},
'Sage/MainView/JobMgr/templates/nls/ar/JobDefinitionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar/JobDefinitionsListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/ar-qa/JobDefinitionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar-qa/JobDefinitionsListSummary',{});
},
'Sage/TaskPane/nls/ar/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/LeadTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-qa/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-qa/LeadTasksTasklet',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar/ReportDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar/ReportDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar-qa/ReportDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar-qa/ReportDetailSummary',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/_ParameterEditorBase':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/_ParameterEditorBase',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-qa/_ParameterEditorBase':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-qa/_ParameterEditorBase',{});
},
'Sage/MailMerge/nls/ar/Service':function(){
define('Sage/MailMerge/nls/ar/Service',{});
},
'Sage/MailMerge/nls/ar-qa/Service':function(){
define('Sage/MailMerge/nls/ar-qa/Service',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar/ConfirmationListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar/ConfirmationListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar-qa/ConfirmationListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar-qa/ConfirmationListSummary',{});
},
'Sage/MainView/ActivityMgr/nls/ar/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/ar/SnoozeOptions',{});
},
'Sage/MainView/ActivityMgr/nls/ar-qa/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/ar-qa/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-qa/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-qa/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-qa/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-qa/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ar/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar/InvoiceRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/ar-qa/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar-qa/InvoiceRTDV',{});
},
'Sage/UI/nls/ar/SDataLookup':function(){
define('Sage/UI/nls/ar/SDataLookup',{});
},
'Sage/UI/nls/ar-qa/SDataLookup':function(){
define('Sage/UI/nls/ar-qa/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/ar/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/RowDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-qa/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-qa/RowDesigner',{});
},
'Sage/Groups/nls/ar/GroupLookup':function(){
define('Sage/Groups/nls/ar/GroupLookup',{});
},
'Sage/Groups/nls/ar-qa/GroupLookup':function(){
define('Sage/Groups/nls/ar-qa/GroupLookup',{});
},
'Sage/TaskPane/nls/ar/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/OpportunityTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-qa/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-qa/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/ar/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/ar/CheckBoxFilter',{});
},
'Sage/UI/Filters/nls/ar-qa/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/ar-qa/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/ar/LibraryDocument':function(){
define('Sage/Utility/File/nls/ar/LibraryDocument',{});
},
'Sage/Utility/File/nls/ar-qa/LibraryDocument':function(){
define('Sage/Utility/File/nls/ar-qa/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar/SpeedSearchLookup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar-qa/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar-qa/SpeedSearchLookup',{});
},
'Sage/UI/nls/ar/ConditionManager':function(){
define('Sage/UI/nls/ar/ConditionManager',{});
},
'Sage/UI/nls/ar-qa/ConditionManager':function(){
define('Sage/UI/nls/ar-qa/ConditionManager',{});
},
'Sage/MainView/JobMgr/templates/nls/ar/SchedulesListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar/SchedulesListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/ar-qa/SchedulesListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar-qa/SchedulesListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar/UserActivityListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar/UserActivityListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar-qa/UserActivityListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar-qa/UserActivityListSummary',{});
},
'Sage/UI/Dashboard/nls/ar/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/ar/WidgetDefinition',{});
},
'Sage/UI/Dashboard/nls/ar-qa/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/ar-qa/WidgetDefinition',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar/AllOpenListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar/AllOpenListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar-qa/AllOpenListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar-qa/AllOpenListSummary',{});
},
'Sage/UI/nls/ar/SearchConditionWidget':function(){
define('Sage/UI/nls/ar/SearchConditionWidget',{});
},
'Sage/UI/nls/ar-qa/SearchConditionWidget':function(){
define('Sage/UI/nls/ar-qa/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-qa/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-qa/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ar/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/ar/JobManagerActions',{});
},
'Sage/MainView/JobMgr/nls/ar-qa/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/ar-qa/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar/ContactLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar-qa/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar-qa/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/ar/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/ar/DataSourcePanel',{});
},
'Sage/QuickForms/Design/nls/ar-qa/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/ar-qa/DataSourcePanel',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar/SchedulesListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar/SchedulesListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar-qa/SchedulesListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar-qa/SchedulesListSummary',{});
},
'Sage/Library/nls/ar/Manager':function(){
define('Sage/Library/nls/ar/Manager',{});
},
'Sage/Library/nls/ar-qa/Manager':function(){
define('Sage/Library/nls/ar-qa/Manager',{});
},
'Sage/UI/nls/ar/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/ar/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/nls/ar-qa/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/ar-qa/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/ar/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/ar/NonVisibleControlContainer',{});
},
'Sage/QuickForms/Design/nls/ar-qa/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/ar-qa/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/ar/Name':function(){
define('Sage/UI/Controls/nls/ar/Name',{});
},
'Sage/UI/Controls/nls/ar-qa/Name':function(){
define('Sage/UI/Controls/nls/ar-qa/Name',{});
},
'Sage/MainView/JobMgr/nls/ar/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar/ExecutionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/ar-qa/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar-qa/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ar/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/PhoneControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-qa/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-qa/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/ar/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/ar/UpdateLeads',{});
},
'Sage/MainView/Lead/nls/ar-qa/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/ar-qa/UpdateLeads',{});
},
'Sage/Library/nls/ar/FileHandler':function(){
define('Sage/Library/nls/ar/FileHandler',{});
},
'Sage/Library/nls/ar-qa/FileHandler':function(){
define('Sage/Library/nls/ar-qa/FileHandler',{});
},
'Sage/UI/nls/ar/ListPanel':function(){
define('Sage/UI/nls/ar/ListPanel',{});
},
'Sage/UI/nls/ar-qa/ListPanel':function(){
define('Sage/UI/nls/ar-qa/ListPanel',{});
},
'Sage/Utility/nls/ar/Sql':function(){
define('Sage/Utility/nls/ar/Sql',{});
},
'Sage/Utility/nls/ar-qa/Sql':function(){
define('Sage/Utility/nls/ar-qa/Sql',{});
},
'Sage/UI/Filters/nls/ar/EditFilters':function(){
define('Sage/UI/Filters/nls/ar/EditFilters',{});
},
'Sage/UI/Filters/nls/ar-qa/EditFilters':function(){
define('Sage/UI/Filters/nls/ar-qa/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/FormUsagesPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-qa/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-qa/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/ar/DurationSelect':function(){
define('Sage/UI/Controls/nls/ar/DurationSelect',{});
},
'Sage/UI/Controls/nls/ar-qa/DurationSelect':function(){
define('Sage/UI/Controls/nls/ar-qa/DurationSelect',{});
},
'Sage/UI/Alarms/nls/ar/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/ar/AlarmCountDown',{});
},
'Sage/UI/Alarms/nls/ar-qa/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/ar-qa/AlarmCountDown',{});
},
'Sage/UI/nls/ar/AttachmentList':function(){
define('Sage/UI/nls/ar/AttachmentList',{});
},
'Sage/UI/nls/ar-qa/AttachmentList':function(){
define('Sage/UI/nls/ar-qa/AttachmentList',{});
},
'Sage/MailMerge/nls/ar/Lookup':function(){
define('Sage/MailMerge/nls/ar/Lookup',{});
},
'Sage/MailMerge/nls/ar-qa/Lookup':function(){
define('Sage/MailMerge/nls/ar-qa/Lookup',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-qa/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-qa/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ar/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/ar/RunJobDialog',{});
},
'Sage/MainView/JobMgr/nls/ar-qa/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/ar-qa/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/ar/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-qa/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-qa/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-qa/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-qa/EditableGridControlDesigner',{});
},
'Sage/MainView/Options/nls/ar/OptionsDialog':function(){
define('Sage/MainView/Options/nls/ar/OptionsDialog',{});
},
'Sage/MainView/Options/nls/ar-qa/OptionsDialog':function(){
define('Sage/MainView/Options/nls/ar-qa/OptionsDialog',{});
},
'Sage/QuickForms/Design/nls/ar/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/HiddenControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-qa/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-qa/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/ar/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/ar/DashboardWidgetCell',{});
},
'Sage/UI/Dashboard/nls/ar-qa/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/ar-qa/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/UserBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-qa/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-qa/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/ar/Dialogs':function(){
define('Sage/UI/nls/ar/Dialogs',{});
},
'Sage/UI/nls/ar-qa/Dialogs':function(){
define('Sage/UI/nls/ar-qa/Dialogs',{});
},
'Sage/MainView/IntegrationContract/nls/ar/SyncResultsHistory':function(){
define('Sage/MainView/IntegrationContract/nls/ar/SyncResultsHistory',{});
},
'Sage/MainView/IntegrationContract/nls/ar-qa/SyncResultsHistory':function(){
define('Sage/MainView/IntegrationContract/nls/ar-qa/SyncResultsHistory',{});
},
'Sage/TaskPane/nls/ar/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/ar/SecuredActionTasklet',{});
},
'Sage/TaskPane/nls/ar-qa/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/ar-qa/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/ar/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/ar/DashboardTabController',{});
},
'Sage/UI/Dashboard/nls/ar-qa/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/ar-qa/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/ar/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar/SalesOrderRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/ar-qa/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar-qa/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/ar/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/UserControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-qa/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-qa/UserControlDesigner',{});
},
'Sage/Groups/nls/ar/GroupNavigator':function(){
define('Sage/Groups/nls/ar/GroupNavigator',{});
},
'Sage/Groups/nls/ar-qa/GroupNavigator':function(){
define('Sage/Groups/nls/ar-qa/GroupNavigator',{});
},
'Sage/Utility/File/nls/ar/AddURLAttachment':function(){
define('Sage/Utility/File/nls/ar/AddURLAttachment',{});
},
'Sage/Utility/File/nls/ar-qa/AddURLAttachment':function(){
define('Sage/Utility/File/nls/ar-qa/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/ar/EditFilterItems':function(){
define('Sage/UI/Filters/nls/ar/EditFilterItems',{});
},
'Sage/UI/Filters/nls/ar-qa/EditFilterItems':function(){
define('Sage/UI/Filters/nls/ar-qa/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportsFormatter',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-qa/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-qa/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/ar/DragDropWatcher':function(){
define('Sage/Utility/File/nls/ar/DragDropWatcher',{});
},
'Sage/Utility/File/nls/ar-qa/DragDropWatcher':function(){
define('Sage/Utility/File/nls/ar-qa/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/ar/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/ar/DesignSurface',{});
},
'Sage/QuickForms/Design/nls/ar-qa/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/ar-qa/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-qa/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-qa/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/FormAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-qa/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-qa/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/EventListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-qa/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-qa/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ar/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ar/AllOpenListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ar-qa/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ar-qa/AllOpenListPanelConfig',{});
},
'Sage/MainView/nls/ar/FormManager':function(){
define('Sage/MainView/nls/ar/FormManager',{});
},
'Sage/MainView/nls/ar-qa/FormManager':function(){
define('Sage/MainView/nls/ar-qa/FormManager',{});
},
'Sage/UI/nls/ar/ActivityScheduler':function(){
define('Sage/UI/nls/ar/ActivityScheduler',{});
},
'Sage/UI/nls/ar-qa/ActivityScheduler':function(){
define('Sage/UI/nls/ar-qa/ActivityScheduler',{});
},
'Sage/MainView/nls/ar/SecurityManager':function(){
define('Sage/MainView/nls/ar/SecurityManager',{});
},
'Sage/MainView/nls/ar-qa/SecurityManager':function(){
define('Sage/MainView/nls/ar-qa/SecurityManager',{});
},
'Sage/TaskPane/nls/ar/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/ar/ActivityTaskConfigurationProvider',{});
},
'Sage/TaskPane/nls/ar-qa/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/ar-qa/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/ar/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/ar/EntityInfoToolTip',{});
},
'Sage/UI/Controls/nls/ar-qa/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/ar-qa/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/ar-qa/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/ar-qa/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar/AllOpenDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar/AllOpenDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar-qa/AllOpenDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar-qa/AllOpenDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar/ReportsListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar/ReportsListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar-qa/ReportsListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar-qa/ReportsListSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/ar/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/ar/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/Common/nls/ar-qa/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/ar-qa/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar/ScheduleDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar/ScheduleDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar-qa/ScheduleDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar-qa/ScheduleDetailSummary',{});
},
'Sage/MainView/Opportunity/nls/ar/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/ar/UpdateOpportunities',{});
},
'Sage/MainView/Opportunity/nls/ar-qa/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/ar-qa/UpdateOpportunities',{});
},
'Sage/UI/nls/ar/EditCalendarUsers':function(){
define('Sage/UI/nls/ar/EditCalendarUsers',{});
},
'Sage/UI/nls/ar-qa/EditCalendarUsers':function(){
define('Sage/UI/nls/ar-qa/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportParametersDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-qa/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-qa/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/ar/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/DateTimePickerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-qa/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-qa/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/ar/HelpMenu':function(){
define('Sage/UI/Controls/nls/ar/HelpMenu',{});
},
'Sage/UI/Controls/nls/ar-qa/HelpMenu':function(){
define('Sage/UI/Controls/nls/ar-qa/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/LayoutPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-qa/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-qa/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/ar/UserTasklet':function(){
define('Sage/TaskPane/nls/ar/UserTasklet',{});
},
'Sage/TaskPane/nls/ar-qa/UserTasklet':function(){
define('Sage/TaskPane/nls/ar-qa/UserTasklet',{});
},
'Sage/UI/Alarms/nls/ar/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/ar/ActivityAlarm',{});
},
'Sage/UI/Alarms/nls/ar-qa/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/ar-qa/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/ar/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/ar/OpportunityStatistics',{});
},
'Sage/MainView/Opportunity/nls/ar-qa/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/ar-qa/OpportunityStatistics',{});
},
'Sage/TaskPane/nls/ar/GroupListTasklet':function(){
define('Sage/TaskPane/nls/ar/GroupListTasklet',{});
},
'Sage/TaskPane/nls/ar-qa/GroupListTasklet':function(){
define('Sage/TaskPane/nls/ar-qa/GroupListTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportConditionEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-qa/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-qa/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ar/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/ar/AdvancedSearchOptions',{});
},
'Sage/MainView/IntegrationContract/nls/ar-qa/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/ar-qa/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/ar/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/ColumnDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-qa/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-qa/ColumnDesigner',{});
},
'Sage/MainView/JobMgr/templates/nls/ar/JobDefinitionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar/JobDefinitionDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/ar-qa/JobDefinitionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar-qa/JobDefinitionDetailSummary',{});
},
'Sage/UI/nls/ar/SearchMenuItem':function(){
define('Sage/UI/nls/ar/SearchMenuItem',{});
},
'Sage/UI/nls/ar-qa/SearchMenuItem':function(){
define('Sage/UI/nls/ar-qa/SearchMenuItem',{});
},
'Sage/Library/nls/ar/DocumentProperties':function(){
define('Sage/Library/nls/ar/DocumentProperties',{});
},
'Sage/Library/nls/ar-qa/DocumentProperties':function(){
define('Sage/Library/nls/ar-qa/DocumentProperties',{});
},
'Sage/UI/nls/ar/NotesHistoryList':function(){
define('Sage/UI/nls/ar/NotesHistoryList',{});
},
'Sage/UI/nls/ar-qa/NotesHistoryList':function(){
define('Sage/UI/nls/ar-qa/NotesHistoryList',{});
},
'Sage/Utility/nls/ar/File':function(){
define('Sage/Utility/nls/ar/File',{});
},
'Sage/Utility/nls/ar-qa/File':function(){
define('Sage/Utility/nls/ar-qa/File',{});
},
'Sage/MainView/ReportMgr/nls/ar/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/ar-qa/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar-qa/HistoryListPanelConfig',{});
},
'Sage/MainView/JobMgr/templates/nls/ar/ScheduleDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar/ScheduleDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/ar-qa/ScheduleDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar-qa/ScheduleDetailSummary',{});
},
'Sage/QuickForms/Design/nls/ar/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/UrlControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-qa/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-qa/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/ar/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/ContactTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-qa/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-qa/ContactTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar/EventSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar/EventSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar-qa/EventSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar-qa/EventSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/ar/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/ar/_WizardDialogBase',{});
},
'Sage/MainView/ReportMgr/Common/nls/ar-qa/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/ar-qa/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/ar/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar/SchedulesListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/ar-qa/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar-qa/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/ar/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/ar/GoogleDocPicker',{});
},
'Sage/Utility/File/nls/ar-qa/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/ar-qa/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/ar/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/ComboBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-qa/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-qa/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/ar/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-qa/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-qa/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/HistoryEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-qa/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-qa/HistoryEditor',{});
},
'Sage/Groups/nls/ar/GroupManager':function(){
define('Sage/Groups/nls/ar/GroupManager',{});
},
'Sage/Groups/nls/ar-qa/GroupManager':function(){
define('Sage/Groups/nls/ar-qa/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-qa/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-qa/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/ComboBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-qa/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-qa/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ar/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar/ReportsListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/ar-qa/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar-qa/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/ar/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/ar/JobNotificationButton',{});
},
'Sage/UI/Alarms/nls/ar-qa/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/ar-qa/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportWizardController',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-qa/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-qa/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/ar/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/ar-qa/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar-qa/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/RecurringEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-qa/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-qa/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportsUtility',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-qa/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-qa/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-qa/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-qa/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ar/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/ar-qa/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar-qa/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ar/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-qa/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-qa/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-qa/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-qa/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-qa/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-qa/PickListControlDesigner',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar/LitRequestSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar/LitRequestSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar-qa/LitRequestSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar-qa/LitRequestSummary',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-qa/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-qa/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/ar/FolderHandler':function(){
define('Sage/Library/nls/ar/FolderHandler',{});
},
'Sage/Library/nls/ar-qa/FolderHandler':function(){
define('Sage/Library/nls/ar-qa/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-qa/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-qa/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/ar/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/ar/ContactSearchForDuplicates',{});
},
'Sage/MainView/Contact/nls/ar-qa/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/ar-qa/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/DateTimePickerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-qa/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-qa/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/ar/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/AccountingTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-qa/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-qa/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-qa/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-qa/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/CurrencyBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-qa/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-qa/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/ar/EditableGrid':function(){
define('Sage/UI/nls/ar/EditableGrid',{});
},
'Sage/UI/nls/ar-qa/EditableGrid':function(){
define('Sage/UI/nls/ar-qa/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/ar/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar/SalesQuoteRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/ar-qa/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar-qa/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/ar/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/ar/SecurityProfile',{});
},
'Sage/MainView/SecurityMgr/nls/ar-qa/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/ar-qa/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/ar/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/ar/ReportWizardController',{});
},
'Sage/MainView/ReportMgr/nls/ar-qa/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/ar-qa/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/UserAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-qa/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-qa/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ar/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/ar/ReportManagerUtility',{});
},
'Sage/MainView/ReportMgr/nls/ar-qa/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/ar-qa/ReportManagerUtility',{});
},
'Sage/UI/nls/ar/SpeedSearch':function(){
define('Sage/UI/nls/ar/SpeedSearch',{});
},
'Sage/UI/nls/ar-qa/SpeedSearch':function(){
define('Sage/UI/nls/ar-qa/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/CurrencyAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-qa/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-qa/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/ar/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/ReportManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-qa/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-qa/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/ar/SLXPreviewGrid':function(){
define('Sage/UI/nls/ar/SLXPreviewGrid',{});
},
'Sage/UI/nls/ar-qa/SLXPreviewGrid':function(){
define('Sage/UI/nls/ar-qa/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/ar/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/ar/UnconfirmedPane',{});
},
'Sage/UI/Alarms/nls/ar-qa/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/ar-qa/UnconfirmedPane',{});
},
'Sage/Utility/nls/ar/Utility':function(){
define('Sage/Utility/nls/ar/Utility',{});
},
'Sage/Utility/nls/ar-qa/Utility':function(){
define('Sage/Utility/nls/ar-qa/Utility',{});
},
'Sage/QuickForms/Design/nls/ar/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/ControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-qa/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-qa/ControlDesigner',{});
},
'Sage/UI/Controls/nls/ar/Address':function(){
define('Sage/UI/Controls/nls/ar/Address',{});
},
'Sage/UI/Controls/nls/ar-qa/Address':function(){
define('Sage/UI/Controls/nls/ar-qa/Address',{});
},
'Sage/MainView/JobMgr/nls/ar/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/ar/JobManagerGroupContextService',{});
},
'Sage/MainView/JobMgr/nls/ar-qa/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/ar-qa/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/ar/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/BaseListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-qa/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-qa/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ar/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/OwnerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-qa/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-qa/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/ar/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/JobManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-qa/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-qa/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/ar-qa/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ar-qa/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/ar/UserType':function(){
define('Sage/UI/nls/ar/UserType',{});
},
'Sage/UI/nls/ar-qa/UserType':function(){
define('Sage/UI/nls/ar-qa/UserType',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar/HistoryDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar/HistoryDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar-qa/HistoryDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar-qa/HistoryDetailSummary',{});
},
'Sage/QuickForms/Design/nls/ar/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/FormDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-qa/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-qa/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityCalendar',{});
},
'Sage/MainView/ActivityMgr/nls/ar-qa/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/ar-qa/ActivityCalendar',{});
},
'Sage/Utility/nls/ar/Jobs':function(){
define('Sage/Utility/nls/ar/Jobs',{});
},
'Sage/Utility/nls/ar-qa/Jobs':function(){
define('Sage/Utility/nls/ar-qa/Jobs',{});
},
'Sage/UI/Controls/nls/ar/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/ar/_DialogHelpIconMixin',{});
},
'Sage/UI/Controls/nls/ar-qa/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/ar-qa/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/PickListAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-qa/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-qa/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/ar/ActivityList':function(){
define('Sage/UI/nls/ar/ActivityList',{});
},
'Sage/UI/nls/ar-qa/ActivityList':function(){
define('Sage/UI/nls/ar-qa/ActivityList',{});
},
'Sage/UI/Alarms/nls/ar/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/ar/JobNotificationPopup',{});
},
'Sage/UI/Alarms/nls/ar-qa/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/ar-qa/JobNotificationPopup',{});
},
'Sage/MainView/JobMgr/templates/nls/ar/ExecutionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar/ExecutionsListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/ar-qa/ExecutionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar-qa/ExecutionsListSummary',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar/LeadLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar-qa/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar-qa/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/ar/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar/SchedulesListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/ar-qa/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar-qa/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/GenericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-qa/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-qa/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/ar/CalendarUsersListPane':function(){
define('Sage/UI/nls/ar/CalendarUsersListPane',{});
},
'Sage/UI/nls/ar-qa/CalendarUsersListPane':function(){
define('Sage/UI/nls/ar-qa/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-qa/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-qa/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/ColumnBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-qa/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-qa/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/templates/nls/ar/ExecutionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar/ExecutionDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/ar-qa/ExecutionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar-qa/ExecutionDetailSummary',{});
},
'Sage/MainView/ReportMgr/nls/ar/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/ar/ReportManagerGroupContextService',{});
},
'Sage/MainView/ReportMgr/nls/ar-qa/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/ar-qa/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/ar/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/ar/MatchingOptionsConfig',{});
},
'Sage/MainView/IntegrationContract/nls/ar-qa/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/ar-qa/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/FormBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-qa/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-qa/FormBasicPropertyEditor',{});
},
'Sage/UI/Alarms/nls/ar/AlarmButton':function(){
define('Sage/UI/Alarms/nls/ar/AlarmButton',{});
},
'Sage/UI/Alarms/nls/ar-qa/AlarmButton':function(){
define('Sage/UI/Alarms/nls/ar-qa/AlarmButton',{});
},
'Sage/MainView/ActivityMgr/nls/ar/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/ar/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/MainView/ActivityMgr/nls/ar-qa/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/ar-qa/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/ar/Attachment':function(){
define('Sage/Utility/File/nls/ar/Attachment',{});
},
'Sage/Utility/File/nls/ar-qa/Attachment':function(){
define('Sage/Utility/File/nls/ar-qa/Attachment',{});
},
'Sage/QuickForms/Design/nls/ar/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-qa/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-qa/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/ar/PropertyEditorContainer',{});
},
'Sage/QuickForms/Design/nls/ar-qa/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/ar-qa/PropertyEditorContainer',{});
},
'Sage/Services/nls/ar/ReportingService':function(){
define('Sage/Services/nls/ar/ReportingService',{});
},
'Sage/Services/nls/ar-qa/ReportingService':function(){
define('Sage/Services/nls/ar-qa/ReportingService',{});
},
'Sage/MailMerge/nls/ar/Helper':function(){
define('Sage/MailMerge/nls/ar/Helper',{});
},
'Sage/MailMerge/nls/ar-qa/Helper':function(){
define('Sage/MailMerge/nls/ar-qa/Helper',{});
},
'Sage/UI/Dashboard/nls/ar/Dashboard':function(){
define('Sage/UI/Dashboard/nls/ar/Dashboard',{});
},
'Sage/UI/Dashboard/nls/ar-qa/Dashboard':function(){
define('Sage/UI/Dashboard/nls/ar-qa/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-qa/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-qa/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/ar/PickList':function(){
define('Sage/UI/Controls/nls/ar/PickList',{});
},
'Sage/UI/Controls/nls/ar-qa/PickList':function(){
define('Sage/UI/Controls/nls/ar-qa/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/ar/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ar/HistoryEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/ar-qa/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ar-qa/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/ar/Email':function(){
define('Sage/Utility/nls/ar/Email',{});
},
'Sage/Utility/nls/ar-qa/Email':function(){
define('Sage/Utility/nls/ar-qa/Email',{});
},
'Sage/TaskPane/nls/ar/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/SecurityManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-qa/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-qa/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/ar/TimeZoneItem':function(){
define('Sage/UI/nls/ar/TimeZoneItem',{});
},
'Sage/UI/nls/ar-qa/TimeZoneItem':function(){
define('Sage/UI/nls/ar-qa/TimeZoneItem',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar/HistoryListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar/HistoryListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar-qa/HistoryListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar-qa/HistoryListSummary',{});
},
'Sage/UI/Columns/nls/ar/SlxEdit':function(){
define('Sage/UI/Columns/nls/ar/SlxEdit',{});
},
'Sage/UI/Columns/nls/ar-qa/SlxEdit':function(){
define('Sage/UI/Columns/nls/ar-qa/SlxEdit',{});
},
'Sage/Reporting/nls/ar/Enumerations':function(){
define('Sage/Reporting/nls/ar/Enumerations',{});
},
'Sage/Reporting/nls/ar-qa/Enumerations':function(){
define('Sage/Reporting/nls/ar-qa/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-qa/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-qa/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportConditionsDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-qa/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-qa/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ar/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ar/ActivityListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ar-qa/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ar-qa/ActivityListPanelConfig',{});
},
'Sage/UI/nls/ar/JobSchedulingWidget':function(){
define('Sage/UI/nls/ar/JobSchedulingWidget',{});
},
'Sage/UI/nls/ar-qa/JobSchedulingWidget':function(){
define('Sage/UI/nls/ar-qa/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/ar/LogOffButton':function(){
define('Sage/UI/Controls/nls/ar/LogOffButton',{});
},
'Sage/UI/Controls/nls/ar-qa/LogOffButton':function(){
define('Sage/UI/Controls/nls/ar-qa/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/TextBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-qa/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-qa/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/EditEventEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-qa/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-qa/EditEventEditor',{});
},
'Sage/MailMerge/nls/ar/Loader':function(){
define('Sage/MailMerge/nls/ar/Loader',{});
},
'Sage/MailMerge/nls/ar-qa/Loader':function(){
define('Sage/MailMerge/nls/ar-qa/Loader',{});
},
'Sage/UI/Controls/nls/ar/DateTimePicker':function(){
define('Sage/UI/Controls/nls/ar/DateTimePicker',{});
},
'Sage/UI/Controls/nls/ar-qa/DateTimePicker':function(){
define('Sage/UI/Controls/nls/ar-qa/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/ar/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/ar/ReportManagerActions',{});
},
'Sage/MainView/ReportMgr/nls/ar-qa/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/ar-qa/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/ar/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/ar/AlarmPopup',{});
},
'Sage/UI/Alarms/nls/ar-qa/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/ar-qa/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/ar/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/ar/ContactUserAssociationEditor',{});
},
'Sage/MainView/Contact/nls/ar-qa/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/ar-qa/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-qa/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-qa/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ar/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar/BaseListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/ar-qa/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar-qa/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ar/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-qa/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-qa/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/EmailControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-qa/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-qa/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/ar/Lookup':function(){
define('Sage/UI/Controls/nls/ar/Lookup',{});
},
'Sage/UI/Controls/nls/ar-qa/Lookup':function(){
define('Sage/UI/Controls/nls/ar-qa/Lookup',{});
},
'Sage/Utility/File/nls/ar/DescriptionsForm':function(){
define('Sage/Utility/File/nls/ar/DescriptionsForm',{});
},
'Sage/Utility/File/nls/ar-qa/DescriptionsForm':function(){
define('Sage/Utility/File/nls/ar-qa/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/NumericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-qa/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-qa/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/ar/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/CommonTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-qa/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-qa/CommonTasksTasklet',{});
},
'Sage/Utility/nls/ar/Dashboard':function(){
define('Sage/Utility/nls/ar/Dashboard',{});
},
'Sage/Utility/nls/ar-qa/Dashboard':function(){
define('Sage/Utility/nls/ar-qa/Dashboard',{});
}}});
define("Sage/nls/Sage_ar-qa", [], 1);
