require({cache:{
'Sage/Utility/File/nls/ar/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/ar/FallbackFilePicker',{});
},
'Sage/Utility/File/nls/ar-kw/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/ar-kw/FallbackFilePicker',{});
},
'Sage/UI/nls/ar/Boolean':function(){
define('Sage/UI/nls/ar/Boolean',{});
},
'Sage/UI/nls/ar-kw/Boolean':function(){
define('Sage/UI/nls/ar-kw/Boolean',{});
},
'Sage/Services/nls/ar/ActivityService':function(){
define('Sage/Services/nls/ar/ActivityService',{});
},
'Sage/Services/nls/ar-kw/ActivityService':function(){
define('Sage/Services/nls/ar-kw/ActivityService',{});
},
'Sage/UI/Controls/nls/ar/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/ar/CopyToClipboard',{});
},
'Sage/UI/Controls/nls/ar-kw/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/ar-kw/CopyToClipboard',{});
},
'Sage/Utility/nls/ar/Activity':function(){
define('Sage/Utility/nls/ar/Activity',{});
},
'Sage/Utility/nls/ar-kw/Activity':function(){
define('Sage/Utility/nls/ar-kw/Activity',{});
},
'Sage/QuickForms/Design/nls/ar/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/ar/DesignPanel',{});
},
'Sage/QuickForms/Design/nls/ar-kw/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/ar-kw/DesignPanel',{});
},
'Sage/UI/nls/ar/TimelessActivitiesPane':function(){
define('Sage/UI/nls/ar/TimelessActivitiesPane',{});
},
'Sage/UI/nls/ar-kw/TimelessActivitiesPane':function(){
define('Sage/UI/nls/ar-kw/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-kw/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-kw/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/ar/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/ar/ContactUserAssociationEditor',{});
},
'Sage/TaskPane/User/nls/ar-kw/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/ar-kw/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/ar/ActivityManager':function(){
define('Sage/MainView/nls/ar/ActivityManager',{});
},
'Sage/MainView/nls/ar-kw/ActivityManager':function(){
define('Sage/MainView/nls/ar-kw/ActivityManager',{});
},
'Sage/Services/nls/ar/JobService':function(){
define('Sage/Services/nls/ar/JobService',{});
},
'Sage/Services/nls/ar-kw/JobService':function(){
define('Sage/Services/nls/ar-kw/JobService',{});
},
'Sage/QuickForms/Design/nls/ar/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-kw/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-kw/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/_PropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-kw/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-kw/_PropertyEditor',{});
},
'Sage/Services/nls/ar/ActivityActionProcessor':function(){
define('Sage/Services/nls/ar/ActivityActionProcessor',{});
},
'Sage/Services/nls/ar-kw/ActivityActionProcessor':function(){
define('Sage/Services/nls/ar-kw/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/TextBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-kw/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-kw/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-kw/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-kw/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar/UserActivityDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar/UserActivityDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar-kw/UserActivityDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar-kw/UserActivityDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar/ConfirmationDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar/ConfirmationDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar-kw/ConfirmationDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar-kw/ConfirmationDetailSummary',{});
},
'Sage/Utility/File/nls/ar/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/ar/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/ar-kw/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/ar-kw/DefaultDropHandler',{});
},
'Sage/UI/nls/ar/TransferBoxWidget':function(){
define('Sage/UI/nls/ar/TransferBoxWidget',{});
},
'Sage/UI/nls/ar-kw/TransferBoxWidget':function(){
define('Sage/UI/nls/ar-kw/TransferBoxWidget',{});
},
'Sage/Utility/File/nls/ar/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/ar/AttachmentPropertiesEditForm',{});
},
'Sage/Utility/File/nls/ar-kw/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/ar-kw/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/ar/AlarmPane':function(){
define('Sage/UI/Alarms/nls/ar/AlarmPane',{});
},
'Sage/UI/Alarms/nls/ar-kw/AlarmPane':function(){
define('Sage/UI/Alarms/nls/ar-kw/AlarmPane',{});
},
'Sage/TaskPane/nls/ar/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/ar/LiteratureManagementTasks',{});
},
'Sage/TaskPane/nls/ar-kw/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/ar-kw/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/ar/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/ar/DashboardWidget',{});
},
'Sage/UI/Dashboard/nls/ar-kw/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/ar-kw/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/NumericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-kw/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-kw/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ar/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar/CustomerPaymentsRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/ar-kw/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar-kw/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/ar/FilterPanel':function(){
define('Sage/UI/Filters/nls/ar/FilterPanel',{});
},
'Sage/UI/Filters/nls/ar-kw/FilterPanel':function(){
define('Sage/UI/Filters/nls/ar-kw/FilterPanel',{});
},
'Sage/TaskPane/nls/ar/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/ar/_BaseTaskPaneTasklet',{});
},
'Sage/TaskPane/nls/ar-kw/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/ar-kw/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/ar/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/ar/ReportManagerFormatter',{});
},
'Sage/MainView/ReportMgr/nls/ar-kw/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/ar-kw/ReportManagerFormatter',{});
},
'Sage/UI/nls/ar/OwnerType':function(){
define('Sage/UI/nls/ar/OwnerType',{});
},
'Sage/UI/nls/ar-kw/OwnerType':function(){
define('Sage/UI/nls/ar-kw/OwnerType',{});
},
'Sage/MainView/JobMgr/templates/nls/ar/JobDefinitionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar/JobDefinitionsListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/ar-kw/JobDefinitionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar-kw/JobDefinitionsListSummary',{});
},
'Sage/TaskPane/nls/ar/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/LeadTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-kw/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-kw/LeadTasksTasklet',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar/ReportDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar/ReportDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar-kw/ReportDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar-kw/ReportDetailSummary',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/_ParameterEditorBase':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/_ParameterEditorBase',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-kw/_ParameterEditorBase':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-kw/_ParameterEditorBase',{});
},
'Sage/MailMerge/nls/ar/Service':function(){
define('Sage/MailMerge/nls/ar/Service',{});
},
'Sage/MailMerge/nls/ar-kw/Service':function(){
define('Sage/MailMerge/nls/ar-kw/Service',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar/ConfirmationListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar/ConfirmationListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar-kw/ConfirmationListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar-kw/ConfirmationListSummary',{});
},
'Sage/MainView/ActivityMgr/nls/ar/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/ar/SnoozeOptions',{});
},
'Sage/MainView/ActivityMgr/nls/ar-kw/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/ar-kw/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-kw/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-kw/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-kw/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-kw/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ar/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar/InvoiceRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/ar-kw/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar-kw/InvoiceRTDV',{});
},
'Sage/UI/nls/ar/SDataLookup':function(){
define('Sage/UI/nls/ar/SDataLookup',{});
},
'Sage/UI/nls/ar-kw/SDataLookup':function(){
define('Sage/UI/nls/ar-kw/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/ar/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/RowDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-kw/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-kw/RowDesigner',{});
},
'Sage/Groups/nls/ar/GroupLookup':function(){
define('Sage/Groups/nls/ar/GroupLookup',{});
},
'Sage/Groups/nls/ar-kw/GroupLookup':function(){
define('Sage/Groups/nls/ar-kw/GroupLookup',{});
},
'Sage/TaskPane/nls/ar/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/OpportunityTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-kw/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-kw/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/ar/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/ar/CheckBoxFilter',{});
},
'Sage/UI/Filters/nls/ar-kw/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/ar-kw/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/ar/LibraryDocument':function(){
define('Sage/Utility/File/nls/ar/LibraryDocument',{});
},
'Sage/Utility/File/nls/ar-kw/LibraryDocument':function(){
define('Sage/Utility/File/nls/ar-kw/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar/SpeedSearchLookup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar-kw/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar-kw/SpeedSearchLookup',{});
},
'Sage/UI/nls/ar/ConditionManager':function(){
define('Sage/UI/nls/ar/ConditionManager',{});
},
'Sage/UI/nls/ar-kw/ConditionManager':function(){
define('Sage/UI/nls/ar-kw/ConditionManager',{});
},
'Sage/MainView/JobMgr/templates/nls/ar/SchedulesListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar/SchedulesListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/ar-kw/SchedulesListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar-kw/SchedulesListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar/UserActivityListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar/UserActivityListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar-kw/UserActivityListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar-kw/UserActivityListSummary',{});
},
'Sage/UI/Dashboard/nls/ar/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/ar/WidgetDefinition',{});
},
'Sage/UI/Dashboard/nls/ar-kw/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/ar-kw/WidgetDefinition',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar/AllOpenListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar/AllOpenListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar-kw/AllOpenListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar-kw/AllOpenListSummary',{});
},
'Sage/UI/nls/ar/SearchConditionWidget':function(){
define('Sage/UI/nls/ar/SearchConditionWidget',{});
},
'Sage/UI/nls/ar-kw/SearchConditionWidget':function(){
define('Sage/UI/nls/ar-kw/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-kw/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-kw/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ar/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/ar/JobManagerActions',{});
},
'Sage/MainView/JobMgr/nls/ar-kw/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/ar-kw/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar/ContactLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar-kw/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar-kw/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/ar/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/ar/DataSourcePanel',{});
},
'Sage/QuickForms/Design/nls/ar-kw/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/ar-kw/DataSourcePanel',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar/SchedulesListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar/SchedulesListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar-kw/SchedulesListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar-kw/SchedulesListSummary',{});
},
'Sage/Library/nls/ar/Manager':function(){
define('Sage/Library/nls/ar/Manager',{});
},
'Sage/Library/nls/ar-kw/Manager':function(){
define('Sage/Library/nls/ar-kw/Manager',{});
},
'Sage/UI/nls/ar/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/ar/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/nls/ar-kw/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/ar-kw/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/ar/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/ar/NonVisibleControlContainer',{});
},
'Sage/QuickForms/Design/nls/ar-kw/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/ar-kw/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/ar/Name':function(){
define('Sage/UI/Controls/nls/ar/Name',{});
},
'Sage/UI/Controls/nls/ar-kw/Name':function(){
define('Sage/UI/Controls/nls/ar-kw/Name',{});
},
'Sage/MainView/JobMgr/nls/ar/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar/ExecutionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/ar-kw/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar-kw/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ar/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/PhoneControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-kw/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-kw/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/ar/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/ar/UpdateLeads',{});
},
'Sage/MainView/Lead/nls/ar-kw/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/ar-kw/UpdateLeads',{});
},
'Sage/Library/nls/ar/FileHandler':function(){
define('Sage/Library/nls/ar/FileHandler',{});
},
'Sage/Library/nls/ar-kw/FileHandler':function(){
define('Sage/Library/nls/ar-kw/FileHandler',{});
},
'Sage/UI/nls/ar/ListPanel':function(){
define('Sage/UI/nls/ar/ListPanel',{});
},
'Sage/UI/nls/ar-kw/ListPanel':function(){
define('Sage/UI/nls/ar-kw/ListPanel',{});
},
'Sage/Utility/nls/ar/Sql':function(){
define('Sage/Utility/nls/ar/Sql',{});
},
'Sage/Utility/nls/ar-kw/Sql':function(){
define('Sage/Utility/nls/ar-kw/Sql',{});
},
'Sage/UI/Filters/nls/ar/EditFilters':function(){
define('Sage/UI/Filters/nls/ar/EditFilters',{});
},
'Sage/UI/Filters/nls/ar-kw/EditFilters':function(){
define('Sage/UI/Filters/nls/ar-kw/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/FormUsagesPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-kw/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-kw/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/ar/DurationSelect':function(){
define('Sage/UI/Controls/nls/ar/DurationSelect',{});
},
'Sage/UI/Controls/nls/ar-kw/DurationSelect':function(){
define('Sage/UI/Controls/nls/ar-kw/DurationSelect',{});
},
'Sage/UI/Alarms/nls/ar/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/ar/AlarmCountDown',{});
},
'Sage/UI/Alarms/nls/ar-kw/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/ar-kw/AlarmCountDown',{});
},
'Sage/UI/nls/ar/AttachmentList':function(){
define('Sage/UI/nls/ar/AttachmentList',{});
},
'Sage/UI/nls/ar-kw/AttachmentList':function(){
define('Sage/UI/nls/ar-kw/AttachmentList',{});
},
'Sage/MailMerge/nls/ar/Lookup':function(){
define('Sage/MailMerge/nls/ar/Lookup',{});
},
'Sage/MailMerge/nls/ar-kw/Lookup':function(){
define('Sage/MailMerge/nls/ar-kw/Lookup',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-kw/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-kw/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ar/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/ar/RunJobDialog',{});
},
'Sage/MainView/JobMgr/nls/ar-kw/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/ar-kw/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/ar/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-kw/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-kw/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-kw/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-kw/EditableGridControlDesigner',{});
},
'Sage/MainView/Options/nls/ar/OptionsDialog':function(){
define('Sage/MainView/Options/nls/ar/OptionsDialog',{});
},
'Sage/MainView/Options/nls/ar-kw/OptionsDialog':function(){
define('Sage/MainView/Options/nls/ar-kw/OptionsDialog',{});
},
'Sage/QuickForms/Design/nls/ar/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/HiddenControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-kw/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-kw/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/ar/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/ar/DashboardWidgetCell',{});
},
'Sage/UI/Dashboard/nls/ar-kw/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/ar-kw/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/UserBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-kw/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-kw/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/ar/Dialogs':function(){
define('Sage/UI/nls/ar/Dialogs',{});
},
'Sage/UI/nls/ar-kw/Dialogs':function(){
define('Sage/UI/nls/ar-kw/Dialogs',{});
},
'Sage/MainView/IntegrationContract/nls/ar/SyncResultsHistory':function(){
define('Sage/MainView/IntegrationContract/nls/ar/SyncResultsHistory',{});
},
'Sage/MainView/IntegrationContract/nls/ar-kw/SyncResultsHistory':function(){
define('Sage/MainView/IntegrationContract/nls/ar-kw/SyncResultsHistory',{});
},
'Sage/TaskPane/nls/ar/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/ar/SecuredActionTasklet',{});
},
'Sage/TaskPane/nls/ar-kw/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/ar-kw/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/ar/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/ar/DashboardTabController',{});
},
'Sage/UI/Dashboard/nls/ar-kw/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/ar-kw/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/ar/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar/SalesOrderRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/ar-kw/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar-kw/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/ar/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/UserControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-kw/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-kw/UserControlDesigner',{});
},
'Sage/Groups/nls/ar/GroupNavigator':function(){
define('Sage/Groups/nls/ar/GroupNavigator',{});
},
'Sage/Groups/nls/ar-kw/GroupNavigator':function(){
define('Sage/Groups/nls/ar-kw/GroupNavigator',{});
},
'Sage/Utility/File/nls/ar/AddURLAttachment':function(){
define('Sage/Utility/File/nls/ar/AddURLAttachment',{});
},
'Sage/Utility/File/nls/ar-kw/AddURLAttachment':function(){
define('Sage/Utility/File/nls/ar-kw/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/ar/EditFilterItems':function(){
define('Sage/UI/Filters/nls/ar/EditFilterItems',{});
},
'Sage/UI/Filters/nls/ar-kw/EditFilterItems':function(){
define('Sage/UI/Filters/nls/ar-kw/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportsFormatter',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-kw/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-kw/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/ar/DragDropWatcher':function(){
define('Sage/Utility/File/nls/ar/DragDropWatcher',{});
},
'Sage/Utility/File/nls/ar-kw/DragDropWatcher':function(){
define('Sage/Utility/File/nls/ar-kw/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/ar/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/ar/DesignSurface',{});
},
'Sage/QuickForms/Design/nls/ar-kw/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/ar-kw/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-kw/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-kw/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/FormAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-kw/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-kw/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/EventListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-kw/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-kw/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ar/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ar/AllOpenListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ar-kw/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ar-kw/AllOpenListPanelConfig',{});
},
'Sage/MainView/nls/ar/FormManager':function(){
define('Sage/MainView/nls/ar/FormManager',{});
},
'Sage/MainView/nls/ar-kw/FormManager':function(){
define('Sage/MainView/nls/ar-kw/FormManager',{});
},
'Sage/UI/nls/ar/ActivityScheduler':function(){
define('Sage/UI/nls/ar/ActivityScheduler',{});
},
'Sage/UI/nls/ar-kw/ActivityScheduler':function(){
define('Sage/UI/nls/ar-kw/ActivityScheduler',{});
},
'Sage/MainView/nls/ar/SecurityManager':function(){
define('Sage/MainView/nls/ar/SecurityManager',{});
},
'Sage/MainView/nls/ar-kw/SecurityManager':function(){
define('Sage/MainView/nls/ar-kw/SecurityManager',{});
},
'Sage/TaskPane/nls/ar/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/ar/ActivityTaskConfigurationProvider',{});
},
'Sage/TaskPane/nls/ar-kw/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/ar-kw/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/ar/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/ar/EntityInfoToolTip',{});
},
'Sage/UI/Controls/nls/ar-kw/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/ar-kw/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/ar-kw/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/ar-kw/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar/AllOpenDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar/AllOpenDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar-kw/AllOpenDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar-kw/AllOpenDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar/ReportsListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar/ReportsListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar-kw/ReportsListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar-kw/ReportsListSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/ar/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/ar/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/Common/nls/ar-kw/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/ar-kw/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar/ScheduleDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar/ScheduleDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar-kw/ScheduleDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar-kw/ScheduleDetailSummary',{});
},
'Sage/MainView/Opportunity/nls/ar/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/ar/UpdateOpportunities',{});
},
'Sage/MainView/Opportunity/nls/ar-kw/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/ar-kw/UpdateOpportunities',{});
},
'Sage/UI/nls/ar/EditCalendarUsers':function(){
define('Sage/UI/nls/ar/EditCalendarUsers',{});
},
'Sage/UI/nls/ar-kw/EditCalendarUsers':function(){
define('Sage/UI/nls/ar-kw/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportParametersDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-kw/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-kw/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/ar/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/DateTimePickerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-kw/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-kw/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/ar/HelpMenu':function(){
define('Sage/UI/Controls/nls/ar/HelpMenu',{});
},
'Sage/UI/Controls/nls/ar-kw/HelpMenu':function(){
define('Sage/UI/Controls/nls/ar-kw/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/LayoutPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-kw/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-kw/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/ar/UserTasklet':function(){
define('Sage/TaskPane/nls/ar/UserTasklet',{});
},
'Sage/TaskPane/nls/ar-kw/UserTasklet':function(){
define('Sage/TaskPane/nls/ar-kw/UserTasklet',{});
},
'Sage/UI/Alarms/nls/ar/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/ar/ActivityAlarm',{});
},
'Sage/UI/Alarms/nls/ar-kw/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/ar-kw/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/ar/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/ar/OpportunityStatistics',{});
},
'Sage/MainView/Opportunity/nls/ar-kw/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/ar-kw/OpportunityStatistics',{});
},
'Sage/TaskPane/nls/ar/GroupListTasklet':function(){
define('Sage/TaskPane/nls/ar/GroupListTasklet',{});
},
'Sage/TaskPane/nls/ar-kw/GroupListTasklet':function(){
define('Sage/TaskPane/nls/ar-kw/GroupListTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportConditionEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-kw/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-kw/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ar/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/ar/AdvancedSearchOptions',{});
},
'Sage/MainView/IntegrationContract/nls/ar-kw/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/ar-kw/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/ar/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/ColumnDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-kw/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-kw/ColumnDesigner',{});
},
'Sage/MainView/JobMgr/templates/nls/ar/JobDefinitionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar/JobDefinitionDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/ar-kw/JobDefinitionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar-kw/JobDefinitionDetailSummary',{});
},
'Sage/UI/nls/ar/SearchMenuItem':function(){
define('Sage/UI/nls/ar/SearchMenuItem',{});
},
'Sage/UI/nls/ar-kw/SearchMenuItem':function(){
define('Sage/UI/nls/ar-kw/SearchMenuItem',{});
},
'Sage/Library/nls/ar/DocumentProperties':function(){
define('Sage/Library/nls/ar/DocumentProperties',{});
},
'Sage/Library/nls/ar-kw/DocumentProperties':function(){
define('Sage/Library/nls/ar-kw/DocumentProperties',{});
},
'Sage/UI/nls/ar/NotesHistoryList':function(){
define('Sage/UI/nls/ar/NotesHistoryList',{});
},
'Sage/UI/nls/ar-kw/NotesHistoryList':function(){
define('Sage/UI/nls/ar-kw/NotesHistoryList',{});
},
'Sage/Utility/nls/ar/File':function(){
define('Sage/Utility/nls/ar/File',{});
},
'Sage/Utility/nls/ar-kw/File':function(){
define('Sage/Utility/nls/ar-kw/File',{});
},
'Sage/MainView/ReportMgr/nls/ar/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/ar-kw/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar-kw/HistoryListPanelConfig',{});
},
'Sage/MainView/JobMgr/templates/nls/ar/ScheduleDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar/ScheduleDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/ar-kw/ScheduleDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar-kw/ScheduleDetailSummary',{});
},
'Sage/QuickForms/Design/nls/ar/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/UrlControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-kw/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-kw/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/ar/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/ContactTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-kw/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-kw/ContactTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar/EventSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar/EventSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar-kw/EventSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar-kw/EventSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/ar/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/ar/_WizardDialogBase',{});
},
'Sage/MainView/ReportMgr/Common/nls/ar-kw/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/ar-kw/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/ar/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar/SchedulesListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/ar-kw/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar-kw/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/ar/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/ar/GoogleDocPicker',{});
},
'Sage/Utility/File/nls/ar-kw/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/ar-kw/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/ar/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/ComboBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-kw/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-kw/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/ar/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-kw/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-kw/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/HistoryEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-kw/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-kw/HistoryEditor',{});
},
'Sage/Groups/nls/ar/GroupManager':function(){
define('Sage/Groups/nls/ar/GroupManager',{});
},
'Sage/Groups/nls/ar-kw/GroupManager':function(){
define('Sage/Groups/nls/ar-kw/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-kw/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-kw/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/ComboBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-kw/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-kw/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ar/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar/ReportsListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/ar-kw/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar-kw/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/ar/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/ar/JobNotificationButton',{});
},
'Sage/UI/Alarms/nls/ar-kw/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/ar-kw/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportWizardController',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-kw/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-kw/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/ar/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/ar-kw/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar-kw/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/RecurringEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-kw/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-kw/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportsUtility',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-kw/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-kw/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-kw/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-kw/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ar/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/ar-kw/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar-kw/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ar/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-kw/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-kw/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-kw/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-kw/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-kw/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-kw/PickListControlDesigner',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar/LitRequestSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar/LitRequestSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar-kw/LitRequestSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar-kw/LitRequestSummary',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-kw/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-kw/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/ar/FolderHandler':function(){
define('Sage/Library/nls/ar/FolderHandler',{});
},
'Sage/Library/nls/ar-kw/FolderHandler':function(){
define('Sage/Library/nls/ar-kw/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-kw/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-kw/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/ar/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/ar/ContactSearchForDuplicates',{});
},
'Sage/MainView/Contact/nls/ar-kw/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/ar-kw/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/DateTimePickerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-kw/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-kw/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/ar/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/AccountingTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-kw/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-kw/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-kw/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-kw/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/CurrencyBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-kw/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-kw/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/ar/EditableGrid':function(){
define('Sage/UI/nls/ar/EditableGrid',{});
},
'Sage/UI/nls/ar-kw/EditableGrid':function(){
define('Sage/UI/nls/ar-kw/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/ar/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar/SalesQuoteRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/ar-kw/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar-kw/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/ar/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/ar/SecurityProfile',{});
},
'Sage/MainView/SecurityMgr/nls/ar-kw/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/ar-kw/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/ar/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/ar/ReportWizardController',{});
},
'Sage/MainView/ReportMgr/nls/ar-kw/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/ar-kw/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/UserAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-kw/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-kw/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ar/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/ar/ReportManagerUtility',{});
},
'Sage/MainView/ReportMgr/nls/ar-kw/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/ar-kw/ReportManagerUtility',{});
},
'Sage/UI/nls/ar/SpeedSearch':function(){
define('Sage/UI/nls/ar/SpeedSearch',{});
},
'Sage/UI/nls/ar-kw/SpeedSearch':function(){
define('Sage/UI/nls/ar-kw/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/CurrencyAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-kw/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-kw/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/ar/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/ReportManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-kw/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-kw/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/ar/SLXPreviewGrid':function(){
define('Sage/UI/nls/ar/SLXPreviewGrid',{});
},
'Sage/UI/nls/ar-kw/SLXPreviewGrid':function(){
define('Sage/UI/nls/ar-kw/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/ar/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/ar/UnconfirmedPane',{});
},
'Sage/UI/Alarms/nls/ar-kw/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/ar-kw/UnconfirmedPane',{});
},
'Sage/Utility/nls/ar/Utility':function(){
define('Sage/Utility/nls/ar/Utility',{});
},
'Sage/Utility/nls/ar-kw/Utility':function(){
define('Sage/Utility/nls/ar-kw/Utility',{});
},
'Sage/QuickForms/Design/nls/ar/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/ControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-kw/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-kw/ControlDesigner',{});
},
'Sage/UI/Controls/nls/ar/Address':function(){
define('Sage/UI/Controls/nls/ar/Address',{});
},
'Sage/UI/Controls/nls/ar-kw/Address':function(){
define('Sage/UI/Controls/nls/ar-kw/Address',{});
},
'Sage/MainView/JobMgr/nls/ar/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/ar/JobManagerGroupContextService',{});
},
'Sage/MainView/JobMgr/nls/ar-kw/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/ar-kw/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/ar/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/BaseListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-kw/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-kw/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ar/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/OwnerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-kw/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-kw/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/ar/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/JobManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-kw/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-kw/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/ar-kw/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ar-kw/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/ar/UserType':function(){
define('Sage/UI/nls/ar/UserType',{});
},
'Sage/UI/nls/ar-kw/UserType':function(){
define('Sage/UI/nls/ar-kw/UserType',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar/HistoryDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar/HistoryDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar-kw/HistoryDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar-kw/HistoryDetailSummary',{});
},
'Sage/QuickForms/Design/nls/ar/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/FormDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-kw/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-kw/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityCalendar',{});
},
'Sage/MainView/ActivityMgr/nls/ar-kw/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/ar-kw/ActivityCalendar',{});
},
'Sage/Utility/nls/ar/Jobs':function(){
define('Sage/Utility/nls/ar/Jobs',{});
},
'Sage/Utility/nls/ar-kw/Jobs':function(){
define('Sage/Utility/nls/ar-kw/Jobs',{});
},
'Sage/UI/Controls/nls/ar/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/ar/_DialogHelpIconMixin',{});
},
'Sage/UI/Controls/nls/ar-kw/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/ar-kw/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/PickListAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-kw/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-kw/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/ar/ActivityList':function(){
define('Sage/UI/nls/ar/ActivityList',{});
},
'Sage/UI/nls/ar-kw/ActivityList':function(){
define('Sage/UI/nls/ar-kw/ActivityList',{});
},
'Sage/UI/Alarms/nls/ar/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/ar/JobNotificationPopup',{});
},
'Sage/UI/Alarms/nls/ar-kw/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/ar-kw/JobNotificationPopup',{});
},
'Sage/MainView/JobMgr/templates/nls/ar/ExecutionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar/ExecutionsListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/ar-kw/ExecutionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar-kw/ExecutionsListSummary',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar/LeadLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar-kw/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar-kw/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/ar/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar/SchedulesListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/ar-kw/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar-kw/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/GenericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-kw/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-kw/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/ar/CalendarUsersListPane':function(){
define('Sage/UI/nls/ar/CalendarUsersListPane',{});
},
'Sage/UI/nls/ar-kw/CalendarUsersListPane':function(){
define('Sage/UI/nls/ar-kw/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-kw/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-kw/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/ColumnBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-kw/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-kw/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/templates/nls/ar/ExecutionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar/ExecutionDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/ar-kw/ExecutionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar-kw/ExecutionDetailSummary',{});
},
'Sage/MainView/ReportMgr/nls/ar/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/ar/ReportManagerGroupContextService',{});
},
'Sage/MainView/ReportMgr/nls/ar-kw/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/ar-kw/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/ar/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/ar/MatchingOptionsConfig',{});
},
'Sage/MainView/IntegrationContract/nls/ar-kw/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/ar-kw/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/FormBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-kw/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-kw/FormBasicPropertyEditor',{});
},
'Sage/UI/Alarms/nls/ar/AlarmButton':function(){
define('Sage/UI/Alarms/nls/ar/AlarmButton',{});
},
'Sage/UI/Alarms/nls/ar-kw/AlarmButton':function(){
define('Sage/UI/Alarms/nls/ar-kw/AlarmButton',{});
},
'Sage/MainView/ActivityMgr/nls/ar/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/ar/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/MainView/ActivityMgr/nls/ar-kw/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/ar-kw/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/ar/Attachment':function(){
define('Sage/Utility/File/nls/ar/Attachment',{});
},
'Sage/Utility/File/nls/ar-kw/Attachment':function(){
define('Sage/Utility/File/nls/ar-kw/Attachment',{});
},
'Sage/QuickForms/Design/nls/ar/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-kw/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-kw/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/ar/PropertyEditorContainer',{});
},
'Sage/QuickForms/Design/nls/ar-kw/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/ar-kw/PropertyEditorContainer',{});
},
'Sage/Services/nls/ar/ReportingService':function(){
define('Sage/Services/nls/ar/ReportingService',{});
},
'Sage/Services/nls/ar-kw/ReportingService':function(){
define('Sage/Services/nls/ar-kw/ReportingService',{});
},
'Sage/MailMerge/nls/ar/Helper':function(){
define('Sage/MailMerge/nls/ar/Helper',{});
},
'Sage/MailMerge/nls/ar-kw/Helper':function(){
define('Sage/MailMerge/nls/ar-kw/Helper',{});
},
'Sage/UI/Dashboard/nls/ar/Dashboard':function(){
define('Sage/UI/Dashboard/nls/ar/Dashboard',{});
},
'Sage/UI/Dashboard/nls/ar-kw/Dashboard':function(){
define('Sage/UI/Dashboard/nls/ar-kw/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-kw/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-kw/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/ar/PickList':function(){
define('Sage/UI/Controls/nls/ar/PickList',{});
},
'Sage/UI/Controls/nls/ar-kw/PickList':function(){
define('Sage/UI/Controls/nls/ar-kw/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/ar/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ar/HistoryEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/ar-kw/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ar-kw/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/ar/Email':function(){
define('Sage/Utility/nls/ar/Email',{});
},
'Sage/Utility/nls/ar-kw/Email':function(){
define('Sage/Utility/nls/ar-kw/Email',{});
},
'Sage/TaskPane/nls/ar/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/SecurityManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-kw/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-kw/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/ar/TimeZoneItem':function(){
define('Sage/UI/nls/ar/TimeZoneItem',{});
},
'Sage/UI/nls/ar-kw/TimeZoneItem':function(){
define('Sage/UI/nls/ar-kw/TimeZoneItem',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar/HistoryListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar/HistoryListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar-kw/HistoryListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar-kw/HistoryListSummary',{});
},
'Sage/UI/Columns/nls/ar/SlxEdit':function(){
define('Sage/UI/Columns/nls/ar/SlxEdit',{});
},
'Sage/UI/Columns/nls/ar-kw/SlxEdit':function(){
define('Sage/UI/Columns/nls/ar-kw/SlxEdit',{});
},
'Sage/Reporting/nls/ar/Enumerations':function(){
define('Sage/Reporting/nls/ar/Enumerations',{});
},
'Sage/Reporting/nls/ar-kw/Enumerations':function(){
define('Sage/Reporting/nls/ar-kw/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-kw/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-kw/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportConditionsDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-kw/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-kw/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ar/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ar/ActivityListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ar-kw/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ar-kw/ActivityListPanelConfig',{});
},
'Sage/UI/nls/ar/JobSchedulingWidget':function(){
define('Sage/UI/nls/ar/JobSchedulingWidget',{});
},
'Sage/UI/nls/ar-kw/JobSchedulingWidget':function(){
define('Sage/UI/nls/ar-kw/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/ar/LogOffButton':function(){
define('Sage/UI/Controls/nls/ar/LogOffButton',{});
},
'Sage/UI/Controls/nls/ar-kw/LogOffButton':function(){
define('Sage/UI/Controls/nls/ar-kw/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/TextBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-kw/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-kw/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/EditEventEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-kw/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-kw/EditEventEditor',{});
},
'Sage/MailMerge/nls/ar/Loader':function(){
define('Sage/MailMerge/nls/ar/Loader',{});
},
'Sage/MailMerge/nls/ar-kw/Loader':function(){
define('Sage/MailMerge/nls/ar-kw/Loader',{});
},
'Sage/UI/Controls/nls/ar/DateTimePicker':function(){
define('Sage/UI/Controls/nls/ar/DateTimePicker',{});
},
'Sage/UI/Controls/nls/ar-kw/DateTimePicker':function(){
define('Sage/UI/Controls/nls/ar-kw/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/ar/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/ar/ReportManagerActions',{});
},
'Sage/MainView/ReportMgr/nls/ar-kw/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/ar-kw/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/ar/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/ar/AlarmPopup',{});
},
'Sage/UI/Alarms/nls/ar-kw/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/ar-kw/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/ar/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/ar/ContactUserAssociationEditor',{});
},
'Sage/MainView/Contact/nls/ar-kw/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/ar-kw/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-kw/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-kw/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ar/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar/BaseListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/ar-kw/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar-kw/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ar/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-kw/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-kw/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/EmailControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-kw/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-kw/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/ar/Lookup':function(){
define('Sage/UI/Controls/nls/ar/Lookup',{});
},
'Sage/UI/Controls/nls/ar-kw/Lookup':function(){
define('Sage/UI/Controls/nls/ar-kw/Lookup',{});
},
'Sage/Utility/File/nls/ar/DescriptionsForm':function(){
define('Sage/Utility/File/nls/ar/DescriptionsForm',{});
},
'Sage/Utility/File/nls/ar-kw/DescriptionsForm':function(){
define('Sage/Utility/File/nls/ar-kw/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/NumericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-kw/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-kw/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/ar/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/CommonTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-kw/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-kw/CommonTasksTasklet',{});
},
'Sage/Utility/nls/ar/Dashboard':function(){
define('Sage/Utility/nls/ar/Dashboard',{});
},
'Sage/Utility/nls/ar-kw/Dashboard':function(){
define('Sage/Utility/nls/ar-kw/Dashboard',{});
}}});
define("Sage/nls/Sage_ar-kw", [], 1);
