require({cache:{
'Sage/Utility/File/nls/sb/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/sb/FallbackFilePicker',{});
},
'Sage/UI/nls/sb/Boolean':function(){
define('Sage/UI/nls/sb/Boolean',{});
},
'Sage/Services/nls/sb/ActivityService':function(){
define('Sage/Services/nls/sb/ActivityService',{});
},
'Sage/UI/Controls/nls/sb/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/sb/CopyToClipboard',{});
},
'Sage/Utility/nls/sb/Activity':function(){
define('Sage/Utility/nls/sb/Activity',{});
},
'Sage/QuickForms/Design/nls/sb/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/sb/DesignPanel',{});
},
'Sage/UI/nls/sb/TimelessActivitiesPane':function(){
define('Sage/UI/nls/sb/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/sb/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sb/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/sb/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/sb/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/sb/ActivityManager':function(){
define('Sage/MainView/nls/sb/ActivityManager',{});
},
'Sage/Services/nls/sb/JobService':function(){
define('Sage/Services/nls/sb/JobService',{});
},
'Sage/QuickForms/Design/nls/sb/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sb/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/sb/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sb/_PropertyEditor',{});
},
'Sage/Services/nls/sb/ActivityActionProcessor':function(){
define('Sage/Services/nls/sb/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/sb/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sb/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sb/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sb/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/templates/nls/sb/UserActivityDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/sb/UserActivityDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/sb/ConfirmationDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/sb/ConfirmationDetailSummary',{});
},
'Sage/Utility/File/nls/sb/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/sb/DefaultDropHandler',{});
},
'Sage/UI/nls/sb/TransferBoxWidget':function(){
define('Sage/UI/nls/sb/TransferBoxWidget',{});
},
'Sage/Utility/File/nls/sb/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/sb/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/sb/AlarmPane':function(){
define('Sage/UI/Alarms/nls/sb/AlarmPane',{});
},
'Sage/TaskPane/nls/sb/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/sb/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/sb/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/sb/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/sb/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sb/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/sb/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/sb/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/sb/FilterPanel':function(){
define('Sage/UI/Filters/nls/sb/FilterPanel',{});
},
'Sage/TaskPane/nls/sb/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/sb/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/sb/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/sb/ReportManagerFormatter',{});
},
'Sage/UI/nls/sb/OwnerType':function(){
define('Sage/UI/nls/sb/OwnerType',{});
},
'Sage/MainView/JobMgr/templates/nls/sb/JobDefinitionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/sb/JobDefinitionsListSummary',{});
},
'Sage/TaskPane/nls/sb/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/sb/LeadTasksTasklet',{});
},
'Sage/MainView/ReportMgr/templates/nls/sb/ReportDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/sb/ReportDetailSummary',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sb/_ParameterEditorBase':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sb/_ParameterEditorBase',{});
},
'Sage/MailMerge/nls/sb/Service':function(){
define('Sage/MailMerge/nls/sb/Service',{});
},
'Sage/MainView/ActivityMgr/templates/nls/sb/ConfirmationListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/sb/ConfirmationListSummary',{});
},
'Sage/MainView/ActivityMgr/nls/sb/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/sb/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/sb/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sb/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sb/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sb/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/sb/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/sb/InvoiceRTDV',{});
},
'Sage/UI/nls/sb/SDataLookup':function(){
define('Sage/UI/nls/sb/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/sb/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/sb/RowDesigner',{});
},
'Sage/Groups/nls/sb/GroupLookup':function(){
define('Sage/Groups/nls/sb/GroupLookup',{});
},
'Sage/TaskPane/nls/sb/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/sb/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/sb/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/sb/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/sb/LibraryDocument':function(){
define('Sage/Utility/File/nls/sb/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/sb/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/sb/SpeedSearchLookup',{});
},
'Sage/UI/nls/sb/ConditionManager':function(){
define('Sage/UI/nls/sb/ConditionManager',{});
},
'Sage/MainView/JobMgr/templates/nls/sb/SchedulesListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/sb/SchedulesListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/sb/UserActivityListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/sb/UserActivityListSummary',{});
},
'Sage/UI/Dashboard/nls/sb/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/sb/WidgetDefinition',{});
},
'Sage/MainView/ActivityMgr/templates/nls/sb/AllOpenListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/sb/AllOpenListSummary',{});
},
'Sage/UI/nls/sb/SearchConditionWidget':function(){
define('Sage/UI/nls/sb/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/sb/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sb/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/sb/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/sb/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/sb/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/sb/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/sb/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/sb/DataSourcePanel',{});
},
'Sage/MainView/ReportMgr/templates/nls/sb/SchedulesListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/sb/SchedulesListSummary',{});
},
'Sage/Library/nls/sb/Manager':function(){
define('Sage/Library/nls/sb/Manager',{});
},
'Sage/UI/nls/sb/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/sb/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/sb/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/sb/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/sb/Name':function(){
define('Sage/UI/Controls/nls/sb/Name',{});
},
'Sage/MainView/JobMgr/nls/sb/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/sb/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/sb/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sb/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/sb/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/sb/UpdateLeads',{});
},
'Sage/Library/nls/sb/FileHandler':function(){
define('Sage/Library/nls/sb/FileHandler',{});
},
'Sage/UI/nls/sb/ListPanel':function(){
define('Sage/UI/nls/sb/ListPanel',{});
},
'Sage/Utility/nls/sb/Sql':function(){
define('Sage/Utility/nls/sb/Sql',{});
},
'Sage/UI/Filters/nls/sb/EditFilters':function(){
define('Sage/UI/Filters/nls/sb/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/sb/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sb/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/sb/DurationSelect':function(){
define('Sage/UI/Controls/nls/sb/DurationSelect',{});
},
'Sage/UI/Alarms/nls/sb/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/sb/AlarmCountDown',{});
},
'Sage/UI/nls/sb/AttachmentList':function(){
define('Sage/UI/nls/sb/AttachmentList',{});
},
'Sage/MailMerge/nls/sb/Lookup':function(){
define('Sage/MailMerge/nls/sb/Lookup',{});
},
'Sage/QuickForms/Design/Editors/nls/sb/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sb/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/sb/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/sb/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/sb/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sb/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sb/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sb/EditableGridControlDesigner',{});
},
'Sage/MainView/Options/nls/sb/OptionsDialog':function(){
define('Sage/MainView/Options/nls/sb/OptionsDialog',{});
},
'Sage/QuickForms/Design/nls/sb/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sb/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/sb/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/sb/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/sb/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sb/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/sb/Dialogs':function(){
define('Sage/UI/nls/sb/Dialogs',{});
},
'Sage/MainView/IntegrationContract/nls/sb/SyncResultsHistory':function(){
define('Sage/MainView/IntegrationContract/nls/sb/SyncResultsHistory',{});
},
'Sage/TaskPane/nls/sb/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/sb/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/sb/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/sb/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/sb/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/sb/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/sb/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sb/UserControlDesigner',{});
},
'Sage/Groups/nls/sb/GroupNavigator':function(){
define('Sage/Groups/nls/sb/GroupNavigator',{});
},
'Sage/Utility/File/nls/sb/AddURLAttachment':function(){
define('Sage/Utility/File/nls/sb/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/sb/EditFilterItems':function(){
define('Sage/UI/Filters/nls/sb/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sb/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sb/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/sb/DragDropWatcher':function(){
define('Sage/Utility/File/nls/sb/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/sb/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/sb/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/sb/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sb/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/sb/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sb/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sb/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sb/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/sb/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/sb/AllOpenListPanelConfig',{});
},
'Sage/MainView/nls/sb/FormManager':function(){
define('Sage/MainView/nls/sb/FormManager',{});
},
'Sage/UI/nls/sb/ActivityScheduler':function(){
define('Sage/UI/nls/sb/ActivityScheduler',{});
},
'Sage/MainView/nls/sb/SecurityManager':function(){
define('Sage/MainView/nls/sb/SecurityManager',{});
},
'Sage/TaskPane/nls/sb/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/sb/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/sb/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/sb/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/sb/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/sb/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/templates/nls/sb/AllOpenDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/sb/AllOpenDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/sb/ReportsListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/sb/ReportsListSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/sb/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/sb/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/templates/nls/sb/ScheduleDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/sb/ScheduleDetailSummary',{});
},
'Sage/MainView/Opportunity/nls/sb/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/sb/UpdateOpportunities',{});
},
'Sage/UI/nls/sb/EditCalendarUsers':function(){
define('Sage/UI/nls/sb/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sb/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sb/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/sb/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sb/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/sb/HelpMenu':function(){
define('Sage/UI/Controls/nls/sb/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/sb/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sb/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/sb/UserTasklet':function(){
define('Sage/TaskPane/nls/sb/UserTasklet',{});
},
'Sage/UI/Alarms/nls/sb/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/sb/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/sb/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/sb/OpportunityStatistics',{});
},
'Sage/TaskPane/nls/sb/GroupListTasklet':function(){
define('Sage/TaskPane/nls/sb/GroupListTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sb/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sb/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/sb/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/sb/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/sb/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/sb/ColumnDesigner',{});
},
'Sage/MainView/JobMgr/templates/nls/sb/JobDefinitionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/sb/JobDefinitionDetailSummary',{});
},
'Sage/UI/nls/sb/SearchMenuItem':function(){
define('Sage/UI/nls/sb/SearchMenuItem',{});
},
'Sage/Library/nls/sb/DocumentProperties':function(){
define('Sage/Library/nls/sb/DocumentProperties',{});
},
'Sage/UI/nls/sb/NotesHistoryList':function(){
define('Sage/UI/nls/sb/NotesHistoryList',{});
},
'Sage/Utility/nls/sb/File':function(){
define('Sage/Utility/nls/sb/File',{});
},
'Sage/MainView/ReportMgr/nls/sb/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/sb/HistoryListPanelConfig',{});
},
'Sage/MainView/JobMgr/templates/nls/sb/ScheduleDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/sb/ScheduleDetailSummary',{});
},
'Sage/QuickForms/Design/nls/sb/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sb/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/sb/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/sb/ContactTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/templates/nls/sb/EventSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/sb/EventSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/sb/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/sb/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/sb/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/sb/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/sb/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/sb/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/sb/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sb/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/sb/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sb/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/sb/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sb/HistoryEditor',{});
},
'Sage/Groups/nls/sb/GroupManager':function(){
define('Sage/Groups/nls/sb/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/sb/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sb/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sb/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sb/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/sb/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/sb/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/sb/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/sb/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sb/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sb/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/sb/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/sb/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/sb/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sb/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sb/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sb/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/sb/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sb/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/sb/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/sb/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/sb/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sb/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sb/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sb/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sb/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sb/PickListControlDesigner',{});
},
'Sage/MainView/ActivityMgr/templates/nls/sb/LitRequestSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/sb/LitRequestSummary',{});
},
'Sage/QuickForms/Design/Editors/nls/sb/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sb/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/sb/FolderHandler':function(){
define('Sage/Library/nls/sb/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/sb/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sb/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/sb/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/sb/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/sb/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sb/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/sb/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/sb/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/sb/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sb/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sb/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sb/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/sb/EditableGrid':function(){
define('Sage/UI/nls/sb/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/sb/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/sb/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/sb/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/sb/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/sb/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/sb/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/sb/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sb/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/sb/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/sb/ReportManagerUtility',{});
},
'Sage/UI/nls/sb/SpeedSearch':function(){
define('Sage/UI/nls/sb/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/sb/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sb/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/sb/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/sb/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/sb/SLXPreviewGrid':function(){
define('Sage/UI/nls/sb/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/sb/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/sb/UnconfirmedPane',{});
},
'Sage/Utility/nls/sb/Utility':function(){
define('Sage/Utility/nls/sb/Utility',{});
},
'Sage/QuickForms/Design/nls/sb/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sb/ControlDesigner',{});
},
'Sage/UI/Controls/nls/sb/Address':function(){
define('Sage/UI/Controls/nls/sb/Address',{});
},
'Sage/MainView/JobMgr/nls/sb/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/sb/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/sb/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sb/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/sb/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sb/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/sb/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/sb/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/sb/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/sb/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/sb/UserType':function(){
define('Sage/UI/nls/sb/UserType',{});
},
'Sage/MainView/ReportMgr/templates/nls/sb/HistoryDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/sb/HistoryDetailSummary',{});
},
'Sage/QuickForms/Design/nls/sb/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/sb/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/sb/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/sb/ActivityCalendar',{});
},
'Sage/Utility/nls/sb/Jobs':function(){
define('Sage/Utility/nls/sb/Jobs',{});
},
'Sage/UI/Controls/nls/sb/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/sb/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/sb/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sb/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/sb/ActivityList':function(){
define('Sage/UI/nls/sb/ActivityList',{});
},
'Sage/UI/Alarms/nls/sb/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/sb/JobNotificationPopup',{});
},
'Sage/MainView/JobMgr/templates/nls/sb/ExecutionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/sb/ExecutionsListSummary',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/sb/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/sb/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/sb/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/sb/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/sb/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sb/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/sb/CalendarUsersListPane':function(){
define('Sage/UI/nls/sb/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/sb/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sb/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sb/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sb/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/templates/nls/sb/ExecutionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/sb/ExecutionDetailSummary',{});
},
'Sage/MainView/ReportMgr/nls/sb/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/sb/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/sb/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/sb/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/sb/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sb/FormBasicPropertyEditor',{});
},
'Sage/UI/Alarms/nls/sb/AlarmButton':function(){
define('Sage/UI/Alarms/nls/sb/AlarmButton',{});
},
'Sage/MainView/ActivityMgr/nls/sb/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/sb/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/sb/Attachment':function(){
define('Sage/Utility/File/nls/sb/Attachment',{});
},
'Sage/QuickForms/Design/nls/sb/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sb/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sb/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/sb/PropertyEditorContainer',{});
},
'Sage/Services/nls/sb/ReportingService':function(){
define('Sage/Services/nls/sb/ReportingService',{});
},
'Sage/MailMerge/nls/sb/Helper':function(){
define('Sage/MailMerge/nls/sb/Helper',{});
},
'Sage/UI/Dashboard/nls/sb/Dashboard':function(){
define('Sage/UI/Dashboard/nls/sb/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/sb/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sb/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/sb/PickList':function(){
define('Sage/UI/Controls/nls/sb/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/sb/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/sb/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/sb/Email':function(){
define('Sage/Utility/nls/sb/Email',{});
},
'Sage/TaskPane/nls/sb/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/sb/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/sb/TimeZoneItem':function(){
define('Sage/UI/nls/sb/TimeZoneItem',{});
},
'Sage/MainView/ReportMgr/templates/nls/sb/HistoryListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/sb/HistoryListSummary',{});
},
'Sage/UI/Columns/nls/sb/SlxEdit':function(){
define('Sage/UI/Columns/nls/sb/SlxEdit',{});
},
'Sage/Reporting/nls/sb/Enumerations':function(){
define('Sage/Reporting/nls/sb/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/sb/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sb/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sb/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sb/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/sb/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/sb/ActivityListPanelConfig',{});
},
'Sage/UI/nls/sb/JobSchedulingWidget':function(){
define('Sage/UI/nls/sb/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/sb/LogOffButton':function(){
define('Sage/UI/Controls/nls/sb/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/sb/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sb/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sb/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sb/EditEventEditor',{});
},
'Sage/MailMerge/nls/sb/Loader':function(){
define('Sage/MailMerge/nls/sb/Loader',{});
},
'Sage/UI/Controls/nls/sb/DateTimePicker':function(){
define('Sage/UI/Controls/nls/sb/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/sb/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/sb/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/sb/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/sb/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/sb/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/sb/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sb/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sb/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/sb/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/sb/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/sb/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sb/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sb/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sb/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/sb/Lookup':function(){
define('Sage/UI/Controls/nls/sb/Lookup',{});
},
'Sage/Utility/File/nls/sb/DescriptionsForm':function(){
define('Sage/Utility/File/nls/sb/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/sb/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sb/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/sb/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/sb/CommonTasksTasklet',{});
},
'Sage/Utility/nls/sb/Dashboard':function(){
define('Sage/Utility/nls/sb/Dashboard',{});
}}});
define("Sage/nls/Sage_sb", [], 1);
