require({cache:{
'Sage/Utility/File/nls/zu/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/zu/FallbackFilePicker',{});
},
'Sage/Utility/File/nls/zu-za/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/zu-za/FallbackFilePicker',{});
},
'Sage/UI/nls/zu/Boolean':function(){
define('Sage/UI/nls/zu/Boolean',{});
},
'Sage/UI/nls/zu-za/Boolean':function(){
define('Sage/UI/nls/zu-za/Boolean',{});
},
'Sage/Services/nls/zu/ActivityService':function(){
define('Sage/Services/nls/zu/ActivityService',{});
},
'Sage/Services/nls/zu-za/ActivityService':function(){
define('Sage/Services/nls/zu-za/ActivityService',{});
},
'Sage/UI/Controls/nls/zu/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/zu/CopyToClipboard',{});
},
'Sage/UI/Controls/nls/zu-za/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/zu-za/CopyToClipboard',{});
},
'Sage/Utility/nls/zu/Activity':function(){
define('Sage/Utility/nls/zu/Activity',{});
},
'Sage/Utility/nls/zu-za/Activity':function(){
define('Sage/Utility/nls/zu-za/Activity',{});
},
'Sage/QuickForms/Design/nls/zu/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/zu/DesignPanel',{});
},
'Sage/QuickForms/Design/nls/zu-za/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/zu-za/DesignPanel',{});
},
'Sage/UI/nls/zu/TimelessActivitiesPane':function(){
define('Sage/UI/nls/zu/TimelessActivitiesPane',{});
},
'Sage/UI/nls/zu-za/TimelessActivitiesPane':function(){
define('Sage/UI/nls/zu-za/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/zu/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zu/ActivityEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zu-za/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zu-za/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/zu/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/zu/ContactUserAssociationEditor',{});
},
'Sage/TaskPane/User/nls/zu-za/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/zu-za/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/zu/ActivityManager':function(){
define('Sage/MainView/nls/zu/ActivityManager',{});
},
'Sage/MainView/nls/zu-za/ActivityManager':function(){
define('Sage/MainView/nls/zu-za/ActivityManager',{});
},
'Sage/Services/nls/zu/JobService':function(){
define('Sage/Services/nls/zu/JobService',{});
},
'Sage/Services/nls/zu-za/JobService':function(){
define('Sage/Services/nls/zu-za/JobService',{});
},
'Sage/QuickForms/Design/nls/zu/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zu-za/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu-za/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/_PropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zu-za/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu-za/_PropertyEditor',{});
},
'Sage/Services/nls/zu/ActivityActionProcessor':function(){
define('Sage/Services/nls/zu/ActivityActionProcessor',{});
},
'Sage/Services/nls/zu-za/ActivityActionProcessor':function(){
define('Sage/Services/nls/zu-za/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/TextBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zu-za/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu-za/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zu/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zu/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zu-za/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zu-za/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/templates/nls/zu/UserActivityDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/zu/UserActivityDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/zu-za/UserActivityDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/zu-za/UserActivityDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/zu/ConfirmationDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/zu/ConfirmationDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/zu-za/ConfirmationDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/zu-za/ConfirmationDetailSummary',{});
},
'Sage/Utility/File/nls/zu/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/zu/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/zu-za/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/zu-za/DefaultDropHandler',{});
},
'Sage/UI/nls/zu/TransferBoxWidget':function(){
define('Sage/UI/nls/zu/TransferBoxWidget',{});
},
'Sage/UI/nls/zu-za/TransferBoxWidget':function(){
define('Sage/UI/nls/zu-za/TransferBoxWidget',{});
},
'Sage/Utility/File/nls/zu/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/zu/AttachmentPropertiesEditForm',{});
},
'Sage/Utility/File/nls/zu-za/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/zu-za/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/zu/AlarmPane':function(){
define('Sage/UI/Alarms/nls/zu/AlarmPane',{});
},
'Sage/UI/Alarms/nls/zu-za/AlarmPane':function(){
define('Sage/UI/Alarms/nls/zu-za/AlarmPane',{});
},
'Sage/TaskPane/nls/zu/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/zu/LiteratureManagementTasks',{});
},
'Sage/TaskPane/nls/zu-za/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/zu-za/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/zu/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/zu/DashboardWidget',{});
},
'Sage/UI/Dashboard/nls/zu-za/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/zu-za/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/NumericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zu-za/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu-za/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/zu/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zu/CustomerPaymentsRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/zu-za/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zu-za/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/zu/FilterPanel':function(){
define('Sage/UI/Filters/nls/zu/FilterPanel',{});
},
'Sage/UI/Filters/nls/zu-za/FilterPanel':function(){
define('Sage/UI/Filters/nls/zu-za/FilterPanel',{});
},
'Sage/TaskPane/nls/zu/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/zu/_BaseTaskPaneTasklet',{});
},
'Sage/TaskPane/nls/zu-za/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/zu-za/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/zu/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/zu/ReportManagerFormatter',{});
},
'Sage/MainView/ReportMgr/nls/zu-za/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/zu-za/ReportManagerFormatter',{});
},
'Sage/UI/nls/zu/OwnerType':function(){
define('Sage/UI/nls/zu/OwnerType',{});
},
'Sage/UI/nls/zu-za/OwnerType':function(){
define('Sage/UI/nls/zu-za/OwnerType',{});
},
'Sage/MainView/JobMgr/templates/nls/zu/JobDefinitionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/zu/JobDefinitionsListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/zu-za/JobDefinitionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/zu-za/JobDefinitionsListSummary',{});
},
'Sage/TaskPane/nls/zu/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/zu/LeadTasksTasklet',{});
},
'Sage/TaskPane/nls/zu-za/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/zu-za/LeadTasksTasklet',{});
},
'Sage/MainView/ReportMgr/templates/nls/zu/ReportDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/zu/ReportDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/zu-za/ReportDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/zu-za/ReportDetailSummary',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zu/_ParameterEditorBase':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zu/_ParameterEditorBase',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zu-za/_ParameterEditorBase':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zu-za/_ParameterEditorBase',{});
},
'Sage/MailMerge/nls/zu/Service':function(){
define('Sage/MailMerge/nls/zu/Service',{});
},
'Sage/MailMerge/nls/zu-za/Service':function(){
define('Sage/MailMerge/nls/zu-za/Service',{});
},
'Sage/MainView/ActivityMgr/templates/nls/zu/ConfirmationListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/zu/ConfirmationListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/zu-za/ConfirmationListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/zu-za/ConfirmationListSummary',{});
},
'Sage/MainView/ActivityMgr/nls/zu/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/zu/SnoozeOptions',{});
},
'Sage/MainView/ActivityMgr/nls/zu-za/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/zu-za/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zu-za/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu-za/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zu-za/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu-za/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/zu/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zu/InvoiceRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/zu-za/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zu-za/InvoiceRTDV',{});
},
'Sage/UI/nls/zu/SDataLookup':function(){
define('Sage/UI/nls/zu/SDataLookup',{});
},
'Sage/UI/nls/zu-za/SDataLookup':function(){
define('Sage/UI/nls/zu-za/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/zu/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/zu/RowDesigner',{});
},
'Sage/QuickForms/Design/nls/zu-za/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/zu-za/RowDesigner',{});
},
'Sage/Groups/nls/zu/GroupLookup':function(){
define('Sage/Groups/nls/zu/GroupLookup',{});
},
'Sage/Groups/nls/zu-za/GroupLookup':function(){
define('Sage/Groups/nls/zu-za/GroupLookup',{});
},
'Sage/TaskPane/nls/zu/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/zu/OpportunityTasksTasklet',{});
},
'Sage/TaskPane/nls/zu-za/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/zu-za/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/zu/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/zu/CheckBoxFilter',{});
},
'Sage/UI/Filters/nls/zu-za/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/zu-za/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/zu/LibraryDocument':function(){
define('Sage/Utility/File/nls/zu/LibraryDocument',{});
},
'Sage/Utility/File/nls/zu-za/LibraryDocument':function(){
define('Sage/Utility/File/nls/zu-za/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/zu/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/zu/SpeedSearchLookup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/zu-za/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/zu-za/SpeedSearchLookup',{});
},
'Sage/UI/nls/zu/ConditionManager':function(){
define('Sage/UI/nls/zu/ConditionManager',{});
},
'Sage/UI/nls/zu-za/ConditionManager':function(){
define('Sage/UI/nls/zu-za/ConditionManager',{});
},
'Sage/MainView/JobMgr/templates/nls/zu/SchedulesListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/zu/SchedulesListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/zu-za/SchedulesListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/zu-za/SchedulesListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/zu/UserActivityListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/zu/UserActivityListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/zu-za/UserActivityListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/zu-za/UserActivityListSummary',{});
},
'Sage/UI/Dashboard/nls/zu/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/zu/WidgetDefinition',{});
},
'Sage/UI/Dashboard/nls/zu-za/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/zu-za/WidgetDefinition',{});
},
'Sage/MainView/ActivityMgr/templates/nls/zu/AllOpenListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/zu/AllOpenListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/zu-za/AllOpenListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/zu-za/AllOpenListSummary',{});
},
'Sage/UI/nls/zu/SearchConditionWidget':function(){
define('Sage/UI/nls/zu/SearchConditionWidget',{});
},
'Sage/UI/nls/zu-za/SearchConditionWidget':function(){
define('Sage/UI/nls/zu-za/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zu-za/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu-za/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/zu/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/zu/JobManagerActions',{});
},
'Sage/MainView/JobMgr/nls/zu-za/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/zu-za/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/zu/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/zu/ContactLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/zu-za/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/zu-za/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/zu/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/zu/DataSourcePanel',{});
},
'Sage/QuickForms/Design/nls/zu-za/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/zu-za/DataSourcePanel',{});
},
'Sage/MainView/ReportMgr/templates/nls/zu/SchedulesListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/zu/SchedulesListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/zu-za/SchedulesListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/zu-za/SchedulesListSummary',{});
},
'Sage/Library/nls/zu/Manager':function(){
define('Sage/Library/nls/zu/Manager',{});
},
'Sage/Library/nls/zu-za/Manager':function(){
define('Sage/Library/nls/zu-za/Manager',{});
},
'Sage/UI/nls/zu/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/zu/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/nls/zu-za/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/zu-za/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/zu/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/zu/NonVisibleControlContainer',{});
},
'Sage/QuickForms/Design/nls/zu-za/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/zu-za/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/zu/Name':function(){
define('Sage/UI/Controls/nls/zu/Name',{});
},
'Sage/UI/Controls/nls/zu-za/Name':function(){
define('Sage/UI/Controls/nls/zu-za/Name',{});
},
'Sage/MainView/JobMgr/nls/zu/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/zu/ExecutionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/zu-za/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/zu-za/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/zu/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu/PhoneControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zu-za/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu-za/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/zu/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/zu/UpdateLeads',{});
},
'Sage/MainView/Lead/nls/zu-za/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/zu-za/UpdateLeads',{});
},
'Sage/Library/nls/zu/FileHandler':function(){
define('Sage/Library/nls/zu/FileHandler',{});
},
'Sage/Library/nls/zu-za/FileHandler':function(){
define('Sage/Library/nls/zu-za/FileHandler',{});
},
'Sage/UI/nls/zu/ListPanel':function(){
define('Sage/UI/nls/zu/ListPanel',{});
},
'Sage/UI/nls/zu-za/ListPanel':function(){
define('Sage/UI/nls/zu-za/ListPanel',{});
},
'Sage/Utility/nls/zu/Sql':function(){
define('Sage/Utility/nls/zu/Sql',{});
},
'Sage/Utility/nls/zu-za/Sql':function(){
define('Sage/Utility/nls/zu-za/Sql',{});
},
'Sage/UI/Filters/nls/zu/EditFilters':function(){
define('Sage/UI/Filters/nls/zu/EditFilters',{});
},
'Sage/UI/Filters/nls/zu-za/EditFilters':function(){
define('Sage/UI/Filters/nls/zu-za/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/FormUsagesPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zu-za/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu-za/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/zu/DurationSelect':function(){
define('Sage/UI/Controls/nls/zu/DurationSelect',{});
},
'Sage/UI/Controls/nls/zu-za/DurationSelect':function(){
define('Sage/UI/Controls/nls/zu-za/DurationSelect',{});
},
'Sage/UI/Alarms/nls/zu/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/zu/AlarmCountDown',{});
},
'Sage/UI/Alarms/nls/zu-za/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/zu-za/AlarmCountDown',{});
},
'Sage/UI/nls/zu/AttachmentList':function(){
define('Sage/UI/nls/zu/AttachmentList',{});
},
'Sage/UI/nls/zu-za/AttachmentList':function(){
define('Sage/UI/nls/zu-za/AttachmentList',{});
},
'Sage/MailMerge/nls/zu/Lookup':function(){
define('Sage/MailMerge/nls/zu/Lookup',{});
},
'Sage/MailMerge/nls/zu-za/Lookup':function(){
define('Sage/MailMerge/nls/zu-za/Lookup',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zu-za/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu-za/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/zu/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/zu/RunJobDialog',{});
},
'Sage/MainView/JobMgr/nls/zu-za/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/zu-za/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/zu/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zu-za/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu-za/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zu/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zu-za/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu-za/EditableGridControlDesigner',{});
},
'Sage/MainView/Options/nls/zu/OptionsDialog':function(){
define('Sage/MainView/Options/nls/zu/OptionsDialog',{});
},
'Sage/MainView/Options/nls/zu-za/OptionsDialog':function(){
define('Sage/MainView/Options/nls/zu-za/OptionsDialog',{});
},
'Sage/QuickForms/Design/nls/zu/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu/HiddenControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zu-za/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu-za/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/zu/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/zu/DashboardWidgetCell',{});
},
'Sage/UI/Dashboard/nls/zu-za/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/zu-za/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/UserBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zu-za/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu-za/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/zu/Dialogs':function(){
define('Sage/UI/nls/zu/Dialogs',{});
},
'Sage/UI/nls/zu-za/Dialogs':function(){
define('Sage/UI/nls/zu-za/Dialogs',{});
},
'Sage/MainView/IntegrationContract/nls/zu/SyncResultsHistory':function(){
define('Sage/MainView/IntegrationContract/nls/zu/SyncResultsHistory',{});
},
'Sage/MainView/IntegrationContract/nls/zu-za/SyncResultsHistory':function(){
define('Sage/MainView/IntegrationContract/nls/zu-za/SyncResultsHistory',{});
},
'Sage/TaskPane/nls/zu/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/zu/SecuredActionTasklet',{});
},
'Sage/TaskPane/nls/zu-za/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/zu-za/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/zu/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/zu/DashboardTabController',{});
},
'Sage/UI/Dashboard/nls/zu-za/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/zu-za/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/zu/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zu/SalesOrderRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/zu-za/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zu-za/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/zu/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu/UserControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zu-za/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu-za/UserControlDesigner',{});
},
'Sage/Groups/nls/zu/GroupNavigator':function(){
define('Sage/Groups/nls/zu/GroupNavigator',{});
},
'Sage/Groups/nls/zu-za/GroupNavigator':function(){
define('Sage/Groups/nls/zu-za/GroupNavigator',{});
},
'Sage/Utility/File/nls/zu/AddURLAttachment':function(){
define('Sage/Utility/File/nls/zu/AddURLAttachment',{});
},
'Sage/Utility/File/nls/zu-za/AddURLAttachment':function(){
define('Sage/Utility/File/nls/zu-za/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/zu/EditFilterItems':function(){
define('Sage/UI/Filters/nls/zu/EditFilterItems',{});
},
'Sage/UI/Filters/nls/zu-za/EditFilterItems':function(){
define('Sage/UI/Filters/nls/zu-za/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zu/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zu/CrystalReportsFormatter',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zu-za/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zu-za/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/zu/DragDropWatcher':function(){
define('Sage/Utility/File/nls/zu/DragDropWatcher',{});
},
'Sage/Utility/File/nls/zu-za/DragDropWatcher':function(){
define('Sage/Utility/File/nls/zu-za/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/zu/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/zu/DesignSurface',{});
},
'Sage/QuickForms/Design/nls/zu-za/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/zu-za/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/zu/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zu/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zu-za/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zu-za/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/FormAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zu-za/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu-za/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zu/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zu/EventListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zu-za/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zu-za/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/zu/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/zu/AllOpenListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/zu-za/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/zu-za/AllOpenListPanelConfig',{});
},
'Sage/MainView/nls/zu/FormManager':function(){
define('Sage/MainView/nls/zu/FormManager',{});
},
'Sage/MainView/nls/zu-za/FormManager':function(){
define('Sage/MainView/nls/zu-za/FormManager',{});
},
'Sage/UI/nls/zu/ActivityScheduler':function(){
define('Sage/UI/nls/zu/ActivityScheduler',{});
},
'Sage/UI/nls/zu-za/ActivityScheduler':function(){
define('Sage/UI/nls/zu-za/ActivityScheduler',{});
},
'Sage/MainView/nls/zu/SecurityManager':function(){
define('Sage/MainView/nls/zu/SecurityManager',{});
},
'Sage/MainView/nls/zu-za/SecurityManager':function(){
define('Sage/MainView/nls/zu-za/SecurityManager',{});
},
'Sage/TaskPane/nls/zu/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/zu/ActivityTaskConfigurationProvider',{});
},
'Sage/TaskPane/nls/zu-za/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/zu-za/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/zu/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/zu/EntityInfoToolTip',{});
},
'Sage/UI/Controls/nls/zu-za/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/zu-za/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/zu/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/zu/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/zu-za/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/zu-za/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/templates/nls/zu/AllOpenDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/zu/AllOpenDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/zu-za/AllOpenDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/zu-za/AllOpenDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/zu/ReportsListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/zu/ReportsListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/zu-za/ReportsListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/zu-za/ReportsListSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/zu/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/zu/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/Common/nls/zu-za/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/zu-za/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/templates/nls/zu/ScheduleDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/zu/ScheduleDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/zu-za/ScheduleDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/zu-za/ScheduleDetailSummary',{});
},
'Sage/MainView/Opportunity/nls/zu/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/zu/UpdateOpportunities',{});
},
'Sage/MainView/Opportunity/nls/zu-za/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/zu-za/UpdateOpportunities',{});
},
'Sage/UI/nls/zu/EditCalendarUsers':function(){
define('Sage/UI/nls/zu/EditCalendarUsers',{});
},
'Sage/UI/nls/zu-za/EditCalendarUsers':function(){
define('Sage/UI/nls/zu-za/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zu/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zu/CrystalReportParametersDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zu-za/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zu-za/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/zu/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu/DateTimePickerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zu-za/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu-za/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/zu/HelpMenu':function(){
define('Sage/UI/Controls/nls/zu/HelpMenu',{});
},
'Sage/UI/Controls/nls/zu-za/HelpMenu':function(){
define('Sage/UI/Controls/nls/zu-za/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/LayoutPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zu-za/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu-za/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/zu/UserTasklet':function(){
define('Sage/TaskPane/nls/zu/UserTasklet',{});
},
'Sage/TaskPane/nls/zu-za/UserTasklet':function(){
define('Sage/TaskPane/nls/zu-za/UserTasklet',{});
},
'Sage/UI/Alarms/nls/zu/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/zu/ActivityAlarm',{});
},
'Sage/UI/Alarms/nls/zu-za/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/zu-za/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/zu/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/zu/OpportunityStatistics',{});
},
'Sage/MainView/Opportunity/nls/zu-za/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/zu-za/OpportunityStatistics',{});
},
'Sage/TaskPane/nls/zu/GroupListTasklet':function(){
define('Sage/TaskPane/nls/zu/GroupListTasklet',{});
},
'Sage/TaskPane/nls/zu-za/GroupListTasklet':function(){
define('Sage/TaskPane/nls/zu-za/GroupListTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zu/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zu/CrystalReportConditionEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zu-za/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zu-za/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/zu/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/zu/AdvancedSearchOptions',{});
},
'Sage/MainView/IntegrationContract/nls/zu-za/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/zu-za/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/zu/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/zu/ColumnDesigner',{});
},
'Sage/QuickForms/Design/nls/zu-za/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/zu-za/ColumnDesigner',{});
},
'Sage/MainView/JobMgr/templates/nls/zu/JobDefinitionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/zu/JobDefinitionDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/zu-za/JobDefinitionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/zu-za/JobDefinitionDetailSummary',{});
},
'Sage/UI/nls/zu/SearchMenuItem':function(){
define('Sage/UI/nls/zu/SearchMenuItem',{});
},
'Sage/UI/nls/zu-za/SearchMenuItem':function(){
define('Sage/UI/nls/zu-za/SearchMenuItem',{});
},
'Sage/Library/nls/zu/DocumentProperties':function(){
define('Sage/Library/nls/zu/DocumentProperties',{});
},
'Sage/Library/nls/zu-za/DocumentProperties':function(){
define('Sage/Library/nls/zu-za/DocumentProperties',{});
},
'Sage/UI/nls/zu/NotesHistoryList':function(){
define('Sage/UI/nls/zu/NotesHistoryList',{});
},
'Sage/UI/nls/zu-za/NotesHistoryList':function(){
define('Sage/UI/nls/zu-za/NotesHistoryList',{});
},
'Sage/Utility/nls/zu/File':function(){
define('Sage/Utility/nls/zu/File',{});
},
'Sage/Utility/nls/zu-za/File':function(){
define('Sage/Utility/nls/zu-za/File',{});
},
'Sage/MainView/ReportMgr/nls/zu/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/zu/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/zu-za/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/zu-za/HistoryListPanelConfig',{});
},
'Sage/MainView/JobMgr/templates/nls/zu/ScheduleDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/zu/ScheduleDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/zu-za/ScheduleDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/zu-za/ScheduleDetailSummary',{});
},
'Sage/QuickForms/Design/nls/zu/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu/UrlControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zu-za/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu-za/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/zu/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/zu/ContactTasksTasklet',{});
},
'Sage/TaskPane/nls/zu-za/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/zu-za/ContactTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/templates/nls/zu/EventSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/zu/EventSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/zu-za/EventSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/zu-za/EventSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/zu/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/zu/_WizardDialogBase',{});
},
'Sage/MainView/ReportMgr/Common/nls/zu-za/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/zu-za/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/zu/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/zu/SchedulesListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/zu-za/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/zu-za/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/zu/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/zu/GoogleDocPicker',{});
},
'Sage/Utility/File/nls/zu-za/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/zu-za/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/zu/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu/ComboBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zu-za/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu-za/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/zu/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zu/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zu-za/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zu-za/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zu/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zu/HistoryEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zu-za/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zu-za/HistoryEditor',{});
},
'Sage/Groups/nls/zu/GroupManager':function(){
define('Sage/Groups/nls/zu/GroupManager',{});
},
'Sage/Groups/nls/zu-za/GroupManager':function(){
define('Sage/Groups/nls/zu-za/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zu-za/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu-za/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/ComboBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zu-za/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu-za/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/zu/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/zu/ReportsListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/zu-za/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/zu-za/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/zu/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/zu/JobNotificationButton',{});
},
'Sage/UI/Alarms/nls/zu-za/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/zu-za/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zu/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zu/CrystalReportWizardController',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zu-za/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zu-za/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/zu/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/zu/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/zu-za/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/zu-za/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zu/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zu/RecurringEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zu-za/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zu-za/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zu/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zu/CrystalReportsUtility',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zu-za/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zu-za/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zu-za/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu-za/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/zu/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/zu/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/zu-za/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/zu-za/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/zu/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zu-za/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu-za/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zu/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zu-za/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu-za/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zu/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zu-za/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu-za/PickListControlDesigner',{});
},
'Sage/MainView/ActivityMgr/templates/nls/zu/LitRequestSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/zu/LitRequestSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/zu-za/LitRequestSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/zu-za/LitRequestSummary',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zu-za/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu-za/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/zu/FolderHandler':function(){
define('Sage/Library/nls/zu/FolderHandler',{});
},
'Sage/Library/nls/zu-za/FolderHandler':function(){
define('Sage/Library/nls/zu-za/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zu-za/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu-za/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/zu/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/zu/ContactSearchForDuplicates',{});
},
'Sage/MainView/Contact/nls/zu-za/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/zu-za/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/DateTimePickerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zu-za/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu-za/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/zu/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/zu/AccountingTasksTasklet',{});
},
'Sage/TaskPane/nls/zu-za/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/zu-za/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zu-za/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu-za/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/CurrencyBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zu-za/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu-za/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/zu/EditableGrid':function(){
define('Sage/UI/nls/zu/EditableGrid',{});
},
'Sage/UI/nls/zu-za/EditableGrid':function(){
define('Sage/UI/nls/zu-za/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/zu/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zu/SalesQuoteRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/zu-za/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zu-za/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/zu/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/zu/SecurityProfile',{});
},
'Sage/MainView/SecurityMgr/nls/zu-za/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/zu-za/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/zu/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/zu/ReportWizardController',{});
},
'Sage/MainView/ReportMgr/nls/zu-za/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/zu-za/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/UserAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zu-za/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu-za/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/zu/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/zu/ReportManagerUtility',{});
},
'Sage/MainView/ReportMgr/nls/zu-za/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/zu-za/ReportManagerUtility',{});
},
'Sage/UI/nls/zu/SpeedSearch':function(){
define('Sage/UI/nls/zu/SpeedSearch',{});
},
'Sage/UI/nls/zu-za/SpeedSearch':function(){
define('Sage/UI/nls/zu-za/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/CurrencyAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zu-za/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu-za/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/zu/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/zu/ReportManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/zu-za/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/zu-za/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/zu/SLXPreviewGrid':function(){
define('Sage/UI/nls/zu/SLXPreviewGrid',{});
},
'Sage/UI/nls/zu-za/SLXPreviewGrid':function(){
define('Sage/UI/nls/zu-za/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/zu/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/zu/UnconfirmedPane',{});
},
'Sage/UI/Alarms/nls/zu-za/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/zu-za/UnconfirmedPane',{});
},
'Sage/Utility/nls/zu/Utility':function(){
define('Sage/Utility/nls/zu/Utility',{});
},
'Sage/Utility/nls/zu-za/Utility':function(){
define('Sage/Utility/nls/zu-za/Utility',{});
},
'Sage/QuickForms/Design/nls/zu/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu/ControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zu-za/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu-za/ControlDesigner',{});
},
'Sage/UI/Controls/nls/zu/Address':function(){
define('Sage/UI/Controls/nls/zu/Address',{});
},
'Sage/UI/Controls/nls/zu-za/Address':function(){
define('Sage/UI/Controls/nls/zu-za/Address',{});
},
'Sage/MainView/JobMgr/nls/zu/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/zu/JobManagerGroupContextService',{});
},
'Sage/MainView/JobMgr/nls/zu-za/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/zu-za/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/zu/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zu/BaseListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zu-za/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zu-za/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/zu/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu/OwnerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zu-za/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu-za/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/zu/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/zu/JobManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/zu-za/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/zu-za/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/zu/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/zu/ActivityEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/zu-za/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/zu-za/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/zu/UserType':function(){
define('Sage/UI/nls/zu/UserType',{});
},
'Sage/UI/nls/zu-za/UserType':function(){
define('Sage/UI/nls/zu-za/UserType',{});
},
'Sage/MainView/ReportMgr/templates/nls/zu/HistoryDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/zu/HistoryDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/zu-za/HistoryDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/zu-za/HistoryDetailSummary',{});
},
'Sage/QuickForms/Design/nls/zu/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/zu/FormDesigner',{});
},
'Sage/QuickForms/Design/nls/zu-za/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/zu-za/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/zu/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/zu/ActivityCalendar',{});
},
'Sage/MainView/ActivityMgr/nls/zu-za/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/zu-za/ActivityCalendar',{});
},
'Sage/Utility/nls/zu/Jobs':function(){
define('Sage/Utility/nls/zu/Jobs',{});
},
'Sage/Utility/nls/zu-za/Jobs':function(){
define('Sage/Utility/nls/zu-za/Jobs',{});
},
'Sage/UI/Controls/nls/zu/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/zu/_DialogHelpIconMixin',{});
},
'Sage/UI/Controls/nls/zu-za/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/zu-za/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/PickListAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zu-za/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu-za/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/zu/ActivityList':function(){
define('Sage/UI/nls/zu/ActivityList',{});
},
'Sage/UI/nls/zu-za/ActivityList':function(){
define('Sage/UI/nls/zu-za/ActivityList',{});
},
'Sage/UI/Alarms/nls/zu/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/zu/JobNotificationPopup',{});
},
'Sage/UI/Alarms/nls/zu-za/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/zu-za/JobNotificationPopup',{});
},
'Sage/MainView/JobMgr/templates/nls/zu/ExecutionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/zu/ExecutionsListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/zu-za/ExecutionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/zu-za/ExecutionsListSummary',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/zu/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/zu/LeadLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/zu-za/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/zu-za/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/zu/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/zu/SchedulesListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/zu-za/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/zu-za/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/GenericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zu-za/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu-za/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/zu/CalendarUsersListPane':function(){
define('Sage/UI/nls/zu/CalendarUsersListPane',{});
},
'Sage/UI/nls/zu-za/CalendarUsersListPane':function(){
define('Sage/UI/nls/zu-za/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zu-za/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu-za/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/ColumnBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zu-za/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu-za/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/templates/nls/zu/ExecutionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/zu/ExecutionDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/zu-za/ExecutionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/zu-za/ExecutionDetailSummary',{});
},
'Sage/MainView/ReportMgr/nls/zu/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/zu/ReportManagerGroupContextService',{});
},
'Sage/MainView/ReportMgr/nls/zu-za/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/zu-za/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/zu/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/zu/MatchingOptionsConfig',{});
},
'Sage/MainView/IntegrationContract/nls/zu-za/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/zu-za/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/FormBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zu-za/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu-za/FormBasicPropertyEditor',{});
},
'Sage/UI/Alarms/nls/zu/AlarmButton':function(){
define('Sage/UI/Alarms/nls/zu/AlarmButton',{});
},
'Sage/UI/Alarms/nls/zu-za/AlarmButton':function(){
define('Sage/UI/Alarms/nls/zu-za/AlarmButton',{});
},
'Sage/MainView/ActivityMgr/nls/zu/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/zu/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/MainView/ActivityMgr/nls/zu-za/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/zu-za/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/zu/Attachment':function(){
define('Sage/Utility/File/nls/zu/Attachment',{});
},
'Sage/Utility/File/nls/zu-za/Attachment':function(){
define('Sage/Utility/File/nls/zu-za/Attachment',{});
},
'Sage/QuickForms/Design/nls/zu/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zu-za/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu-za/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zu/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/zu/PropertyEditorContainer',{});
},
'Sage/QuickForms/Design/nls/zu-za/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/zu-za/PropertyEditorContainer',{});
},
'Sage/Services/nls/zu/ReportingService':function(){
define('Sage/Services/nls/zu/ReportingService',{});
},
'Sage/Services/nls/zu-za/ReportingService':function(){
define('Sage/Services/nls/zu-za/ReportingService',{});
},
'Sage/MailMerge/nls/zu/Helper':function(){
define('Sage/MailMerge/nls/zu/Helper',{});
},
'Sage/MailMerge/nls/zu-za/Helper':function(){
define('Sage/MailMerge/nls/zu-za/Helper',{});
},
'Sage/UI/Dashboard/nls/zu/Dashboard':function(){
define('Sage/UI/Dashboard/nls/zu/Dashboard',{});
},
'Sage/UI/Dashboard/nls/zu-za/Dashboard':function(){
define('Sage/UI/Dashboard/nls/zu-za/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/zu/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zu/ActivityListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zu-za/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zu-za/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/zu/PickList':function(){
define('Sage/UI/Controls/nls/zu/PickList',{});
},
'Sage/UI/Controls/nls/zu-za/PickList':function(){
define('Sage/UI/Controls/nls/zu-za/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/zu/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/zu/HistoryEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/zu-za/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/zu-za/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/zu/Email':function(){
define('Sage/Utility/nls/zu/Email',{});
},
'Sage/Utility/nls/zu-za/Email':function(){
define('Sage/Utility/nls/zu-za/Email',{});
},
'Sage/TaskPane/nls/zu/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/zu/SecurityManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/zu-za/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/zu-za/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/zu/TimeZoneItem':function(){
define('Sage/UI/nls/zu/TimeZoneItem',{});
},
'Sage/UI/nls/zu-za/TimeZoneItem':function(){
define('Sage/UI/nls/zu-za/TimeZoneItem',{});
},
'Sage/MainView/ReportMgr/templates/nls/zu/HistoryListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/zu/HistoryListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/zu-za/HistoryListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/zu-za/HistoryListSummary',{});
},
'Sage/UI/Columns/nls/zu/SlxEdit':function(){
define('Sage/UI/Columns/nls/zu/SlxEdit',{});
},
'Sage/UI/Columns/nls/zu-za/SlxEdit':function(){
define('Sage/UI/Columns/nls/zu-za/SlxEdit',{});
},
'Sage/Reporting/nls/zu/Enumerations':function(){
define('Sage/Reporting/nls/zu/Enumerations',{});
},
'Sage/Reporting/nls/zu-za/Enumerations':function(){
define('Sage/Reporting/nls/zu-za/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zu-za/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu-za/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zu/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zu/CrystalReportConditionsDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zu-za/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zu-za/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/zu/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/zu/ActivityListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/zu-za/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/zu-za/ActivityListPanelConfig',{});
},
'Sage/UI/nls/zu/JobSchedulingWidget':function(){
define('Sage/UI/nls/zu/JobSchedulingWidget',{});
},
'Sage/UI/nls/zu-za/JobSchedulingWidget':function(){
define('Sage/UI/nls/zu-za/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/zu/LogOffButton':function(){
define('Sage/UI/Controls/nls/zu/LogOffButton',{});
},
'Sage/UI/Controls/nls/zu-za/LogOffButton':function(){
define('Sage/UI/Controls/nls/zu-za/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/TextBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zu-za/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu-za/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zu/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zu/EditEventEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zu-za/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zu-za/EditEventEditor',{});
},
'Sage/MailMerge/nls/zu/Loader':function(){
define('Sage/MailMerge/nls/zu/Loader',{});
},
'Sage/MailMerge/nls/zu-za/Loader':function(){
define('Sage/MailMerge/nls/zu-za/Loader',{});
},
'Sage/UI/Controls/nls/zu/DateTimePicker':function(){
define('Sage/UI/Controls/nls/zu/DateTimePicker',{});
},
'Sage/UI/Controls/nls/zu-za/DateTimePicker':function(){
define('Sage/UI/Controls/nls/zu-za/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/zu/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/zu/ReportManagerActions',{});
},
'Sage/MainView/ReportMgr/nls/zu-za/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/zu-za/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/zu/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/zu/AlarmPopup',{});
},
'Sage/UI/Alarms/nls/zu-za/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/zu-za/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/zu/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/zu/ContactUserAssociationEditor',{});
},
'Sage/MainView/Contact/nls/zu-za/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/zu-za/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zu-za/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu-za/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/zu/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/zu/BaseListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/zu-za/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/zu-za/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/zu/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zu-za/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu-za/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zu/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu/EmailControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zu-za/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu-za/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/zu/Lookup':function(){
define('Sage/UI/Controls/nls/zu/Lookup',{});
},
'Sage/UI/Controls/nls/zu-za/Lookup':function(){
define('Sage/UI/Controls/nls/zu-za/Lookup',{});
},
'Sage/Utility/File/nls/zu/DescriptionsForm':function(){
define('Sage/Utility/File/nls/zu/DescriptionsForm',{});
},
'Sage/Utility/File/nls/zu-za/DescriptionsForm':function(){
define('Sage/Utility/File/nls/zu-za/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/NumericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zu-za/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu-za/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/zu/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/zu/CommonTasksTasklet',{});
},
'Sage/TaskPane/nls/zu-za/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/zu-za/CommonTasksTasklet',{});
},
'Sage/Utility/nls/zu/Dashboard':function(){
define('Sage/Utility/nls/zu/Dashboard',{});
},
'Sage/Utility/nls/zu-za/Dashboard':function(){
define('Sage/Utility/nls/zu-za/Dashboard',{});
}}});
define("Sage/nls/Sage_zu-za", [], 1);
