require({cache:{
'Sage/Utility/File/nls/af/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/af/FallbackFilePicker',{});
},
'Sage/Utility/File/nls/af-za/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/af-za/FallbackFilePicker',{});
},
'Sage/UI/nls/af/Boolean':function(){
define('Sage/UI/nls/af/Boolean',{});
},
'Sage/UI/nls/af-za/Boolean':function(){
define('Sage/UI/nls/af-za/Boolean',{});
},
'Sage/Services/nls/af/ActivityService':function(){
define('Sage/Services/nls/af/ActivityService',{});
},
'Sage/Services/nls/af-za/ActivityService':function(){
define('Sage/Services/nls/af-za/ActivityService',{});
},
'Sage/UI/Controls/nls/af/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/af/CopyToClipboard',{});
},
'Sage/UI/Controls/nls/af-za/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/af-za/CopyToClipboard',{});
},
'Sage/Utility/nls/af/Activity':function(){
define('Sage/Utility/nls/af/Activity',{});
},
'Sage/Utility/nls/af-za/Activity':function(){
define('Sage/Utility/nls/af-za/Activity',{});
},
'Sage/QuickForms/Design/nls/af/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/af/DesignPanel',{});
},
'Sage/QuickForms/Design/nls/af-za/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/af-za/DesignPanel',{});
},
'Sage/UI/nls/af/TimelessActivitiesPane':function(){
define('Sage/UI/nls/af/TimelessActivitiesPane',{});
},
'Sage/UI/nls/af-za/TimelessActivitiesPane':function(){
define('Sage/UI/nls/af-za/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/af/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/af/ActivityEditor',{});
},
'Sage/MainView/ActivityMgr/nls/af-za/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/af-za/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/af/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/af/ContactUserAssociationEditor',{});
},
'Sage/TaskPane/User/nls/af-za/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/af-za/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/af/ActivityManager':function(){
define('Sage/MainView/nls/af/ActivityManager',{});
},
'Sage/MainView/nls/af-za/ActivityManager':function(){
define('Sage/MainView/nls/af-za/ActivityManager',{});
},
'Sage/Services/nls/af/JobService':function(){
define('Sage/Services/nls/af/JobService',{});
},
'Sage/Services/nls/af-za/JobService':function(){
define('Sage/Services/nls/af-za/JobService',{});
},
'Sage/QuickForms/Design/nls/af/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/af-za/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af-za/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/af/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/_PropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/af-za/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af-za/_PropertyEditor',{});
},
'Sage/Services/nls/af/ActivityActionProcessor':function(){
define('Sage/Services/nls/af/ActivityActionProcessor',{});
},
'Sage/Services/nls/af-za/ActivityActionProcessor':function(){
define('Sage/Services/nls/af-za/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/af/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/TextBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/af-za/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af-za/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/af/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/af/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/nls/af-za/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/af-za/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/templates/nls/af/UserActivityDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/af/UserActivityDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/af-za/UserActivityDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/af-za/UserActivityDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/af/ConfirmationDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/af/ConfirmationDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/af-za/ConfirmationDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/af-za/ConfirmationDetailSummary',{});
},
'Sage/Utility/File/nls/af/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/af/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/af-za/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/af-za/DefaultDropHandler',{});
},
'Sage/UI/nls/af/TransferBoxWidget':function(){
define('Sage/UI/nls/af/TransferBoxWidget',{});
},
'Sage/UI/nls/af-za/TransferBoxWidget':function(){
define('Sage/UI/nls/af-za/TransferBoxWidget',{});
},
'Sage/Utility/File/nls/af/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/af/AttachmentPropertiesEditForm',{});
},
'Sage/Utility/File/nls/af-za/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/af-za/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/af/AlarmPane':function(){
define('Sage/UI/Alarms/nls/af/AlarmPane',{});
},
'Sage/UI/Alarms/nls/af-za/AlarmPane':function(){
define('Sage/UI/Alarms/nls/af-za/AlarmPane',{});
},
'Sage/TaskPane/nls/af/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/af/LiteratureManagementTasks',{});
},
'Sage/TaskPane/nls/af-za/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/af-za/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/af/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/af/DashboardWidget',{});
},
'Sage/UI/Dashboard/nls/af-za/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/af-za/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/af/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/NumericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/af-za/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af-za/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/af/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/af/CustomerPaymentsRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/af-za/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/af-za/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/af/FilterPanel':function(){
define('Sage/UI/Filters/nls/af/FilterPanel',{});
},
'Sage/UI/Filters/nls/af-za/FilterPanel':function(){
define('Sage/UI/Filters/nls/af-za/FilterPanel',{});
},
'Sage/TaskPane/nls/af/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/af/_BaseTaskPaneTasklet',{});
},
'Sage/TaskPane/nls/af-za/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/af-za/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/af/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/af/ReportManagerFormatter',{});
},
'Sage/MainView/ReportMgr/nls/af-za/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/af-za/ReportManagerFormatter',{});
},
'Sage/UI/nls/af/OwnerType':function(){
define('Sage/UI/nls/af/OwnerType',{});
},
'Sage/UI/nls/af-za/OwnerType':function(){
define('Sage/UI/nls/af-za/OwnerType',{});
},
'Sage/MainView/JobMgr/templates/nls/af/JobDefinitionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/af/JobDefinitionsListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/af-za/JobDefinitionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/af-za/JobDefinitionsListSummary',{});
},
'Sage/TaskPane/nls/af/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/af/LeadTasksTasklet',{});
},
'Sage/TaskPane/nls/af-za/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/af-za/LeadTasksTasklet',{});
},
'Sage/MainView/ReportMgr/templates/nls/af/ReportDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/af/ReportDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/af-za/ReportDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/af-za/ReportDetailSummary',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/af/_ParameterEditorBase':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/af/_ParameterEditorBase',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/af-za/_ParameterEditorBase':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/af-za/_ParameterEditorBase',{});
},
'Sage/MailMerge/nls/af/Service':function(){
define('Sage/MailMerge/nls/af/Service',{});
},
'Sage/MailMerge/nls/af-za/Service':function(){
define('Sage/MailMerge/nls/af-za/Service',{});
},
'Sage/MainView/ActivityMgr/templates/nls/af/ConfirmationListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/af/ConfirmationListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/af-za/ConfirmationListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/af-za/ConfirmationListSummary',{});
},
'Sage/MainView/ActivityMgr/nls/af/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/af/SnoozeOptions',{});
},
'Sage/MainView/ActivityMgr/nls/af-za/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/af-za/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/af/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/af-za/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af-za/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/af/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/af-za/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af-za/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/af/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/af/InvoiceRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/af-za/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/af-za/InvoiceRTDV',{});
},
'Sage/UI/nls/af/SDataLookup':function(){
define('Sage/UI/nls/af/SDataLookup',{});
},
'Sage/UI/nls/af-za/SDataLookup':function(){
define('Sage/UI/nls/af-za/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/af/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/af/RowDesigner',{});
},
'Sage/QuickForms/Design/nls/af-za/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/af-za/RowDesigner',{});
},
'Sage/Groups/nls/af/GroupLookup':function(){
define('Sage/Groups/nls/af/GroupLookup',{});
},
'Sage/Groups/nls/af-za/GroupLookup':function(){
define('Sage/Groups/nls/af-za/GroupLookup',{});
},
'Sage/TaskPane/nls/af/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/af/OpportunityTasksTasklet',{});
},
'Sage/TaskPane/nls/af-za/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/af-za/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/af/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/af/CheckBoxFilter',{});
},
'Sage/UI/Filters/nls/af-za/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/af-za/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/af/LibraryDocument':function(){
define('Sage/Utility/File/nls/af/LibraryDocument',{});
},
'Sage/Utility/File/nls/af-za/LibraryDocument':function(){
define('Sage/Utility/File/nls/af-za/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/af/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/af/SpeedSearchLookup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/af-za/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/af-za/SpeedSearchLookup',{});
},
'Sage/UI/nls/af/ConditionManager':function(){
define('Sage/UI/nls/af/ConditionManager',{});
},
'Sage/UI/nls/af-za/ConditionManager':function(){
define('Sage/UI/nls/af-za/ConditionManager',{});
},
'Sage/MainView/JobMgr/templates/nls/af/SchedulesListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/af/SchedulesListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/af-za/SchedulesListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/af-za/SchedulesListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/af/UserActivityListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/af/UserActivityListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/af-za/UserActivityListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/af-za/UserActivityListSummary',{});
},
'Sage/UI/Dashboard/nls/af/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/af/WidgetDefinition',{});
},
'Sage/UI/Dashboard/nls/af-za/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/af-za/WidgetDefinition',{});
},
'Sage/MainView/ActivityMgr/templates/nls/af/AllOpenListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/af/AllOpenListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/af-za/AllOpenListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/af-za/AllOpenListSummary',{});
},
'Sage/UI/nls/af/SearchConditionWidget':function(){
define('Sage/UI/nls/af/SearchConditionWidget',{});
},
'Sage/UI/nls/af-za/SearchConditionWidget':function(){
define('Sage/UI/nls/af-za/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/af/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/af-za/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af-za/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/af/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/af/JobManagerActions',{});
},
'Sage/MainView/JobMgr/nls/af-za/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/af-za/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/af/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/af/ContactLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/af-za/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/af-za/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/af/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/af/DataSourcePanel',{});
},
'Sage/QuickForms/Design/nls/af-za/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/af-za/DataSourcePanel',{});
},
'Sage/MainView/ReportMgr/templates/nls/af/SchedulesListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/af/SchedulesListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/af-za/SchedulesListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/af-za/SchedulesListSummary',{});
},
'Sage/Library/nls/af/Manager':function(){
define('Sage/Library/nls/af/Manager',{});
},
'Sage/Library/nls/af-za/Manager':function(){
define('Sage/Library/nls/af-za/Manager',{});
},
'Sage/UI/nls/af/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/af/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/nls/af-za/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/af-za/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/af/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/af/NonVisibleControlContainer',{});
},
'Sage/QuickForms/Design/nls/af-za/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/af-za/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/af/Name':function(){
define('Sage/UI/Controls/nls/af/Name',{});
},
'Sage/UI/Controls/nls/af-za/Name':function(){
define('Sage/UI/Controls/nls/af-za/Name',{});
},
'Sage/MainView/JobMgr/nls/af/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/af/ExecutionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/af-za/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/af-za/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/af/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af/PhoneControlDesigner',{});
},
'Sage/QuickForms/Design/nls/af-za/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af-za/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/af/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/af/UpdateLeads',{});
},
'Sage/MainView/Lead/nls/af-za/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/af-za/UpdateLeads',{});
},
'Sage/Library/nls/af/FileHandler':function(){
define('Sage/Library/nls/af/FileHandler',{});
},
'Sage/Library/nls/af-za/FileHandler':function(){
define('Sage/Library/nls/af-za/FileHandler',{});
},
'Sage/UI/nls/af/ListPanel':function(){
define('Sage/UI/nls/af/ListPanel',{});
},
'Sage/UI/nls/af-za/ListPanel':function(){
define('Sage/UI/nls/af-za/ListPanel',{});
},
'Sage/Utility/nls/af/Sql':function(){
define('Sage/Utility/nls/af/Sql',{});
},
'Sage/Utility/nls/af-za/Sql':function(){
define('Sage/Utility/nls/af-za/Sql',{});
},
'Sage/UI/Filters/nls/af/EditFilters':function(){
define('Sage/UI/Filters/nls/af/EditFilters',{});
},
'Sage/UI/Filters/nls/af-za/EditFilters':function(){
define('Sage/UI/Filters/nls/af-za/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/af/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/FormUsagesPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/af-za/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af-za/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/af/DurationSelect':function(){
define('Sage/UI/Controls/nls/af/DurationSelect',{});
},
'Sage/UI/Controls/nls/af-za/DurationSelect':function(){
define('Sage/UI/Controls/nls/af-za/DurationSelect',{});
},
'Sage/UI/Alarms/nls/af/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/af/AlarmCountDown',{});
},
'Sage/UI/Alarms/nls/af-za/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/af-za/AlarmCountDown',{});
},
'Sage/UI/nls/af/AttachmentList':function(){
define('Sage/UI/nls/af/AttachmentList',{});
},
'Sage/UI/nls/af-za/AttachmentList':function(){
define('Sage/UI/nls/af-za/AttachmentList',{});
},
'Sage/MailMerge/nls/af/Lookup':function(){
define('Sage/MailMerge/nls/af/Lookup',{});
},
'Sage/MailMerge/nls/af-za/Lookup':function(){
define('Sage/MailMerge/nls/af-za/Lookup',{});
},
'Sage/QuickForms/Design/Editors/nls/af/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/af-za/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af-za/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/af/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/af/RunJobDialog',{});
},
'Sage/MainView/JobMgr/nls/af-za/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/af-za/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/af/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/af-za/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af-za/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/af/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/af-za/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af-za/EditableGridControlDesigner',{});
},
'Sage/MainView/Options/nls/af/OptionsDialog':function(){
define('Sage/MainView/Options/nls/af/OptionsDialog',{});
},
'Sage/MainView/Options/nls/af-za/OptionsDialog':function(){
define('Sage/MainView/Options/nls/af-za/OptionsDialog',{});
},
'Sage/QuickForms/Design/nls/af/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af/HiddenControlDesigner',{});
},
'Sage/QuickForms/Design/nls/af-za/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af-za/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/af/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/af/DashboardWidgetCell',{});
},
'Sage/UI/Dashboard/nls/af-za/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/af-za/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/af/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/UserBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/af-za/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af-za/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/af/Dialogs':function(){
define('Sage/UI/nls/af/Dialogs',{});
},
'Sage/UI/nls/af-za/Dialogs':function(){
define('Sage/UI/nls/af-za/Dialogs',{});
},
'Sage/MainView/IntegrationContract/nls/af/SyncResultsHistory':function(){
define('Sage/MainView/IntegrationContract/nls/af/SyncResultsHistory',{});
},
'Sage/MainView/IntegrationContract/nls/af-za/SyncResultsHistory':function(){
define('Sage/MainView/IntegrationContract/nls/af-za/SyncResultsHistory',{});
},
'Sage/TaskPane/nls/af/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/af/SecuredActionTasklet',{});
},
'Sage/TaskPane/nls/af-za/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/af-za/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/af/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/af/DashboardTabController',{});
},
'Sage/UI/Dashboard/nls/af-za/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/af-za/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/af/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/af/SalesOrderRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/af-za/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/af-za/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/af/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af/UserControlDesigner',{});
},
'Sage/QuickForms/Design/nls/af-za/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af-za/UserControlDesigner',{});
},
'Sage/Groups/nls/af/GroupNavigator':function(){
define('Sage/Groups/nls/af/GroupNavigator',{});
},
'Sage/Groups/nls/af-za/GroupNavigator':function(){
define('Sage/Groups/nls/af-za/GroupNavigator',{});
},
'Sage/Utility/File/nls/af/AddURLAttachment':function(){
define('Sage/Utility/File/nls/af/AddURLAttachment',{});
},
'Sage/Utility/File/nls/af-za/AddURLAttachment':function(){
define('Sage/Utility/File/nls/af-za/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/af/EditFilterItems':function(){
define('Sage/UI/Filters/nls/af/EditFilterItems',{});
},
'Sage/UI/Filters/nls/af-za/EditFilterItems':function(){
define('Sage/UI/Filters/nls/af-za/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/af/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/af/CrystalReportsFormatter',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/af-za/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/af-za/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/af/DragDropWatcher':function(){
define('Sage/Utility/File/nls/af/DragDropWatcher',{});
},
'Sage/Utility/File/nls/af-za/DragDropWatcher':function(){
define('Sage/Utility/File/nls/af-za/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/af/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/af/DesignSurface',{});
},
'Sage/QuickForms/Design/nls/af-za/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/af-za/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/af/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/af/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/af-za/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/af-za/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/af/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/FormAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/af-za/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af-za/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/af/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/af/EventListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/af-za/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/af-za/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/af/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/af/AllOpenListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/af-za/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/af-za/AllOpenListPanelConfig',{});
},
'Sage/MainView/nls/af/FormManager':function(){
define('Sage/MainView/nls/af/FormManager',{});
},
'Sage/MainView/nls/af-za/FormManager':function(){
define('Sage/MainView/nls/af-za/FormManager',{});
},
'Sage/UI/nls/af/ActivityScheduler':function(){
define('Sage/UI/nls/af/ActivityScheduler',{});
},
'Sage/UI/nls/af-za/ActivityScheduler':function(){
define('Sage/UI/nls/af-za/ActivityScheduler',{});
},
'Sage/MainView/nls/af/SecurityManager':function(){
define('Sage/MainView/nls/af/SecurityManager',{});
},
'Sage/MainView/nls/af-za/SecurityManager':function(){
define('Sage/MainView/nls/af-za/SecurityManager',{});
},
'Sage/TaskPane/nls/af/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/af/ActivityTaskConfigurationProvider',{});
},
'Sage/TaskPane/nls/af-za/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/af-za/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/af/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/af/EntityInfoToolTip',{});
},
'Sage/UI/Controls/nls/af-za/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/af-za/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/af/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/af/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/af-za/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/af-za/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/templates/nls/af/AllOpenDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/af/AllOpenDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/af-za/AllOpenDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/af-za/AllOpenDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/af/ReportsListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/af/ReportsListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/af-za/ReportsListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/af-za/ReportsListSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/af/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/af/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/Common/nls/af-za/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/af-za/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/templates/nls/af/ScheduleDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/af/ScheduleDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/af-za/ScheduleDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/af-za/ScheduleDetailSummary',{});
},
'Sage/MainView/Opportunity/nls/af/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/af/UpdateOpportunities',{});
},
'Sage/MainView/Opportunity/nls/af-za/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/af-za/UpdateOpportunities',{});
},
'Sage/UI/nls/af/EditCalendarUsers':function(){
define('Sage/UI/nls/af/EditCalendarUsers',{});
},
'Sage/UI/nls/af-za/EditCalendarUsers':function(){
define('Sage/UI/nls/af-za/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/af/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/af/CrystalReportParametersDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/af-za/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/af-za/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/af/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af/DateTimePickerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/af-za/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af-za/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/af/HelpMenu':function(){
define('Sage/UI/Controls/nls/af/HelpMenu',{});
},
'Sage/UI/Controls/nls/af-za/HelpMenu':function(){
define('Sage/UI/Controls/nls/af-za/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/af/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/LayoutPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/af-za/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af-za/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/af/UserTasklet':function(){
define('Sage/TaskPane/nls/af/UserTasklet',{});
},
'Sage/TaskPane/nls/af-za/UserTasklet':function(){
define('Sage/TaskPane/nls/af-za/UserTasklet',{});
},
'Sage/UI/Alarms/nls/af/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/af/ActivityAlarm',{});
},
'Sage/UI/Alarms/nls/af-za/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/af-za/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/af/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/af/OpportunityStatistics',{});
},
'Sage/MainView/Opportunity/nls/af-za/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/af-za/OpportunityStatistics',{});
},
'Sage/TaskPane/nls/af/GroupListTasklet':function(){
define('Sage/TaskPane/nls/af/GroupListTasklet',{});
},
'Sage/TaskPane/nls/af-za/GroupListTasklet':function(){
define('Sage/TaskPane/nls/af-za/GroupListTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/af/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/af/CrystalReportConditionEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/af-za/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/af-za/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/af/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/af/AdvancedSearchOptions',{});
},
'Sage/MainView/IntegrationContract/nls/af-za/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/af-za/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/af/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/af/ColumnDesigner',{});
},
'Sage/QuickForms/Design/nls/af-za/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/af-za/ColumnDesigner',{});
},
'Sage/MainView/JobMgr/templates/nls/af/JobDefinitionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/af/JobDefinitionDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/af-za/JobDefinitionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/af-za/JobDefinitionDetailSummary',{});
},
'Sage/UI/nls/af/SearchMenuItem':function(){
define('Sage/UI/nls/af/SearchMenuItem',{});
},
'Sage/UI/nls/af-za/SearchMenuItem':function(){
define('Sage/UI/nls/af-za/SearchMenuItem',{});
},
'Sage/Library/nls/af/DocumentProperties':function(){
define('Sage/Library/nls/af/DocumentProperties',{});
},
'Sage/Library/nls/af-za/DocumentProperties':function(){
define('Sage/Library/nls/af-za/DocumentProperties',{});
},
'Sage/UI/nls/af/NotesHistoryList':function(){
define('Sage/UI/nls/af/NotesHistoryList',{});
},
'Sage/UI/nls/af-za/NotesHistoryList':function(){
define('Sage/UI/nls/af-za/NotesHistoryList',{});
},
'Sage/Utility/nls/af/File':function(){
define('Sage/Utility/nls/af/File',{});
},
'Sage/Utility/nls/af-za/File':function(){
define('Sage/Utility/nls/af-za/File',{});
},
'Sage/MainView/ReportMgr/nls/af/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/af/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/af-za/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/af-za/HistoryListPanelConfig',{});
},
'Sage/MainView/JobMgr/templates/nls/af/ScheduleDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/af/ScheduleDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/af-za/ScheduleDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/af-za/ScheduleDetailSummary',{});
},
'Sage/QuickForms/Design/nls/af/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af/UrlControlDesigner',{});
},
'Sage/QuickForms/Design/nls/af-za/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af-za/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/af/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/af/ContactTasksTasklet',{});
},
'Sage/TaskPane/nls/af-za/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/af-za/ContactTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/templates/nls/af/EventSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/af/EventSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/af-za/EventSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/af-za/EventSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/af/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/af/_WizardDialogBase',{});
},
'Sage/MainView/ReportMgr/Common/nls/af-za/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/af-za/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/af/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/af/SchedulesListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/af-za/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/af-za/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/af/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/af/GoogleDocPicker',{});
},
'Sage/Utility/File/nls/af-za/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/af-za/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/af/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af/ComboBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/af-za/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af-za/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/af/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/af/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/af-za/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/af-za/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/af/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/af/HistoryEditor',{});
},
'Sage/MainView/ActivityMgr/nls/af-za/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/af-za/HistoryEditor',{});
},
'Sage/Groups/nls/af/GroupManager':function(){
define('Sage/Groups/nls/af/GroupManager',{});
},
'Sage/Groups/nls/af-za/GroupManager':function(){
define('Sage/Groups/nls/af-za/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/af/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/af-za/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af-za/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/af/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/ComboBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/af-za/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af-za/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/af/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/af/ReportsListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/af-za/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/af-za/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/af/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/af/JobNotificationButton',{});
},
'Sage/UI/Alarms/nls/af-za/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/af-za/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/af/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/af/CrystalReportWizardController',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/af-za/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/af-za/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/af/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/af/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/af-za/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/af-za/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/af/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/af/RecurringEditor',{});
},
'Sage/MainView/ActivityMgr/nls/af-za/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/af-za/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/af/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/af/CrystalReportsUtility',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/af-za/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/af-za/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/af/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/af-za/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af-za/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/af/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/af/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/af-za/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/af-za/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/af/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/af-za/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af-za/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/af/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/af-za/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af-za/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/af/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/nls/af-za/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af-za/PickListControlDesigner',{});
},
'Sage/MainView/ActivityMgr/templates/nls/af/LitRequestSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/af/LitRequestSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/af-za/LitRequestSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/af-za/LitRequestSummary',{});
},
'Sage/QuickForms/Design/Editors/nls/af/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/af-za/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af-za/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/af/FolderHandler':function(){
define('Sage/Library/nls/af/FolderHandler',{});
},
'Sage/Library/nls/af-za/FolderHandler':function(){
define('Sage/Library/nls/af-za/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/af/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/af-za/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af-za/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/af/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/af/ContactSearchForDuplicates',{});
},
'Sage/MainView/Contact/nls/af-za/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/af-za/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/af/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/DateTimePickerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/af-za/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af-za/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/af/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/af/AccountingTasksTasklet',{});
},
'Sage/TaskPane/nls/af-za/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/af-za/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/af/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/af-za/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af-za/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/af/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/CurrencyBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/af-za/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af-za/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/af/EditableGrid':function(){
define('Sage/UI/nls/af/EditableGrid',{});
},
'Sage/UI/nls/af-za/EditableGrid':function(){
define('Sage/UI/nls/af-za/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/af/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/af/SalesQuoteRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/af-za/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/af-za/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/af/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/af/SecurityProfile',{});
},
'Sage/MainView/SecurityMgr/nls/af-za/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/af-za/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/af/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/af/ReportWizardController',{});
},
'Sage/MainView/ReportMgr/nls/af-za/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/af-za/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/af/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/UserAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/af-za/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af-za/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/af/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/af/ReportManagerUtility',{});
},
'Sage/MainView/ReportMgr/nls/af-za/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/af-za/ReportManagerUtility',{});
},
'Sage/UI/nls/af/SpeedSearch':function(){
define('Sage/UI/nls/af/SpeedSearch',{});
},
'Sage/UI/nls/af-za/SpeedSearch':function(){
define('Sage/UI/nls/af-za/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/af/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/CurrencyAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/af-za/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af-za/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/af/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/af/ReportManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/af-za/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/af-za/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/af/SLXPreviewGrid':function(){
define('Sage/UI/nls/af/SLXPreviewGrid',{});
},
'Sage/UI/nls/af-za/SLXPreviewGrid':function(){
define('Sage/UI/nls/af-za/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/af/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/af/UnconfirmedPane',{});
},
'Sage/UI/Alarms/nls/af-za/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/af-za/UnconfirmedPane',{});
},
'Sage/Utility/nls/af/Utility':function(){
define('Sage/Utility/nls/af/Utility',{});
},
'Sage/Utility/nls/af-za/Utility':function(){
define('Sage/Utility/nls/af-za/Utility',{});
},
'Sage/QuickForms/Design/nls/af/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af/ControlDesigner',{});
},
'Sage/QuickForms/Design/nls/af-za/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af-za/ControlDesigner',{});
},
'Sage/UI/Controls/nls/af/Address':function(){
define('Sage/UI/Controls/nls/af/Address',{});
},
'Sage/UI/Controls/nls/af-za/Address':function(){
define('Sage/UI/Controls/nls/af-za/Address',{});
},
'Sage/MainView/JobMgr/nls/af/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/af/JobManagerGroupContextService',{});
},
'Sage/MainView/JobMgr/nls/af-za/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/af-za/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/af/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/af/BaseListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/af-za/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/af-za/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/af/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af/OwnerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/af-za/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af-za/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/af/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/af/JobManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/af-za/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/af-za/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/af/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/af/ActivityEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/af-za/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/af-za/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/af/UserType':function(){
define('Sage/UI/nls/af/UserType',{});
},
'Sage/UI/nls/af-za/UserType':function(){
define('Sage/UI/nls/af-za/UserType',{});
},
'Sage/MainView/ReportMgr/templates/nls/af/HistoryDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/af/HistoryDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/af-za/HistoryDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/af-za/HistoryDetailSummary',{});
},
'Sage/QuickForms/Design/nls/af/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/af/FormDesigner',{});
},
'Sage/QuickForms/Design/nls/af-za/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/af-za/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/af/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/af/ActivityCalendar',{});
},
'Sage/MainView/ActivityMgr/nls/af-za/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/af-za/ActivityCalendar',{});
},
'Sage/Utility/nls/af/Jobs':function(){
define('Sage/Utility/nls/af/Jobs',{});
},
'Sage/Utility/nls/af-za/Jobs':function(){
define('Sage/Utility/nls/af-za/Jobs',{});
},
'Sage/UI/Controls/nls/af/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/af/_DialogHelpIconMixin',{});
},
'Sage/UI/Controls/nls/af-za/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/af-za/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/af/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/PickListAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/af-za/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af-za/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/af/ActivityList':function(){
define('Sage/UI/nls/af/ActivityList',{});
},
'Sage/UI/nls/af-za/ActivityList':function(){
define('Sage/UI/nls/af-za/ActivityList',{});
},
'Sage/UI/Alarms/nls/af/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/af/JobNotificationPopup',{});
},
'Sage/UI/Alarms/nls/af-za/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/af-za/JobNotificationPopup',{});
},
'Sage/MainView/JobMgr/templates/nls/af/ExecutionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/af/ExecutionsListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/af-za/ExecutionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/af-za/ExecutionsListSummary',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/af/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/af/LeadLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/af-za/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/af-za/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/af/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/af/SchedulesListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/af-za/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/af-za/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/af/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/GenericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/af-za/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af-za/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/af/CalendarUsersListPane':function(){
define('Sage/UI/nls/af/CalendarUsersListPane',{});
},
'Sage/UI/nls/af-za/CalendarUsersListPane':function(){
define('Sage/UI/nls/af-za/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/af/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/af-za/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af-za/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/af/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/ColumnBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/af-za/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af-za/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/templates/nls/af/ExecutionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/af/ExecutionDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/af-za/ExecutionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/af-za/ExecutionDetailSummary',{});
},
'Sage/MainView/ReportMgr/nls/af/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/af/ReportManagerGroupContextService',{});
},
'Sage/MainView/ReportMgr/nls/af-za/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/af-za/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/af/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/af/MatchingOptionsConfig',{});
},
'Sage/MainView/IntegrationContract/nls/af-za/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/af-za/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/af/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/FormBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/af-za/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af-za/FormBasicPropertyEditor',{});
},
'Sage/UI/Alarms/nls/af/AlarmButton':function(){
define('Sage/UI/Alarms/nls/af/AlarmButton',{});
},
'Sage/UI/Alarms/nls/af-za/AlarmButton':function(){
define('Sage/UI/Alarms/nls/af-za/AlarmButton',{});
},
'Sage/MainView/ActivityMgr/nls/af/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/af/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/MainView/ActivityMgr/nls/af-za/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/af-za/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/af/Attachment':function(){
define('Sage/Utility/File/nls/af/Attachment',{});
},
'Sage/Utility/File/nls/af-za/Attachment':function(){
define('Sage/Utility/File/nls/af-za/Attachment',{});
},
'Sage/QuickForms/Design/nls/af/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/af-za/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af-za/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/af/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/af/PropertyEditorContainer',{});
},
'Sage/QuickForms/Design/nls/af-za/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/af-za/PropertyEditorContainer',{});
},
'Sage/Services/nls/af/ReportingService':function(){
define('Sage/Services/nls/af/ReportingService',{});
},
'Sage/Services/nls/af-za/ReportingService':function(){
define('Sage/Services/nls/af-za/ReportingService',{});
},
'Sage/MailMerge/nls/af/Helper':function(){
define('Sage/MailMerge/nls/af/Helper',{});
},
'Sage/MailMerge/nls/af-za/Helper':function(){
define('Sage/MailMerge/nls/af-za/Helper',{});
},
'Sage/UI/Dashboard/nls/af/Dashboard':function(){
define('Sage/UI/Dashboard/nls/af/Dashboard',{});
},
'Sage/UI/Dashboard/nls/af-za/Dashboard':function(){
define('Sage/UI/Dashboard/nls/af-za/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/af/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/af/ActivityListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/af-za/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/af-za/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/af/PickList':function(){
define('Sage/UI/Controls/nls/af/PickList',{});
},
'Sage/UI/Controls/nls/af-za/PickList':function(){
define('Sage/UI/Controls/nls/af-za/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/af/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/af/HistoryEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/af-za/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/af-za/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/af/Email':function(){
define('Sage/Utility/nls/af/Email',{});
},
'Sage/Utility/nls/af-za/Email':function(){
define('Sage/Utility/nls/af-za/Email',{});
},
'Sage/TaskPane/nls/af/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/af/SecurityManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/af-za/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/af-za/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/af/TimeZoneItem':function(){
define('Sage/UI/nls/af/TimeZoneItem',{});
},
'Sage/UI/nls/af-za/TimeZoneItem':function(){
define('Sage/UI/nls/af-za/TimeZoneItem',{});
},
'Sage/MainView/ReportMgr/templates/nls/af/HistoryListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/af/HistoryListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/af-za/HistoryListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/af-za/HistoryListSummary',{});
},
'Sage/UI/Columns/nls/af/SlxEdit':function(){
define('Sage/UI/Columns/nls/af/SlxEdit',{});
},
'Sage/UI/Columns/nls/af-za/SlxEdit':function(){
define('Sage/UI/Columns/nls/af-za/SlxEdit',{});
},
'Sage/Reporting/nls/af/Enumerations':function(){
define('Sage/Reporting/nls/af/Enumerations',{});
},
'Sage/Reporting/nls/af-za/Enumerations':function(){
define('Sage/Reporting/nls/af-za/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/af/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/af-za/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af-za/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/af/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/af/CrystalReportConditionsDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/af-za/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/af-za/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/af/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/af/ActivityListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/af-za/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/af-za/ActivityListPanelConfig',{});
},
'Sage/UI/nls/af/JobSchedulingWidget':function(){
define('Sage/UI/nls/af/JobSchedulingWidget',{});
},
'Sage/UI/nls/af-za/JobSchedulingWidget':function(){
define('Sage/UI/nls/af-za/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/af/LogOffButton':function(){
define('Sage/UI/Controls/nls/af/LogOffButton',{});
},
'Sage/UI/Controls/nls/af-za/LogOffButton':function(){
define('Sage/UI/Controls/nls/af-za/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/af/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/TextBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/af-za/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af-za/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/af/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/af/EditEventEditor',{});
},
'Sage/MainView/ActivityMgr/nls/af-za/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/af-za/EditEventEditor',{});
},
'Sage/MailMerge/nls/af/Loader':function(){
define('Sage/MailMerge/nls/af/Loader',{});
},
'Sage/MailMerge/nls/af-za/Loader':function(){
define('Sage/MailMerge/nls/af-za/Loader',{});
},
'Sage/UI/Controls/nls/af/DateTimePicker':function(){
define('Sage/UI/Controls/nls/af/DateTimePicker',{});
},
'Sage/UI/Controls/nls/af-za/DateTimePicker':function(){
define('Sage/UI/Controls/nls/af-za/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/af/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/af/ReportManagerActions',{});
},
'Sage/MainView/ReportMgr/nls/af-za/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/af-za/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/af/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/af/AlarmPopup',{});
},
'Sage/UI/Alarms/nls/af-za/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/af-za/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/af/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/af/ContactUserAssociationEditor',{});
},
'Sage/MainView/Contact/nls/af-za/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/af-za/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/af/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/af-za/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af-za/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/af/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/af/BaseListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/af-za/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/af-za/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/af/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/af-za/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af-za/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/af/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af/EmailControlDesigner',{});
},
'Sage/QuickForms/Design/nls/af-za/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af-za/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/af/Lookup':function(){
define('Sage/UI/Controls/nls/af/Lookup',{});
},
'Sage/UI/Controls/nls/af-za/Lookup':function(){
define('Sage/UI/Controls/nls/af-za/Lookup',{});
},
'Sage/Utility/File/nls/af/DescriptionsForm':function(){
define('Sage/Utility/File/nls/af/DescriptionsForm',{});
},
'Sage/Utility/File/nls/af-za/DescriptionsForm':function(){
define('Sage/Utility/File/nls/af-za/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/af/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/NumericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/af-za/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af-za/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/af/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/af/CommonTasksTasklet',{});
},
'Sage/TaskPane/nls/af-za/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/af-za/CommonTasksTasklet',{});
},
'Sage/Utility/nls/af/Dashboard':function(){
define('Sage/Utility/nls/af/Dashboard',{});
},
'Sage/Utility/nls/af-za/Dashboard':function(){
define('Sage/Utility/nls/af-za/Dashboard',{});
}}});
define("Sage/nls/Sage_af-za", [], 1);
