require({cache:{
'Sage/Utility/File/nls/sx/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/sx/FallbackFilePicker',{});
},
'Sage/UI/nls/sx/Boolean':function(){
define('Sage/UI/nls/sx/Boolean',{});
},
'Sage/Services/nls/sx/ActivityService':function(){
define('Sage/Services/nls/sx/ActivityService',{});
},
'Sage/UI/Controls/nls/sx/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/sx/CopyToClipboard',{});
},
'Sage/Utility/nls/sx/Activity':function(){
define('Sage/Utility/nls/sx/Activity',{});
},
'Sage/QuickForms/Design/nls/sx/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/sx/DesignPanel',{});
},
'Sage/UI/nls/sx/TimelessActivitiesPane':function(){
define('Sage/UI/nls/sx/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/sx/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sx/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/sx/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/sx/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/sx/ActivityManager':function(){
define('Sage/MainView/nls/sx/ActivityManager',{});
},
'Sage/Services/nls/sx/JobService':function(){
define('Sage/Services/nls/sx/JobService',{});
},
'Sage/QuickForms/Design/nls/sx/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sx/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/sx/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sx/_PropertyEditor',{});
},
'Sage/Services/nls/sx/ActivityActionProcessor':function(){
define('Sage/Services/nls/sx/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/sx/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sx/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sx/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sx/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/templates/nls/sx/UserActivityDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/sx/UserActivityDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/sx/ConfirmationDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/sx/ConfirmationDetailSummary',{});
},
'Sage/Utility/File/nls/sx/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/sx/DefaultDropHandler',{});
},
'Sage/UI/nls/sx/TransferBoxWidget':function(){
define('Sage/UI/nls/sx/TransferBoxWidget',{});
},
'Sage/Utility/File/nls/sx/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/sx/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/sx/AlarmPane':function(){
define('Sage/UI/Alarms/nls/sx/AlarmPane',{});
},
'Sage/TaskPane/nls/sx/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/sx/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/sx/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/sx/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/sx/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sx/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/sx/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/sx/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/sx/FilterPanel':function(){
define('Sage/UI/Filters/nls/sx/FilterPanel',{});
},
'Sage/TaskPane/nls/sx/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/sx/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/sx/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/sx/ReportManagerFormatter',{});
},
'Sage/UI/nls/sx/OwnerType':function(){
define('Sage/UI/nls/sx/OwnerType',{});
},
'Sage/MainView/JobMgr/templates/nls/sx/JobDefinitionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/sx/JobDefinitionsListSummary',{});
},
'Sage/TaskPane/nls/sx/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/sx/LeadTasksTasklet',{});
},
'Sage/MainView/ReportMgr/templates/nls/sx/ReportDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/sx/ReportDetailSummary',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sx/_ParameterEditorBase':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sx/_ParameterEditorBase',{});
},
'Sage/MailMerge/nls/sx/Service':function(){
define('Sage/MailMerge/nls/sx/Service',{});
},
'Sage/MainView/ActivityMgr/templates/nls/sx/ConfirmationListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/sx/ConfirmationListSummary',{});
},
'Sage/MainView/ActivityMgr/nls/sx/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/sx/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/sx/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sx/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sx/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sx/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/sx/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/sx/InvoiceRTDV',{});
},
'Sage/UI/nls/sx/SDataLookup':function(){
define('Sage/UI/nls/sx/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/sx/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/sx/RowDesigner',{});
},
'Sage/Groups/nls/sx/GroupLookup':function(){
define('Sage/Groups/nls/sx/GroupLookup',{});
},
'Sage/TaskPane/nls/sx/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/sx/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/sx/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/sx/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/sx/LibraryDocument':function(){
define('Sage/Utility/File/nls/sx/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/sx/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/sx/SpeedSearchLookup',{});
},
'Sage/UI/nls/sx/ConditionManager':function(){
define('Sage/UI/nls/sx/ConditionManager',{});
},
'Sage/MainView/JobMgr/templates/nls/sx/SchedulesListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/sx/SchedulesListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/sx/UserActivityListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/sx/UserActivityListSummary',{});
},
'Sage/UI/Dashboard/nls/sx/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/sx/WidgetDefinition',{});
},
'Sage/MainView/ActivityMgr/templates/nls/sx/AllOpenListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/sx/AllOpenListSummary',{});
},
'Sage/UI/nls/sx/SearchConditionWidget':function(){
define('Sage/UI/nls/sx/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/sx/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sx/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/sx/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/sx/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/sx/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/sx/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/sx/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/sx/DataSourcePanel',{});
},
'Sage/MainView/ReportMgr/templates/nls/sx/SchedulesListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/sx/SchedulesListSummary',{});
},
'Sage/Library/nls/sx/Manager':function(){
define('Sage/Library/nls/sx/Manager',{});
},
'Sage/UI/nls/sx/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/sx/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/sx/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/sx/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/sx/Name':function(){
define('Sage/UI/Controls/nls/sx/Name',{});
},
'Sage/MainView/JobMgr/nls/sx/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/sx/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/sx/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sx/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/sx/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/sx/UpdateLeads',{});
},
'Sage/Library/nls/sx/FileHandler':function(){
define('Sage/Library/nls/sx/FileHandler',{});
},
'Sage/UI/nls/sx/ListPanel':function(){
define('Sage/UI/nls/sx/ListPanel',{});
},
'Sage/Utility/nls/sx/Sql':function(){
define('Sage/Utility/nls/sx/Sql',{});
},
'Sage/UI/Filters/nls/sx/EditFilters':function(){
define('Sage/UI/Filters/nls/sx/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/sx/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sx/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/sx/DurationSelect':function(){
define('Sage/UI/Controls/nls/sx/DurationSelect',{});
},
'Sage/UI/Alarms/nls/sx/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/sx/AlarmCountDown',{});
},
'Sage/UI/nls/sx/AttachmentList':function(){
define('Sage/UI/nls/sx/AttachmentList',{});
},
'Sage/MailMerge/nls/sx/Lookup':function(){
define('Sage/MailMerge/nls/sx/Lookup',{});
},
'Sage/QuickForms/Design/Editors/nls/sx/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sx/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/sx/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/sx/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/sx/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sx/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sx/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sx/EditableGridControlDesigner',{});
},
'Sage/MainView/Options/nls/sx/OptionsDialog':function(){
define('Sage/MainView/Options/nls/sx/OptionsDialog',{});
},
'Sage/QuickForms/Design/nls/sx/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sx/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/sx/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/sx/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/sx/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sx/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/sx/Dialogs':function(){
define('Sage/UI/nls/sx/Dialogs',{});
},
'Sage/MainView/IntegrationContract/nls/sx/SyncResultsHistory':function(){
define('Sage/MainView/IntegrationContract/nls/sx/SyncResultsHistory',{});
},
'Sage/TaskPane/nls/sx/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/sx/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/sx/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/sx/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/sx/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/sx/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/sx/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sx/UserControlDesigner',{});
},
'Sage/Groups/nls/sx/GroupNavigator':function(){
define('Sage/Groups/nls/sx/GroupNavigator',{});
},
'Sage/Utility/File/nls/sx/AddURLAttachment':function(){
define('Sage/Utility/File/nls/sx/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/sx/EditFilterItems':function(){
define('Sage/UI/Filters/nls/sx/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sx/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sx/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/sx/DragDropWatcher':function(){
define('Sage/Utility/File/nls/sx/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/sx/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/sx/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/sx/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sx/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/sx/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sx/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sx/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sx/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/sx/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/sx/AllOpenListPanelConfig',{});
},
'Sage/MainView/nls/sx/FormManager':function(){
define('Sage/MainView/nls/sx/FormManager',{});
},
'Sage/UI/nls/sx/ActivityScheduler':function(){
define('Sage/UI/nls/sx/ActivityScheduler',{});
},
'Sage/MainView/nls/sx/SecurityManager':function(){
define('Sage/MainView/nls/sx/SecurityManager',{});
},
'Sage/TaskPane/nls/sx/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/sx/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/sx/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/sx/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/sx/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/sx/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/templates/nls/sx/AllOpenDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/sx/AllOpenDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/sx/ReportsListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/sx/ReportsListSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/sx/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/sx/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/templates/nls/sx/ScheduleDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/sx/ScheduleDetailSummary',{});
},
'Sage/MainView/Opportunity/nls/sx/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/sx/UpdateOpportunities',{});
},
'Sage/UI/nls/sx/EditCalendarUsers':function(){
define('Sage/UI/nls/sx/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sx/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sx/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/sx/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sx/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/sx/HelpMenu':function(){
define('Sage/UI/Controls/nls/sx/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/sx/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sx/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/sx/UserTasklet':function(){
define('Sage/TaskPane/nls/sx/UserTasklet',{});
},
'Sage/UI/Alarms/nls/sx/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/sx/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/sx/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/sx/OpportunityStatistics',{});
},
'Sage/TaskPane/nls/sx/GroupListTasklet':function(){
define('Sage/TaskPane/nls/sx/GroupListTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sx/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sx/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/sx/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/sx/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/sx/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/sx/ColumnDesigner',{});
},
'Sage/MainView/JobMgr/templates/nls/sx/JobDefinitionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/sx/JobDefinitionDetailSummary',{});
},
'Sage/UI/nls/sx/SearchMenuItem':function(){
define('Sage/UI/nls/sx/SearchMenuItem',{});
},
'Sage/Library/nls/sx/DocumentProperties':function(){
define('Sage/Library/nls/sx/DocumentProperties',{});
},
'Sage/UI/nls/sx/NotesHistoryList':function(){
define('Sage/UI/nls/sx/NotesHistoryList',{});
},
'Sage/Utility/nls/sx/File':function(){
define('Sage/Utility/nls/sx/File',{});
},
'Sage/MainView/ReportMgr/nls/sx/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/sx/HistoryListPanelConfig',{});
},
'Sage/MainView/JobMgr/templates/nls/sx/ScheduleDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/sx/ScheduleDetailSummary',{});
},
'Sage/QuickForms/Design/nls/sx/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sx/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/sx/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/sx/ContactTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/templates/nls/sx/EventSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/sx/EventSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/sx/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/sx/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/sx/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/sx/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/sx/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/sx/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/sx/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sx/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/sx/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sx/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/sx/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sx/HistoryEditor',{});
},
'Sage/Groups/nls/sx/GroupManager':function(){
define('Sage/Groups/nls/sx/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/sx/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sx/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sx/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sx/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/sx/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/sx/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/sx/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/sx/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sx/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sx/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/sx/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/sx/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/sx/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sx/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sx/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sx/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/sx/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sx/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/sx/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/sx/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/sx/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sx/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sx/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sx/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sx/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sx/PickListControlDesigner',{});
},
'Sage/MainView/ActivityMgr/templates/nls/sx/LitRequestSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/sx/LitRequestSummary',{});
},
'Sage/QuickForms/Design/Editors/nls/sx/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sx/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/sx/FolderHandler':function(){
define('Sage/Library/nls/sx/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/sx/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sx/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/sx/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/sx/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/sx/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sx/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/sx/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/sx/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/sx/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sx/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sx/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sx/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/sx/EditableGrid':function(){
define('Sage/UI/nls/sx/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/sx/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/sx/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/sx/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/sx/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/sx/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/sx/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/sx/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sx/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/sx/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/sx/ReportManagerUtility',{});
},
'Sage/UI/nls/sx/SpeedSearch':function(){
define('Sage/UI/nls/sx/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/sx/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sx/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/sx/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/sx/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/sx/SLXPreviewGrid':function(){
define('Sage/UI/nls/sx/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/sx/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/sx/UnconfirmedPane',{});
},
'Sage/Utility/nls/sx/Utility':function(){
define('Sage/Utility/nls/sx/Utility',{});
},
'Sage/QuickForms/Design/nls/sx/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sx/ControlDesigner',{});
},
'Sage/UI/Controls/nls/sx/Address':function(){
define('Sage/UI/Controls/nls/sx/Address',{});
},
'Sage/MainView/JobMgr/nls/sx/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/sx/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/sx/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sx/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/sx/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sx/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/sx/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/sx/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/sx/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/sx/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/sx/UserType':function(){
define('Sage/UI/nls/sx/UserType',{});
},
'Sage/MainView/ReportMgr/templates/nls/sx/HistoryDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/sx/HistoryDetailSummary',{});
},
'Sage/QuickForms/Design/nls/sx/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/sx/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/sx/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/sx/ActivityCalendar',{});
},
'Sage/Utility/nls/sx/Jobs':function(){
define('Sage/Utility/nls/sx/Jobs',{});
},
'Sage/UI/Controls/nls/sx/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/sx/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/sx/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sx/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/sx/ActivityList':function(){
define('Sage/UI/nls/sx/ActivityList',{});
},
'Sage/UI/Alarms/nls/sx/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/sx/JobNotificationPopup',{});
},
'Sage/MainView/JobMgr/templates/nls/sx/ExecutionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/sx/ExecutionsListSummary',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/sx/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/sx/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/sx/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/sx/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/sx/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sx/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/sx/CalendarUsersListPane':function(){
define('Sage/UI/nls/sx/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/sx/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sx/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sx/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sx/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/templates/nls/sx/ExecutionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/sx/ExecutionDetailSummary',{});
},
'Sage/MainView/ReportMgr/nls/sx/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/sx/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/sx/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/sx/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/sx/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sx/FormBasicPropertyEditor',{});
},
'Sage/UI/Alarms/nls/sx/AlarmButton':function(){
define('Sage/UI/Alarms/nls/sx/AlarmButton',{});
},
'Sage/MainView/ActivityMgr/nls/sx/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/sx/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/sx/Attachment':function(){
define('Sage/Utility/File/nls/sx/Attachment',{});
},
'Sage/QuickForms/Design/nls/sx/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sx/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sx/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/sx/PropertyEditorContainer',{});
},
'Sage/Services/nls/sx/ReportingService':function(){
define('Sage/Services/nls/sx/ReportingService',{});
},
'Sage/MailMerge/nls/sx/Helper':function(){
define('Sage/MailMerge/nls/sx/Helper',{});
},
'Sage/UI/Dashboard/nls/sx/Dashboard':function(){
define('Sage/UI/Dashboard/nls/sx/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/sx/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sx/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/sx/PickList':function(){
define('Sage/UI/Controls/nls/sx/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/sx/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/sx/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/sx/Email':function(){
define('Sage/Utility/nls/sx/Email',{});
},
'Sage/TaskPane/nls/sx/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/sx/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/sx/TimeZoneItem':function(){
define('Sage/UI/nls/sx/TimeZoneItem',{});
},
'Sage/MainView/ReportMgr/templates/nls/sx/HistoryListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/sx/HistoryListSummary',{});
},
'Sage/UI/Columns/nls/sx/SlxEdit':function(){
define('Sage/UI/Columns/nls/sx/SlxEdit',{});
},
'Sage/Reporting/nls/sx/Enumerations':function(){
define('Sage/Reporting/nls/sx/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/sx/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sx/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sx/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sx/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/sx/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/sx/ActivityListPanelConfig',{});
},
'Sage/UI/nls/sx/JobSchedulingWidget':function(){
define('Sage/UI/nls/sx/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/sx/LogOffButton':function(){
define('Sage/UI/Controls/nls/sx/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/sx/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sx/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sx/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sx/EditEventEditor',{});
},
'Sage/MailMerge/nls/sx/Loader':function(){
define('Sage/MailMerge/nls/sx/Loader',{});
},
'Sage/UI/Controls/nls/sx/DateTimePicker':function(){
define('Sage/UI/Controls/nls/sx/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/sx/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/sx/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/sx/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/sx/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/sx/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/sx/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sx/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sx/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/sx/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/sx/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/sx/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sx/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sx/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sx/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/sx/Lookup':function(){
define('Sage/UI/Controls/nls/sx/Lookup',{});
},
'Sage/Utility/File/nls/sx/DescriptionsForm':function(){
define('Sage/Utility/File/nls/sx/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/sx/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sx/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/sx/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/sx/CommonTasksTasklet',{});
},
'Sage/Utility/nls/sx/Dashboard':function(){
define('Sage/Utility/nls/sx/Dashboard',{});
}}});
define("Sage/nls/Sage_sx", [], 1);
