require({cache:{
'Sage/Utility/File/nls/nb/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/nb/FallbackFilePicker',{});
},
'Sage/Utility/File/nls/nb-no/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/nb-no/FallbackFilePicker',{});
},
'Sage/UI/nls/nb/Boolean':function(){
define('Sage/UI/nls/nb/Boolean',{});
},
'Sage/UI/nls/nb-no/Boolean':function(){
define('Sage/UI/nls/nb-no/Boolean',{});
},
'Sage/Services/nls/nb/ActivityService':function(){
define('Sage/Services/nls/nb/ActivityService',{});
},
'Sage/Services/nls/nb-no/ActivityService':function(){
define('Sage/Services/nls/nb-no/ActivityService',{});
},
'Sage/UI/Controls/nls/nb/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/nb/CopyToClipboard',{});
},
'Sage/UI/Controls/nls/nb-no/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/nb-no/CopyToClipboard',{});
},
'Sage/Utility/nls/nb/Activity':function(){
define('Sage/Utility/nls/nb/Activity',{});
},
'Sage/Utility/nls/nb-no/Activity':function(){
define('Sage/Utility/nls/nb-no/Activity',{});
},
'Sage/QuickForms/Design/nls/nb/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/nb/DesignPanel',{});
},
'Sage/QuickForms/Design/nls/nb-no/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/nb-no/DesignPanel',{});
},
'Sage/UI/nls/nb/TimelessActivitiesPane':function(){
define('Sage/UI/nls/nb/TimelessActivitiesPane',{});
},
'Sage/UI/nls/nb-no/TimelessActivitiesPane':function(){
define('Sage/UI/nls/nb-no/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/nb/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/nb/ActivityEditor',{});
},
'Sage/MainView/ActivityMgr/nls/nb-no/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/nb-no/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/nb/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/nb/ContactUserAssociationEditor',{});
},
'Sage/TaskPane/User/nls/nb-no/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/nb-no/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/nb/ActivityManager':function(){
define('Sage/MainView/nls/nb/ActivityManager',{});
},
'Sage/MainView/nls/nb-no/ActivityManager':function(){
define('Sage/MainView/nls/nb-no/ActivityManager',{});
},
'Sage/Services/nls/nb/JobService':function(){
define('Sage/Services/nls/nb/JobService',{});
},
'Sage/Services/nls/nb-no/JobService':function(){
define('Sage/Services/nls/nb-no/JobService',{});
},
'Sage/QuickForms/Design/nls/nb/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nb-no/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb-no/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/_PropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nb-no/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb-no/_PropertyEditor',{});
},
'Sage/Services/nls/nb/ActivityActionProcessor':function(){
define('Sage/Services/nls/nb/ActivityActionProcessor',{});
},
'Sage/Services/nls/nb-no/ActivityActionProcessor':function(){
define('Sage/Services/nls/nb-no/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/TextBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nb-no/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb-no/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/nb/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/nb/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/nls/nb-no/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/nb-no/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/templates/nls/nb/UserActivityDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/nb/UserActivityDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/nb-no/UserActivityDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/nb-no/UserActivityDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/nb/ConfirmationDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/nb/ConfirmationDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/nb-no/ConfirmationDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/nb-no/ConfirmationDetailSummary',{});
},
'Sage/Utility/File/nls/nb/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/nb/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/nb-no/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/nb-no/DefaultDropHandler',{});
},
'Sage/UI/nls/nb/TransferBoxWidget':function(){
define('Sage/UI/nls/nb/TransferBoxWidget',{});
},
'Sage/UI/nls/nb-no/TransferBoxWidget':function(){
define('Sage/UI/nls/nb-no/TransferBoxWidget',{});
},
'Sage/Utility/File/nls/nb/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/nb/AttachmentPropertiesEditForm',{});
},
'Sage/Utility/File/nls/nb-no/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/nb-no/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/nb/AlarmPane':function(){
define('Sage/UI/Alarms/nls/nb/AlarmPane',{});
},
'Sage/UI/Alarms/nls/nb-no/AlarmPane':function(){
define('Sage/UI/Alarms/nls/nb-no/AlarmPane',{});
},
'Sage/TaskPane/nls/nb/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/nb/LiteratureManagementTasks',{});
},
'Sage/TaskPane/nls/nb-no/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/nb-no/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/nb/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/nb/DashboardWidget',{});
},
'Sage/UI/Dashboard/nls/nb-no/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/nb-no/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/NumericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nb-no/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb-no/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/nb/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/nb/CustomerPaymentsRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/nb-no/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/nb-no/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/nb/FilterPanel':function(){
define('Sage/UI/Filters/nls/nb/FilterPanel',{});
},
'Sage/UI/Filters/nls/nb-no/FilterPanel':function(){
define('Sage/UI/Filters/nls/nb-no/FilterPanel',{});
},
'Sage/TaskPane/nls/nb/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/nb/_BaseTaskPaneTasklet',{});
},
'Sage/TaskPane/nls/nb-no/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/nb-no/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/nb/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/nb/ReportManagerFormatter',{});
},
'Sage/MainView/ReportMgr/nls/nb-no/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/nb-no/ReportManagerFormatter',{});
},
'Sage/UI/nls/nb/OwnerType':function(){
define('Sage/UI/nls/nb/OwnerType',{});
},
'Sage/UI/nls/nb-no/OwnerType':function(){
define('Sage/UI/nls/nb-no/OwnerType',{});
},
'Sage/MainView/JobMgr/templates/nls/nb/JobDefinitionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/nb/JobDefinitionsListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/nb-no/JobDefinitionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/nb-no/JobDefinitionsListSummary',{});
},
'Sage/TaskPane/nls/nb/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/nb/LeadTasksTasklet',{});
},
'Sage/TaskPane/nls/nb-no/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/nb-no/LeadTasksTasklet',{});
},
'Sage/MainView/ReportMgr/templates/nls/nb/ReportDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/nb/ReportDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/nb-no/ReportDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/nb-no/ReportDetailSummary',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/nb/_ParameterEditorBase':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/nb/_ParameterEditorBase',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/nb-no/_ParameterEditorBase':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/nb-no/_ParameterEditorBase',{});
},
'Sage/MailMerge/nls/nb/Service':function(){
define('Sage/MailMerge/nls/nb/Service',{});
},
'Sage/MailMerge/nls/nb-no/Service':function(){
define('Sage/MailMerge/nls/nb-no/Service',{});
},
'Sage/MainView/ActivityMgr/templates/nls/nb/ConfirmationListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/nb/ConfirmationListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/nb-no/ConfirmationListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/nb-no/ConfirmationListSummary',{});
},
'Sage/MainView/ActivityMgr/nls/nb/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/nb/SnoozeOptions',{});
},
'Sage/MainView/ActivityMgr/nls/nb-no/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/nb-no/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nb-no/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb-no/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nb-no/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb-no/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/nb/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/nb/InvoiceRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/nb-no/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/nb-no/InvoiceRTDV',{});
},
'Sage/UI/nls/nb/SDataLookup':function(){
define('Sage/UI/nls/nb/SDataLookup',{});
},
'Sage/UI/nls/nb-no/SDataLookup':function(){
define('Sage/UI/nls/nb-no/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/nb/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/nb/RowDesigner',{});
},
'Sage/QuickForms/Design/nls/nb-no/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/nb-no/RowDesigner',{});
},
'Sage/Groups/nls/nb/GroupLookup':function(){
define('Sage/Groups/nls/nb/GroupLookup',{});
},
'Sage/Groups/nls/nb-no/GroupLookup':function(){
define('Sage/Groups/nls/nb-no/GroupLookup',{});
},
'Sage/TaskPane/nls/nb/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/nb/OpportunityTasksTasklet',{});
},
'Sage/TaskPane/nls/nb-no/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/nb-no/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/nb/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/nb/CheckBoxFilter',{});
},
'Sage/UI/Filters/nls/nb-no/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/nb-no/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/nb/LibraryDocument':function(){
define('Sage/Utility/File/nls/nb/LibraryDocument',{});
},
'Sage/Utility/File/nls/nb-no/LibraryDocument':function(){
define('Sage/Utility/File/nls/nb-no/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/nb/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/nb/SpeedSearchLookup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/nb-no/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/nb-no/SpeedSearchLookup',{});
},
'Sage/UI/nls/nb/ConditionManager':function(){
define('Sage/UI/nls/nb/ConditionManager',{});
},
'Sage/UI/nls/nb-no/ConditionManager':function(){
define('Sage/UI/nls/nb-no/ConditionManager',{});
},
'Sage/MainView/JobMgr/templates/nls/nb/SchedulesListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/nb/SchedulesListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/nb-no/SchedulesListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/nb-no/SchedulesListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/nb/UserActivityListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/nb/UserActivityListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/nb-no/UserActivityListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/nb-no/UserActivityListSummary',{});
},
'Sage/UI/Dashboard/nls/nb/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/nb/WidgetDefinition',{});
},
'Sage/UI/Dashboard/nls/nb-no/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/nb-no/WidgetDefinition',{});
},
'Sage/MainView/ActivityMgr/templates/nls/nb/AllOpenListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/nb/AllOpenListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/nb-no/AllOpenListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/nb-no/AllOpenListSummary',{});
},
'Sage/UI/nls/nb/SearchConditionWidget':function(){
define('Sage/UI/nls/nb/SearchConditionWidget',{});
},
'Sage/UI/nls/nb-no/SearchConditionWidget':function(){
define('Sage/UI/nls/nb-no/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nb-no/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb-no/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/nb/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/nb/JobManagerActions',{});
},
'Sage/MainView/JobMgr/nls/nb-no/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/nb-no/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/nb/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/nb/ContactLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/nb-no/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/nb-no/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/nb/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/nb/DataSourcePanel',{});
},
'Sage/QuickForms/Design/nls/nb-no/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/nb-no/DataSourcePanel',{});
},
'Sage/MainView/ReportMgr/templates/nls/nb/SchedulesListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/nb/SchedulesListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/nb-no/SchedulesListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/nb-no/SchedulesListSummary',{});
},
'Sage/Library/nls/nb/Manager':function(){
define('Sage/Library/nls/nb/Manager',{});
},
'Sage/Library/nls/nb-no/Manager':function(){
define('Sage/Library/nls/nb-no/Manager',{});
},
'Sage/UI/nls/nb/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/nb/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/nls/nb-no/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/nb-no/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/nb/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/nb/NonVisibleControlContainer',{});
},
'Sage/QuickForms/Design/nls/nb-no/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/nb-no/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/nb/Name':function(){
define('Sage/UI/Controls/nls/nb/Name',{});
},
'Sage/UI/Controls/nls/nb-no/Name':function(){
define('Sage/UI/Controls/nls/nb-no/Name',{});
},
'Sage/MainView/JobMgr/nls/nb/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/nb/ExecutionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/nb-no/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/nb-no/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/nb/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb/PhoneControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nb-no/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb-no/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/nb/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/nb/UpdateLeads',{});
},
'Sage/MainView/Lead/nls/nb-no/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/nb-no/UpdateLeads',{});
},
'Sage/Library/nls/nb/FileHandler':function(){
define('Sage/Library/nls/nb/FileHandler',{});
},
'Sage/Library/nls/nb-no/FileHandler':function(){
define('Sage/Library/nls/nb-no/FileHandler',{});
},
'Sage/UI/nls/nb/ListPanel':function(){
define('Sage/UI/nls/nb/ListPanel',{});
},
'Sage/UI/nls/nb-no/ListPanel':function(){
define('Sage/UI/nls/nb-no/ListPanel',{});
},
'Sage/Utility/nls/nb/Sql':function(){
define('Sage/Utility/nls/nb/Sql',{});
},
'Sage/Utility/nls/nb-no/Sql':function(){
define('Sage/Utility/nls/nb-no/Sql',{});
},
'Sage/UI/Filters/nls/nb/EditFilters':function(){
define('Sage/UI/Filters/nls/nb/EditFilters',{});
},
'Sage/UI/Filters/nls/nb-no/EditFilters':function(){
define('Sage/UI/Filters/nls/nb-no/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/FormUsagesPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nb-no/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb-no/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/nb/DurationSelect':function(){
define('Sage/UI/Controls/nls/nb/DurationSelect',{});
},
'Sage/UI/Controls/nls/nb-no/DurationSelect':function(){
define('Sage/UI/Controls/nls/nb-no/DurationSelect',{});
},
'Sage/UI/Alarms/nls/nb/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/nb/AlarmCountDown',{});
},
'Sage/UI/Alarms/nls/nb-no/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/nb-no/AlarmCountDown',{});
},
'Sage/UI/nls/nb/AttachmentList':function(){
define('Sage/UI/nls/nb/AttachmentList',{});
},
'Sage/UI/nls/nb-no/AttachmentList':function(){
define('Sage/UI/nls/nb-no/AttachmentList',{});
},
'Sage/MailMerge/nls/nb/Lookup':function(){
define('Sage/MailMerge/nls/nb/Lookup',{});
},
'Sage/MailMerge/nls/nb-no/Lookup':function(){
define('Sage/MailMerge/nls/nb-no/Lookup',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nb-no/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb-no/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/nb/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/nb/RunJobDialog',{});
},
'Sage/MainView/JobMgr/nls/nb-no/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/nb-no/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/nb/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nb-no/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb-no/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nb/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nb-no/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb-no/EditableGridControlDesigner',{});
},
'Sage/MainView/Options/nls/nb/OptionsDialog':function(){
define('Sage/MainView/Options/nls/nb/OptionsDialog',{});
},
'Sage/MainView/Options/nls/nb-no/OptionsDialog':function(){
define('Sage/MainView/Options/nls/nb-no/OptionsDialog',{});
},
'Sage/QuickForms/Design/nls/nb/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb/HiddenControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nb-no/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb-no/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/nb/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/nb/DashboardWidgetCell',{});
},
'Sage/UI/Dashboard/nls/nb-no/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/nb-no/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/UserBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nb-no/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb-no/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/nb/Dialogs':function(){
define('Sage/UI/nls/nb/Dialogs',{});
},
'Sage/UI/nls/nb-no/Dialogs':function(){
define('Sage/UI/nls/nb-no/Dialogs',{});
},
'Sage/MainView/IntegrationContract/nls/nb/SyncResultsHistory':function(){
define('Sage/MainView/IntegrationContract/nls/nb/SyncResultsHistory',{});
},
'Sage/MainView/IntegrationContract/nls/nb-no/SyncResultsHistory':function(){
define('Sage/MainView/IntegrationContract/nls/nb-no/SyncResultsHistory',{});
},
'Sage/TaskPane/nls/nb/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/nb/SecuredActionTasklet',{});
},
'Sage/TaskPane/nls/nb-no/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/nb-no/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/nb/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/nb/DashboardTabController',{});
},
'Sage/UI/Dashboard/nls/nb-no/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/nb-no/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/nb/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/nb/SalesOrderRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/nb-no/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/nb-no/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/nb/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb/UserControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nb-no/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb-no/UserControlDesigner',{});
},
'Sage/Groups/nls/nb/GroupNavigator':function(){
define('Sage/Groups/nls/nb/GroupNavigator',{});
},
'Sage/Groups/nls/nb-no/GroupNavigator':function(){
define('Sage/Groups/nls/nb-no/GroupNavigator',{});
},
'Sage/Utility/File/nls/nb/AddURLAttachment':function(){
define('Sage/Utility/File/nls/nb/AddURLAttachment',{});
},
'Sage/Utility/File/nls/nb-no/AddURLAttachment':function(){
define('Sage/Utility/File/nls/nb-no/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/nb/EditFilterItems':function(){
define('Sage/UI/Filters/nls/nb/EditFilterItems',{});
},
'Sage/UI/Filters/nls/nb-no/EditFilterItems':function(){
define('Sage/UI/Filters/nls/nb-no/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/nb/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/nb/CrystalReportsFormatter',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/nb-no/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/nb-no/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/nb/DragDropWatcher':function(){
define('Sage/Utility/File/nls/nb/DragDropWatcher',{});
},
'Sage/Utility/File/nls/nb-no/DragDropWatcher':function(){
define('Sage/Utility/File/nls/nb-no/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/nb/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/nb/DesignSurface',{});
},
'Sage/QuickForms/Design/nls/nb-no/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/nb-no/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/nb/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/nb/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/nb-no/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/nb-no/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/FormAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nb-no/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb-no/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/nb/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/nb/EventListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/nb-no/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/nb-no/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/nb/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/nb/AllOpenListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/nb-no/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/nb-no/AllOpenListPanelConfig',{});
},
'Sage/MainView/nls/nb/FormManager':function(){
define('Sage/MainView/nls/nb/FormManager',{});
},
'Sage/MainView/nls/nb-no/FormManager':function(){
define('Sage/MainView/nls/nb-no/FormManager',{});
},
'Sage/UI/nls/nb/ActivityScheduler':function(){
define('Sage/UI/nls/nb/ActivityScheduler',{});
},
'Sage/UI/nls/nb-no/ActivityScheduler':function(){
define('Sage/UI/nls/nb-no/ActivityScheduler',{});
},
'Sage/MainView/nls/nb/SecurityManager':function(){
define('Sage/MainView/nls/nb/SecurityManager',{});
},
'Sage/MainView/nls/nb-no/SecurityManager':function(){
define('Sage/MainView/nls/nb-no/SecurityManager',{});
},
'Sage/TaskPane/nls/nb/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/nb/ActivityTaskConfigurationProvider',{});
},
'Sage/TaskPane/nls/nb-no/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/nb-no/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/nb/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/nb/EntityInfoToolTip',{});
},
'Sage/UI/Controls/nls/nb-no/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/nb-no/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/nb/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/nb/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/nb-no/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/nb-no/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/templates/nls/nb/AllOpenDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/nb/AllOpenDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/nb-no/AllOpenDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/nb-no/AllOpenDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/nb/ReportsListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/nb/ReportsListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/nb-no/ReportsListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/nb-no/ReportsListSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/nb/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/nb/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/Common/nls/nb-no/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/nb-no/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/templates/nls/nb/ScheduleDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/nb/ScheduleDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/nb-no/ScheduleDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/nb-no/ScheduleDetailSummary',{});
},
'Sage/MainView/Opportunity/nls/nb/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/nb/UpdateOpportunities',{});
},
'Sage/MainView/Opportunity/nls/nb-no/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/nb-no/UpdateOpportunities',{});
},
'Sage/UI/nls/nb/EditCalendarUsers':function(){
define('Sage/UI/nls/nb/EditCalendarUsers',{});
},
'Sage/UI/nls/nb-no/EditCalendarUsers':function(){
define('Sage/UI/nls/nb-no/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/nb/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/nb/CrystalReportParametersDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/nb-no/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/nb-no/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/nb/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb/DateTimePickerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nb-no/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb-no/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/nb/HelpMenu':function(){
define('Sage/UI/Controls/nls/nb/HelpMenu',{});
},
'Sage/UI/Controls/nls/nb-no/HelpMenu':function(){
define('Sage/UI/Controls/nls/nb-no/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/LayoutPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nb-no/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb-no/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/nb/UserTasklet':function(){
define('Sage/TaskPane/nls/nb/UserTasklet',{});
},
'Sage/TaskPane/nls/nb-no/UserTasklet':function(){
define('Sage/TaskPane/nls/nb-no/UserTasklet',{});
},
'Sage/UI/Alarms/nls/nb/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/nb/ActivityAlarm',{});
},
'Sage/UI/Alarms/nls/nb-no/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/nb-no/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/nb/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/nb/OpportunityStatistics',{});
},
'Sage/MainView/Opportunity/nls/nb-no/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/nb-no/OpportunityStatistics',{});
},
'Sage/TaskPane/nls/nb/GroupListTasklet':function(){
define('Sage/TaskPane/nls/nb/GroupListTasklet',{});
},
'Sage/TaskPane/nls/nb-no/GroupListTasklet':function(){
define('Sage/TaskPane/nls/nb-no/GroupListTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/nb/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/nb/CrystalReportConditionEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/nb-no/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/nb-no/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/nb/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/nb/AdvancedSearchOptions',{});
},
'Sage/MainView/IntegrationContract/nls/nb-no/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/nb-no/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/nb/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/nb/ColumnDesigner',{});
},
'Sage/QuickForms/Design/nls/nb-no/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/nb-no/ColumnDesigner',{});
},
'Sage/MainView/JobMgr/templates/nls/nb/JobDefinitionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/nb/JobDefinitionDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/nb-no/JobDefinitionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/nb-no/JobDefinitionDetailSummary',{});
},
'Sage/UI/nls/nb/SearchMenuItem':function(){
define('Sage/UI/nls/nb/SearchMenuItem',{});
},
'Sage/UI/nls/nb-no/SearchMenuItem':function(){
define('Sage/UI/nls/nb-no/SearchMenuItem',{});
},
'Sage/Library/nls/nb/DocumentProperties':function(){
define('Sage/Library/nls/nb/DocumentProperties',{});
},
'Sage/Library/nls/nb-no/DocumentProperties':function(){
define('Sage/Library/nls/nb-no/DocumentProperties',{});
},
'Sage/UI/nls/nb/NotesHistoryList':function(){
define('Sage/UI/nls/nb/NotesHistoryList',{});
},
'Sage/UI/nls/nb-no/NotesHistoryList':function(){
define('Sage/UI/nls/nb-no/NotesHistoryList',{});
},
'Sage/Utility/nls/nb/File':function(){
define('Sage/Utility/nls/nb/File',{});
},
'Sage/Utility/nls/nb-no/File':function(){
define('Sage/Utility/nls/nb-no/File',{});
},
'Sage/MainView/ReportMgr/nls/nb/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/nb/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/nb-no/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/nb-no/HistoryListPanelConfig',{});
},
'Sage/MainView/JobMgr/templates/nls/nb/ScheduleDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/nb/ScheduleDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/nb-no/ScheduleDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/nb-no/ScheduleDetailSummary',{});
},
'Sage/QuickForms/Design/nls/nb/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb/UrlControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nb-no/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb-no/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/nb/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/nb/ContactTasksTasklet',{});
},
'Sage/TaskPane/nls/nb-no/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/nb-no/ContactTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/templates/nls/nb/EventSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/nb/EventSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/nb-no/EventSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/nb-no/EventSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/nb/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/nb/_WizardDialogBase',{});
},
'Sage/MainView/ReportMgr/Common/nls/nb-no/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/nb-no/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/nb/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/nb/SchedulesListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/nb-no/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/nb-no/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/nb/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/nb/GoogleDocPicker',{});
},
'Sage/Utility/File/nls/nb-no/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/nb-no/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/nb/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb/ComboBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nb-no/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb-no/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/nb/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/nb/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/nb-no/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/nb-no/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/nb/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/nb/HistoryEditor',{});
},
'Sage/MainView/ActivityMgr/nls/nb-no/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/nb-no/HistoryEditor',{});
},
'Sage/Groups/nls/nb/GroupManager':function(){
define('Sage/Groups/nls/nb/GroupManager',{});
},
'Sage/Groups/nls/nb-no/GroupManager':function(){
define('Sage/Groups/nls/nb-no/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nb-no/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb-no/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/ComboBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nb-no/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb-no/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/nb/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/nb/ReportsListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/nb-no/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/nb-no/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/nb/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/nb/JobNotificationButton',{});
},
'Sage/UI/Alarms/nls/nb-no/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/nb-no/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/nb/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/nb/CrystalReportWizardController',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/nb-no/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/nb-no/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/nb/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/nb/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/nb-no/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/nb-no/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/nb/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/nb/RecurringEditor',{});
},
'Sage/MainView/ActivityMgr/nls/nb-no/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/nb-no/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/nb/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/nb/CrystalReportsUtility',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/nb-no/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/nb-no/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nb-no/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb-no/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/nb/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/nb/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/nb-no/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/nb-no/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/nb/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nb-no/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb-no/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nb/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nb-no/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb-no/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nb/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nb-no/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb-no/PickListControlDesigner',{});
},
'Sage/MainView/ActivityMgr/templates/nls/nb/LitRequestSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/nb/LitRequestSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/nb-no/LitRequestSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/nb-no/LitRequestSummary',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nb-no/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb-no/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/nb/FolderHandler':function(){
define('Sage/Library/nls/nb/FolderHandler',{});
},
'Sage/Library/nls/nb-no/FolderHandler':function(){
define('Sage/Library/nls/nb-no/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nb-no/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb-no/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/nb/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/nb/ContactSearchForDuplicates',{});
},
'Sage/MainView/Contact/nls/nb-no/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/nb-no/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/DateTimePickerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nb-no/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb-no/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/nb/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/nb/AccountingTasksTasklet',{});
},
'Sage/TaskPane/nls/nb-no/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/nb-no/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nb-no/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb-no/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/CurrencyBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nb-no/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb-no/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/nb/EditableGrid':function(){
define('Sage/UI/nls/nb/EditableGrid',{});
},
'Sage/UI/nls/nb-no/EditableGrid':function(){
define('Sage/UI/nls/nb-no/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/nb/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/nb/SalesQuoteRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/nb-no/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/nb-no/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/nb/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/nb/SecurityProfile',{});
},
'Sage/MainView/SecurityMgr/nls/nb-no/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/nb-no/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/nb/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/nb/ReportWizardController',{});
},
'Sage/MainView/ReportMgr/nls/nb-no/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/nb-no/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/UserAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nb-no/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb-no/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/nb/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/nb/ReportManagerUtility',{});
},
'Sage/MainView/ReportMgr/nls/nb-no/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/nb-no/ReportManagerUtility',{});
},
'Sage/UI/nls/nb/SpeedSearch':function(){
define('Sage/UI/nls/nb/SpeedSearch',{});
},
'Sage/UI/nls/nb-no/SpeedSearch':function(){
define('Sage/UI/nls/nb-no/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/CurrencyAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nb-no/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb-no/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/nb/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/nb/ReportManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/nb-no/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/nb-no/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/nb/SLXPreviewGrid':function(){
define('Sage/UI/nls/nb/SLXPreviewGrid',{});
},
'Sage/UI/nls/nb-no/SLXPreviewGrid':function(){
define('Sage/UI/nls/nb-no/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/nb/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/nb/UnconfirmedPane',{});
},
'Sage/UI/Alarms/nls/nb-no/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/nb-no/UnconfirmedPane',{});
},
'Sage/Utility/nls/nb/Utility':function(){
define('Sage/Utility/nls/nb/Utility',{});
},
'Sage/Utility/nls/nb-no/Utility':function(){
define('Sage/Utility/nls/nb-no/Utility',{});
},
'Sage/QuickForms/Design/nls/nb/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb/ControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nb-no/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb-no/ControlDesigner',{});
},
'Sage/UI/Controls/nls/nb/Address':function(){
define('Sage/UI/Controls/nls/nb/Address',{});
},
'Sage/UI/Controls/nls/nb-no/Address':function(){
define('Sage/UI/Controls/nls/nb-no/Address',{});
},
'Sage/MainView/JobMgr/nls/nb/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/nb/JobManagerGroupContextService',{});
},
'Sage/MainView/JobMgr/nls/nb-no/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/nb-no/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/nb/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/nb/BaseListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/nb-no/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/nb-no/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/nb/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb/OwnerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nb-no/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb-no/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/nb/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/nb/JobManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/nb-no/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/nb-no/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/nb/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/nb/ActivityEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/nb-no/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/nb-no/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/nb/UserType':function(){
define('Sage/UI/nls/nb/UserType',{});
},
'Sage/UI/nls/nb-no/UserType':function(){
define('Sage/UI/nls/nb-no/UserType',{});
},
'Sage/MainView/ReportMgr/templates/nls/nb/HistoryDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/nb/HistoryDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/nb-no/HistoryDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/nb-no/HistoryDetailSummary',{});
},
'Sage/QuickForms/Design/nls/nb/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/nb/FormDesigner',{});
},
'Sage/QuickForms/Design/nls/nb-no/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/nb-no/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/nb/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/nb/ActivityCalendar',{});
},
'Sage/MainView/ActivityMgr/nls/nb-no/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/nb-no/ActivityCalendar',{});
},
'Sage/Utility/nls/nb/Jobs':function(){
define('Sage/Utility/nls/nb/Jobs',{});
},
'Sage/Utility/nls/nb-no/Jobs':function(){
define('Sage/Utility/nls/nb-no/Jobs',{});
},
'Sage/UI/Controls/nls/nb/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/nb/_DialogHelpIconMixin',{});
},
'Sage/UI/Controls/nls/nb-no/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/nb-no/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/PickListAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nb-no/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb-no/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/nb/ActivityList':function(){
define('Sage/UI/nls/nb/ActivityList',{});
},
'Sage/UI/nls/nb-no/ActivityList':function(){
define('Sage/UI/nls/nb-no/ActivityList',{});
},
'Sage/UI/Alarms/nls/nb/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/nb/JobNotificationPopup',{});
},
'Sage/UI/Alarms/nls/nb-no/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/nb-no/JobNotificationPopup',{});
},
'Sage/MainView/JobMgr/templates/nls/nb/ExecutionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/nb/ExecutionsListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/nb-no/ExecutionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/nb-no/ExecutionsListSummary',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/nb/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/nb/LeadLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/nb-no/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/nb-no/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/nb/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/nb/SchedulesListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/nb-no/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/nb-no/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/GenericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nb-no/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb-no/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/nb/CalendarUsersListPane':function(){
define('Sage/UI/nls/nb/CalendarUsersListPane',{});
},
'Sage/UI/nls/nb-no/CalendarUsersListPane':function(){
define('Sage/UI/nls/nb-no/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nb-no/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb-no/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/ColumnBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nb-no/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb-no/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/templates/nls/nb/ExecutionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/nb/ExecutionDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/nb-no/ExecutionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/nb-no/ExecutionDetailSummary',{});
},
'Sage/MainView/ReportMgr/nls/nb/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/nb/ReportManagerGroupContextService',{});
},
'Sage/MainView/ReportMgr/nls/nb-no/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/nb-no/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/nb/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/nb/MatchingOptionsConfig',{});
},
'Sage/MainView/IntegrationContract/nls/nb-no/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/nb-no/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/FormBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nb-no/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb-no/FormBasicPropertyEditor',{});
},
'Sage/UI/Alarms/nls/nb/AlarmButton':function(){
define('Sage/UI/Alarms/nls/nb/AlarmButton',{});
},
'Sage/UI/Alarms/nls/nb-no/AlarmButton':function(){
define('Sage/UI/Alarms/nls/nb-no/AlarmButton',{});
},
'Sage/MainView/ActivityMgr/nls/nb/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/nb/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/MainView/ActivityMgr/nls/nb-no/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/nb-no/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/nb/Attachment':function(){
define('Sage/Utility/File/nls/nb/Attachment',{});
},
'Sage/Utility/File/nls/nb-no/Attachment':function(){
define('Sage/Utility/File/nls/nb-no/Attachment',{});
},
'Sage/QuickForms/Design/nls/nb/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nb-no/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb-no/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nb/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/nb/PropertyEditorContainer',{});
},
'Sage/QuickForms/Design/nls/nb-no/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/nb-no/PropertyEditorContainer',{});
},
'Sage/Services/nls/nb/ReportingService':function(){
define('Sage/Services/nls/nb/ReportingService',{});
},
'Sage/Services/nls/nb-no/ReportingService':function(){
define('Sage/Services/nls/nb-no/ReportingService',{});
},
'Sage/MailMerge/nls/nb/Helper':function(){
define('Sage/MailMerge/nls/nb/Helper',{});
},
'Sage/MailMerge/nls/nb-no/Helper':function(){
define('Sage/MailMerge/nls/nb-no/Helper',{});
},
'Sage/UI/Dashboard/nls/nb/Dashboard':function(){
define('Sage/UI/Dashboard/nls/nb/Dashboard',{});
},
'Sage/UI/Dashboard/nls/nb-no/Dashboard':function(){
define('Sage/UI/Dashboard/nls/nb-no/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/nb/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/nb/ActivityListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/nb-no/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/nb-no/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/nb/PickList':function(){
define('Sage/UI/Controls/nls/nb/PickList',{});
},
'Sage/UI/Controls/nls/nb-no/PickList':function(){
define('Sage/UI/Controls/nls/nb-no/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/nb/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/nb/HistoryEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/nb-no/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/nb-no/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/nb/Email':function(){
define('Sage/Utility/nls/nb/Email',{});
},
'Sage/Utility/nls/nb-no/Email':function(){
define('Sage/Utility/nls/nb-no/Email',{});
},
'Sage/TaskPane/nls/nb/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/nb/SecurityManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/nb-no/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/nb-no/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/nb/TimeZoneItem':function(){
define('Sage/UI/nls/nb/TimeZoneItem',{});
},
'Sage/UI/nls/nb-no/TimeZoneItem':function(){
define('Sage/UI/nls/nb-no/TimeZoneItem',{});
},
'Sage/MainView/ReportMgr/templates/nls/nb/HistoryListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/nb/HistoryListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/nb-no/HistoryListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/nb-no/HistoryListSummary',{});
},
'Sage/UI/Columns/nls/nb/SlxEdit':function(){
define('Sage/UI/Columns/nls/nb/SlxEdit',{});
},
'Sage/UI/Columns/nls/nb-no/SlxEdit':function(){
define('Sage/UI/Columns/nls/nb-no/SlxEdit',{});
},
'Sage/Reporting/nls/nb/Enumerations':function(){
define('Sage/Reporting/nls/nb/Enumerations',{});
},
'Sage/Reporting/nls/nb-no/Enumerations':function(){
define('Sage/Reporting/nls/nb-no/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nb-no/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb-no/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/nb/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/nb/CrystalReportConditionsDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/nb-no/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/nb-no/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/nb/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/nb/ActivityListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/nb-no/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/nb-no/ActivityListPanelConfig',{});
},
'Sage/UI/nls/nb/JobSchedulingWidget':function(){
define('Sage/UI/nls/nb/JobSchedulingWidget',{});
},
'Sage/UI/nls/nb-no/JobSchedulingWidget':function(){
define('Sage/UI/nls/nb-no/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/nb/LogOffButton':function(){
define('Sage/UI/Controls/nls/nb/LogOffButton',{});
},
'Sage/UI/Controls/nls/nb-no/LogOffButton':function(){
define('Sage/UI/Controls/nls/nb-no/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/TextBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nb-no/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb-no/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/nb/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/nb/EditEventEditor',{});
},
'Sage/MainView/ActivityMgr/nls/nb-no/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/nb-no/EditEventEditor',{});
},
'Sage/MailMerge/nls/nb/Loader':function(){
define('Sage/MailMerge/nls/nb/Loader',{});
},
'Sage/MailMerge/nls/nb-no/Loader':function(){
define('Sage/MailMerge/nls/nb-no/Loader',{});
},
'Sage/UI/Controls/nls/nb/DateTimePicker':function(){
define('Sage/UI/Controls/nls/nb/DateTimePicker',{});
},
'Sage/UI/Controls/nls/nb-no/DateTimePicker':function(){
define('Sage/UI/Controls/nls/nb-no/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/nb/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/nb/ReportManagerActions',{});
},
'Sage/MainView/ReportMgr/nls/nb-no/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/nb-no/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/nb/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/nb/AlarmPopup',{});
},
'Sage/UI/Alarms/nls/nb-no/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/nb-no/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/nb/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/nb/ContactUserAssociationEditor',{});
},
'Sage/MainView/Contact/nls/nb-no/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/nb-no/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nb-no/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb-no/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/nb/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/nb/BaseListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/nb-no/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/nb-no/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/nb/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nb-no/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb-no/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nb/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb/EmailControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nb-no/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb-no/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/nb/Lookup':function(){
define('Sage/UI/Controls/nls/nb/Lookup',{});
},
'Sage/UI/Controls/nls/nb-no/Lookup':function(){
define('Sage/UI/Controls/nls/nb-no/Lookup',{});
},
'Sage/Utility/File/nls/nb/DescriptionsForm':function(){
define('Sage/Utility/File/nls/nb/DescriptionsForm',{});
},
'Sage/Utility/File/nls/nb-no/DescriptionsForm':function(){
define('Sage/Utility/File/nls/nb-no/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/NumericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nb-no/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb-no/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/nb/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/nb/CommonTasksTasklet',{});
},
'Sage/TaskPane/nls/nb-no/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/nb-no/CommonTasksTasklet',{});
},
'Sage/Utility/nls/nb/Dashboard':function(){
define('Sage/Utility/nls/nb/Dashboard',{});
},
'Sage/Utility/nls/nb-no/Dashboard':function(){
define('Sage/Utility/nls/nb-no/Dashboard',{});
}}});
define("Sage/nls/Sage_nb-no", [], 1);
