require({cache:{
'Sage/Utility/File/nls/kk/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/kk/FallbackFilePicker',{});
},
'Sage/Utility/File/nls/kk-kz/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/kk-kz/FallbackFilePicker',{});
},
'Sage/UI/nls/kk/Boolean':function(){
define('Sage/UI/nls/kk/Boolean',{});
},
'Sage/UI/nls/kk-kz/Boolean':function(){
define('Sage/UI/nls/kk-kz/Boolean',{});
},
'Sage/Services/nls/kk/ActivityService':function(){
define('Sage/Services/nls/kk/ActivityService',{});
},
'Sage/Services/nls/kk-kz/ActivityService':function(){
define('Sage/Services/nls/kk-kz/ActivityService',{});
},
'Sage/UI/Controls/nls/kk/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/kk/CopyToClipboard',{});
},
'Sage/UI/Controls/nls/kk-kz/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/kk-kz/CopyToClipboard',{});
},
'Sage/Utility/nls/kk/Activity':function(){
define('Sage/Utility/nls/kk/Activity',{});
},
'Sage/Utility/nls/kk-kz/Activity':function(){
define('Sage/Utility/nls/kk-kz/Activity',{});
},
'Sage/QuickForms/Design/nls/kk/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/kk/DesignPanel',{});
},
'Sage/QuickForms/Design/nls/kk-kz/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/kk-kz/DesignPanel',{});
},
'Sage/UI/nls/kk/TimelessActivitiesPane':function(){
define('Sage/UI/nls/kk/TimelessActivitiesPane',{});
},
'Sage/UI/nls/kk-kz/TimelessActivitiesPane':function(){
define('Sage/UI/nls/kk-kz/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/kk/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/kk/ActivityEditor',{});
},
'Sage/MainView/ActivityMgr/nls/kk-kz/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/kk-kz/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/kk/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/kk/ContactUserAssociationEditor',{});
},
'Sage/TaskPane/User/nls/kk-kz/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/kk-kz/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/kk/ActivityManager':function(){
define('Sage/MainView/nls/kk/ActivityManager',{});
},
'Sage/MainView/nls/kk-kz/ActivityManager':function(){
define('Sage/MainView/nls/kk-kz/ActivityManager',{});
},
'Sage/Services/nls/kk/JobService':function(){
define('Sage/Services/nls/kk/JobService',{});
},
'Sage/Services/nls/kk-kz/JobService':function(){
define('Sage/Services/nls/kk-kz/JobService',{});
},
'Sage/QuickForms/Design/nls/kk/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/kk-kz/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk-kz/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/_PropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk-kz/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk-kz/_PropertyEditor',{});
},
'Sage/Services/nls/kk/ActivityActionProcessor':function(){
define('Sage/Services/nls/kk/ActivityActionProcessor',{});
},
'Sage/Services/nls/kk-kz/ActivityActionProcessor':function(){
define('Sage/Services/nls/kk-kz/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/TextBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk-kz/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk-kz/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/kk/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/kk/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/nls/kk-kz/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/kk-kz/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/templates/nls/kk/UserActivityDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/kk/UserActivityDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/kk-kz/UserActivityDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/kk-kz/UserActivityDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/kk/ConfirmationDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/kk/ConfirmationDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/kk-kz/ConfirmationDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/kk-kz/ConfirmationDetailSummary',{});
},
'Sage/Utility/File/nls/kk/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/kk/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/kk-kz/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/kk-kz/DefaultDropHandler',{});
},
'Sage/UI/nls/kk/TransferBoxWidget':function(){
define('Sage/UI/nls/kk/TransferBoxWidget',{});
},
'Sage/UI/nls/kk-kz/TransferBoxWidget':function(){
define('Sage/UI/nls/kk-kz/TransferBoxWidget',{});
},
'Sage/Utility/File/nls/kk/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/kk/AttachmentPropertiesEditForm',{});
},
'Sage/Utility/File/nls/kk-kz/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/kk-kz/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/kk/AlarmPane':function(){
define('Sage/UI/Alarms/nls/kk/AlarmPane',{});
},
'Sage/UI/Alarms/nls/kk-kz/AlarmPane':function(){
define('Sage/UI/Alarms/nls/kk-kz/AlarmPane',{});
},
'Sage/TaskPane/nls/kk/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/kk/LiteratureManagementTasks',{});
},
'Sage/TaskPane/nls/kk-kz/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/kk-kz/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/kk/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/kk/DashboardWidget',{});
},
'Sage/UI/Dashboard/nls/kk-kz/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/kk-kz/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/NumericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk-kz/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk-kz/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/kk/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/kk/CustomerPaymentsRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/kk-kz/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/kk-kz/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/kk/FilterPanel':function(){
define('Sage/UI/Filters/nls/kk/FilterPanel',{});
},
'Sage/UI/Filters/nls/kk-kz/FilterPanel':function(){
define('Sage/UI/Filters/nls/kk-kz/FilterPanel',{});
},
'Sage/TaskPane/nls/kk/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/kk/_BaseTaskPaneTasklet',{});
},
'Sage/TaskPane/nls/kk-kz/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/kk-kz/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/kk/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/kk/ReportManagerFormatter',{});
},
'Sage/MainView/ReportMgr/nls/kk-kz/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/kk-kz/ReportManagerFormatter',{});
},
'Sage/UI/nls/kk/OwnerType':function(){
define('Sage/UI/nls/kk/OwnerType',{});
},
'Sage/UI/nls/kk-kz/OwnerType':function(){
define('Sage/UI/nls/kk-kz/OwnerType',{});
},
'Sage/MainView/JobMgr/templates/nls/kk/JobDefinitionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/kk/JobDefinitionsListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/kk-kz/JobDefinitionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/kk-kz/JobDefinitionsListSummary',{});
},
'Sage/TaskPane/nls/kk/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/kk/LeadTasksTasklet',{});
},
'Sage/TaskPane/nls/kk-kz/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/kk-kz/LeadTasksTasklet',{});
},
'Sage/MainView/ReportMgr/templates/nls/kk/ReportDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/kk/ReportDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/kk-kz/ReportDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/kk-kz/ReportDetailSummary',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/kk/_ParameterEditorBase':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/kk/_ParameterEditorBase',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/kk-kz/_ParameterEditorBase':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/kk-kz/_ParameterEditorBase',{});
},
'Sage/MailMerge/nls/kk/Service':function(){
define('Sage/MailMerge/nls/kk/Service',{});
},
'Sage/MailMerge/nls/kk-kz/Service':function(){
define('Sage/MailMerge/nls/kk-kz/Service',{});
},
'Sage/MainView/ActivityMgr/templates/nls/kk/ConfirmationListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/kk/ConfirmationListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/kk-kz/ConfirmationListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/kk-kz/ConfirmationListSummary',{});
},
'Sage/MainView/ActivityMgr/nls/kk/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/kk/SnoozeOptions',{});
},
'Sage/MainView/ActivityMgr/nls/kk-kz/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/kk-kz/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk-kz/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk-kz/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk-kz/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk-kz/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/kk/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/kk/InvoiceRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/kk-kz/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/kk-kz/InvoiceRTDV',{});
},
'Sage/UI/nls/kk/SDataLookup':function(){
define('Sage/UI/nls/kk/SDataLookup',{});
},
'Sage/UI/nls/kk-kz/SDataLookup':function(){
define('Sage/UI/nls/kk-kz/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/kk/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/RowDesigner',{});
},
'Sage/QuickForms/Design/nls/kk-kz/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/kk-kz/RowDesigner',{});
},
'Sage/Groups/nls/kk/GroupLookup':function(){
define('Sage/Groups/nls/kk/GroupLookup',{});
},
'Sage/Groups/nls/kk-kz/GroupLookup':function(){
define('Sage/Groups/nls/kk-kz/GroupLookup',{});
},
'Sage/TaskPane/nls/kk/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/kk/OpportunityTasksTasklet',{});
},
'Sage/TaskPane/nls/kk-kz/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/kk-kz/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/kk/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/kk/CheckBoxFilter',{});
},
'Sage/UI/Filters/nls/kk-kz/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/kk-kz/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/kk/LibraryDocument':function(){
define('Sage/Utility/File/nls/kk/LibraryDocument',{});
},
'Sage/Utility/File/nls/kk-kz/LibraryDocument':function(){
define('Sage/Utility/File/nls/kk-kz/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/kk/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/kk/SpeedSearchLookup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/kk-kz/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/kk-kz/SpeedSearchLookup',{});
},
'Sage/UI/nls/kk/ConditionManager':function(){
define('Sage/UI/nls/kk/ConditionManager',{});
},
'Sage/UI/nls/kk-kz/ConditionManager':function(){
define('Sage/UI/nls/kk-kz/ConditionManager',{});
},
'Sage/MainView/JobMgr/templates/nls/kk/SchedulesListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/kk/SchedulesListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/kk-kz/SchedulesListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/kk-kz/SchedulesListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/kk/UserActivityListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/kk/UserActivityListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/kk-kz/UserActivityListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/kk-kz/UserActivityListSummary',{});
},
'Sage/UI/Dashboard/nls/kk/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/kk/WidgetDefinition',{});
},
'Sage/UI/Dashboard/nls/kk-kz/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/kk-kz/WidgetDefinition',{});
},
'Sage/MainView/ActivityMgr/templates/nls/kk/AllOpenListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/kk/AllOpenListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/kk-kz/AllOpenListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/kk-kz/AllOpenListSummary',{});
},
'Sage/UI/nls/kk/SearchConditionWidget':function(){
define('Sage/UI/nls/kk/SearchConditionWidget',{});
},
'Sage/UI/nls/kk-kz/SearchConditionWidget':function(){
define('Sage/UI/nls/kk-kz/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk-kz/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk-kz/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/kk/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/kk/JobManagerActions',{});
},
'Sage/MainView/JobMgr/nls/kk-kz/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/kk-kz/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/kk/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/kk/ContactLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/kk-kz/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/kk-kz/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/kk/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/kk/DataSourcePanel',{});
},
'Sage/QuickForms/Design/nls/kk-kz/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/kk-kz/DataSourcePanel',{});
},
'Sage/MainView/ReportMgr/templates/nls/kk/SchedulesListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/kk/SchedulesListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/kk-kz/SchedulesListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/kk-kz/SchedulesListSummary',{});
},
'Sage/Library/nls/kk/Manager':function(){
define('Sage/Library/nls/kk/Manager',{});
},
'Sage/Library/nls/kk-kz/Manager':function(){
define('Sage/Library/nls/kk-kz/Manager',{});
},
'Sage/UI/nls/kk/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/kk/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/nls/kk-kz/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/kk-kz/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/kk/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/kk/NonVisibleControlContainer',{});
},
'Sage/QuickForms/Design/nls/kk-kz/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/kk-kz/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/kk/Name':function(){
define('Sage/UI/Controls/nls/kk/Name',{});
},
'Sage/UI/Controls/nls/kk-kz/Name':function(){
define('Sage/UI/Controls/nls/kk-kz/Name',{});
},
'Sage/MainView/JobMgr/nls/kk/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/kk/ExecutionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/kk-kz/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/kk-kz/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/kk/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/PhoneControlDesigner',{});
},
'Sage/QuickForms/Design/nls/kk-kz/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk-kz/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/kk/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/kk/UpdateLeads',{});
},
'Sage/MainView/Lead/nls/kk-kz/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/kk-kz/UpdateLeads',{});
},
'Sage/Library/nls/kk/FileHandler':function(){
define('Sage/Library/nls/kk/FileHandler',{});
},
'Sage/Library/nls/kk-kz/FileHandler':function(){
define('Sage/Library/nls/kk-kz/FileHandler',{});
},
'Sage/UI/nls/kk/ListPanel':function(){
define('Sage/UI/nls/kk/ListPanel',{});
},
'Sage/UI/nls/kk-kz/ListPanel':function(){
define('Sage/UI/nls/kk-kz/ListPanel',{});
},
'Sage/Utility/nls/kk/Sql':function(){
define('Sage/Utility/nls/kk/Sql',{});
},
'Sage/Utility/nls/kk-kz/Sql':function(){
define('Sage/Utility/nls/kk-kz/Sql',{});
},
'Sage/UI/Filters/nls/kk/EditFilters':function(){
define('Sage/UI/Filters/nls/kk/EditFilters',{});
},
'Sage/UI/Filters/nls/kk-kz/EditFilters':function(){
define('Sage/UI/Filters/nls/kk-kz/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/FormUsagesPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk-kz/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk-kz/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/kk/DurationSelect':function(){
define('Sage/UI/Controls/nls/kk/DurationSelect',{});
},
'Sage/UI/Controls/nls/kk-kz/DurationSelect':function(){
define('Sage/UI/Controls/nls/kk-kz/DurationSelect',{});
},
'Sage/UI/Alarms/nls/kk/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/kk/AlarmCountDown',{});
},
'Sage/UI/Alarms/nls/kk-kz/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/kk-kz/AlarmCountDown',{});
},
'Sage/UI/nls/kk/AttachmentList':function(){
define('Sage/UI/nls/kk/AttachmentList',{});
},
'Sage/UI/nls/kk-kz/AttachmentList':function(){
define('Sage/UI/nls/kk-kz/AttachmentList',{});
},
'Sage/MailMerge/nls/kk/Lookup':function(){
define('Sage/MailMerge/nls/kk/Lookup',{});
},
'Sage/MailMerge/nls/kk-kz/Lookup':function(){
define('Sage/MailMerge/nls/kk-kz/Lookup',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk-kz/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk-kz/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/kk/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/kk/RunJobDialog',{});
},
'Sage/MainView/JobMgr/nls/kk-kz/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/kk-kz/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/kk/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/kk-kz/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk-kz/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/kk/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/kk-kz/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk-kz/EditableGridControlDesigner',{});
},
'Sage/MainView/Options/nls/kk/OptionsDialog':function(){
define('Sage/MainView/Options/nls/kk/OptionsDialog',{});
},
'Sage/MainView/Options/nls/kk-kz/OptionsDialog':function(){
define('Sage/MainView/Options/nls/kk-kz/OptionsDialog',{});
},
'Sage/QuickForms/Design/nls/kk/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/HiddenControlDesigner',{});
},
'Sage/QuickForms/Design/nls/kk-kz/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk-kz/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/kk/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/kk/DashboardWidgetCell',{});
},
'Sage/UI/Dashboard/nls/kk-kz/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/kk-kz/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/UserBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk-kz/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk-kz/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/kk/Dialogs':function(){
define('Sage/UI/nls/kk/Dialogs',{});
},
'Sage/UI/nls/kk-kz/Dialogs':function(){
define('Sage/UI/nls/kk-kz/Dialogs',{});
},
'Sage/MainView/IntegrationContract/nls/kk/SyncResultsHistory':function(){
define('Sage/MainView/IntegrationContract/nls/kk/SyncResultsHistory',{});
},
'Sage/MainView/IntegrationContract/nls/kk-kz/SyncResultsHistory':function(){
define('Sage/MainView/IntegrationContract/nls/kk-kz/SyncResultsHistory',{});
},
'Sage/TaskPane/nls/kk/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/kk/SecuredActionTasklet',{});
},
'Sage/TaskPane/nls/kk-kz/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/kk-kz/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/kk/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/kk/DashboardTabController',{});
},
'Sage/UI/Dashboard/nls/kk-kz/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/kk-kz/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/kk/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/kk/SalesOrderRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/kk-kz/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/kk-kz/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/kk/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/UserControlDesigner',{});
},
'Sage/QuickForms/Design/nls/kk-kz/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk-kz/UserControlDesigner',{});
},
'Sage/Groups/nls/kk/GroupNavigator':function(){
define('Sage/Groups/nls/kk/GroupNavigator',{});
},
'Sage/Groups/nls/kk-kz/GroupNavigator':function(){
define('Sage/Groups/nls/kk-kz/GroupNavigator',{});
},
'Sage/Utility/File/nls/kk/AddURLAttachment':function(){
define('Sage/Utility/File/nls/kk/AddURLAttachment',{});
},
'Sage/Utility/File/nls/kk-kz/AddURLAttachment':function(){
define('Sage/Utility/File/nls/kk-kz/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/kk/EditFilterItems':function(){
define('Sage/UI/Filters/nls/kk/EditFilterItems',{});
},
'Sage/UI/Filters/nls/kk-kz/EditFilterItems':function(){
define('Sage/UI/Filters/nls/kk-kz/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/kk/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/kk/CrystalReportsFormatter',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/kk-kz/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/kk-kz/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/kk/DragDropWatcher':function(){
define('Sage/Utility/File/nls/kk/DragDropWatcher',{});
},
'Sage/Utility/File/nls/kk-kz/DragDropWatcher':function(){
define('Sage/Utility/File/nls/kk-kz/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/kk/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/kk/DesignSurface',{});
},
'Sage/QuickForms/Design/nls/kk-kz/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/kk-kz/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/kk/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/kk/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/kk-kz/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/kk-kz/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/FormAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk-kz/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk-kz/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/kk/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/kk/EventListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/kk-kz/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/kk-kz/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/kk/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/kk/AllOpenListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/kk-kz/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/kk-kz/AllOpenListPanelConfig',{});
},
'Sage/MainView/nls/kk/FormManager':function(){
define('Sage/MainView/nls/kk/FormManager',{});
},
'Sage/MainView/nls/kk-kz/FormManager':function(){
define('Sage/MainView/nls/kk-kz/FormManager',{});
},
'Sage/UI/nls/kk/ActivityScheduler':function(){
define('Sage/UI/nls/kk/ActivityScheduler',{});
},
'Sage/UI/nls/kk-kz/ActivityScheduler':function(){
define('Sage/UI/nls/kk-kz/ActivityScheduler',{});
},
'Sage/MainView/nls/kk/SecurityManager':function(){
define('Sage/MainView/nls/kk/SecurityManager',{});
},
'Sage/MainView/nls/kk-kz/SecurityManager':function(){
define('Sage/MainView/nls/kk-kz/SecurityManager',{});
},
'Sage/TaskPane/nls/kk/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/kk/ActivityTaskConfigurationProvider',{});
},
'Sage/TaskPane/nls/kk-kz/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/kk-kz/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/kk/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/kk/EntityInfoToolTip',{});
},
'Sage/UI/Controls/nls/kk-kz/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/kk-kz/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/kk/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/kk/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/kk-kz/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/kk-kz/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/templates/nls/kk/AllOpenDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/kk/AllOpenDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/kk-kz/AllOpenDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/kk-kz/AllOpenDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/kk/ReportsListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/kk/ReportsListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/kk-kz/ReportsListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/kk-kz/ReportsListSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/kk/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/kk/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/Common/nls/kk-kz/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/kk-kz/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/templates/nls/kk/ScheduleDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/kk/ScheduleDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/kk-kz/ScheduleDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/kk-kz/ScheduleDetailSummary',{});
},
'Sage/MainView/Opportunity/nls/kk/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/kk/UpdateOpportunities',{});
},
'Sage/MainView/Opportunity/nls/kk-kz/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/kk-kz/UpdateOpportunities',{});
},
'Sage/UI/nls/kk/EditCalendarUsers':function(){
define('Sage/UI/nls/kk/EditCalendarUsers',{});
},
'Sage/UI/nls/kk-kz/EditCalendarUsers':function(){
define('Sage/UI/nls/kk-kz/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/kk/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/kk/CrystalReportParametersDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/kk-kz/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/kk-kz/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/kk/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/DateTimePickerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/kk-kz/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk-kz/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/kk/HelpMenu':function(){
define('Sage/UI/Controls/nls/kk/HelpMenu',{});
},
'Sage/UI/Controls/nls/kk-kz/HelpMenu':function(){
define('Sage/UI/Controls/nls/kk-kz/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/LayoutPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk-kz/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk-kz/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/kk/UserTasklet':function(){
define('Sage/TaskPane/nls/kk/UserTasklet',{});
},
'Sage/TaskPane/nls/kk-kz/UserTasklet':function(){
define('Sage/TaskPane/nls/kk-kz/UserTasklet',{});
},
'Sage/UI/Alarms/nls/kk/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/kk/ActivityAlarm',{});
},
'Sage/UI/Alarms/nls/kk-kz/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/kk-kz/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/kk/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/kk/OpportunityStatistics',{});
},
'Sage/MainView/Opportunity/nls/kk-kz/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/kk-kz/OpportunityStatistics',{});
},
'Sage/TaskPane/nls/kk/GroupListTasklet':function(){
define('Sage/TaskPane/nls/kk/GroupListTasklet',{});
},
'Sage/TaskPane/nls/kk-kz/GroupListTasklet':function(){
define('Sage/TaskPane/nls/kk-kz/GroupListTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/kk/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/kk/CrystalReportConditionEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/kk-kz/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/kk-kz/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/kk/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/kk/AdvancedSearchOptions',{});
},
'Sage/MainView/IntegrationContract/nls/kk-kz/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/kk-kz/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/kk/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/ColumnDesigner',{});
},
'Sage/QuickForms/Design/nls/kk-kz/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/kk-kz/ColumnDesigner',{});
},
'Sage/MainView/JobMgr/templates/nls/kk/JobDefinitionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/kk/JobDefinitionDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/kk-kz/JobDefinitionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/kk-kz/JobDefinitionDetailSummary',{});
},
'Sage/UI/nls/kk/SearchMenuItem':function(){
define('Sage/UI/nls/kk/SearchMenuItem',{});
},
'Sage/UI/nls/kk-kz/SearchMenuItem':function(){
define('Sage/UI/nls/kk-kz/SearchMenuItem',{});
},
'Sage/Library/nls/kk/DocumentProperties':function(){
define('Sage/Library/nls/kk/DocumentProperties',{});
},
'Sage/Library/nls/kk-kz/DocumentProperties':function(){
define('Sage/Library/nls/kk-kz/DocumentProperties',{});
},
'Sage/UI/nls/kk/NotesHistoryList':function(){
define('Sage/UI/nls/kk/NotesHistoryList',{});
},
'Sage/UI/nls/kk-kz/NotesHistoryList':function(){
define('Sage/UI/nls/kk-kz/NotesHistoryList',{});
},
'Sage/Utility/nls/kk/File':function(){
define('Sage/Utility/nls/kk/File',{});
},
'Sage/Utility/nls/kk-kz/File':function(){
define('Sage/Utility/nls/kk-kz/File',{});
},
'Sage/MainView/ReportMgr/nls/kk/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/kk/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/kk-kz/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/kk-kz/HistoryListPanelConfig',{});
},
'Sage/MainView/JobMgr/templates/nls/kk/ScheduleDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/kk/ScheduleDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/kk-kz/ScheduleDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/kk-kz/ScheduleDetailSummary',{});
},
'Sage/QuickForms/Design/nls/kk/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/UrlControlDesigner',{});
},
'Sage/QuickForms/Design/nls/kk-kz/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk-kz/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/kk/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/kk/ContactTasksTasklet',{});
},
'Sage/TaskPane/nls/kk-kz/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/kk-kz/ContactTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/templates/nls/kk/EventSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/kk/EventSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/kk-kz/EventSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/kk-kz/EventSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/kk/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/kk/_WizardDialogBase',{});
},
'Sage/MainView/ReportMgr/Common/nls/kk-kz/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/kk-kz/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/kk/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/kk/SchedulesListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/kk-kz/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/kk-kz/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/kk/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/kk/GoogleDocPicker',{});
},
'Sage/Utility/File/nls/kk-kz/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/kk-kz/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/kk/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/ComboBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/kk-kz/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk-kz/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/kk/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/kk/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/kk-kz/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/kk-kz/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/kk/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/kk/HistoryEditor',{});
},
'Sage/MainView/ActivityMgr/nls/kk-kz/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/kk-kz/HistoryEditor',{});
},
'Sage/Groups/nls/kk/GroupManager':function(){
define('Sage/Groups/nls/kk/GroupManager',{});
},
'Sage/Groups/nls/kk-kz/GroupManager':function(){
define('Sage/Groups/nls/kk-kz/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk-kz/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk-kz/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/ComboBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk-kz/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk-kz/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/kk/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/kk/ReportsListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/kk-kz/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/kk-kz/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/kk/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/kk/JobNotificationButton',{});
},
'Sage/UI/Alarms/nls/kk-kz/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/kk-kz/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/kk/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/kk/CrystalReportWizardController',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/kk-kz/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/kk-kz/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/kk/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/kk/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/kk-kz/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/kk-kz/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/kk/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/kk/RecurringEditor',{});
},
'Sage/MainView/ActivityMgr/nls/kk-kz/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/kk-kz/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/kk/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/kk/CrystalReportsUtility',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/kk-kz/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/kk-kz/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk-kz/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk-kz/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/kk/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/kk/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/kk-kz/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/kk-kz/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/kk/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/kk-kz/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk-kz/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/kk/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/kk-kz/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk-kz/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/kk/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/nls/kk-kz/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk-kz/PickListControlDesigner',{});
},
'Sage/MainView/ActivityMgr/templates/nls/kk/LitRequestSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/kk/LitRequestSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/kk-kz/LitRequestSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/kk-kz/LitRequestSummary',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk-kz/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk-kz/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/kk/FolderHandler':function(){
define('Sage/Library/nls/kk/FolderHandler',{});
},
'Sage/Library/nls/kk-kz/FolderHandler':function(){
define('Sage/Library/nls/kk-kz/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk-kz/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk-kz/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/kk/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/kk/ContactSearchForDuplicates',{});
},
'Sage/MainView/Contact/nls/kk-kz/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/kk-kz/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/DateTimePickerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk-kz/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk-kz/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/kk/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/kk/AccountingTasksTasklet',{});
},
'Sage/TaskPane/nls/kk-kz/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/kk-kz/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk-kz/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk-kz/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/CurrencyBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk-kz/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk-kz/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/kk/EditableGrid':function(){
define('Sage/UI/nls/kk/EditableGrid',{});
},
'Sage/UI/nls/kk-kz/EditableGrid':function(){
define('Sage/UI/nls/kk-kz/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/kk/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/kk/SalesQuoteRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/kk-kz/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/kk-kz/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/kk/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/kk/SecurityProfile',{});
},
'Sage/MainView/SecurityMgr/nls/kk-kz/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/kk-kz/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/kk/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/kk/ReportWizardController',{});
},
'Sage/MainView/ReportMgr/nls/kk-kz/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/kk-kz/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/UserAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk-kz/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk-kz/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/kk/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/kk/ReportManagerUtility',{});
},
'Sage/MainView/ReportMgr/nls/kk-kz/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/kk-kz/ReportManagerUtility',{});
},
'Sage/UI/nls/kk/SpeedSearch':function(){
define('Sage/UI/nls/kk/SpeedSearch',{});
},
'Sage/UI/nls/kk-kz/SpeedSearch':function(){
define('Sage/UI/nls/kk-kz/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/CurrencyAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk-kz/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk-kz/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/kk/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/kk/ReportManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/kk-kz/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/kk-kz/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/kk/SLXPreviewGrid':function(){
define('Sage/UI/nls/kk/SLXPreviewGrid',{});
},
'Sage/UI/nls/kk-kz/SLXPreviewGrid':function(){
define('Sage/UI/nls/kk-kz/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/kk/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/kk/UnconfirmedPane',{});
},
'Sage/UI/Alarms/nls/kk-kz/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/kk-kz/UnconfirmedPane',{});
},
'Sage/Utility/nls/kk/Utility':function(){
define('Sage/Utility/nls/kk/Utility',{});
},
'Sage/Utility/nls/kk-kz/Utility':function(){
define('Sage/Utility/nls/kk-kz/Utility',{});
},
'Sage/QuickForms/Design/nls/kk/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/ControlDesigner',{});
},
'Sage/QuickForms/Design/nls/kk-kz/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk-kz/ControlDesigner',{});
},
'Sage/UI/Controls/nls/kk/Address':function(){
define('Sage/UI/Controls/nls/kk/Address',{});
},
'Sage/UI/Controls/nls/kk-kz/Address':function(){
define('Sage/UI/Controls/nls/kk-kz/Address',{});
},
'Sage/MainView/JobMgr/nls/kk/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/kk/JobManagerGroupContextService',{});
},
'Sage/MainView/JobMgr/nls/kk-kz/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/kk-kz/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/kk/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/kk/BaseListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/kk-kz/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/kk-kz/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/kk/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/OwnerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/kk-kz/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk-kz/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/kk/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/kk/JobManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/kk-kz/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/kk-kz/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/kk/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/kk/ActivityEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/kk-kz/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/kk-kz/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/kk/UserType':function(){
define('Sage/UI/nls/kk/UserType',{});
},
'Sage/UI/nls/kk-kz/UserType':function(){
define('Sage/UI/nls/kk-kz/UserType',{});
},
'Sage/MainView/ReportMgr/templates/nls/kk/HistoryDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/kk/HistoryDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/kk-kz/HistoryDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/kk-kz/HistoryDetailSummary',{});
},
'Sage/QuickForms/Design/nls/kk/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/FormDesigner',{});
},
'Sage/QuickForms/Design/nls/kk-kz/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/kk-kz/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/kk/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/kk/ActivityCalendar',{});
},
'Sage/MainView/ActivityMgr/nls/kk-kz/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/kk-kz/ActivityCalendar',{});
},
'Sage/Utility/nls/kk/Jobs':function(){
define('Sage/Utility/nls/kk/Jobs',{});
},
'Sage/Utility/nls/kk-kz/Jobs':function(){
define('Sage/Utility/nls/kk-kz/Jobs',{});
},
'Sage/UI/Controls/nls/kk/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/kk/_DialogHelpIconMixin',{});
},
'Sage/UI/Controls/nls/kk-kz/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/kk-kz/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/PickListAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk-kz/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk-kz/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/kk/ActivityList':function(){
define('Sage/UI/nls/kk/ActivityList',{});
},
'Sage/UI/nls/kk-kz/ActivityList':function(){
define('Sage/UI/nls/kk-kz/ActivityList',{});
},
'Sage/UI/Alarms/nls/kk/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/kk/JobNotificationPopup',{});
},
'Sage/UI/Alarms/nls/kk-kz/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/kk-kz/JobNotificationPopup',{});
},
'Sage/MainView/JobMgr/templates/nls/kk/ExecutionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/kk/ExecutionsListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/kk-kz/ExecutionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/kk-kz/ExecutionsListSummary',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/kk/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/kk/LeadLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/kk-kz/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/kk-kz/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/kk/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/kk/SchedulesListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/kk-kz/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/kk-kz/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/GenericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk-kz/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk-kz/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/kk/CalendarUsersListPane':function(){
define('Sage/UI/nls/kk/CalendarUsersListPane',{});
},
'Sage/UI/nls/kk-kz/CalendarUsersListPane':function(){
define('Sage/UI/nls/kk-kz/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk-kz/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk-kz/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/ColumnBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk-kz/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk-kz/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/templates/nls/kk/ExecutionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/kk/ExecutionDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/kk-kz/ExecutionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/kk-kz/ExecutionDetailSummary',{});
},
'Sage/MainView/ReportMgr/nls/kk/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/kk/ReportManagerGroupContextService',{});
},
'Sage/MainView/ReportMgr/nls/kk-kz/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/kk-kz/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/kk/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/kk/MatchingOptionsConfig',{});
},
'Sage/MainView/IntegrationContract/nls/kk-kz/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/kk-kz/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/FormBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk-kz/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk-kz/FormBasicPropertyEditor',{});
},
'Sage/UI/Alarms/nls/kk/AlarmButton':function(){
define('Sage/UI/Alarms/nls/kk/AlarmButton',{});
},
'Sage/UI/Alarms/nls/kk-kz/AlarmButton':function(){
define('Sage/UI/Alarms/nls/kk-kz/AlarmButton',{});
},
'Sage/MainView/ActivityMgr/nls/kk/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/kk/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/MainView/ActivityMgr/nls/kk-kz/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/kk-kz/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/kk/Attachment':function(){
define('Sage/Utility/File/nls/kk/Attachment',{});
},
'Sage/Utility/File/nls/kk-kz/Attachment':function(){
define('Sage/Utility/File/nls/kk-kz/Attachment',{});
},
'Sage/QuickForms/Design/nls/kk/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/kk-kz/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk-kz/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/kk/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/kk/PropertyEditorContainer',{});
},
'Sage/QuickForms/Design/nls/kk-kz/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/kk-kz/PropertyEditorContainer',{});
},
'Sage/Services/nls/kk/ReportingService':function(){
define('Sage/Services/nls/kk/ReportingService',{});
},
'Sage/Services/nls/kk-kz/ReportingService':function(){
define('Sage/Services/nls/kk-kz/ReportingService',{});
},
'Sage/MailMerge/nls/kk/Helper':function(){
define('Sage/MailMerge/nls/kk/Helper',{});
},
'Sage/MailMerge/nls/kk-kz/Helper':function(){
define('Sage/MailMerge/nls/kk-kz/Helper',{});
},
'Sage/UI/Dashboard/nls/kk/Dashboard':function(){
define('Sage/UI/Dashboard/nls/kk/Dashboard',{});
},
'Sage/UI/Dashboard/nls/kk-kz/Dashboard':function(){
define('Sage/UI/Dashboard/nls/kk-kz/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/kk/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/kk/ActivityListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/kk-kz/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/kk-kz/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/kk/PickList':function(){
define('Sage/UI/Controls/nls/kk/PickList',{});
},
'Sage/UI/Controls/nls/kk-kz/PickList':function(){
define('Sage/UI/Controls/nls/kk-kz/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/kk/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/kk/HistoryEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/kk-kz/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/kk-kz/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/kk/Email':function(){
define('Sage/Utility/nls/kk/Email',{});
},
'Sage/Utility/nls/kk-kz/Email':function(){
define('Sage/Utility/nls/kk-kz/Email',{});
},
'Sage/TaskPane/nls/kk/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/kk/SecurityManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/kk-kz/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/kk-kz/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/kk/TimeZoneItem':function(){
define('Sage/UI/nls/kk/TimeZoneItem',{});
},
'Sage/UI/nls/kk-kz/TimeZoneItem':function(){
define('Sage/UI/nls/kk-kz/TimeZoneItem',{});
},
'Sage/MainView/ReportMgr/templates/nls/kk/HistoryListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/kk/HistoryListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/kk-kz/HistoryListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/kk-kz/HistoryListSummary',{});
},
'Sage/UI/Columns/nls/kk/SlxEdit':function(){
define('Sage/UI/Columns/nls/kk/SlxEdit',{});
},
'Sage/UI/Columns/nls/kk-kz/SlxEdit':function(){
define('Sage/UI/Columns/nls/kk-kz/SlxEdit',{});
},
'Sage/Reporting/nls/kk/Enumerations':function(){
define('Sage/Reporting/nls/kk/Enumerations',{});
},
'Sage/Reporting/nls/kk-kz/Enumerations':function(){
define('Sage/Reporting/nls/kk-kz/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk-kz/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk-kz/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/kk/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/kk/CrystalReportConditionsDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/kk-kz/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/kk-kz/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/kk/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/kk/ActivityListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/kk-kz/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/kk-kz/ActivityListPanelConfig',{});
},
'Sage/UI/nls/kk/JobSchedulingWidget':function(){
define('Sage/UI/nls/kk/JobSchedulingWidget',{});
},
'Sage/UI/nls/kk-kz/JobSchedulingWidget':function(){
define('Sage/UI/nls/kk-kz/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/kk/LogOffButton':function(){
define('Sage/UI/Controls/nls/kk/LogOffButton',{});
},
'Sage/UI/Controls/nls/kk-kz/LogOffButton':function(){
define('Sage/UI/Controls/nls/kk-kz/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/TextBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk-kz/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk-kz/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/kk/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/kk/EditEventEditor',{});
},
'Sage/MainView/ActivityMgr/nls/kk-kz/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/kk-kz/EditEventEditor',{});
},
'Sage/MailMerge/nls/kk/Loader':function(){
define('Sage/MailMerge/nls/kk/Loader',{});
},
'Sage/MailMerge/nls/kk-kz/Loader':function(){
define('Sage/MailMerge/nls/kk-kz/Loader',{});
},
'Sage/UI/Controls/nls/kk/DateTimePicker':function(){
define('Sage/UI/Controls/nls/kk/DateTimePicker',{});
},
'Sage/UI/Controls/nls/kk-kz/DateTimePicker':function(){
define('Sage/UI/Controls/nls/kk-kz/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/kk/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/kk/ReportManagerActions',{});
},
'Sage/MainView/ReportMgr/nls/kk-kz/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/kk-kz/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/kk/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/kk/AlarmPopup',{});
},
'Sage/UI/Alarms/nls/kk-kz/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/kk-kz/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/kk/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/kk/ContactUserAssociationEditor',{});
},
'Sage/MainView/Contact/nls/kk-kz/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/kk-kz/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk-kz/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk-kz/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/kk/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/kk/BaseListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/kk-kz/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/kk-kz/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/kk/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/kk-kz/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk-kz/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/kk/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/EmailControlDesigner',{});
},
'Sage/QuickForms/Design/nls/kk-kz/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk-kz/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/kk/Lookup':function(){
define('Sage/UI/Controls/nls/kk/Lookup',{});
},
'Sage/UI/Controls/nls/kk-kz/Lookup':function(){
define('Sage/UI/Controls/nls/kk-kz/Lookup',{});
},
'Sage/Utility/File/nls/kk/DescriptionsForm':function(){
define('Sage/Utility/File/nls/kk/DescriptionsForm',{});
},
'Sage/Utility/File/nls/kk-kz/DescriptionsForm':function(){
define('Sage/Utility/File/nls/kk-kz/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/NumericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk-kz/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk-kz/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/kk/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/kk/CommonTasksTasklet',{});
},
'Sage/TaskPane/nls/kk-kz/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/kk-kz/CommonTasksTasklet',{});
},
'Sage/Utility/nls/kk/Dashboard':function(){
define('Sage/Utility/nls/kk/Dashboard',{});
},
'Sage/Utility/nls/kk-kz/Dashboard':function(){
define('Sage/Utility/nls/kk-kz/Dashboard',{});
}}});
define("Sage/nls/Sage_kk-kz", [], 1);
