require({cache:{
'Sage/Utility/File/nls/mk/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/mk/FallbackFilePicker',{});
},
'Sage/UI/nls/mk/Boolean':function(){
define('Sage/UI/nls/mk/Boolean',{});
},
'Sage/Services/nls/mk/ActivityService':function(){
define('Sage/Services/nls/mk/ActivityService',{});
},
'Sage/UI/Controls/nls/mk/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/mk/CopyToClipboard',{});
},
'Sage/Utility/nls/mk/Activity':function(){
define('Sage/Utility/nls/mk/Activity',{});
},
'Sage/QuickForms/Design/nls/mk/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/mk/DesignPanel',{});
},
'Sage/UI/nls/mk/TimelessActivitiesPane':function(){
define('Sage/UI/nls/mk/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/mk/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/mk/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/mk/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/mk/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/mk/ActivityManager':function(){
define('Sage/MainView/nls/mk/ActivityManager',{});
},
'Sage/Services/nls/mk/JobService':function(){
define('Sage/Services/nls/mk/JobService',{});
},
'Sage/QuickForms/Design/nls/mk/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mk/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/_PropertyEditor',{});
},
'Sage/Services/nls/mk/ActivityActionProcessor':function(){
define('Sage/Services/nls/mk/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/mk/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/mk/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/templates/nls/mk/UserActivityDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/mk/UserActivityDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/mk/ConfirmationDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/mk/ConfirmationDetailSummary',{});
},
'Sage/Utility/File/nls/mk/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/mk/DefaultDropHandler',{});
},
'Sage/UI/nls/mk/TransferBoxWidget':function(){
define('Sage/UI/nls/mk/TransferBoxWidget',{});
},
'Sage/Utility/File/nls/mk/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/mk/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/mk/AlarmPane':function(){
define('Sage/UI/Alarms/nls/mk/AlarmPane',{});
},
'Sage/TaskPane/nls/mk/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/mk/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/mk/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/mk/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/mk/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/mk/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/mk/FilterPanel':function(){
define('Sage/UI/Filters/nls/mk/FilterPanel',{});
},
'Sage/TaskPane/nls/mk/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/mk/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/mk/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/mk/ReportManagerFormatter',{});
},
'Sage/UI/nls/mk/OwnerType':function(){
define('Sage/UI/nls/mk/OwnerType',{});
},
'Sage/MainView/JobMgr/templates/nls/mk/JobDefinitionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/mk/JobDefinitionsListSummary',{});
},
'Sage/TaskPane/nls/mk/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/mk/LeadTasksTasklet',{});
},
'Sage/MainView/ReportMgr/templates/nls/mk/ReportDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/mk/ReportDetailSummary',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/mk/_ParameterEditorBase':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/mk/_ParameterEditorBase',{});
},
'Sage/MailMerge/nls/mk/Service':function(){
define('Sage/MailMerge/nls/mk/Service',{});
},
'Sage/MainView/ActivityMgr/templates/nls/mk/ConfirmationListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/mk/ConfirmationListSummary',{});
},
'Sage/MainView/ActivityMgr/nls/mk/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/mk/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/mk/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/mk/InvoiceRTDV',{});
},
'Sage/UI/nls/mk/SDataLookup':function(){
define('Sage/UI/nls/mk/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/mk/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/mk/RowDesigner',{});
},
'Sage/Groups/nls/mk/GroupLookup':function(){
define('Sage/Groups/nls/mk/GroupLookup',{});
},
'Sage/TaskPane/nls/mk/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/mk/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/mk/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/mk/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/mk/LibraryDocument':function(){
define('Sage/Utility/File/nls/mk/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/mk/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/mk/SpeedSearchLookup',{});
},
'Sage/UI/nls/mk/ConditionManager':function(){
define('Sage/UI/nls/mk/ConditionManager',{});
},
'Sage/MainView/JobMgr/templates/nls/mk/SchedulesListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/mk/SchedulesListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/mk/UserActivityListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/mk/UserActivityListSummary',{});
},
'Sage/UI/Dashboard/nls/mk/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/mk/WidgetDefinition',{});
},
'Sage/MainView/ActivityMgr/templates/nls/mk/AllOpenListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/mk/AllOpenListSummary',{});
},
'Sage/UI/nls/mk/SearchConditionWidget':function(){
define('Sage/UI/nls/mk/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/mk/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/mk/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/mk/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/mk/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/mk/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/mk/DataSourcePanel',{});
},
'Sage/MainView/ReportMgr/templates/nls/mk/SchedulesListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/mk/SchedulesListSummary',{});
},
'Sage/Library/nls/mk/Manager':function(){
define('Sage/Library/nls/mk/Manager',{});
},
'Sage/UI/nls/mk/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/mk/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/mk/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/mk/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/mk/Name':function(){
define('Sage/UI/Controls/nls/mk/Name',{});
},
'Sage/MainView/JobMgr/nls/mk/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/mk/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/mk/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mk/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/mk/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/mk/UpdateLeads',{});
},
'Sage/Library/nls/mk/FileHandler':function(){
define('Sage/Library/nls/mk/FileHandler',{});
},
'Sage/UI/nls/mk/ListPanel':function(){
define('Sage/UI/nls/mk/ListPanel',{});
},
'Sage/Utility/nls/mk/Sql':function(){
define('Sage/Utility/nls/mk/Sql',{});
},
'Sage/UI/Filters/nls/mk/EditFilters':function(){
define('Sage/UI/Filters/nls/mk/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/mk/DurationSelect':function(){
define('Sage/UI/Controls/nls/mk/DurationSelect',{});
},
'Sage/UI/Alarms/nls/mk/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/mk/AlarmCountDown',{});
},
'Sage/UI/nls/mk/AttachmentList':function(){
define('Sage/UI/nls/mk/AttachmentList',{});
},
'Sage/MailMerge/nls/mk/Lookup':function(){
define('Sage/MailMerge/nls/mk/Lookup',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/mk/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/mk/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/mk/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mk/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/mk/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mk/EditableGridControlDesigner',{});
},
'Sage/MainView/Options/nls/mk/OptionsDialog':function(){
define('Sage/MainView/Options/nls/mk/OptionsDialog',{});
},
'Sage/QuickForms/Design/nls/mk/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mk/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/mk/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/mk/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/mk/Dialogs':function(){
define('Sage/UI/nls/mk/Dialogs',{});
},
'Sage/MainView/IntegrationContract/nls/mk/SyncResultsHistory':function(){
define('Sage/MainView/IntegrationContract/nls/mk/SyncResultsHistory',{});
},
'Sage/TaskPane/nls/mk/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/mk/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/mk/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/mk/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/mk/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/mk/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/mk/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mk/UserControlDesigner',{});
},
'Sage/Groups/nls/mk/GroupNavigator':function(){
define('Sage/Groups/nls/mk/GroupNavigator',{});
},
'Sage/Utility/File/nls/mk/AddURLAttachment':function(){
define('Sage/Utility/File/nls/mk/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/mk/EditFilterItems':function(){
define('Sage/UI/Filters/nls/mk/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/mk/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/mk/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/mk/DragDropWatcher':function(){
define('Sage/Utility/File/nls/mk/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/mk/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/mk/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/mk/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/mk/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/mk/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/mk/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/mk/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/mk/AllOpenListPanelConfig',{});
},
'Sage/MainView/nls/mk/FormManager':function(){
define('Sage/MainView/nls/mk/FormManager',{});
},
'Sage/UI/nls/mk/ActivityScheduler':function(){
define('Sage/UI/nls/mk/ActivityScheduler',{});
},
'Sage/MainView/nls/mk/SecurityManager':function(){
define('Sage/MainView/nls/mk/SecurityManager',{});
},
'Sage/TaskPane/nls/mk/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/mk/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/mk/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/mk/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/mk/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/mk/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/templates/nls/mk/AllOpenDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/mk/AllOpenDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/mk/ReportsListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/mk/ReportsListSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/mk/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/mk/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/templates/nls/mk/ScheduleDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/mk/ScheduleDetailSummary',{});
},
'Sage/MainView/Opportunity/nls/mk/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/mk/UpdateOpportunities',{});
},
'Sage/UI/nls/mk/EditCalendarUsers':function(){
define('Sage/UI/nls/mk/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/mk/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/mk/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/mk/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mk/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/mk/HelpMenu':function(){
define('Sage/UI/Controls/nls/mk/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/mk/UserTasklet':function(){
define('Sage/TaskPane/nls/mk/UserTasklet',{});
},
'Sage/UI/Alarms/nls/mk/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/mk/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/mk/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/mk/OpportunityStatistics',{});
},
'Sage/TaskPane/nls/mk/GroupListTasklet':function(){
define('Sage/TaskPane/nls/mk/GroupListTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/mk/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/mk/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/mk/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/mk/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/mk/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/mk/ColumnDesigner',{});
},
'Sage/MainView/JobMgr/templates/nls/mk/JobDefinitionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/mk/JobDefinitionDetailSummary',{});
},
'Sage/UI/nls/mk/SearchMenuItem':function(){
define('Sage/UI/nls/mk/SearchMenuItem',{});
},
'Sage/Library/nls/mk/DocumentProperties':function(){
define('Sage/Library/nls/mk/DocumentProperties',{});
},
'Sage/UI/nls/mk/NotesHistoryList':function(){
define('Sage/UI/nls/mk/NotesHistoryList',{});
},
'Sage/Utility/nls/mk/File':function(){
define('Sage/Utility/nls/mk/File',{});
},
'Sage/MainView/ReportMgr/nls/mk/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/mk/HistoryListPanelConfig',{});
},
'Sage/MainView/JobMgr/templates/nls/mk/ScheduleDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/mk/ScheduleDetailSummary',{});
},
'Sage/QuickForms/Design/nls/mk/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mk/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/mk/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/mk/ContactTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/templates/nls/mk/EventSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/mk/EventSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/mk/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/mk/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/mk/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/mk/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/mk/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/mk/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/mk/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mk/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/mk/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/mk/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/mk/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/mk/HistoryEditor',{});
},
'Sage/Groups/nls/mk/GroupManager':function(){
define('Sage/Groups/nls/mk/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/mk/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/mk/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/mk/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/mk/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/mk/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/mk/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/mk/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/mk/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/mk/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/mk/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/mk/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/mk/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/mk/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/mk/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/mk/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mk/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/mk/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mk/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/mk/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mk/PickListControlDesigner',{});
},
'Sage/MainView/ActivityMgr/templates/nls/mk/LitRequestSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/mk/LitRequestSummary',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/mk/FolderHandler':function(){
define('Sage/Library/nls/mk/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/mk/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/mk/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/mk/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/mk/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/mk/EditableGrid':function(){
define('Sage/UI/nls/mk/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/mk/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/mk/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/mk/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/mk/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/mk/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/mk/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/mk/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/mk/ReportManagerUtility',{});
},
'Sage/UI/nls/mk/SpeedSearch':function(){
define('Sage/UI/nls/mk/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/mk/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/mk/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/mk/SLXPreviewGrid':function(){
define('Sage/UI/nls/mk/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/mk/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/mk/UnconfirmedPane',{});
},
'Sage/Utility/nls/mk/Utility':function(){
define('Sage/Utility/nls/mk/Utility',{});
},
'Sage/QuickForms/Design/nls/mk/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mk/ControlDesigner',{});
},
'Sage/UI/Controls/nls/mk/Address':function(){
define('Sage/UI/Controls/nls/mk/Address',{});
},
'Sage/MainView/JobMgr/nls/mk/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/mk/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/mk/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/mk/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/mk/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mk/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/mk/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/mk/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/mk/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/mk/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/mk/UserType':function(){
define('Sage/UI/nls/mk/UserType',{});
},
'Sage/MainView/ReportMgr/templates/nls/mk/HistoryDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/mk/HistoryDetailSummary',{});
},
'Sage/QuickForms/Design/nls/mk/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/mk/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/mk/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/mk/ActivityCalendar',{});
},
'Sage/Utility/nls/mk/Jobs':function(){
define('Sage/Utility/nls/mk/Jobs',{});
},
'Sage/UI/Controls/nls/mk/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/mk/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/mk/ActivityList':function(){
define('Sage/UI/nls/mk/ActivityList',{});
},
'Sage/UI/Alarms/nls/mk/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/mk/JobNotificationPopup',{});
},
'Sage/MainView/JobMgr/templates/nls/mk/ExecutionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/mk/ExecutionsListSummary',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/mk/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/mk/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/mk/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/mk/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/mk/CalendarUsersListPane':function(){
define('Sage/UI/nls/mk/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/templates/nls/mk/ExecutionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/mk/ExecutionDetailSummary',{});
},
'Sage/MainView/ReportMgr/nls/mk/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/mk/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/mk/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/mk/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/FormBasicPropertyEditor',{});
},
'Sage/UI/Alarms/nls/mk/AlarmButton':function(){
define('Sage/UI/Alarms/nls/mk/AlarmButton',{});
},
'Sage/MainView/ActivityMgr/nls/mk/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/mk/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/mk/Attachment':function(){
define('Sage/Utility/File/nls/mk/Attachment',{});
},
'Sage/QuickForms/Design/nls/mk/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mk/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/mk/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/mk/PropertyEditorContainer',{});
},
'Sage/Services/nls/mk/ReportingService':function(){
define('Sage/Services/nls/mk/ReportingService',{});
},
'Sage/MailMerge/nls/mk/Helper':function(){
define('Sage/MailMerge/nls/mk/Helper',{});
},
'Sage/UI/Dashboard/nls/mk/Dashboard':function(){
define('Sage/UI/Dashboard/nls/mk/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/mk/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/mk/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/mk/PickList':function(){
define('Sage/UI/Controls/nls/mk/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/mk/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/mk/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/mk/Email':function(){
define('Sage/Utility/nls/mk/Email',{});
},
'Sage/TaskPane/nls/mk/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/mk/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/mk/TimeZoneItem':function(){
define('Sage/UI/nls/mk/TimeZoneItem',{});
},
'Sage/MainView/ReportMgr/templates/nls/mk/HistoryListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/mk/HistoryListSummary',{});
},
'Sage/UI/Columns/nls/mk/SlxEdit':function(){
define('Sage/UI/Columns/nls/mk/SlxEdit',{});
},
'Sage/Reporting/nls/mk/Enumerations':function(){
define('Sage/Reporting/nls/mk/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/mk/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/mk/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/mk/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/mk/ActivityListPanelConfig',{});
},
'Sage/UI/nls/mk/JobSchedulingWidget':function(){
define('Sage/UI/nls/mk/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/mk/LogOffButton':function(){
define('Sage/UI/Controls/nls/mk/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/mk/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/mk/EditEventEditor',{});
},
'Sage/MailMerge/nls/mk/Loader':function(){
define('Sage/MailMerge/nls/mk/Loader',{});
},
'Sage/UI/Controls/nls/mk/DateTimePicker':function(){
define('Sage/UI/Controls/nls/mk/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/mk/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/mk/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/mk/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/mk/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/mk/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/mk/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/mk/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/mk/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/mk/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mk/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/mk/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mk/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/mk/Lookup':function(){
define('Sage/UI/Controls/nls/mk/Lookup',{});
},
'Sage/Utility/File/nls/mk/DescriptionsForm':function(){
define('Sage/Utility/File/nls/mk/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/mk/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/mk/CommonTasksTasklet',{});
},
'Sage/Utility/nls/mk/Dashboard':function(){
define('Sage/Utility/nls/mk/Dashboard',{});
}}});
define("Sage/nls/Sage_mk", [], 1);
