require({cache:{
'Sage/Utility/File/nls/ro/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/ro/FallbackFilePicker',{});
},
'Sage/Utility/File/nls/ro-mo/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/ro-mo/FallbackFilePicker',{});
},
'Sage/UI/nls/ro/Boolean':function(){
define('Sage/UI/nls/ro/Boolean',{});
},
'Sage/UI/nls/ro-mo/Boolean':function(){
define('Sage/UI/nls/ro-mo/Boolean',{});
},
'Sage/Services/nls/ro/ActivityService':function(){
define('Sage/Services/nls/ro/ActivityService',{});
},
'Sage/Services/nls/ro-mo/ActivityService':function(){
define('Sage/Services/nls/ro-mo/ActivityService',{});
},
'Sage/UI/Controls/nls/ro/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/ro/CopyToClipboard',{});
},
'Sage/UI/Controls/nls/ro-mo/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/ro-mo/CopyToClipboard',{});
},
'Sage/Utility/nls/ro/Activity':function(){
define('Sage/Utility/nls/ro/Activity',{});
},
'Sage/Utility/nls/ro-mo/Activity':function(){
define('Sage/Utility/nls/ro-mo/Activity',{});
},
'Sage/QuickForms/Design/nls/ro/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/ro/DesignPanel',{});
},
'Sage/QuickForms/Design/nls/ro-mo/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/ro-mo/DesignPanel',{});
},
'Sage/UI/nls/ro/TimelessActivitiesPane':function(){
define('Sage/UI/nls/ro/TimelessActivitiesPane',{});
},
'Sage/UI/nls/ro-mo/TimelessActivitiesPane':function(){
define('Sage/UI/nls/ro-mo/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/ro/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ro/ActivityEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ro-mo/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ro-mo/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/ro/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/ro/ContactUserAssociationEditor',{});
},
'Sage/TaskPane/User/nls/ro-mo/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/ro-mo/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/ro/ActivityManager':function(){
define('Sage/MainView/nls/ro/ActivityManager',{});
},
'Sage/MainView/nls/ro-mo/ActivityManager':function(){
define('Sage/MainView/nls/ro-mo/ActivityManager',{});
},
'Sage/Services/nls/ro/JobService':function(){
define('Sage/Services/nls/ro/JobService',{});
},
'Sage/Services/nls/ro-mo/JobService':function(){
define('Sage/Services/nls/ro-mo/JobService',{});
},
'Sage/QuickForms/Design/nls/ro/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ro-mo/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro-mo/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/_PropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ro-mo/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro-mo/_PropertyEditor',{});
},
'Sage/Services/nls/ro/ActivityActionProcessor':function(){
define('Sage/Services/nls/ro/ActivityActionProcessor',{});
},
'Sage/Services/nls/ro-mo/ActivityActionProcessor':function(){
define('Sage/Services/nls/ro-mo/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/TextBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ro-mo/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro-mo/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ro/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ro/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ro-mo/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ro-mo/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ro/UserActivityDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ro/UserActivityDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ro-mo/UserActivityDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ro-mo/UserActivityDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ro/ConfirmationDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ro/ConfirmationDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ro-mo/ConfirmationDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ro-mo/ConfirmationDetailSummary',{});
},
'Sage/Utility/File/nls/ro/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/ro/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/ro-mo/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/ro-mo/DefaultDropHandler',{});
},
'Sage/UI/nls/ro/TransferBoxWidget':function(){
define('Sage/UI/nls/ro/TransferBoxWidget',{});
},
'Sage/UI/nls/ro-mo/TransferBoxWidget':function(){
define('Sage/UI/nls/ro-mo/TransferBoxWidget',{});
},
'Sage/Utility/File/nls/ro/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/ro/AttachmentPropertiesEditForm',{});
},
'Sage/Utility/File/nls/ro-mo/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/ro-mo/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/ro/AlarmPane':function(){
define('Sage/UI/Alarms/nls/ro/AlarmPane',{});
},
'Sage/UI/Alarms/nls/ro-mo/AlarmPane':function(){
define('Sage/UI/Alarms/nls/ro-mo/AlarmPane',{});
},
'Sage/TaskPane/nls/ro/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/ro/LiteratureManagementTasks',{});
},
'Sage/TaskPane/nls/ro-mo/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/ro-mo/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/ro/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/ro/DashboardWidget',{});
},
'Sage/UI/Dashboard/nls/ro-mo/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/ro-mo/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/NumericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ro-mo/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro-mo/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ro/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ro/CustomerPaymentsRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/ro-mo/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ro-mo/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/ro/FilterPanel':function(){
define('Sage/UI/Filters/nls/ro/FilterPanel',{});
},
'Sage/UI/Filters/nls/ro-mo/FilterPanel':function(){
define('Sage/UI/Filters/nls/ro-mo/FilterPanel',{});
},
'Sage/TaskPane/nls/ro/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/ro/_BaseTaskPaneTasklet',{});
},
'Sage/TaskPane/nls/ro-mo/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/ro-mo/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/ro/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/ro/ReportManagerFormatter',{});
},
'Sage/MainView/ReportMgr/nls/ro-mo/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/ro-mo/ReportManagerFormatter',{});
},
'Sage/UI/nls/ro/OwnerType':function(){
define('Sage/UI/nls/ro/OwnerType',{});
},
'Sage/UI/nls/ro-mo/OwnerType':function(){
define('Sage/UI/nls/ro-mo/OwnerType',{});
},
'Sage/MainView/JobMgr/templates/nls/ro/JobDefinitionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ro/JobDefinitionsListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/ro-mo/JobDefinitionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ro-mo/JobDefinitionsListSummary',{});
},
'Sage/TaskPane/nls/ro/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/ro/LeadTasksTasklet',{});
},
'Sage/TaskPane/nls/ro-mo/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/ro-mo/LeadTasksTasklet',{});
},
'Sage/MainView/ReportMgr/templates/nls/ro/ReportDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ro/ReportDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ro-mo/ReportDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ro-mo/ReportDetailSummary',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ro/_ParameterEditorBase':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ro/_ParameterEditorBase',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ro-mo/_ParameterEditorBase':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ro-mo/_ParameterEditorBase',{});
},
'Sage/MailMerge/nls/ro/Service':function(){
define('Sage/MailMerge/nls/ro/Service',{});
},
'Sage/MailMerge/nls/ro-mo/Service':function(){
define('Sage/MailMerge/nls/ro-mo/Service',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ro/ConfirmationListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ro/ConfirmationListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ro-mo/ConfirmationListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ro-mo/ConfirmationListSummary',{});
},
'Sage/MainView/ActivityMgr/nls/ro/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/ro/SnoozeOptions',{});
},
'Sage/MainView/ActivityMgr/nls/ro-mo/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/ro-mo/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ro-mo/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro-mo/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ro-mo/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro-mo/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ro/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ro/InvoiceRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/ro-mo/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ro-mo/InvoiceRTDV',{});
},
'Sage/UI/nls/ro/SDataLookup':function(){
define('Sage/UI/nls/ro/SDataLookup',{});
},
'Sage/UI/nls/ro-mo/SDataLookup':function(){
define('Sage/UI/nls/ro-mo/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/ro/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/ro/RowDesigner',{});
},
'Sage/QuickForms/Design/nls/ro-mo/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/ro-mo/RowDesigner',{});
},
'Sage/Groups/nls/ro/GroupLookup':function(){
define('Sage/Groups/nls/ro/GroupLookup',{});
},
'Sage/Groups/nls/ro-mo/GroupLookup':function(){
define('Sage/Groups/nls/ro-mo/GroupLookup',{});
},
'Sage/TaskPane/nls/ro/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/ro/OpportunityTasksTasklet',{});
},
'Sage/TaskPane/nls/ro-mo/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/ro-mo/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/ro/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/ro/CheckBoxFilter',{});
},
'Sage/UI/Filters/nls/ro-mo/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/ro-mo/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/ro/LibraryDocument':function(){
define('Sage/Utility/File/nls/ro/LibraryDocument',{});
},
'Sage/Utility/File/nls/ro-mo/LibraryDocument':function(){
define('Sage/Utility/File/nls/ro-mo/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ro/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ro/SpeedSearchLookup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ro-mo/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ro-mo/SpeedSearchLookup',{});
},
'Sage/UI/nls/ro/ConditionManager':function(){
define('Sage/UI/nls/ro/ConditionManager',{});
},
'Sage/UI/nls/ro-mo/ConditionManager':function(){
define('Sage/UI/nls/ro-mo/ConditionManager',{});
},
'Sage/MainView/JobMgr/templates/nls/ro/SchedulesListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ro/SchedulesListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/ro-mo/SchedulesListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ro-mo/SchedulesListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ro/UserActivityListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ro/UserActivityListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ro-mo/UserActivityListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ro-mo/UserActivityListSummary',{});
},
'Sage/UI/Dashboard/nls/ro/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/ro/WidgetDefinition',{});
},
'Sage/UI/Dashboard/nls/ro-mo/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/ro-mo/WidgetDefinition',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ro/AllOpenListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ro/AllOpenListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ro-mo/AllOpenListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ro-mo/AllOpenListSummary',{});
},
'Sage/UI/nls/ro/SearchConditionWidget':function(){
define('Sage/UI/nls/ro/SearchConditionWidget',{});
},
'Sage/UI/nls/ro-mo/SearchConditionWidget':function(){
define('Sage/UI/nls/ro-mo/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ro-mo/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro-mo/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ro/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/ro/JobManagerActions',{});
},
'Sage/MainView/JobMgr/nls/ro-mo/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/ro-mo/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ro/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ro/ContactLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ro-mo/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ro-mo/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/ro/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/ro/DataSourcePanel',{});
},
'Sage/QuickForms/Design/nls/ro-mo/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/ro-mo/DataSourcePanel',{});
},
'Sage/MainView/ReportMgr/templates/nls/ro/SchedulesListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ro/SchedulesListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ro-mo/SchedulesListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ro-mo/SchedulesListSummary',{});
},
'Sage/Library/nls/ro/Manager':function(){
define('Sage/Library/nls/ro/Manager',{});
},
'Sage/Library/nls/ro-mo/Manager':function(){
define('Sage/Library/nls/ro-mo/Manager',{});
},
'Sage/UI/nls/ro/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/ro/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/nls/ro-mo/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/ro-mo/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/ro/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/ro/NonVisibleControlContainer',{});
},
'Sage/QuickForms/Design/nls/ro-mo/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/ro-mo/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/ro/Name':function(){
define('Sage/UI/Controls/nls/ro/Name',{});
},
'Sage/UI/Controls/nls/ro-mo/Name':function(){
define('Sage/UI/Controls/nls/ro-mo/Name',{});
},
'Sage/MainView/JobMgr/nls/ro/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ro/ExecutionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/ro-mo/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ro-mo/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ro/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro/PhoneControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ro-mo/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro-mo/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/ro/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/ro/UpdateLeads',{});
},
'Sage/MainView/Lead/nls/ro-mo/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/ro-mo/UpdateLeads',{});
},
'Sage/Library/nls/ro/FileHandler':function(){
define('Sage/Library/nls/ro/FileHandler',{});
},
'Sage/Library/nls/ro-mo/FileHandler':function(){
define('Sage/Library/nls/ro-mo/FileHandler',{});
},
'Sage/UI/nls/ro/ListPanel':function(){
define('Sage/UI/nls/ro/ListPanel',{});
},
'Sage/UI/nls/ro-mo/ListPanel':function(){
define('Sage/UI/nls/ro-mo/ListPanel',{});
},
'Sage/Utility/nls/ro/Sql':function(){
define('Sage/Utility/nls/ro/Sql',{});
},
'Sage/Utility/nls/ro-mo/Sql':function(){
define('Sage/Utility/nls/ro-mo/Sql',{});
},
'Sage/UI/Filters/nls/ro/EditFilters':function(){
define('Sage/UI/Filters/nls/ro/EditFilters',{});
},
'Sage/UI/Filters/nls/ro-mo/EditFilters':function(){
define('Sage/UI/Filters/nls/ro-mo/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/FormUsagesPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ro-mo/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro-mo/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/ro/DurationSelect':function(){
define('Sage/UI/Controls/nls/ro/DurationSelect',{});
},
'Sage/UI/Controls/nls/ro-mo/DurationSelect':function(){
define('Sage/UI/Controls/nls/ro-mo/DurationSelect',{});
},
'Sage/UI/Alarms/nls/ro/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/ro/AlarmCountDown',{});
},
'Sage/UI/Alarms/nls/ro-mo/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/ro-mo/AlarmCountDown',{});
},
'Sage/UI/nls/ro/AttachmentList':function(){
define('Sage/UI/nls/ro/AttachmentList',{});
},
'Sage/UI/nls/ro-mo/AttachmentList':function(){
define('Sage/UI/nls/ro-mo/AttachmentList',{});
},
'Sage/MailMerge/nls/ro/Lookup':function(){
define('Sage/MailMerge/nls/ro/Lookup',{});
},
'Sage/MailMerge/nls/ro-mo/Lookup':function(){
define('Sage/MailMerge/nls/ro-mo/Lookup',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ro-mo/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro-mo/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ro/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/ro/RunJobDialog',{});
},
'Sage/MainView/JobMgr/nls/ro-mo/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/ro-mo/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/ro/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ro-mo/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro-mo/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ro/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ro-mo/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro-mo/EditableGridControlDesigner',{});
},
'Sage/MainView/Options/nls/ro/OptionsDialog':function(){
define('Sage/MainView/Options/nls/ro/OptionsDialog',{});
},
'Sage/MainView/Options/nls/ro-mo/OptionsDialog':function(){
define('Sage/MainView/Options/nls/ro-mo/OptionsDialog',{});
},
'Sage/QuickForms/Design/nls/ro/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro/HiddenControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ro-mo/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro-mo/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/ro/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/ro/DashboardWidgetCell',{});
},
'Sage/UI/Dashboard/nls/ro-mo/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/ro-mo/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/UserBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ro-mo/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro-mo/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/ro/Dialogs':function(){
define('Sage/UI/nls/ro/Dialogs',{});
},
'Sage/UI/nls/ro-mo/Dialogs':function(){
define('Sage/UI/nls/ro-mo/Dialogs',{});
},
'Sage/MainView/IntegrationContract/nls/ro/SyncResultsHistory':function(){
define('Sage/MainView/IntegrationContract/nls/ro/SyncResultsHistory',{});
},
'Sage/MainView/IntegrationContract/nls/ro-mo/SyncResultsHistory':function(){
define('Sage/MainView/IntegrationContract/nls/ro-mo/SyncResultsHistory',{});
},
'Sage/TaskPane/nls/ro/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/ro/SecuredActionTasklet',{});
},
'Sage/TaskPane/nls/ro-mo/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/ro-mo/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/ro/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/ro/DashboardTabController',{});
},
'Sage/UI/Dashboard/nls/ro-mo/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/ro-mo/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/ro/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ro/SalesOrderRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/ro-mo/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ro-mo/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/ro/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro/UserControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ro-mo/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro-mo/UserControlDesigner',{});
},
'Sage/Groups/nls/ro/GroupNavigator':function(){
define('Sage/Groups/nls/ro/GroupNavigator',{});
},
'Sage/Groups/nls/ro-mo/GroupNavigator':function(){
define('Sage/Groups/nls/ro-mo/GroupNavigator',{});
},
'Sage/Utility/File/nls/ro/AddURLAttachment':function(){
define('Sage/Utility/File/nls/ro/AddURLAttachment',{});
},
'Sage/Utility/File/nls/ro-mo/AddURLAttachment':function(){
define('Sage/Utility/File/nls/ro-mo/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/ro/EditFilterItems':function(){
define('Sage/UI/Filters/nls/ro/EditFilterItems',{});
},
'Sage/UI/Filters/nls/ro-mo/EditFilterItems':function(){
define('Sage/UI/Filters/nls/ro-mo/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ro/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ro/CrystalReportsFormatter',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ro-mo/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ro-mo/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/ro/DragDropWatcher':function(){
define('Sage/Utility/File/nls/ro/DragDropWatcher',{});
},
'Sage/Utility/File/nls/ro-mo/DragDropWatcher':function(){
define('Sage/Utility/File/nls/ro-mo/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/ro/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/ro/DesignSurface',{});
},
'Sage/QuickForms/Design/nls/ro-mo/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/ro-mo/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/ro/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ro/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ro-mo/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ro-mo/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/FormAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ro-mo/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro-mo/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ro/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ro/EventListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ro-mo/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ro-mo/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ro/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ro/AllOpenListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ro-mo/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ro-mo/AllOpenListPanelConfig',{});
},
'Sage/MainView/nls/ro/FormManager':function(){
define('Sage/MainView/nls/ro/FormManager',{});
},
'Sage/MainView/nls/ro-mo/FormManager':function(){
define('Sage/MainView/nls/ro-mo/FormManager',{});
},
'Sage/UI/nls/ro/ActivityScheduler':function(){
define('Sage/UI/nls/ro/ActivityScheduler',{});
},
'Sage/UI/nls/ro-mo/ActivityScheduler':function(){
define('Sage/UI/nls/ro-mo/ActivityScheduler',{});
},
'Sage/MainView/nls/ro/SecurityManager':function(){
define('Sage/MainView/nls/ro/SecurityManager',{});
},
'Sage/MainView/nls/ro-mo/SecurityManager':function(){
define('Sage/MainView/nls/ro-mo/SecurityManager',{});
},
'Sage/TaskPane/nls/ro/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/ro/ActivityTaskConfigurationProvider',{});
},
'Sage/TaskPane/nls/ro-mo/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/ro-mo/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/ro/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/ro/EntityInfoToolTip',{});
},
'Sage/UI/Controls/nls/ro-mo/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/ro-mo/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/ro/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/ro/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/ro-mo/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/ro-mo/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ro/AllOpenDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ro/AllOpenDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ro-mo/AllOpenDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ro-mo/AllOpenDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ro/ReportsListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ro/ReportsListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ro-mo/ReportsListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ro-mo/ReportsListSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/ro/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/ro/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/Common/nls/ro-mo/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/ro-mo/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/templates/nls/ro/ScheduleDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ro/ScheduleDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ro-mo/ScheduleDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ro-mo/ScheduleDetailSummary',{});
},
'Sage/MainView/Opportunity/nls/ro/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/ro/UpdateOpportunities',{});
},
'Sage/MainView/Opportunity/nls/ro-mo/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/ro-mo/UpdateOpportunities',{});
},
'Sage/UI/nls/ro/EditCalendarUsers':function(){
define('Sage/UI/nls/ro/EditCalendarUsers',{});
},
'Sage/UI/nls/ro-mo/EditCalendarUsers':function(){
define('Sage/UI/nls/ro-mo/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ro/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ro/CrystalReportParametersDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ro-mo/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ro-mo/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/ro/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro/DateTimePickerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ro-mo/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro-mo/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/ro/HelpMenu':function(){
define('Sage/UI/Controls/nls/ro/HelpMenu',{});
},
'Sage/UI/Controls/nls/ro-mo/HelpMenu':function(){
define('Sage/UI/Controls/nls/ro-mo/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/LayoutPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ro-mo/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro-mo/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/ro/UserTasklet':function(){
define('Sage/TaskPane/nls/ro/UserTasklet',{});
},
'Sage/TaskPane/nls/ro-mo/UserTasklet':function(){
define('Sage/TaskPane/nls/ro-mo/UserTasklet',{});
},
'Sage/UI/Alarms/nls/ro/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/ro/ActivityAlarm',{});
},
'Sage/UI/Alarms/nls/ro-mo/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/ro-mo/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/ro/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/ro/OpportunityStatistics',{});
},
'Sage/MainView/Opportunity/nls/ro-mo/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/ro-mo/OpportunityStatistics',{});
},
'Sage/TaskPane/nls/ro/GroupListTasklet':function(){
define('Sage/TaskPane/nls/ro/GroupListTasklet',{});
},
'Sage/TaskPane/nls/ro-mo/GroupListTasklet':function(){
define('Sage/TaskPane/nls/ro-mo/GroupListTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ro/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ro/CrystalReportConditionEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ro-mo/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ro-mo/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ro/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/ro/AdvancedSearchOptions',{});
},
'Sage/MainView/IntegrationContract/nls/ro-mo/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/ro-mo/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/ro/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/ro/ColumnDesigner',{});
},
'Sage/QuickForms/Design/nls/ro-mo/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/ro-mo/ColumnDesigner',{});
},
'Sage/MainView/JobMgr/templates/nls/ro/JobDefinitionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ro/JobDefinitionDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/ro-mo/JobDefinitionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ro-mo/JobDefinitionDetailSummary',{});
},
'Sage/UI/nls/ro/SearchMenuItem':function(){
define('Sage/UI/nls/ro/SearchMenuItem',{});
},
'Sage/UI/nls/ro-mo/SearchMenuItem':function(){
define('Sage/UI/nls/ro-mo/SearchMenuItem',{});
},
'Sage/Library/nls/ro/DocumentProperties':function(){
define('Sage/Library/nls/ro/DocumentProperties',{});
},
'Sage/Library/nls/ro-mo/DocumentProperties':function(){
define('Sage/Library/nls/ro-mo/DocumentProperties',{});
},
'Sage/UI/nls/ro/NotesHistoryList':function(){
define('Sage/UI/nls/ro/NotesHistoryList',{});
},
'Sage/UI/nls/ro-mo/NotesHistoryList':function(){
define('Sage/UI/nls/ro-mo/NotesHistoryList',{});
},
'Sage/Utility/nls/ro/File':function(){
define('Sage/Utility/nls/ro/File',{});
},
'Sage/Utility/nls/ro-mo/File':function(){
define('Sage/Utility/nls/ro-mo/File',{});
},
'Sage/MainView/ReportMgr/nls/ro/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ro/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/ro-mo/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ro-mo/HistoryListPanelConfig',{});
},
'Sage/MainView/JobMgr/templates/nls/ro/ScheduleDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ro/ScheduleDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/ro-mo/ScheduleDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ro-mo/ScheduleDetailSummary',{});
},
'Sage/QuickForms/Design/nls/ro/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro/UrlControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ro-mo/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro-mo/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/ro/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/ro/ContactTasksTasklet',{});
},
'Sage/TaskPane/nls/ro-mo/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/ro-mo/ContactTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ro/EventSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ro/EventSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ro-mo/EventSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ro-mo/EventSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/ro/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/ro/_WizardDialogBase',{});
},
'Sage/MainView/ReportMgr/Common/nls/ro-mo/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/ro-mo/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/ro/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ro/SchedulesListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/ro-mo/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ro-mo/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/ro/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/ro/GoogleDocPicker',{});
},
'Sage/Utility/File/nls/ro-mo/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/ro-mo/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/ro/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro/ComboBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ro-mo/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro-mo/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/ro/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ro/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ro-mo/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ro-mo/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ro/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ro/HistoryEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ro-mo/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ro-mo/HistoryEditor',{});
},
'Sage/Groups/nls/ro/GroupManager':function(){
define('Sage/Groups/nls/ro/GroupManager',{});
},
'Sage/Groups/nls/ro-mo/GroupManager':function(){
define('Sage/Groups/nls/ro-mo/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ro-mo/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro-mo/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/ComboBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ro-mo/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro-mo/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ro/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ro/ReportsListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/ro-mo/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ro-mo/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/ro/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/ro/JobNotificationButton',{});
},
'Sage/UI/Alarms/nls/ro-mo/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/ro-mo/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ro/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ro/CrystalReportWizardController',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ro-mo/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ro-mo/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/ro/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ro/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/ro-mo/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ro-mo/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ro/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ro/RecurringEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ro-mo/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ro-mo/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ro/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ro/CrystalReportsUtility',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ro-mo/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ro-mo/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ro-mo/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro-mo/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ro/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ro/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/ro-mo/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ro-mo/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ro/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ro-mo/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro-mo/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ro/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ro-mo/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro-mo/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ro/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ro-mo/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro-mo/PickListControlDesigner',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ro/LitRequestSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ro/LitRequestSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ro-mo/LitRequestSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ro-mo/LitRequestSummary',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ro-mo/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro-mo/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/ro/FolderHandler':function(){
define('Sage/Library/nls/ro/FolderHandler',{});
},
'Sage/Library/nls/ro-mo/FolderHandler':function(){
define('Sage/Library/nls/ro-mo/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ro-mo/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro-mo/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/ro/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/ro/ContactSearchForDuplicates',{});
},
'Sage/MainView/Contact/nls/ro-mo/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/ro-mo/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/DateTimePickerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ro-mo/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro-mo/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/ro/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/ro/AccountingTasksTasklet',{});
},
'Sage/TaskPane/nls/ro-mo/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/ro-mo/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ro-mo/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro-mo/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/CurrencyBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ro-mo/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro-mo/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/ro/EditableGrid':function(){
define('Sage/UI/nls/ro/EditableGrid',{});
},
'Sage/UI/nls/ro-mo/EditableGrid':function(){
define('Sage/UI/nls/ro-mo/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/ro/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ro/SalesQuoteRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/ro-mo/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ro-mo/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/ro/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/ro/SecurityProfile',{});
},
'Sage/MainView/SecurityMgr/nls/ro-mo/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/ro-mo/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/ro/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/ro/ReportWizardController',{});
},
'Sage/MainView/ReportMgr/nls/ro-mo/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/ro-mo/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/UserAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ro-mo/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro-mo/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ro/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/ro/ReportManagerUtility',{});
},
'Sage/MainView/ReportMgr/nls/ro-mo/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/ro-mo/ReportManagerUtility',{});
},
'Sage/UI/nls/ro/SpeedSearch':function(){
define('Sage/UI/nls/ro/SpeedSearch',{});
},
'Sage/UI/nls/ro-mo/SpeedSearch':function(){
define('Sage/UI/nls/ro-mo/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/CurrencyAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ro-mo/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro-mo/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/ro/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ro/ReportManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/ro-mo/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ro-mo/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/ro/SLXPreviewGrid':function(){
define('Sage/UI/nls/ro/SLXPreviewGrid',{});
},
'Sage/UI/nls/ro-mo/SLXPreviewGrid':function(){
define('Sage/UI/nls/ro-mo/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/ro/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/ro/UnconfirmedPane',{});
},
'Sage/UI/Alarms/nls/ro-mo/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/ro-mo/UnconfirmedPane',{});
},
'Sage/Utility/nls/ro/Utility':function(){
define('Sage/Utility/nls/ro/Utility',{});
},
'Sage/Utility/nls/ro-mo/Utility':function(){
define('Sage/Utility/nls/ro-mo/Utility',{});
},
'Sage/QuickForms/Design/nls/ro/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro/ControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ro-mo/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro-mo/ControlDesigner',{});
},
'Sage/UI/Controls/nls/ro/Address':function(){
define('Sage/UI/Controls/nls/ro/Address',{});
},
'Sage/UI/Controls/nls/ro-mo/Address':function(){
define('Sage/UI/Controls/nls/ro-mo/Address',{});
},
'Sage/MainView/JobMgr/nls/ro/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/ro/JobManagerGroupContextService',{});
},
'Sage/MainView/JobMgr/nls/ro-mo/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/ro-mo/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/ro/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ro/BaseListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ro-mo/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ro-mo/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ro/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro/OwnerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ro-mo/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro-mo/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/ro/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ro/JobManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/ro-mo/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ro-mo/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/ro/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ro/ActivityEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/ro-mo/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ro-mo/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/ro/UserType':function(){
define('Sage/UI/nls/ro/UserType',{});
},
'Sage/UI/nls/ro-mo/UserType':function(){
define('Sage/UI/nls/ro-mo/UserType',{});
},
'Sage/MainView/ReportMgr/templates/nls/ro/HistoryDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ro/HistoryDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ro-mo/HistoryDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ro-mo/HistoryDetailSummary',{});
},
'Sage/QuickForms/Design/nls/ro/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/ro/FormDesigner',{});
},
'Sage/QuickForms/Design/nls/ro-mo/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/ro-mo/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/ro/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/ro/ActivityCalendar',{});
},
'Sage/MainView/ActivityMgr/nls/ro-mo/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/ro-mo/ActivityCalendar',{});
},
'Sage/Utility/nls/ro/Jobs':function(){
define('Sage/Utility/nls/ro/Jobs',{});
},
'Sage/Utility/nls/ro-mo/Jobs':function(){
define('Sage/Utility/nls/ro-mo/Jobs',{});
},
'Sage/UI/Controls/nls/ro/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/ro/_DialogHelpIconMixin',{});
},
'Sage/UI/Controls/nls/ro-mo/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/ro-mo/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/PickListAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ro-mo/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro-mo/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/ro/ActivityList':function(){
define('Sage/UI/nls/ro/ActivityList',{});
},
'Sage/UI/nls/ro-mo/ActivityList':function(){
define('Sage/UI/nls/ro-mo/ActivityList',{});
},
'Sage/UI/Alarms/nls/ro/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/ro/JobNotificationPopup',{});
},
'Sage/UI/Alarms/nls/ro-mo/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/ro-mo/JobNotificationPopup',{});
},
'Sage/MainView/JobMgr/templates/nls/ro/ExecutionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ro/ExecutionsListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/ro-mo/ExecutionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ro-mo/ExecutionsListSummary',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ro/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ro/LeadLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ro-mo/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ro-mo/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/ro/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ro/SchedulesListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/ro-mo/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ro-mo/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/GenericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ro-mo/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro-mo/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/ro/CalendarUsersListPane':function(){
define('Sage/UI/nls/ro/CalendarUsersListPane',{});
},
'Sage/UI/nls/ro-mo/CalendarUsersListPane':function(){
define('Sage/UI/nls/ro-mo/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ro-mo/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro-mo/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/ColumnBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ro-mo/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro-mo/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/templates/nls/ro/ExecutionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ro/ExecutionDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/ro-mo/ExecutionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ro-mo/ExecutionDetailSummary',{});
},
'Sage/MainView/ReportMgr/nls/ro/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/ro/ReportManagerGroupContextService',{});
},
'Sage/MainView/ReportMgr/nls/ro-mo/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/ro-mo/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/ro/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/ro/MatchingOptionsConfig',{});
},
'Sage/MainView/IntegrationContract/nls/ro-mo/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/ro-mo/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/FormBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ro-mo/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro-mo/FormBasicPropertyEditor',{});
},
'Sage/UI/Alarms/nls/ro/AlarmButton':function(){
define('Sage/UI/Alarms/nls/ro/AlarmButton',{});
},
'Sage/UI/Alarms/nls/ro-mo/AlarmButton':function(){
define('Sage/UI/Alarms/nls/ro-mo/AlarmButton',{});
},
'Sage/MainView/ActivityMgr/nls/ro/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/ro/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/MainView/ActivityMgr/nls/ro-mo/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/ro-mo/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/ro/Attachment':function(){
define('Sage/Utility/File/nls/ro/Attachment',{});
},
'Sage/Utility/File/nls/ro-mo/Attachment':function(){
define('Sage/Utility/File/nls/ro-mo/Attachment',{});
},
'Sage/QuickForms/Design/nls/ro/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ro-mo/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro-mo/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ro/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/ro/PropertyEditorContainer',{});
},
'Sage/QuickForms/Design/nls/ro-mo/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/ro-mo/PropertyEditorContainer',{});
},
'Sage/Services/nls/ro/ReportingService':function(){
define('Sage/Services/nls/ro/ReportingService',{});
},
'Sage/Services/nls/ro-mo/ReportingService':function(){
define('Sage/Services/nls/ro-mo/ReportingService',{});
},
'Sage/MailMerge/nls/ro/Helper':function(){
define('Sage/MailMerge/nls/ro/Helper',{});
},
'Sage/MailMerge/nls/ro-mo/Helper':function(){
define('Sage/MailMerge/nls/ro-mo/Helper',{});
},
'Sage/UI/Dashboard/nls/ro/Dashboard':function(){
define('Sage/UI/Dashboard/nls/ro/Dashboard',{});
},
'Sage/UI/Dashboard/nls/ro-mo/Dashboard':function(){
define('Sage/UI/Dashboard/nls/ro-mo/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/ro/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ro/ActivityListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ro-mo/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ro-mo/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/ro/PickList':function(){
define('Sage/UI/Controls/nls/ro/PickList',{});
},
'Sage/UI/Controls/nls/ro-mo/PickList':function(){
define('Sage/UI/Controls/nls/ro-mo/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/ro/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ro/HistoryEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/ro-mo/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ro-mo/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/ro/Email':function(){
define('Sage/Utility/nls/ro/Email',{});
},
'Sage/Utility/nls/ro-mo/Email':function(){
define('Sage/Utility/nls/ro-mo/Email',{});
},
'Sage/TaskPane/nls/ro/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ro/SecurityManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/ro-mo/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ro-mo/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/ro/TimeZoneItem':function(){
define('Sage/UI/nls/ro/TimeZoneItem',{});
},
'Sage/UI/nls/ro-mo/TimeZoneItem':function(){
define('Sage/UI/nls/ro-mo/TimeZoneItem',{});
},
'Sage/MainView/ReportMgr/templates/nls/ro/HistoryListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ro/HistoryListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ro-mo/HistoryListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ro-mo/HistoryListSummary',{});
},
'Sage/UI/Columns/nls/ro/SlxEdit':function(){
define('Sage/UI/Columns/nls/ro/SlxEdit',{});
},
'Sage/UI/Columns/nls/ro-mo/SlxEdit':function(){
define('Sage/UI/Columns/nls/ro-mo/SlxEdit',{});
},
'Sage/Reporting/nls/ro/Enumerations':function(){
define('Sage/Reporting/nls/ro/Enumerations',{});
},
'Sage/Reporting/nls/ro-mo/Enumerations':function(){
define('Sage/Reporting/nls/ro-mo/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ro-mo/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro-mo/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ro/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ro/CrystalReportConditionsDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ro-mo/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ro-mo/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ro/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ro/ActivityListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ro-mo/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ro-mo/ActivityListPanelConfig',{});
},
'Sage/UI/nls/ro/JobSchedulingWidget':function(){
define('Sage/UI/nls/ro/JobSchedulingWidget',{});
},
'Sage/UI/nls/ro-mo/JobSchedulingWidget':function(){
define('Sage/UI/nls/ro-mo/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/ro/LogOffButton':function(){
define('Sage/UI/Controls/nls/ro/LogOffButton',{});
},
'Sage/UI/Controls/nls/ro-mo/LogOffButton':function(){
define('Sage/UI/Controls/nls/ro-mo/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/TextBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ro-mo/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro-mo/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ro/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ro/EditEventEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ro-mo/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ro-mo/EditEventEditor',{});
},
'Sage/MailMerge/nls/ro/Loader':function(){
define('Sage/MailMerge/nls/ro/Loader',{});
},
'Sage/MailMerge/nls/ro-mo/Loader':function(){
define('Sage/MailMerge/nls/ro-mo/Loader',{});
},
'Sage/UI/Controls/nls/ro/DateTimePicker':function(){
define('Sage/UI/Controls/nls/ro/DateTimePicker',{});
},
'Sage/UI/Controls/nls/ro-mo/DateTimePicker':function(){
define('Sage/UI/Controls/nls/ro-mo/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/ro/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/ro/ReportManagerActions',{});
},
'Sage/MainView/ReportMgr/nls/ro-mo/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/ro-mo/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/ro/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/ro/AlarmPopup',{});
},
'Sage/UI/Alarms/nls/ro-mo/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/ro-mo/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/ro/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/ro/ContactUserAssociationEditor',{});
},
'Sage/MainView/Contact/nls/ro-mo/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/ro-mo/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ro-mo/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro-mo/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ro/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ro/BaseListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/ro-mo/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ro-mo/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ro/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ro-mo/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro-mo/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ro/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro/EmailControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ro-mo/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro-mo/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/ro/Lookup':function(){
define('Sage/UI/Controls/nls/ro/Lookup',{});
},
'Sage/UI/Controls/nls/ro-mo/Lookup':function(){
define('Sage/UI/Controls/nls/ro-mo/Lookup',{});
},
'Sage/Utility/File/nls/ro/DescriptionsForm':function(){
define('Sage/Utility/File/nls/ro/DescriptionsForm',{});
},
'Sage/Utility/File/nls/ro-mo/DescriptionsForm':function(){
define('Sage/Utility/File/nls/ro-mo/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/NumericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ro-mo/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro-mo/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/ro/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/ro/CommonTasksTasklet',{});
},
'Sage/TaskPane/nls/ro-mo/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/ro-mo/CommonTasksTasklet',{});
},
'Sage/Utility/nls/ro/Dashboard':function(){
define('Sage/Utility/nls/ro/Dashboard',{});
},
'Sage/Utility/nls/ro-mo/Dashboard':function(){
define('Sage/Utility/nls/ro-mo/Dashboard',{});
}}});
define("Sage/nls/Sage_ro-mo", [], 1);
