require({cache:{
'Sage/Utility/File/nls/tn/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/tn/FallbackFilePicker',{});
},
'Sage/UI/nls/tn/Boolean':function(){
define('Sage/UI/nls/tn/Boolean',{});
},
'Sage/Services/nls/tn/ActivityService':function(){
define('Sage/Services/nls/tn/ActivityService',{});
},
'Sage/UI/Controls/nls/tn/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/tn/CopyToClipboard',{});
},
'Sage/Utility/nls/tn/Activity':function(){
define('Sage/Utility/nls/tn/Activity',{});
},
'Sage/QuickForms/Design/nls/tn/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/tn/DesignPanel',{});
},
'Sage/UI/nls/tn/TimelessActivitiesPane':function(){
define('Sage/UI/nls/tn/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/tn/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/tn/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/tn/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/tn/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/tn/ActivityManager':function(){
define('Sage/MainView/nls/tn/ActivityManager',{});
},
'Sage/Services/nls/tn/JobService':function(){
define('Sage/Services/nls/tn/JobService',{});
},
'Sage/QuickForms/Design/nls/tn/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tn/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/_PropertyEditor',{});
},
'Sage/Services/nls/tn/ActivityActionProcessor':function(){
define('Sage/Services/nls/tn/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/tn/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/tn/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/templates/nls/tn/UserActivityDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/tn/UserActivityDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/tn/ConfirmationDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/tn/ConfirmationDetailSummary',{});
},
'Sage/Utility/File/nls/tn/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/tn/DefaultDropHandler',{});
},
'Sage/UI/nls/tn/TransferBoxWidget':function(){
define('Sage/UI/nls/tn/TransferBoxWidget',{});
},
'Sage/Utility/File/nls/tn/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/tn/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/tn/AlarmPane':function(){
define('Sage/UI/Alarms/nls/tn/AlarmPane',{});
},
'Sage/TaskPane/nls/tn/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/tn/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/tn/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/tn/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/tn/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/tn/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/tn/FilterPanel':function(){
define('Sage/UI/Filters/nls/tn/FilterPanel',{});
},
'Sage/TaskPane/nls/tn/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/tn/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/tn/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/tn/ReportManagerFormatter',{});
},
'Sage/UI/nls/tn/OwnerType':function(){
define('Sage/UI/nls/tn/OwnerType',{});
},
'Sage/MainView/JobMgr/templates/nls/tn/JobDefinitionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/tn/JobDefinitionsListSummary',{});
},
'Sage/TaskPane/nls/tn/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/tn/LeadTasksTasklet',{});
},
'Sage/MainView/ReportMgr/templates/nls/tn/ReportDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/tn/ReportDetailSummary',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/tn/_ParameterEditorBase':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/tn/_ParameterEditorBase',{});
},
'Sage/MailMerge/nls/tn/Service':function(){
define('Sage/MailMerge/nls/tn/Service',{});
},
'Sage/MainView/ActivityMgr/templates/nls/tn/ConfirmationListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/tn/ConfirmationListSummary',{});
},
'Sage/MainView/ActivityMgr/nls/tn/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/tn/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/tn/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/tn/InvoiceRTDV',{});
},
'Sage/UI/nls/tn/SDataLookup':function(){
define('Sage/UI/nls/tn/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/tn/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/tn/RowDesigner',{});
},
'Sage/Groups/nls/tn/GroupLookup':function(){
define('Sage/Groups/nls/tn/GroupLookup',{});
},
'Sage/TaskPane/nls/tn/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/tn/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/tn/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/tn/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/tn/LibraryDocument':function(){
define('Sage/Utility/File/nls/tn/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/tn/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/tn/SpeedSearchLookup',{});
},
'Sage/UI/nls/tn/ConditionManager':function(){
define('Sage/UI/nls/tn/ConditionManager',{});
},
'Sage/MainView/JobMgr/templates/nls/tn/SchedulesListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/tn/SchedulesListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/tn/UserActivityListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/tn/UserActivityListSummary',{});
},
'Sage/UI/Dashboard/nls/tn/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/tn/WidgetDefinition',{});
},
'Sage/MainView/ActivityMgr/templates/nls/tn/AllOpenListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/tn/AllOpenListSummary',{});
},
'Sage/UI/nls/tn/SearchConditionWidget':function(){
define('Sage/UI/nls/tn/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/tn/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/tn/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/tn/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/tn/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/tn/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/tn/DataSourcePanel',{});
},
'Sage/MainView/ReportMgr/templates/nls/tn/SchedulesListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/tn/SchedulesListSummary',{});
},
'Sage/Library/nls/tn/Manager':function(){
define('Sage/Library/nls/tn/Manager',{});
},
'Sage/UI/nls/tn/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/tn/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/tn/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/tn/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/tn/Name':function(){
define('Sage/UI/Controls/nls/tn/Name',{});
},
'Sage/MainView/JobMgr/nls/tn/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/tn/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/tn/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tn/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/tn/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/tn/UpdateLeads',{});
},
'Sage/Library/nls/tn/FileHandler':function(){
define('Sage/Library/nls/tn/FileHandler',{});
},
'Sage/UI/nls/tn/ListPanel':function(){
define('Sage/UI/nls/tn/ListPanel',{});
},
'Sage/Utility/nls/tn/Sql':function(){
define('Sage/Utility/nls/tn/Sql',{});
},
'Sage/UI/Filters/nls/tn/EditFilters':function(){
define('Sage/UI/Filters/nls/tn/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/tn/DurationSelect':function(){
define('Sage/UI/Controls/nls/tn/DurationSelect',{});
},
'Sage/UI/Alarms/nls/tn/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/tn/AlarmCountDown',{});
},
'Sage/UI/nls/tn/AttachmentList':function(){
define('Sage/UI/nls/tn/AttachmentList',{});
},
'Sage/MailMerge/nls/tn/Lookup':function(){
define('Sage/MailMerge/nls/tn/Lookup',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/tn/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/tn/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/tn/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tn/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/tn/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tn/EditableGridControlDesigner',{});
},
'Sage/MainView/Options/nls/tn/OptionsDialog':function(){
define('Sage/MainView/Options/nls/tn/OptionsDialog',{});
},
'Sage/QuickForms/Design/nls/tn/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tn/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/tn/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/tn/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/tn/Dialogs':function(){
define('Sage/UI/nls/tn/Dialogs',{});
},
'Sage/MainView/IntegrationContract/nls/tn/SyncResultsHistory':function(){
define('Sage/MainView/IntegrationContract/nls/tn/SyncResultsHistory',{});
},
'Sage/TaskPane/nls/tn/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/tn/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/tn/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/tn/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/tn/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/tn/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/tn/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tn/UserControlDesigner',{});
},
'Sage/Groups/nls/tn/GroupNavigator':function(){
define('Sage/Groups/nls/tn/GroupNavigator',{});
},
'Sage/Utility/File/nls/tn/AddURLAttachment':function(){
define('Sage/Utility/File/nls/tn/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/tn/EditFilterItems':function(){
define('Sage/UI/Filters/nls/tn/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/tn/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/tn/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/tn/DragDropWatcher':function(){
define('Sage/Utility/File/nls/tn/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/tn/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/tn/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/tn/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/tn/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/tn/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/tn/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/tn/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/tn/AllOpenListPanelConfig',{});
},
'Sage/MainView/nls/tn/FormManager':function(){
define('Sage/MainView/nls/tn/FormManager',{});
},
'Sage/UI/nls/tn/ActivityScheduler':function(){
define('Sage/UI/nls/tn/ActivityScheduler',{});
},
'Sage/MainView/nls/tn/SecurityManager':function(){
define('Sage/MainView/nls/tn/SecurityManager',{});
},
'Sage/TaskPane/nls/tn/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/tn/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/tn/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/tn/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/tn/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/tn/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/templates/nls/tn/AllOpenDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/tn/AllOpenDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/tn/ReportsListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/tn/ReportsListSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/tn/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/tn/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/templates/nls/tn/ScheduleDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/tn/ScheduleDetailSummary',{});
},
'Sage/MainView/Opportunity/nls/tn/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/tn/UpdateOpportunities',{});
},
'Sage/UI/nls/tn/EditCalendarUsers':function(){
define('Sage/UI/nls/tn/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/tn/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/tn/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/tn/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tn/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/tn/HelpMenu':function(){
define('Sage/UI/Controls/nls/tn/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/tn/UserTasklet':function(){
define('Sage/TaskPane/nls/tn/UserTasklet',{});
},
'Sage/UI/Alarms/nls/tn/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/tn/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/tn/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/tn/OpportunityStatistics',{});
},
'Sage/TaskPane/nls/tn/GroupListTasklet':function(){
define('Sage/TaskPane/nls/tn/GroupListTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/tn/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/tn/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/tn/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/tn/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/tn/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/tn/ColumnDesigner',{});
},
'Sage/MainView/JobMgr/templates/nls/tn/JobDefinitionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/tn/JobDefinitionDetailSummary',{});
},
'Sage/UI/nls/tn/SearchMenuItem':function(){
define('Sage/UI/nls/tn/SearchMenuItem',{});
},
'Sage/Library/nls/tn/DocumentProperties':function(){
define('Sage/Library/nls/tn/DocumentProperties',{});
},
'Sage/UI/nls/tn/NotesHistoryList':function(){
define('Sage/UI/nls/tn/NotesHistoryList',{});
},
'Sage/Utility/nls/tn/File':function(){
define('Sage/Utility/nls/tn/File',{});
},
'Sage/MainView/ReportMgr/nls/tn/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/tn/HistoryListPanelConfig',{});
},
'Sage/MainView/JobMgr/templates/nls/tn/ScheduleDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/tn/ScheduleDetailSummary',{});
},
'Sage/QuickForms/Design/nls/tn/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tn/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/tn/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/tn/ContactTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/templates/nls/tn/EventSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/tn/EventSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/tn/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/tn/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/tn/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/tn/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/tn/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/tn/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/tn/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tn/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/tn/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/tn/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/tn/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/tn/HistoryEditor',{});
},
'Sage/Groups/nls/tn/GroupManager':function(){
define('Sage/Groups/nls/tn/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/tn/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/tn/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/tn/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/tn/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/tn/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/tn/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/tn/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/tn/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/tn/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/tn/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/tn/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/tn/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/tn/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/tn/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/tn/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tn/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/tn/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tn/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/tn/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tn/PickListControlDesigner',{});
},
'Sage/MainView/ActivityMgr/templates/nls/tn/LitRequestSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/tn/LitRequestSummary',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/tn/FolderHandler':function(){
define('Sage/Library/nls/tn/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/tn/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/tn/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/tn/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/tn/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/tn/EditableGrid':function(){
define('Sage/UI/nls/tn/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/tn/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/tn/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/tn/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/tn/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/tn/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/tn/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/tn/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/tn/ReportManagerUtility',{});
},
'Sage/UI/nls/tn/SpeedSearch':function(){
define('Sage/UI/nls/tn/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/tn/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/tn/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/tn/SLXPreviewGrid':function(){
define('Sage/UI/nls/tn/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/tn/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/tn/UnconfirmedPane',{});
},
'Sage/Utility/nls/tn/Utility':function(){
define('Sage/Utility/nls/tn/Utility',{});
},
'Sage/QuickForms/Design/nls/tn/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tn/ControlDesigner',{});
},
'Sage/UI/Controls/nls/tn/Address':function(){
define('Sage/UI/Controls/nls/tn/Address',{});
},
'Sage/MainView/JobMgr/nls/tn/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/tn/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/tn/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/tn/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/tn/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tn/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/tn/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/tn/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/tn/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/tn/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/tn/UserType':function(){
define('Sage/UI/nls/tn/UserType',{});
},
'Sage/MainView/ReportMgr/templates/nls/tn/HistoryDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/tn/HistoryDetailSummary',{});
},
'Sage/QuickForms/Design/nls/tn/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/tn/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/tn/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/tn/ActivityCalendar',{});
},
'Sage/Utility/nls/tn/Jobs':function(){
define('Sage/Utility/nls/tn/Jobs',{});
},
'Sage/UI/Controls/nls/tn/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/tn/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/tn/ActivityList':function(){
define('Sage/UI/nls/tn/ActivityList',{});
},
'Sage/UI/Alarms/nls/tn/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/tn/JobNotificationPopup',{});
},
'Sage/MainView/JobMgr/templates/nls/tn/ExecutionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/tn/ExecutionsListSummary',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/tn/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/tn/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/tn/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/tn/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/tn/CalendarUsersListPane':function(){
define('Sage/UI/nls/tn/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/templates/nls/tn/ExecutionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/tn/ExecutionDetailSummary',{});
},
'Sage/MainView/ReportMgr/nls/tn/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/tn/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/tn/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/tn/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/FormBasicPropertyEditor',{});
},
'Sage/UI/Alarms/nls/tn/AlarmButton':function(){
define('Sage/UI/Alarms/nls/tn/AlarmButton',{});
},
'Sage/MainView/ActivityMgr/nls/tn/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/tn/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/tn/Attachment':function(){
define('Sage/Utility/File/nls/tn/Attachment',{});
},
'Sage/QuickForms/Design/nls/tn/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tn/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/tn/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/tn/PropertyEditorContainer',{});
},
'Sage/Services/nls/tn/ReportingService':function(){
define('Sage/Services/nls/tn/ReportingService',{});
},
'Sage/MailMerge/nls/tn/Helper':function(){
define('Sage/MailMerge/nls/tn/Helper',{});
},
'Sage/UI/Dashboard/nls/tn/Dashboard':function(){
define('Sage/UI/Dashboard/nls/tn/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/tn/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/tn/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/tn/PickList':function(){
define('Sage/UI/Controls/nls/tn/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/tn/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/tn/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/tn/Email':function(){
define('Sage/Utility/nls/tn/Email',{});
},
'Sage/TaskPane/nls/tn/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/tn/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/tn/TimeZoneItem':function(){
define('Sage/UI/nls/tn/TimeZoneItem',{});
},
'Sage/MainView/ReportMgr/templates/nls/tn/HistoryListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/tn/HistoryListSummary',{});
},
'Sage/UI/Columns/nls/tn/SlxEdit':function(){
define('Sage/UI/Columns/nls/tn/SlxEdit',{});
},
'Sage/Reporting/nls/tn/Enumerations':function(){
define('Sage/Reporting/nls/tn/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/tn/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/tn/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/tn/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/tn/ActivityListPanelConfig',{});
},
'Sage/UI/nls/tn/JobSchedulingWidget':function(){
define('Sage/UI/nls/tn/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/tn/LogOffButton':function(){
define('Sage/UI/Controls/nls/tn/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/tn/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/tn/EditEventEditor',{});
},
'Sage/MailMerge/nls/tn/Loader':function(){
define('Sage/MailMerge/nls/tn/Loader',{});
},
'Sage/UI/Controls/nls/tn/DateTimePicker':function(){
define('Sage/UI/Controls/nls/tn/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/tn/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/tn/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/tn/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/tn/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/tn/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/tn/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/tn/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/tn/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/tn/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tn/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/tn/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tn/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/tn/Lookup':function(){
define('Sage/UI/Controls/nls/tn/Lookup',{});
},
'Sage/Utility/File/nls/tn/DescriptionsForm':function(){
define('Sage/Utility/File/nls/tn/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/tn/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/tn/CommonTasksTasklet',{});
},
'Sage/Utility/nls/tn/Dashboard':function(){
define('Sage/Utility/nls/tn/Dashboard',{});
}}});
define("Sage/nls/Sage_tn", [], 1);
