require({cache:{
'Sage/Utility/File/nls/ro/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/ro/FallbackFilePicker',{});
},
'Sage/UI/nls/ro/Boolean':function(){
define('Sage/UI/nls/ro/Boolean',{});
},
'Sage/Services/nls/ro/ActivityService':function(){
define('Sage/Services/nls/ro/ActivityService',{});
},
'Sage/UI/Controls/nls/ro/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/ro/CopyToClipboard',{});
},
'Sage/Utility/nls/ro/Activity':function(){
define('Sage/Utility/nls/ro/Activity',{});
},
'Sage/QuickForms/Design/nls/ro/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/ro/DesignPanel',{});
},
'Sage/UI/nls/ro/TimelessActivitiesPane':function(){
define('Sage/UI/nls/ro/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/ro/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ro/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/ro/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/ro/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/ro/ActivityManager':function(){
define('Sage/MainView/nls/ro/ActivityManager',{});
},
'Sage/Services/nls/ro/JobService':function(){
define('Sage/Services/nls/ro/JobService',{});
},
'Sage/QuickForms/Design/nls/ro/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/_PropertyEditor',{});
},
'Sage/Services/nls/ro/ActivityActionProcessor':function(){
define('Sage/Services/nls/ro/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ro/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ro/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ro/UserActivityDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ro/UserActivityDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ro/ConfirmationDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ro/ConfirmationDetailSummary',{});
},
'Sage/Utility/File/nls/ro/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/ro/DefaultDropHandler',{});
},
'Sage/UI/nls/ro/TransferBoxWidget':function(){
define('Sage/UI/nls/ro/TransferBoxWidget',{});
},
'Sage/Utility/File/nls/ro/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/ro/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/ro/AlarmPane':function(){
define('Sage/UI/Alarms/nls/ro/AlarmPane',{});
},
'Sage/TaskPane/nls/ro/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/ro/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/ro/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/ro/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ro/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ro/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/ro/FilterPanel':function(){
define('Sage/UI/Filters/nls/ro/FilterPanel',{});
},
'Sage/TaskPane/nls/ro/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/ro/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/ro/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/ro/ReportManagerFormatter',{});
},
'Sage/UI/nls/ro/OwnerType':function(){
define('Sage/UI/nls/ro/OwnerType',{});
},
'Sage/MainView/JobMgr/templates/nls/ro/JobDefinitionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ro/JobDefinitionsListSummary',{});
},
'Sage/TaskPane/nls/ro/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/ro/LeadTasksTasklet',{});
},
'Sage/MainView/ReportMgr/templates/nls/ro/ReportDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ro/ReportDetailSummary',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ro/_ParameterEditorBase':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ro/_ParameterEditorBase',{});
},
'Sage/MailMerge/nls/ro/Service':function(){
define('Sage/MailMerge/nls/ro/Service',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ro/ConfirmationListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ro/ConfirmationListSummary',{});
},
'Sage/MainView/ActivityMgr/nls/ro/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/ro/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ro/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ro/InvoiceRTDV',{});
},
'Sage/UI/nls/ro/SDataLookup':function(){
define('Sage/UI/nls/ro/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/ro/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/ro/RowDesigner',{});
},
'Sage/Groups/nls/ro/GroupLookup':function(){
define('Sage/Groups/nls/ro/GroupLookup',{});
},
'Sage/TaskPane/nls/ro/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/ro/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/ro/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/ro/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/ro/LibraryDocument':function(){
define('Sage/Utility/File/nls/ro/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ro/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ro/SpeedSearchLookup',{});
},
'Sage/UI/nls/ro/ConditionManager':function(){
define('Sage/UI/nls/ro/ConditionManager',{});
},
'Sage/MainView/JobMgr/templates/nls/ro/SchedulesListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ro/SchedulesListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ro/UserActivityListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ro/UserActivityListSummary',{});
},
'Sage/UI/Dashboard/nls/ro/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/ro/WidgetDefinition',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ro/AllOpenListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ro/AllOpenListSummary',{});
},
'Sage/UI/nls/ro/SearchConditionWidget':function(){
define('Sage/UI/nls/ro/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ro/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/ro/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ro/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ro/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/ro/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/ro/DataSourcePanel',{});
},
'Sage/MainView/ReportMgr/templates/nls/ro/SchedulesListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ro/SchedulesListSummary',{});
},
'Sage/Library/nls/ro/Manager':function(){
define('Sage/Library/nls/ro/Manager',{});
},
'Sage/UI/nls/ro/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/ro/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/ro/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/ro/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/ro/Name':function(){
define('Sage/UI/Controls/nls/ro/Name',{});
},
'Sage/MainView/JobMgr/nls/ro/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ro/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ro/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/ro/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/ro/UpdateLeads',{});
},
'Sage/Library/nls/ro/FileHandler':function(){
define('Sage/Library/nls/ro/FileHandler',{});
},
'Sage/UI/nls/ro/ListPanel':function(){
define('Sage/UI/nls/ro/ListPanel',{});
},
'Sage/Utility/nls/ro/Sql':function(){
define('Sage/Utility/nls/ro/Sql',{});
},
'Sage/UI/Filters/nls/ro/EditFilters':function(){
define('Sage/UI/Filters/nls/ro/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/ro/DurationSelect':function(){
define('Sage/UI/Controls/nls/ro/DurationSelect',{});
},
'Sage/UI/Alarms/nls/ro/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/ro/AlarmCountDown',{});
},
'Sage/UI/nls/ro/AttachmentList':function(){
define('Sage/UI/nls/ro/AttachmentList',{});
},
'Sage/MailMerge/nls/ro/Lookup':function(){
define('Sage/MailMerge/nls/ro/Lookup',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ro/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/ro/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/ro/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ro/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro/EditableGridControlDesigner',{});
},
'Sage/MainView/Options/nls/ro/OptionsDialog':function(){
define('Sage/MainView/Options/nls/ro/OptionsDialog',{});
},
'Sage/QuickForms/Design/nls/ro/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/ro/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/ro/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/ro/Dialogs':function(){
define('Sage/UI/nls/ro/Dialogs',{});
},
'Sage/MainView/IntegrationContract/nls/ro/SyncResultsHistory':function(){
define('Sage/MainView/IntegrationContract/nls/ro/SyncResultsHistory',{});
},
'Sage/TaskPane/nls/ro/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/ro/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/ro/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/ro/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/ro/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ro/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/ro/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro/UserControlDesigner',{});
},
'Sage/Groups/nls/ro/GroupNavigator':function(){
define('Sage/Groups/nls/ro/GroupNavigator',{});
},
'Sage/Utility/File/nls/ro/AddURLAttachment':function(){
define('Sage/Utility/File/nls/ro/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/ro/EditFilterItems':function(){
define('Sage/UI/Filters/nls/ro/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ro/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ro/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/ro/DragDropWatcher':function(){
define('Sage/Utility/File/nls/ro/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/ro/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/ro/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/ro/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ro/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ro/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ro/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ro/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ro/AllOpenListPanelConfig',{});
},
'Sage/MainView/nls/ro/FormManager':function(){
define('Sage/MainView/nls/ro/FormManager',{});
},
'Sage/UI/nls/ro/ActivityScheduler':function(){
define('Sage/UI/nls/ro/ActivityScheduler',{});
},
'Sage/MainView/nls/ro/SecurityManager':function(){
define('Sage/MainView/nls/ro/SecurityManager',{});
},
'Sage/TaskPane/nls/ro/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/ro/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/ro/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/ro/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/ro/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/ro/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ro/AllOpenDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ro/AllOpenDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ro/ReportsListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ro/ReportsListSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/ro/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/ro/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/templates/nls/ro/ScheduleDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ro/ScheduleDetailSummary',{});
},
'Sage/MainView/Opportunity/nls/ro/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/ro/UpdateOpportunities',{});
},
'Sage/UI/nls/ro/EditCalendarUsers':function(){
define('Sage/UI/nls/ro/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ro/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ro/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/ro/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/ro/HelpMenu':function(){
define('Sage/UI/Controls/nls/ro/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/ro/UserTasklet':function(){
define('Sage/TaskPane/nls/ro/UserTasklet',{});
},
'Sage/UI/Alarms/nls/ro/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/ro/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/ro/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/ro/OpportunityStatistics',{});
},
'Sage/TaskPane/nls/ro/GroupListTasklet':function(){
define('Sage/TaskPane/nls/ro/GroupListTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ro/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ro/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ro/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/ro/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/ro/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/ro/ColumnDesigner',{});
},
'Sage/MainView/JobMgr/templates/nls/ro/JobDefinitionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ro/JobDefinitionDetailSummary',{});
},
'Sage/UI/nls/ro/SearchMenuItem':function(){
define('Sage/UI/nls/ro/SearchMenuItem',{});
},
'Sage/Library/nls/ro/DocumentProperties':function(){
define('Sage/Library/nls/ro/DocumentProperties',{});
},
'Sage/UI/nls/ro/NotesHistoryList':function(){
define('Sage/UI/nls/ro/NotesHistoryList',{});
},
'Sage/Utility/nls/ro/File':function(){
define('Sage/Utility/nls/ro/File',{});
},
'Sage/MainView/ReportMgr/nls/ro/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ro/HistoryListPanelConfig',{});
},
'Sage/MainView/JobMgr/templates/nls/ro/ScheduleDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ro/ScheduleDetailSummary',{});
},
'Sage/QuickForms/Design/nls/ro/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/ro/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/ro/ContactTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ro/EventSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ro/EventSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/ro/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/ro/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/ro/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ro/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/ro/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/ro/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/ro/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/ro/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ro/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ro/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ro/HistoryEditor',{});
},
'Sage/Groups/nls/ro/GroupManager':function(){
define('Sage/Groups/nls/ro/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ro/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ro/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/ro/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/ro/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ro/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ro/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/ro/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ro/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ro/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ro/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ro/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ro/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ro/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ro/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ro/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ro/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ro/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro/PickListControlDesigner',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ro/LitRequestSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ro/LitRequestSummary',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/ro/FolderHandler':function(){
define('Sage/Library/nls/ro/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/ro/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/ro/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/ro/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/ro/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/ro/EditableGrid':function(){
define('Sage/UI/nls/ro/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/ro/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ro/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/ro/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/ro/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/ro/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/ro/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ro/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/ro/ReportManagerUtility',{});
},
'Sage/UI/nls/ro/SpeedSearch':function(){
define('Sage/UI/nls/ro/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/ro/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ro/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/ro/SLXPreviewGrid':function(){
define('Sage/UI/nls/ro/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/ro/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/ro/UnconfirmedPane',{});
},
'Sage/Utility/nls/ro/Utility':function(){
define('Sage/Utility/nls/ro/Utility',{});
},
'Sage/QuickForms/Design/nls/ro/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro/ControlDesigner',{});
},
'Sage/UI/Controls/nls/ro/Address':function(){
define('Sage/UI/Controls/nls/ro/Address',{});
},
'Sage/MainView/JobMgr/nls/ro/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/ro/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/ro/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ro/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ro/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/ro/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ro/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/ro/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ro/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/ro/UserType':function(){
define('Sage/UI/nls/ro/UserType',{});
},
'Sage/MainView/ReportMgr/templates/nls/ro/HistoryDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ro/HistoryDetailSummary',{});
},
'Sage/QuickForms/Design/nls/ro/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/ro/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/ro/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/ro/ActivityCalendar',{});
},
'Sage/Utility/nls/ro/Jobs':function(){
define('Sage/Utility/nls/ro/Jobs',{});
},
'Sage/UI/Controls/nls/ro/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/ro/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/ro/ActivityList':function(){
define('Sage/UI/nls/ro/ActivityList',{});
},
'Sage/UI/Alarms/nls/ro/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/ro/JobNotificationPopup',{});
},
'Sage/MainView/JobMgr/templates/nls/ro/ExecutionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ro/ExecutionsListSummary',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ro/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ro/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/ro/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ro/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/ro/CalendarUsersListPane':function(){
define('Sage/UI/nls/ro/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/templates/nls/ro/ExecutionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ro/ExecutionDetailSummary',{});
},
'Sage/MainView/ReportMgr/nls/ro/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/ro/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/ro/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/ro/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/FormBasicPropertyEditor',{});
},
'Sage/UI/Alarms/nls/ro/AlarmButton':function(){
define('Sage/UI/Alarms/nls/ro/AlarmButton',{});
},
'Sage/MainView/ActivityMgr/nls/ro/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/ro/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/ro/Attachment':function(){
define('Sage/Utility/File/nls/ro/Attachment',{});
},
'Sage/QuickForms/Design/nls/ro/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ro/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/ro/PropertyEditorContainer',{});
},
'Sage/Services/nls/ro/ReportingService':function(){
define('Sage/Services/nls/ro/ReportingService',{});
},
'Sage/MailMerge/nls/ro/Helper':function(){
define('Sage/MailMerge/nls/ro/Helper',{});
},
'Sage/UI/Dashboard/nls/ro/Dashboard':function(){
define('Sage/UI/Dashboard/nls/ro/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/ro/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ro/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/ro/PickList':function(){
define('Sage/UI/Controls/nls/ro/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/ro/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ro/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/ro/Email':function(){
define('Sage/Utility/nls/ro/Email',{});
},
'Sage/TaskPane/nls/ro/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ro/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/ro/TimeZoneItem':function(){
define('Sage/UI/nls/ro/TimeZoneItem',{});
},
'Sage/MainView/ReportMgr/templates/nls/ro/HistoryListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ro/HistoryListSummary',{});
},
'Sage/UI/Columns/nls/ro/SlxEdit':function(){
define('Sage/UI/Columns/nls/ro/SlxEdit',{});
},
'Sage/Reporting/nls/ro/Enumerations':function(){
define('Sage/Reporting/nls/ro/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ro/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ro/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ro/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ro/ActivityListPanelConfig',{});
},
'Sage/UI/nls/ro/JobSchedulingWidget':function(){
define('Sage/UI/nls/ro/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/ro/LogOffButton':function(){
define('Sage/UI/Controls/nls/ro/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ro/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ro/EditEventEditor',{});
},
'Sage/MailMerge/nls/ro/Loader':function(){
define('Sage/MailMerge/nls/ro/Loader',{});
},
'Sage/UI/Controls/nls/ro/DateTimePicker':function(){
define('Sage/UI/Controls/nls/ro/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/ro/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/ro/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/ro/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/ro/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/ro/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/ro/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ro/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ro/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ro/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ro/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ro/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/ro/Lookup':function(){
define('Sage/UI/Controls/nls/ro/Lookup',{});
},
'Sage/Utility/File/nls/ro/DescriptionsForm':function(){
define('Sage/Utility/File/nls/ro/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/ro/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ro/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/ro/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/ro/CommonTasksTasklet',{});
},
'Sage/Utility/nls/ro/Dashboard':function(){
define('Sage/Utility/nls/ro/Dashboard',{});
}}});
define("Sage/nls/Sage_ro", [], 1);
