require({cache:{
'Sage/Utility/File/nls/ar/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/ar/FallbackFilePicker',{});
},
'Sage/Utility/File/nls/ar-ly/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/ar-ly/FallbackFilePicker',{});
},
'Sage/UI/nls/ar/Boolean':function(){
define('Sage/UI/nls/ar/Boolean',{});
},
'Sage/UI/nls/ar-ly/Boolean':function(){
define('Sage/UI/nls/ar-ly/Boolean',{});
},
'Sage/Services/nls/ar/ActivityService':function(){
define('Sage/Services/nls/ar/ActivityService',{});
},
'Sage/Services/nls/ar-ly/ActivityService':function(){
define('Sage/Services/nls/ar-ly/ActivityService',{});
},
'Sage/UI/Controls/nls/ar/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/ar/CopyToClipboard',{});
},
'Sage/UI/Controls/nls/ar-ly/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/ar-ly/CopyToClipboard',{});
},
'Sage/Utility/nls/ar/Activity':function(){
define('Sage/Utility/nls/ar/Activity',{});
},
'Sage/Utility/nls/ar-ly/Activity':function(){
define('Sage/Utility/nls/ar-ly/Activity',{});
},
'Sage/QuickForms/Design/nls/ar/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/ar/DesignPanel',{});
},
'Sage/QuickForms/Design/nls/ar-ly/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/ar-ly/DesignPanel',{});
},
'Sage/UI/nls/ar/TimelessActivitiesPane':function(){
define('Sage/UI/nls/ar/TimelessActivitiesPane',{});
},
'Sage/UI/nls/ar-ly/TimelessActivitiesPane':function(){
define('Sage/UI/nls/ar-ly/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ly/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ly/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/ar/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/ar/ContactUserAssociationEditor',{});
},
'Sage/TaskPane/User/nls/ar-ly/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/ar-ly/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/ar/ActivityManager':function(){
define('Sage/MainView/nls/ar/ActivityManager',{});
},
'Sage/MainView/nls/ar-ly/ActivityManager':function(){
define('Sage/MainView/nls/ar-ly/ActivityManager',{});
},
'Sage/Services/nls/ar/JobService':function(){
define('Sage/Services/nls/ar/JobService',{});
},
'Sage/Services/nls/ar-ly/JobService':function(){
define('Sage/Services/nls/ar-ly/JobService',{});
},
'Sage/QuickForms/Design/nls/ar/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-ly/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-ly/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/_PropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ly/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ly/_PropertyEditor',{});
},
'Sage/Services/nls/ar/ActivityActionProcessor':function(){
define('Sage/Services/nls/ar/ActivityActionProcessor',{});
},
'Sage/Services/nls/ar-ly/ActivityActionProcessor':function(){
define('Sage/Services/nls/ar-ly/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/TextBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ly/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ly/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ly/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ly/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar/UserActivityDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar/UserActivityDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar-ly/UserActivityDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar-ly/UserActivityDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar/ConfirmationDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar/ConfirmationDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar-ly/ConfirmationDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar-ly/ConfirmationDetailSummary',{});
},
'Sage/Utility/File/nls/ar/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/ar/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/ar-ly/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/ar-ly/DefaultDropHandler',{});
},
'Sage/UI/nls/ar/TransferBoxWidget':function(){
define('Sage/UI/nls/ar/TransferBoxWidget',{});
},
'Sage/UI/nls/ar-ly/TransferBoxWidget':function(){
define('Sage/UI/nls/ar-ly/TransferBoxWidget',{});
},
'Sage/Utility/File/nls/ar/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/ar/AttachmentPropertiesEditForm',{});
},
'Sage/Utility/File/nls/ar-ly/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/ar-ly/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/ar/AlarmPane':function(){
define('Sage/UI/Alarms/nls/ar/AlarmPane',{});
},
'Sage/UI/Alarms/nls/ar-ly/AlarmPane':function(){
define('Sage/UI/Alarms/nls/ar-ly/AlarmPane',{});
},
'Sage/TaskPane/nls/ar/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/ar/LiteratureManagementTasks',{});
},
'Sage/TaskPane/nls/ar-ly/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/ar-ly/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/ar/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/ar/DashboardWidget',{});
},
'Sage/UI/Dashboard/nls/ar-ly/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/ar-ly/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/NumericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ly/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ly/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ar/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar/CustomerPaymentsRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/ar-ly/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar-ly/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/ar/FilterPanel':function(){
define('Sage/UI/Filters/nls/ar/FilterPanel',{});
},
'Sage/UI/Filters/nls/ar-ly/FilterPanel':function(){
define('Sage/UI/Filters/nls/ar-ly/FilterPanel',{});
},
'Sage/TaskPane/nls/ar/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/ar/_BaseTaskPaneTasklet',{});
},
'Sage/TaskPane/nls/ar-ly/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/ar-ly/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/ar/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/ar/ReportManagerFormatter',{});
},
'Sage/MainView/ReportMgr/nls/ar-ly/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/ar-ly/ReportManagerFormatter',{});
},
'Sage/UI/nls/ar/OwnerType':function(){
define('Sage/UI/nls/ar/OwnerType',{});
},
'Sage/UI/nls/ar-ly/OwnerType':function(){
define('Sage/UI/nls/ar-ly/OwnerType',{});
},
'Sage/MainView/JobMgr/templates/nls/ar/JobDefinitionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar/JobDefinitionsListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/ar-ly/JobDefinitionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar-ly/JobDefinitionsListSummary',{});
},
'Sage/TaskPane/nls/ar/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/LeadTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-ly/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-ly/LeadTasksTasklet',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar/ReportDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar/ReportDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar-ly/ReportDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar-ly/ReportDetailSummary',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/_ParameterEditorBase':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/_ParameterEditorBase',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-ly/_ParameterEditorBase':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-ly/_ParameterEditorBase',{});
},
'Sage/MailMerge/nls/ar/Service':function(){
define('Sage/MailMerge/nls/ar/Service',{});
},
'Sage/MailMerge/nls/ar-ly/Service':function(){
define('Sage/MailMerge/nls/ar-ly/Service',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar/ConfirmationListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar/ConfirmationListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar-ly/ConfirmationListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar-ly/ConfirmationListSummary',{});
},
'Sage/MainView/ActivityMgr/nls/ar/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/ar/SnoozeOptions',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ly/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ly/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ly/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ly/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ly/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ly/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ar/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar/InvoiceRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/ar-ly/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar-ly/InvoiceRTDV',{});
},
'Sage/UI/nls/ar/SDataLookup':function(){
define('Sage/UI/nls/ar/SDataLookup',{});
},
'Sage/UI/nls/ar-ly/SDataLookup':function(){
define('Sage/UI/nls/ar-ly/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/ar/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/RowDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-ly/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-ly/RowDesigner',{});
},
'Sage/Groups/nls/ar/GroupLookup':function(){
define('Sage/Groups/nls/ar/GroupLookup',{});
},
'Sage/Groups/nls/ar-ly/GroupLookup':function(){
define('Sage/Groups/nls/ar-ly/GroupLookup',{});
},
'Sage/TaskPane/nls/ar/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/OpportunityTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-ly/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-ly/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/ar/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/ar/CheckBoxFilter',{});
},
'Sage/UI/Filters/nls/ar-ly/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/ar-ly/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/ar/LibraryDocument':function(){
define('Sage/Utility/File/nls/ar/LibraryDocument',{});
},
'Sage/Utility/File/nls/ar-ly/LibraryDocument':function(){
define('Sage/Utility/File/nls/ar-ly/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar/SpeedSearchLookup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar-ly/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar-ly/SpeedSearchLookup',{});
},
'Sage/UI/nls/ar/ConditionManager':function(){
define('Sage/UI/nls/ar/ConditionManager',{});
},
'Sage/UI/nls/ar-ly/ConditionManager':function(){
define('Sage/UI/nls/ar-ly/ConditionManager',{});
},
'Sage/MainView/JobMgr/templates/nls/ar/SchedulesListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar/SchedulesListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/ar-ly/SchedulesListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar-ly/SchedulesListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar/UserActivityListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar/UserActivityListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar-ly/UserActivityListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar-ly/UserActivityListSummary',{});
},
'Sage/UI/Dashboard/nls/ar/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/ar/WidgetDefinition',{});
},
'Sage/UI/Dashboard/nls/ar-ly/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/ar-ly/WidgetDefinition',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar/AllOpenListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar/AllOpenListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar-ly/AllOpenListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar-ly/AllOpenListSummary',{});
},
'Sage/UI/nls/ar/SearchConditionWidget':function(){
define('Sage/UI/nls/ar/SearchConditionWidget',{});
},
'Sage/UI/nls/ar-ly/SearchConditionWidget':function(){
define('Sage/UI/nls/ar-ly/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ly/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ly/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ar/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/ar/JobManagerActions',{});
},
'Sage/MainView/JobMgr/nls/ar-ly/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/ar-ly/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar/ContactLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar-ly/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar-ly/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/ar/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/ar/DataSourcePanel',{});
},
'Sage/QuickForms/Design/nls/ar-ly/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/ar-ly/DataSourcePanel',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar/SchedulesListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar/SchedulesListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar-ly/SchedulesListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar-ly/SchedulesListSummary',{});
},
'Sage/Library/nls/ar/Manager':function(){
define('Sage/Library/nls/ar/Manager',{});
},
'Sage/Library/nls/ar-ly/Manager':function(){
define('Sage/Library/nls/ar-ly/Manager',{});
},
'Sage/UI/nls/ar/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/ar/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/nls/ar-ly/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/ar-ly/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/ar/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/ar/NonVisibleControlContainer',{});
},
'Sage/QuickForms/Design/nls/ar-ly/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/ar-ly/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/ar/Name':function(){
define('Sage/UI/Controls/nls/ar/Name',{});
},
'Sage/UI/Controls/nls/ar-ly/Name':function(){
define('Sage/UI/Controls/nls/ar-ly/Name',{});
},
'Sage/MainView/JobMgr/nls/ar/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar/ExecutionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/ar-ly/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar-ly/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ar/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/PhoneControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-ly/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-ly/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/ar/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/ar/UpdateLeads',{});
},
'Sage/MainView/Lead/nls/ar-ly/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/ar-ly/UpdateLeads',{});
},
'Sage/Library/nls/ar/FileHandler':function(){
define('Sage/Library/nls/ar/FileHandler',{});
},
'Sage/Library/nls/ar-ly/FileHandler':function(){
define('Sage/Library/nls/ar-ly/FileHandler',{});
},
'Sage/UI/nls/ar/ListPanel':function(){
define('Sage/UI/nls/ar/ListPanel',{});
},
'Sage/UI/nls/ar-ly/ListPanel':function(){
define('Sage/UI/nls/ar-ly/ListPanel',{});
},
'Sage/Utility/nls/ar/Sql':function(){
define('Sage/Utility/nls/ar/Sql',{});
},
'Sage/Utility/nls/ar-ly/Sql':function(){
define('Sage/Utility/nls/ar-ly/Sql',{});
},
'Sage/UI/Filters/nls/ar/EditFilters':function(){
define('Sage/UI/Filters/nls/ar/EditFilters',{});
},
'Sage/UI/Filters/nls/ar-ly/EditFilters':function(){
define('Sage/UI/Filters/nls/ar-ly/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/FormUsagesPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ly/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ly/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/ar/DurationSelect':function(){
define('Sage/UI/Controls/nls/ar/DurationSelect',{});
},
'Sage/UI/Controls/nls/ar-ly/DurationSelect':function(){
define('Sage/UI/Controls/nls/ar-ly/DurationSelect',{});
},
'Sage/UI/Alarms/nls/ar/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/ar/AlarmCountDown',{});
},
'Sage/UI/Alarms/nls/ar-ly/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/ar-ly/AlarmCountDown',{});
},
'Sage/UI/nls/ar/AttachmentList':function(){
define('Sage/UI/nls/ar/AttachmentList',{});
},
'Sage/UI/nls/ar-ly/AttachmentList':function(){
define('Sage/UI/nls/ar-ly/AttachmentList',{});
},
'Sage/MailMerge/nls/ar/Lookup':function(){
define('Sage/MailMerge/nls/ar/Lookup',{});
},
'Sage/MailMerge/nls/ar-ly/Lookup':function(){
define('Sage/MailMerge/nls/ar-ly/Lookup',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ly/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ly/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ar/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/ar/RunJobDialog',{});
},
'Sage/MainView/JobMgr/nls/ar-ly/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/ar-ly/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/ar/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-ly/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-ly/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-ly/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-ly/EditableGridControlDesigner',{});
},
'Sage/MainView/Options/nls/ar/OptionsDialog':function(){
define('Sage/MainView/Options/nls/ar/OptionsDialog',{});
},
'Sage/MainView/Options/nls/ar-ly/OptionsDialog':function(){
define('Sage/MainView/Options/nls/ar-ly/OptionsDialog',{});
},
'Sage/QuickForms/Design/nls/ar/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/HiddenControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-ly/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-ly/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/ar/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/ar/DashboardWidgetCell',{});
},
'Sage/UI/Dashboard/nls/ar-ly/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/ar-ly/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/UserBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ly/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ly/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/ar/Dialogs':function(){
define('Sage/UI/nls/ar/Dialogs',{});
},
'Sage/UI/nls/ar-ly/Dialogs':function(){
define('Sage/UI/nls/ar-ly/Dialogs',{});
},
'Sage/MainView/IntegrationContract/nls/ar/SyncResultsHistory':function(){
define('Sage/MainView/IntegrationContract/nls/ar/SyncResultsHistory',{});
},
'Sage/MainView/IntegrationContract/nls/ar-ly/SyncResultsHistory':function(){
define('Sage/MainView/IntegrationContract/nls/ar-ly/SyncResultsHistory',{});
},
'Sage/TaskPane/nls/ar/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/ar/SecuredActionTasklet',{});
},
'Sage/TaskPane/nls/ar-ly/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/ar-ly/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/ar/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/ar/DashboardTabController',{});
},
'Sage/UI/Dashboard/nls/ar-ly/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/ar-ly/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/ar/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar/SalesOrderRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/ar-ly/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar-ly/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/ar/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/UserControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-ly/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-ly/UserControlDesigner',{});
},
'Sage/Groups/nls/ar/GroupNavigator':function(){
define('Sage/Groups/nls/ar/GroupNavigator',{});
},
'Sage/Groups/nls/ar-ly/GroupNavigator':function(){
define('Sage/Groups/nls/ar-ly/GroupNavigator',{});
},
'Sage/Utility/File/nls/ar/AddURLAttachment':function(){
define('Sage/Utility/File/nls/ar/AddURLAttachment',{});
},
'Sage/Utility/File/nls/ar-ly/AddURLAttachment':function(){
define('Sage/Utility/File/nls/ar-ly/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/ar/EditFilterItems':function(){
define('Sage/UI/Filters/nls/ar/EditFilterItems',{});
},
'Sage/UI/Filters/nls/ar-ly/EditFilterItems':function(){
define('Sage/UI/Filters/nls/ar-ly/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportsFormatter',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-ly/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-ly/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/ar/DragDropWatcher':function(){
define('Sage/Utility/File/nls/ar/DragDropWatcher',{});
},
'Sage/Utility/File/nls/ar-ly/DragDropWatcher':function(){
define('Sage/Utility/File/nls/ar-ly/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/ar/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/ar/DesignSurface',{});
},
'Sage/QuickForms/Design/nls/ar-ly/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/ar-ly/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ly/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ly/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/FormAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ly/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ly/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/EventListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ly/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ly/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ar/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ar/AllOpenListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ar-ly/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ar-ly/AllOpenListPanelConfig',{});
},
'Sage/MainView/nls/ar/FormManager':function(){
define('Sage/MainView/nls/ar/FormManager',{});
},
'Sage/MainView/nls/ar-ly/FormManager':function(){
define('Sage/MainView/nls/ar-ly/FormManager',{});
},
'Sage/UI/nls/ar/ActivityScheduler':function(){
define('Sage/UI/nls/ar/ActivityScheduler',{});
},
'Sage/UI/nls/ar-ly/ActivityScheduler':function(){
define('Sage/UI/nls/ar-ly/ActivityScheduler',{});
},
'Sage/MainView/nls/ar/SecurityManager':function(){
define('Sage/MainView/nls/ar/SecurityManager',{});
},
'Sage/MainView/nls/ar-ly/SecurityManager':function(){
define('Sage/MainView/nls/ar-ly/SecurityManager',{});
},
'Sage/TaskPane/nls/ar/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/ar/ActivityTaskConfigurationProvider',{});
},
'Sage/TaskPane/nls/ar-ly/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/ar-ly/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/ar/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/ar/EntityInfoToolTip',{});
},
'Sage/UI/Controls/nls/ar-ly/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/ar-ly/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ly/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ly/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar/AllOpenDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar/AllOpenDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar-ly/AllOpenDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar-ly/AllOpenDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar/ReportsListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar/ReportsListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar-ly/ReportsListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar-ly/ReportsListSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/ar/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/ar/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/Common/nls/ar-ly/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/ar-ly/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar/ScheduleDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar/ScheduleDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar-ly/ScheduleDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar-ly/ScheduleDetailSummary',{});
},
'Sage/MainView/Opportunity/nls/ar/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/ar/UpdateOpportunities',{});
},
'Sage/MainView/Opportunity/nls/ar-ly/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/ar-ly/UpdateOpportunities',{});
},
'Sage/UI/nls/ar/EditCalendarUsers':function(){
define('Sage/UI/nls/ar/EditCalendarUsers',{});
},
'Sage/UI/nls/ar-ly/EditCalendarUsers':function(){
define('Sage/UI/nls/ar-ly/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportParametersDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-ly/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-ly/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/ar/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/DateTimePickerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-ly/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-ly/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/ar/HelpMenu':function(){
define('Sage/UI/Controls/nls/ar/HelpMenu',{});
},
'Sage/UI/Controls/nls/ar-ly/HelpMenu':function(){
define('Sage/UI/Controls/nls/ar-ly/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/LayoutPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ly/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ly/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/ar/UserTasklet':function(){
define('Sage/TaskPane/nls/ar/UserTasklet',{});
},
'Sage/TaskPane/nls/ar-ly/UserTasklet':function(){
define('Sage/TaskPane/nls/ar-ly/UserTasklet',{});
},
'Sage/UI/Alarms/nls/ar/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/ar/ActivityAlarm',{});
},
'Sage/UI/Alarms/nls/ar-ly/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/ar-ly/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/ar/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/ar/OpportunityStatistics',{});
},
'Sage/MainView/Opportunity/nls/ar-ly/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/ar-ly/OpportunityStatistics',{});
},
'Sage/TaskPane/nls/ar/GroupListTasklet':function(){
define('Sage/TaskPane/nls/ar/GroupListTasklet',{});
},
'Sage/TaskPane/nls/ar-ly/GroupListTasklet':function(){
define('Sage/TaskPane/nls/ar-ly/GroupListTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportConditionEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-ly/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-ly/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ar/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/ar/AdvancedSearchOptions',{});
},
'Sage/MainView/IntegrationContract/nls/ar-ly/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/ar-ly/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/ar/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/ColumnDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-ly/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-ly/ColumnDesigner',{});
},
'Sage/MainView/JobMgr/templates/nls/ar/JobDefinitionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar/JobDefinitionDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/ar-ly/JobDefinitionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar-ly/JobDefinitionDetailSummary',{});
},
'Sage/UI/nls/ar/SearchMenuItem':function(){
define('Sage/UI/nls/ar/SearchMenuItem',{});
},
'Sage/UI/nls/ar-ly/SearchMenuItem':function(){
define('Sage/UI/nls/ar-ly/SearchMenuItem',{});
},
'Sage/Library/nls/ar/DocumentProperties':function(){
define('Sage/Library/nls/ar/DocumentProperties',{});
},
'Sage/Library/nls/ar-ly/DocumentProperties':function(){
define('Sage/Library/nls/ar-ly/DocumentProperties',{});
},
'Sage/UI/nls/ar/NotesHistoryList':function(){
define('Sage/UI/nls/ar/NotesHistoryList',{});
},
'Sage/UI/nls/ar-ly/NotesHistoryList':function(){
define('Sage/UI/nls/ar-ly/NotesHistoryList',{});
},
'Sage/Utility/nls/ar/File':function(){
define('Sage/Utility/nls/ar/File',{});
},
'Sage/Utility/nls/ar-ly/File':function(){
define('Sage/Utility/nls/ar-ly/File',{});
},
'Sage/MainView/ReportMgr/nls/ar/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/ar-ly/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar-ly/HistoryListPanelConfig',{});
},
'Sage/MainView/JobMgr/templates/nls/ar/ScheduleDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar/ScheduleDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/ar-ly/ScheduleDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar-ly/ScheduleDetailSummary',{});
},
'Sage/QuickForms/Design/nls/ar/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/UrlControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-ly/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-ly/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/ar/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/ContactTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-ly/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-ly/ContactTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar/EventSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar/EventSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar-ly/EventSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar-ly/EventSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/ar/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/ar/_WizardDialogBase',{});
},
'Sage/MainView/ReportMgr/Common/nls/ar-ly/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/ar-ly/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/ar/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar/SchedulesListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/ar-ly/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar-ly/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/ar/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/ar/GoogleDocPicker',{});
},
'Sage/Utility/File/nls/ar-ly/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/ar-ly/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/ar/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/ComboBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-ly/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-ly/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/ar/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ly/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ly/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/HistoryEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ly/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ly/HistoryEditor',{});
},
'Sage/Groups/nls/ar/GroupManager':function(){
define('Sage/Groups/nls/ar/GroupManager',{});
},
'Sage/Groups/nls/ar-ly/GroupManager':function(){
define('Sage/Groups/nls/ar-ly/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ly/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ly/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/ComboBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ly/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ly/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ar/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar/ReportsListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/ar-ly/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar-ly/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/ar/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/ar/JobNotificationButton',{});
},
'Sage/UI/Alarms/nls/ar-ly/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/ar-ly/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportWizardController',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-ly/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-ly/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/ar/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/ar-ly/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar-ly/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/RecurringEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ly/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ly/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportsUtility',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-ly/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-ly/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ly/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ly/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ar/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/ar-ly/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar-ly/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ar/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-ly/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-ly/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-ly/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-ly/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-ly/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-ly/PickListControlDesigner',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar/LitRequestSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar/LitRequestSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ar-ly/LitRequestSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ar-ly/LitRequestSummary',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ly/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ly/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/ar/FolderHandler':function(){
define('Sage/Library/nls/ar/FolderHandler',{});
},
'Sage/Library/nls/ar-ly/FolderHandler':function(){
define('Sage/Library/nls/ar-ly/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ly/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ly/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/ar/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/ar/ContactSearchForDuplicates',{});
},
'Sage/MainView/Contact/nls/ar-ly/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/ar-ly/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/DateTimePickerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ly/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ly/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/ar/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/AccountingTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-ly/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-ly/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ly/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ly/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/CurrencyBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ly/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ly/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/ar/EditableGrid':function(){
define('Sage/UI/nls/ar/EditableGrid',{});
},
'Sage/UI/nls/ar-ly/EditableGrid':function(){
define('Sage/UI/nls/ar-ly/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/ar/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar/SalesQuoteRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/ar-ly/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar-ly/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/ar/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/ar/SecurityProfile',{});
},
'Sage/MainView/SecurityMgr/nls/ar-ly/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/ar-ly/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/ar/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/ar/ReportWizardController',{});
},
'Sage/MainView/ReportMgr/nls/ar-ly/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/ar-ly/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/UserAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ly/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ly/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ar/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/ar/ReportManagerUtility',{});
},
'Sage/MainView/ReportMgr/nls/ar-ly/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/ar-ly/ReportManagerUtility',{});
},
'Sage/UI/nls/ar/SpeedSearch':function(){
define('Sage/UI/nls/ar/SpeedSearch',{});
},
'Sage/UI/nls/ar-ly/SpeedSearch':function(){
define('Sage/UI/nls/ar-ly/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/CurrencyAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ly/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ly/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/ar/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/ReportManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-ly/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-ly/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/ar/SLXPreviewGrid':function(){
define('Sage/UI/nls/ar/SLXPreviewGrid',{});
},
'Sage/UI/nls/ar-ly/SLXPreviewGrid':function(){
define('Sage/UI/nls/ar-ly/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/ar/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/ar/UnconfirmedPane',{});
},
'Sage/UI/Alarms/nls/ar-ly/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/ar-ly/UnconfirmedPane',{});
},
'Sage/Utility/nls/ar/Utility':function(){
define('Sage/Utility/nls/ar/Utility',{});
},
'Sage/Utility/nls/ar-ly/Utility':function(){
define('Sage/Utility/nls/ar-ly/Utility',{});
},
'Sage/QuickForms/Design/nls/ar/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/ControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-ly/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-ly/ControlDesigner',{});
},
'Sage/UI/Controls/nls/ar/Address':function(){
define('Sage/UI/Controls/nls/ar/Address',{});
},
'Sage/UI/Controls/nls/ar-ly/Address':function(){
define('Sage/UI/Controls/nls/ar-ly/Address',{});
},
'Sage/MainView/JobMgr/nls/ar/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/ar/JobManagerGroupContextService',{});
},
'Sage/MainView/JobMgr/nls/ar-ly/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/ar-ly/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/ar/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/BaseListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ly/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ly/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ar/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/OwnerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-ly/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-ly/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/ar/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/JobManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-ly/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-ly/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ly/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ly/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/ar/UserType':function(){
define('Sage/UI/nls/ar/UserType',{});
},
'Sage/UI/nls/ar-ly/UserType':function(){
define('Sage/UI/nls/ar-ly/UserType',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar/HistoryDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar/HistoryDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar-ly/HistoryDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar-ly/HistoryDetailSummary',{});
},
'Sage/QuickForms/Design/nls/ar/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/FormDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-ly/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-ly/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityCalendar',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ly/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ly/ActivityCalendar',{});
},
'Sage/Utility/nls/ar/Jobs':function(){
define('Sage/Utility/nls/ar/Jobs',{});
},
'Sage/Utility/nls/ar-ly/Jobs':function(){
define('Sage/Utility/nls/ar-ly/Jobs',{});
},
'Sage/UI/Controls/nls/ar/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/ar/_DialogHelpIconMixin',{});
},
'Sage/UI/Controls/nls/ar-ly/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/ar-ly/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/PickListAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ly/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ly/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/ar/ActivityList':function(){
define('Sage/UI/nls/ar/ActivityList',{});
},
'Sage/UI/nls/ar-ly/ActivityList':function(){
define('Sage/UI/nls/ar-ly/ActivityList',{});
},
'Sage/UI/Alarms/nls/ar/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/ar/JobNotificationPopup',{});
},
'Sage/UI/Alarms/nls/ar-ly/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/ar-ly/JobNotificationPopup',{});
},
'Sage/MainView/JobMgr/templates/nls/ar/ExecutionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar/ExecutionsListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/ar-ly/ExecutionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar-ly/ExecutionsListSummary',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar/LeadLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar-ly/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar-ly/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/ar/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar/SchedulesListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/ar-ly/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar-ly/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/GenericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ly/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ly/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/ar/CalendarUsersListPane':function(){
define('Sage/UI/nls/ar/CalendarUsersListPane',{});
},
'Sage/UI/nls/ar-ly/CalendarUsersListPane':function(){
define('Sage/UI/nls/ar-ly/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ly/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ly/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/ColumnBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ly/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ly/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/templates/nls/ar/ExecutionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar/ExecutionDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/ar-ly/ExecutionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ar-ly/ExecutionDetailSummary',{});
},
'Sage/MainView/ReportMgr/nls/ar/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/ar/ReportManagerGroupContextService',{});
},
'Sage/MainView/ReportMgr/nls/ar-ly/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/ar-ly/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/ar/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/ar/MatchingOptionsConfig',{});
},
'Sage/MainView/IntegrationContract/nls/ar-ly/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/ar-ly/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/FormBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ly/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ly/FormBasicPropertyEditor',{});
},
'Sage/UI/Alarms/nls/ar/AlarmButton':function(){
define('Sage/UI/Alarms/nls/ar/AlarmButton',{});
},
'Sage/UI/Alarms/nls/ar-ly/AlarmButton':function(){
define('Sage/UI/Alarms/nls/ar-ly/AlarmButton',{});
},
'Sage/MainView/ActivityMgr/nls/ar/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/ar/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ly/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ly/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/ar/Attachment':function(){
define('Sage/Utility/File/nls/ar/Attachment',{});
},
'Sage/Utility/File/nls/ar-ly/Attachment':function(){
define('Sage/Utility/File/nls/ar-ly/Attachment',{});
},
'Sage/QuickForms/Design/nls/ar/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-ly/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-ly/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/ar/PropertyEditorContainer',{});
},
'Sage/QuickForms/Design/nls/ar-ly/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/ar-ly/PropertyEditorContainer',{});
},
'Sage/Services/nls/ar/ReportingService':function(){
define('Sage/Services/nls/ar/ReportingService',{});
},
'Sage/Services/nls/ar-ly/ReportingService':function(){
define('Sage/Services/nls/ar-ly/ReportingService',{});
},
'Sage/MailMerge/nls/ar/Helper':function(){
define('Sage/MailMerge/nls/ar/Helper',{});
},
'Sage/MailMerge/nls/ar-ly/Helper':function(){
define('Sage/MailMerge/nls/ar-ly/Helper',{});
},
'Sage/UI/Dashboard/nls/ar/Dashboard':function(){
define('Sage/UI/Dashboard/nls/ar/Dashboard',{});
},
'Sage/UI/Dashboard/nls/ar-ly/Dashboard':function(){
define('Sage/UI/Dashboard/nls/ar-ly/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ly/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ly/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/ar/PickList':function(){
define('Sage/UI/Controls/nls/ar/PickList',{});
},
'Sage/UI/Controls/nls/ar-ly/PickList':function(){
define('Sage/UI/Controls/nls/ar-ly/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/ar/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ar/HistoryEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ly/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ly/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/ar/Email':function(){
define('Sage/Utility/nls/ar/Email',{});
},
'Sage/Utility/nls/ar-ly/Email':function(){
define('Sage/Utility/nls/ar-ly/Email',{});
},
'Sage/TaskPane/nls/ar/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/SecurityManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-ly/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-ly/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/ar/TimeZoneItem':function(){
define('Sage/UI/nls/ar/TimeZoneItem',{});
},
'Sage/UI/nls/ar-ly/TimeZoneItem':function(){
define('Sage/UI/nls/ar-ly/TimeZoneItem',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar/HistoryListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar/HistoryListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ar-ly/HistoryListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ar-ly/HistoryListSummary',{});
},
'Sage/UI/Columns/nls/ar/SlxEdit':function(){
define('Sage/UI/Columns/nls/ar/SlxEdit',{});
},
'Sage/UI/Columns/nls/ar-ly/SlxEdit':function(){
define('Sage/UI/Columns/nls/ar-ly/SlxEdit',{});
},
'Sage/Reporting/nls/ar/Enumerations':function(){
define('Sage/Reporting/nls/ar/Enumerations',{});
},
'Sage/Reporting/nls/ar-ly/Enumerations':function(){
define('Sage/Reporting/nls/ar-ly/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ly/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ly/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportConditionsDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-ly/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-ly/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ar/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ar/ActivityListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ar-ly/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ar-ly/ActivityListPanelConfig',{});
},
'Sage/UI/nls/ar/JobSchedulingWidget':function(){
define('Sage/UI/nls/ar/JobSchedulingWidget',{});
},
'Sage/UI/nls/ar-ly/JobSchedulingWidget':function(){
define('Sage/UI/nls/ar-ly/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/ar/LogOffButton':function(){
define('Sage/UI/Controls/nls/ar/LogOffButton',{});
},
'Sage/UI/Controls/nls/ar-ly/LogOffButton':function(){
define('Sage/UI/Controls/nls/ar-ly/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/TextBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ly/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ly/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/EditEventEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ly/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ly/EditEventEditor',{});
},
'Sage/MailMerge/nls/ar/Loader':function(){
define('Sage/MailMerge/nls/ar/Loader',{});
},
'Sage/MailMerge/nls/ar-ly/Loader':function(){
define('Sage/MailMerge/nls/ar-ly/Loader',{});
},
'Sage/UI/Controls/nls/ar/DateTimePicker':function(){
define('Sage/UI/Controls/nls/ar/DateTimePicker',{});
},
'Sage/UI/Controls/nls/ar-ly/DateTimePicker':function(){
define('Sage/UI/Controls/nls/ar-ly/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/ar/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/ar/ReportManagerActions',{});
},
'Sage/MainView/ReportMgr/nls/ar-ly/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/ar-ly/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/ar/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/ar/AlarmPopup',{});
},
'Sage/UI/Alarms/nls/ar-ly/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/ar-ly/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/ar/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/ar/ContactUserAssociationEditor',{});
},
'Sage/MainView/Contact/nls/ar-ly/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/ar-ly/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ly/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ly/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ar/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar/BaseListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/ar-ly/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar-ly/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ar/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-ly/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-ly/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/EmailControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-ly/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-ly/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/ar/Lookup':function(){
define('Sage/UI/Controls/nls/ar/Lookup',{});
},
'Sage/UI/Controls/nls/ar-ly/Lookup':function(){
define('Sage/UI/Controls/nls/ar-ly/Lookup',{});
},
'Sage/Utility/File/nls/ar/DescriptionsForm':function(){
define('Sage/Utility/File/nls/ar/DescriptionsForm',{});
},
'Sage/Utility/File/nls/ar-ly/DescriptionsForm':function(){
define('Sage/Utility/File/nls/ar-ly/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/NumericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-ly/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-ly/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/ar/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/CommonTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-ly/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-ly/CommonTasksTasklet',{});
},
'Sage/Utility/nls/ar/Dashboard':function(){
define('Sage/Utility/nls/ar/Dashboard',{});
},
'Sage/Utility/nls/ar-ly/Dashboard':function(){
define('Sage/Utility/nls/ar-ly/Dashboard',{});
}}});
define("Sage/nls/Sage_ar-ly", [], 1);
