require({cache:{
'Sage/Utility/File/nls/no/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/no/FallbackFilePicker',{});
},
'Sage/UI/nls/no/Boolean':function(){
define('Sage/UI/nls/no/Boolean',{});
},
'Sage/Services/nls/no/ActivityService':function(){
define('Sage/Services/nls/no/ActivityService',{});
},
'Sage/UI/Controls/nls/no/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/no/CopyToClipboard',{});
},
'Sage/Utility/nls/no/Activity':function(){
define('Sage/Utility/nls/no/Activity',{});
},
'Sage/QuickForms/Design/nls/no/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/no/DesignPanel',{});
},
'Sage/UI/nls/no/TimelessActivitiesPane':function(){
define('Sage/UI/nls/no/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/no/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/no/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/no/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/no/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/no/ActivityManager':function(){
define('Sage/MainView/nls/no/ActivityManager',{});
},
'Sage/Services/nls/no/JobService':function(){
define('Sage/Services/nls/no/JobService',{});
},
'Sage/QuickForms/Design/nls/no/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/no/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/no/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/no/_PropertyEditor',{});
},
'Sage/Services/nls/no/ActivityActionProcessor':function(){
define('Sage/Services/nls/no/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/no/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/no/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/no/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/no/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/templates/nls/no/UserActivityDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/no/UserActivityDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/no/ConfirmationDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/no/ConfirmationDetailSummary',{});
},
'Sage/Utility/File/nls/no/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/no/DefaultDropHandler',{});
},
'Sage/UI/nls/no/TransferBoxWidget':function(){
define('Sage/UI/nls/no/TransferBoxWidget',{});
},
'Sage/Utility/File/nls/no/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/no/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/no/AlarmPane':function(){
define('Sage/UI/Alarms/nls/no/AlarmPane',{});
},
'Sage/TaskPane/nls/no/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/no/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/no/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/no/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/no/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/no/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/no/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/no/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/no/FilterPanel':function(){
define('Sage/UI/Filters/nls/no/FilterPanel',{});
},
'Sage/TaskPane/nls/no/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/no/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/no/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/no/ReportManagerFormatter',{});
},
'Sage/UI/nls/no/OwnerType':function(){
define('Sage/UI/nls/no/OwnerType',{});
},
'Sage/MainView/JobMgr/templates/nls/no/JobDefinitionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/no/JobDefinitionsListSummary',{});
},
'Sage/TaskPane/nls/no/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/no/LeadTasksTasklet',{});
},
'Sage/MainView/ReportMgr/templates/nls/no/ReportDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/no/ReportDetailSummary',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/no/_ParameterEditorBase':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/no/_ParameterEditorBase',{});
},
'Sage/MailMerge/nls/no/Service':function(){
define('Sage/MailMerge/nls/no/Service',{});
},
'Sage/MainView/ActivityMgr/templates/nls/no/ConfirmationListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/no/ConfirmationListSummary',{});
},
'Sage/MainView/ActivityMgr/nls/no/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/no/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/no/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/no/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/no/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/no/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/no/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/no/InvoiceRTDV',{});
},
'Sage/UI/nls/no/SDataLookup':function(){
define('Sage/UI/nls/no/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/no/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/no/RowDesigner',{});
},
'Sage/Groups/nls/no/GroupLookup':function(){
define('Sage/Groups/nls/no/GroupLookup',{});
},
'Sage/TaskPane/nls/no/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/no/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/no/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/no/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/no/LibraryDocument':function(){
define('Sage/Utility/File/nls/no/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/no/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/no/SpeedSearchLookup',{});
},
'Sage/UI/nls/no/ConditionManager':function(){
define('Sage/UI/nls/no/ConditionManager',{});
},
'Sage/MainView/JobMgr/templates/nls/no/SchedulesListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/no/SchedulesListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/no/UserActivityListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/no/UserActivityListSummary',{});
},
'Sage/UI/Dashboard/nls/no/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/no/WidgetDefinition',{});
},
'Sage/MainView/ActivityMgr/templates/nls/no/AllOpenListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/no/AllOpenListSummary',{});
},
'Sage/UI/nls/no/SearchConditionWidget':function(){
define('Sage/UI/nls/no/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/no/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/no/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/no/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/no/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/no/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/no/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/no/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/no/DataSourcePanel',{});
},
'Sage/MainView/ReportMgr/templates/nls/no/SchedulesListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/no/SchedulesListSummary',{});
},
'Sage/Library/nls/no/Manager':function(){
define('Sage/Library/nls/no/Manager',{});
},
'Sage/UI/nls/no/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/no/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/no/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/no/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/no/Name':function(){
define('Sage/UI/Controls/nls/no/Name',{});
},
'Sage/MainView/JobMgr/nls/no/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/no/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/no/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/no/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/no/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/no/UpdateLeads',{});
},
'Sage/Library/nls/no/FileHandler':function(){
define('Sage/Library/nls/no/FileHandler',{});
},
'Sage/UI/nls/no/ListPanel':function(){
define('Sage/UI/nls/no/ListPanel',{});
},
'Sage/Utility/nls/no/Sql':function(){
define('Sage/Utility/nls/no/Sql',{});
},
'Sage/UI/Filters/nls/no/EditFilters':function(){
define('Sage/UI/Filters/nls/no/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/no/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/no/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/no/DurationSelect':function(){
define('Sage/UI/Controls/nls/no/DurationSelect',{});
},
'Sage/UI/Alarms/nls/no/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/no/AlarmCountDown',{});
},
'Sage/UI/nls/no/AttachmentList':function(){
define('Sage/UI/nls/no/AttachmentList',{});
},
'Sage/MailMerge/nls/no/Lookup':function(){
define('Sage/MailMerge/nls/no/Lookup',{});
},
'Sage/QuickForms/Design/Editors/nls/no/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/no/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/no/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/no/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/no/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/no/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/no/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/no/EditableGridControlDesigner',{});
},
'Sage/MainView/Options/nls/no/OptionsDialog':function(){
define('Sage/MainView/Options/nls/no/OptionsDialog',{});
},
'Sage/QuickForms/Design/nls/no/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/no/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/no/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/no/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/no/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/no/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/no/Dialogs':function(){
define('Sage/UI/nls/no/Dialogs',{});
},
'Sage/MainView/IntegrationContract/nls/no/SyncResultsHistory':function(){
define('Sage/MainView/IntegrationContract/nls/no/SyncResultsHistory',{});
},
'Sage/TaskPane/nls/no/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/no/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/no/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/no/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/no/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/no/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/no/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/no/UserControlDesigner',{});
},
'Sage/Groups/nls/no/GroupNavigator':function(){
define('Sage/Groups/nls/no/GroupNavigator',{});
},
'Sage/Utility/File/nls/no/AddURLAttachment':function(){
define('Sage/Utility/File/nls/no/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/no/EditFilterItems':function(){
define('Sage/UI/Filters/nls/no/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/no/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/no/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/no/DragDropWatcher':function(){
define('Sage/Utility/File/nls/no/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/no/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/no/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/no/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/no/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/no/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/no/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/no/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/no/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/no/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/no/AllOpenListPanelConfig',{});
},
'Sage/MainView/nls/no/FormManager':function(){
define('Sage/MainView/nls/no/FormManager',{});
},
'Sage/UI/nls/no/ActivityScheduler':function(){
define('Sage/UI/nls/no/ActivityScheduler',{});
},
'Sage/MainView/nls/no/SecurityManager':function(){
define('Sage/MainView/nls/no/SecurityManager',{});
},
'Sage/TaskPane/nls/no/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/no/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/no/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/no/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/no/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/no/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/templates/nls/no/AllOpenDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/no/AllOpenDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/no/ReportsListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/no/ReportsListSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/no/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/no/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/templates/nls/no/ScheduleDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/no/ScheduleDetailSummary',{});
},
'Sage/MainView/Opportunity/nls/no/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/no/UpdateOpportunities',{});
},
'Sage/UI/nls/no/EditCalendarUsers':function(){
define('Sage/UI/nls/no/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/no/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/no/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/no/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/no/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/no/HelpMenu':function(){
define('Sage/UI/Controls/nls/no/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/no/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/no/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/no/UserTasklet':function(){
define('Sage/TaskPane/nls/no/UserTasklet',{});
},
'Sage/UI/Alarms/nls/no/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/no/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/no/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/no/OpportunityStatistics',{});
},
'Sage/TaskPane/nls/no/GroupListTasklet':function(){
define('Sage/TaskPane/nls/no/GroupListTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/no/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/no/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/no/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/no/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/no/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/no/ColumnDesigner',{});
},
'Sage/MainView/JobMgr/templates/nls/no/JobDefinitionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/no/JobDefinitionDetailSummary',{});
},
'Sage/UI/nls/no/SearchMenuItem':function(){
define('Sage/UI/nls/no/SearchMenuItem',{});
},
'Sage/Library/nls/no/DocumentProperties':function(){
define('Sage/Library/nls/no/DocumentProperties',{});
},
'Sage/UI/nls/no/NotesHistoryList':function(){
define('Sage/UI/nls/no/NotesHistoryList',{});
},
'Sage/Utility/nls/no/File':function(){
define('Sage/Utility/nls/no/File',{});
},
'Sage/MainView/ReportMgr/nls/no/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/no/HistoryListPanelConfig',{});
},
'Sage/MainView/JobMgr/templates/nls/no/ScheduleDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/no/ScheduleDetailSummary',{});
},
'Sage/QuickForms/Design/nls/no/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/no/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/no/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/no/ContactTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/templates/nls/no/EventSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/no/EventSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/no/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/no/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/no/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/no/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/no/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/no/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/no/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/no/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/no/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/no/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/no/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/no/HistoryEditor',{});
},
'Sage/Groups/nls/no/GroupManager':function(){
define('Sage/Groups/nls/no/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/no/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/no/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/no/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/no/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/no/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/no/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/no/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/no/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/no/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/no/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/no/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/no/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/no/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/no/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/no/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/no/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/no/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/no/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/no/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/no/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/no/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/no/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/no/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/no/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/no/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/no/PickListControlDesigner',{});
},
'Sage/MainView/ActivityMgr/templates/nls/no/LitRequestSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/no/LitRequestSummary',{});
},
'Sage/QuickForms/Design/Editors/nls/no/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/no/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/no/FolderHandler':function(){
define('Sage/Library/nls/no/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/no/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/no/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/no/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/no/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/no/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/no/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/no/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/no/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/no/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/no/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/no/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/no/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/no/EditableGrid':function(){
define('Sage/UI/nls/no/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/no/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/no/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/no/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/no/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/no/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/no/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/no/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/no/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/no/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/no/ReportManagerUtility',{});
},
'Sage/UI/nls/no/SpeedSearch':function(){
define('Sage/UI/nls/no/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/no/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/no/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/no/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/no/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/no/SLXPreviewGrid':function(){
define('Sage/UI/nls/no/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/no/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/no/UnconfirmedPane',{});
},
'Sage/Utility/nls/no/Utility':function(){
define('Sage/Utility/nls/no/Utility',{});
},
'Sage/QuickForms/Design/nls/no/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/no/ControlDesigner',{});
},
'Sage/UI/Controls/nls/no/Address':function(){
define('Sage/UI/Controls/nls/no/Address',{});
},
'Sage/MainView/JobMgr/nls/no/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/no/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/no/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/no/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/no/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/no/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/no/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/no/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/no/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/no/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/no/UserType':function(){
define('Sage/UI/nls/no/UserType',{});
},
'Sage/MainView/ReportMgr/templates/nls/no/HistoryDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/no/HistoryDetailSummary',{});
},
'Sage/QuickForms/Design/nls/no/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/no/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/no/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/no/ActivityCalendar',{});
},
'Sage/Utility/nls/no/Jobs':function(){
define('Sage/Utility/nls/no/Jobs',{});
},
'Sage/UI/Controls/nls/no/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/no/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/no/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/no/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/no/ActivityList':function(){
define('Sage/UI/nls/no/ActivityList',{});
},
'Sage/UI/Alarms/nls/no/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/no/JobNotificationPopup',{});
},
'Sage/MainView/JobMgr/templates/nls/no/ExecutionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/no/ExecutionsListSummary',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/no/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/no/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/no/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/no/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/no/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/no/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/no/CalendarUsersListPane':function(){
define('Sage/UI/nls/no/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/no/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/no/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/no/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/no/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/templates/nls/no/ExecutionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/no/ExecutionDetailSummary',{});
},
'Sage/MainView/ReportMgr/nls/no/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/no/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/no/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/no/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/no/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/no/FormBasicPropertyEditor',{});
},
'Sage/UI/Alarms/nls/no/AlarmButton':function(){
define('Sage/UI/Alarms/nls/no/AlarmButton',{});
},
'Sage/MainView/ActivityMgr/nls/no/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/no/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/no/Attachment':function(){
define('Sage/Utility/File/nls/no/Attachment',{});
},
'Sage/QuickForms/Design/nls/no/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/no/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/no/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/no/PropertyEditorContainer',{});
},
'Sage/Services/nls/no/ReportingService':function(){
define('Sage/Services/nls/no/ReportingService',{});
},
'Sage/MailMerge/nls/no/Helper':function(){
define('Sage/MailMerge/nls/no/Helper',{});
},
'Sage/UI/Dashboard/nls/no/Dashboard':function(){
define('Sage/UI/Dashboard/nls/no/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/no/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/no/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/no/PickList':function(){
define('Sage/UI/Controls/nls/no/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/no/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/no/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/no/Email':function(){
define('Sage/Utility/nls/no/Email',{});
},
'Sage/TaskPane/nls/no/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/no/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/no/TimeZoneItem':function(){
define('Sage/UI/nls/no/TimeZoneItem',{});
},
'Sage/MainView/ReportMgr/templates/nls/no/HistoryListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/no/HistoryListSummary',{});
},
'Sage/UI/Columns/nls/no/SlxEdit':function(){
define('Sage/UI/Columns/nls/no/SlxEdit',{});
},
'Sage/Reporting/nls/no/Enumerations':function(){
define('Sage/Reporting/nls/no/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/no/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/no/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/no/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/no/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/no/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/no/ActivityListPanelConfig',{});
},
'Sage/UI/nls/no/JobSchedulingWidget':function(){
define('Sage/UI/nls/no/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/no/LogOffButton':function(){
define('Sage/UI/Controls/nls/no/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/no/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/no/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/no/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/no/EditEventEditor',{});
},
'Sage/MailMerge/nls/no/Loader':function(){
define('Sage/MailMerge/nls/no/Loader',{});
},
'Sage/UI/Controls/nls/no/DateTimePicker':function(){
define('Sage/UI/Controls/nls/no/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/no/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/no/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/no/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/no/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/no/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/no/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/no/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/no/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/no/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/no/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/no/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/no/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/no/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/no/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/no/Lookup':function(){
define('Sage/UI/Controls/nls/no/Lookup',{});
},
'Sage/Utility/File/nls/no/DescriptionsForm':function(){
define('Sage/Utility/File/nls/no/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/no/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/no/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/no/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/no/CommonTasksTasklet',{});
},
'Sage/Utility/nls/no/Dashboard':function(){
define('Sage/Utility/nls/no/Dashboard',{});
}}});
define("Sage/nls/Sage_no", [], 1);
