require({cache:{
'Sage/Utility/File/nls/hr/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/hr/FallbackFilePicker',{});
},
'Sage/UI/nls/hr/Boolean':function(){
define('Sage/UI/nls/hr/Boolean',{});
},
'Sage/Services/nls/hr/ActivityService':function(){
define('Sage/Services/nls/hr/ActivityService',{});
},
'Sage/UI/Controls/nls/hr/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/hr/CopyToClipboard',{});
},
'Sage/Utility/nls/hr/Activity':function(){
define('Sage/Utility/nls/hr/Activity',{});
},
'Sage/QuickForms/Design/nls/hr/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/hr/DesignPanel',{});
},
'Sage/UI/nls/hr/TimelessActivitiesPane':function(){
define('Sage/UI/nls/hr/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/hr/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/hr/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/hr/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/hr/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/hr/ActivityManager':function(){
define('Sage/MainView/nls/hr/ActivityManager',{});
},
'Sage/Services/nls/hr/JobService':function(){
define('Sage/Services/nls/hr/JobService',{});
},
'Sage/QuickForms/Design/nls/hr/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hr/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/hr/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hr/_PropertyEditor',{});
},
'Sage/Services/nls/hr/ActivityActionProcessor':function(){
define('Sage/Services/nls/hr/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/hr/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hr/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/hr/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/hr/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/templates/nls/hr/UserActivityDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/hr/UserActivityDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/hr/ConfirmationDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/hr/ConfirmationDetailSummary',{});
},
'Sage/Utility/File/nls/hr/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/hr/DefaultDropHandler',{});
},
'Sage/UI/nls/hr/TransferBoxWidget':function(){
define('Sage/UI/nls/hr/TransferBoxWidget',{});
},
'Sage/Utility/File/nls/hr/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/hr/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/hr/AlarmPane':function(){
define('Sage/UI/Alarms/nls/hr/AlarmPane',{});
},
'Sage/TaskPane/nls/hr/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/hr/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/hr/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/hr/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/hr/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hr/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/hr/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/hr/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/hr/FilterPanel':function(){
define('Sage/UI/Filters/nls/hr/FilterPanel',{});
},
'Sage/TaskPane/nls/hr/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/hr/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/hr/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/hr/ReportManagerFormatter',{});
},
'Sage/UI/nls/hr/OwnerType':function(){
define('Sage/UI/nls/hr/OwnerType',{});
},
'Sage/MainView/JobMgr/templates/nls/hr/JobDefinitionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/hr/JobDefinitionsListSummary',{});
},
'Sage/TaskPane/nls/hr/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/hr/LeadTasksTasklet',{});
},
'Sage/MainView/ReportMgr/templates/nls/hr/ReportDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/hr/ReportDetailSummary',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/hr/_ParameterEditorBase':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/hr/_ParameterEditorBase',{});
},
'Sage/MailMerge/nls/hr/Service':function(){
define('Sage/MailMerge/nls/hr/Service',{});
},
'Sage/MainView/ActivityMgr/templates/nls/hr/ConfirmationListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/hr/ConfirmationListSummary',{});
},
'Sage/MainView/ActivityMgr/nls/hr/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/hr/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/hr/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hr/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/hr/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hr/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/hr/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/hr/InvoiceRTDV',{});
},
'Sage/UI/nls/hr/SDataLookup':function(){
define('Sage/UI/nls/hr/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/hr/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/hr/RowDesigner',{});
},
'Sage/Groups/nls/hr/GroupLookup':function(){
define('Sage/Groups/nls/hr/GroupLookup',{});
},
'Sage/TaskPane/nls/hr/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/hr/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/hr/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/hr/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/hr/LibraryDocument':function(){
define('Sage/Utility/File/nls/hr/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/hr/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/hr/SpeedSearchLookup',{});
},
'Sage/UI/nls/hr/ConditionManager':function(){
define('Sage/UI/nls/hr/ConditionManager',{});
},
'Sage/MainView/JobMgr/templates/nls/hr/SchedulesListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/hr/SchedulesListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/hr/UserActivityListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/hr/UserActivityListSummary',{});
},
'Sage/UI/Dashboard/nls/hr/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/hr/WidgetDefinition',{});
},
'Sage/MainView/ActivityMgr/templates/nls/hr/AllOpenListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/hr/AllOpenListSummary',{});
},
'Sage/UI/nls/hr/SearchConditionWidget':function(){
define('Sage/UI/nls/hr/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/hr/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hr/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/hr/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/hr/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/hr/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/hr/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/hr/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/hr/DataSourcePanel',{});
},
'Sage/MainView/ReportMgr/templates/nls/hr/SchedulesListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/hr/SchedulesListSummary',{});
},
'Sage/Library/nls/hr/Manager':function(){
define('Sage/Library/nls/hr/Manager',{});
},
'Sage/UI/nls/hr/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/hr/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/hr/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/hr/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/hr/Name':function(){
define('Sage/UI/Controls/nls/hr/Name',{});
},
'Sage/MainView/JobMgr/nls/hr/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/hr/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/hr/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hr/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/hr/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/hr/UpdateLeads',{});
},
'Sage/Library/nls/hr/FileHandler':function(){
define('Sage/Library/nls/hr/FileHandler',{});
},
'Sage/UI/nls/hr/ListPanel':function(){
define('Sage/UI/nls/hr/ListPanel',{});
},
'Sage/Utility/nls/hr/Sql':function(){
define('Sage/Utility/nls/hr/Sql',{});
},
'Sage/UI/Filters/nls/hr/EditFilters':function(){
define('Sage/UI/Filters/nls/hr/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/hr/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hr/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/hr/DurationSelect':function(){
define('Sage/UI/Controls/nls/hr/DurationSelect',{});
},
'Sage/UI/Alarms/nls/hr/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/hr/AlarmCountDown',{});
},
'Sage/UI/nls/hr/AttachmentList':function(){
define('Sage/UI/nls/hr/AttachmentList',{});
},
'Sage/MailMerge/nls/hr/Lookup':function(){
define('Sage/MailMerge/nls/hr/Lookup',{});
},
'Sage/QuickForms/Design/Editors/nls/hr/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hr/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/hr/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/hr/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/hr/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hr/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/hr/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hr/EditableGridControlDesigner',{});
},
'Sage/MainView/Options/nls/hr/OptionsDialog':function(){
define('Sage/MainView/Options/nls/hr/OptionsDialog',{});
},
'Sage/QuickForms/Design/nls/hr/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hr/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/hr/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/hr/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/hr/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hr/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/hr/Dialogs':function(){
define('Sage/UI/nls/hr/Dialogs',{});
},
'Sage/MainView/IntegrationContract/nls/hr/SyncResultsHistory':function(){
define('Sage/MainView/IntegrationContract/nls/hr/SyncResultsHistory',{});
},
'Sage/TaskPane/nls/hr/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/hr/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/hr/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/hr/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/hr/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/hr/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/hr/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hr/UserControlDesigner',{});
},
'Sage/Groups/nls/hr/GroupNavigator':function(){
define('Sage/Groups/nls/hr/GroupNavigator',{});
},
'Sage/Utility/File/nls/hr/AddURLAttachment':function(){
define('Sage/Utility/File/nls/hr/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/hr/EditFilterItems':function(){
define('Sage/UI/Filters/nls/hr/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/hr/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/hr/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/hr/DragDropWatcher':function(){
define('Sage/Utility/File/nls/hr/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/hr/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/hr/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/hr/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/hr/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/hr/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hr/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/hr/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/hr/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/hr/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/hr/AllOpenListPanelConfig',{});
},
'Sage/MainView/nls/hr/FormManager':function(){
define('Sage/MainView/nls/hr/FormManager',{});
},
'Sage/UI/nls/hr/ActivityScheduler':function(){
define('Sage/UI/nls/hr/ActivityScheduler',{});
},
'Sage/MainView/nls/hr/SecurityManager':function(){
define('Sage/MainView/nls/hr/SecurityManager',{});
},
'Sage/TaskPane/nls/hr/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/hr/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/hr/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/hr/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/hr/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/hr/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/templates/nls/hr/AllOpenDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/hr/AllOpenDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/hr/ReportsListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/hr/ReportsListSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/hr/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/hr/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/templates/nls/hr/ScheduleDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/hr/ScheduleDetailSummary',{});
},
'Sage/MainView/Opportunity/nls/hr/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/hr/UpdateOpportunities',{});
},
'Sage/UI/nls/hr/EditCalendarUsers':function(){
define('Sage/UI/nls/hr/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/hr/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/hr/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/hr/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hr/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/hr/HelpMenu':function(){
define('Sage/UI/Controls/nls/hr/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/hr/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hr/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/hr/UserTasklet':function(){
define('Sage/TaskPane/nls/hr/UserTasklet',{});
},
'Sage/UI/Alarms/nls/hr/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/hr/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/hr/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/hr/OpportunityStatistics',{});
},
'Sage/TaskPane/nls/hr/GroupListTasklet':function(){
define('Sage/TaskPane/nls/hr/GroupListTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/hr/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/hr/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/hr/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/hr/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/hr/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/hr/ColumnDesigner',{});
},
'Sage/MainView/JobMgr/templates/nls/hr/JobDefinitionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/hr/JobDefinitionDetailSummary',{});
},
'Sage/UI/nls/hr/SearchMenuItem':function(){
define('Sage/UI/nls/hr/SearchMenuItem',{});
},
'Sage/Library/nls/hr/DocumentProperties':function(){
define('Sage/Library/nls/hr/DocumentProperties',{});
},
'Sage/UI/nls/hr/NotesHistoryList':function(){
define('Sage/UI/nls/hr/NotesHistoryList',{});
},
'Sage/Utility/nls/hr/File':function(){
define('Sage/Utility/nls/hr/File',{});
},
'Sage/MainView/ReportMgr/nls/hr/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/hr/HistoryListPanelConfig',{});
},
'Sage/MainView/JobMgr/templates/nls/hr/ScheduleDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/hr/ScheduleDetailSummary',{});
},
'Sage/QuickForms/Design/nls/hr/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hr/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/hr/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/hr/ContactTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/templates/nls/hr/EventSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/hr/EventSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/hr/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/hr/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/hr/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/hr/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/hr/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/hr/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/hr/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hr/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/hr/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/hr/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/hr/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/hr/HistoryEditor',{});
},
'Sage/Groups/nls/hr/GroupManager':function(){
define('Sage/Groups/nls/hr/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/hr/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hr/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/hr/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hr/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/hr/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/hr/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/hr/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/hr/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/hr/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/hr/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/hr/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/hr/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/hr/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/hr/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/hr/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/hr/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/hr/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hr/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/hr/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/hr/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/hr/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hr/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/hr/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hr/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/hr/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hr/PickListControlDesigner',{});
},
'Sage/MainView/ActivityMgr/templates/nls/hr/LitRequestSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/hr/LitRequestSummary',{});
},
'Sage/QuickForms/Design/Editors/nls/hr/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hr/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/hr/FolderHandler':function(){
define('Sage/Library/nls/hr/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/hr/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hr/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/hr/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/hr/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/hr/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hr/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/hr/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/hr/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/hr/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hr/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/hr/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hr/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/hr/EditableGrid':function(){
define('Sage/UI/nls/hr/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/hr/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/hr/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/hr/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/hr/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/hr/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/hr/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/hr/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hr/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/hr/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/hr/ReportManagerUtility',{});
},
'Sage/UI/nls/hr/SpeedSearch':function(){
define('Sage/UI/nls/hr/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/hr/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hr/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/hr/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/hr/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/hr/SLXPreviewGrid':function(){
define('Sage/UI/nls/hr/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/hr/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/hr/UnconfirmedPane',{});
},
'Sage/Utility/nls/hr/Utility':function(){
define('Sage/Utility/nls/hr/Utility',{});
},
'Sage/QuickForms/Design/nls/hr/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hr/ControlDesigner',{});
},
'Sage/UI/Controls/nls/hr/Address':function(){
define('Sage/UI/Controls/nls/hr/Address',{});
},
'Sage/MainView/JobMgr/nls/hr/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/hr/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/hr/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/hr/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/hr/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hr/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/hr/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/hr/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/hr/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/hr/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/hr/UserType':function(){
define('Sage/UI/nls/hr/UserType',{});
},
'Sage/MainView/ReportMgr/templates/nls/hr/HistoryDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/hr/HistoryDetailSummary',{});
},
'Sage/QuickForms/Design/nls/hr/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/hr/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/hr/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/hr/ActivityCalendar',{});
},
'Sage/Utility/nls/hr/Jobs':function(){
define('Sage/Utility/nls/hr/Jobs',{});
},
'Sage/UI/Controls/nls/hr/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/hr/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/hr/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hr/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/hr/ActivityList':function(){
define('Sage/UI/nls/hr/ActivityList',{});
},
'Sage/UI/Alarms/nls/hr/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/hr/JobNotificationPopup',{});
},
'Sage/MainView/JobMgr/templates/nls/hr/ExecutionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/hr/ExecutionsListSummary',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/hr/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/hr/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/hr/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/hr/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/hr/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hr/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/hr/CalendarUsersListPane':function(){
define('Sage/UI/nls/hr/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/hr/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hr/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/hr/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hr/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/templates/nls/hr/ExecutionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/hr/ExecutionDetailSummary',{});
},
'Sage/MainView/ReportMgr/nls/hr/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/hr/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/hr/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/hr/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/hr/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hr/FormBasicPropertyEditor',{});
},
'Sage/UI/Alarms/nls/hr/AlarmButton':function(){
define('Sage/UI/Alarms/nls/hr/AlarmButton',{});
},
'Sage/MainView/ActivityMgr/nls/hr/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/hr/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/hr/Attachment':function(){
define('Sage/Utility/File/nls/hr/Attachment',{});
},
'Sage/QuickForms/Design/nls/hr/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hr/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/hr/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/hr/PropertyEditorContainer',{});
},
'Sage/Services/nls/hr/ReportingService':function(){
define('Sage/Services/nls/hr/ReportingService',{});
},
'Sage/MailMerge/nls/hr/Helper':function(){
define('Sage/MailMerge/nls/hr/Helper',{});
},
'Sage/UI/Dashboard/nls/hr/Dashboard':function(){
define('Sage/UI/Dashboard/nls/hr/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/hr/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/hr/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/hr/PickList':function(){
define('Sage/UI/Controls/nls/hr/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/hr/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/hr/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/hr/Email':function(){
define('Sage/Utility/nls/hr/Email',{});
},
'Sage/TaskPane/nls/hr/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/hr/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/hr/TimeZoneItem':function(){
define('Sage/UI/nls/hr/TimeZoneItem',{});
},
'Sage/MainView/ReportMgr/templates/nls/hr/HistoryListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/hr/HistoryListSummary',{});
},
'Sage/UI/Columns/nls/hr/SlxEdit':function(){
define('Sage/UI/Columns/nls/hr/SlxEdit',{});
},
'Sage/Reporting/nls/hr/Enumerations':function(){
define('Sage/Reporting/nls/hr/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/hr/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hr/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/hr/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/hr/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/hr/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/hr/ActivityListPanelConfig',{});
},
'Sage/UI/nls/hr/JobSchedulingWidget':function(){
define('Sage/UI/nls/hr/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/hr/LogOffButton':function(){
define('Sage/UI/Controls/nls/hr/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/hr/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hr/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/hr/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/hr/EditEventEditor',{});
},
'Sage/MailMerge/nls/hr/Loader':function(){
define('Sage/MailMerge/nls/hr/Loader',{});
},
'Sage/UI/Controls/nls/hr/DateTimePicker':function(){
define('Sage/UI/Controls/nls/hr/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/hr/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/hr/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/hr/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/hr/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/hr/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/hr/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/hr/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hr/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/hr/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/hr/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/hr/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hr/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/hr/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hr/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/hr/Lookup':function(){
define('Sage/UI/Controls/nls/hr/Lookup',{});
},
'Sage/Utility/File/nls/hr/DescriptionsForm':function(){
define('Sage/Utility/File/nls/hr/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/hr/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hr/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/hr/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/hr/CommonTasksTasklet',{});
},
'Sage/Utility/nls/hr/Dashboard':function(){
define('Sage/Utility/nls/hr/Dashboard',{});
}}});
define("Sage/nls/Sage_hr", [], 1);
