require({cache:{
'Sage/Utility/File/nls/ga/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/ga/FallbackFilePicker',{});
},
'Sage/UI/nls/ga/Boolean':function(){
define('Sage/UI/nls/ga/Boolean',{});
},
'Sage/Services/nls/ga/ActivityService':function(){
define('Sage/Services/nls/ga/ActivityService',{});
},
'Sage/UI/Controls/nls/ga/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/ga/CopyToClipboard',{});
},
'Sage/Utility/nls/ga/Activity':function(){
define('Sage/Utility/nls/ga/Activity',{});
},
'Sage/QuickForms/Design/nls/ga/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/ga/DesignPanel',{});
},
'Sage/UI/nls/ga/TimelessActivitiesPane':function(){
define('Sage/UI/nls/ga/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/ga/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ga/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/ga/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/ga/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/ga/ActivityManager':function(){
define('Sage/MainView/nls/ga/ActivityManager',{});
},
'Sage/Services/nls/ga/JobService':function(){
define('Sage/Services/nls/ga/JobService',{});
},
'Sage/QuickForms/Design/nls/ga/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ga/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/ga/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ga/_PropertyEditor',{});
},
'Sage/Services/nls/ga/ActivityActionProcessor':function(){
define('Sage/Services/nls/ga/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/ga/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ga/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ga/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ga/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ga/UserActivityDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ga/UserActivityDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ga/ConfirmationDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ga/ConfirmationDetailSummary',{});
},
'Sage/Utility/File/nls/ga/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/ga/DefaultDropHandler',{});
},
'Sage/UI/nls/ga/TransferBoxWidget':function(){
define('Sage/UI/nls/ga/TransferBoxWidget',{});
},
'Sage/Utility/File/nls/ga/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/ga/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/ga/AlarmPane':function(){
define('Sage/UI/Alarms/nls/ga/AlarmPane',{});
},
'Sage/TaskPane/nls/ga/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/ga/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/ga/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/ga/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/ga/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ga/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ga/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ga/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/ga/FilterPanel':function(){
define('Sage/UI/Filters/nls/ga/FilterPanel',{});
},
'Sage/TaskPane/nls/ga/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/ga/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/ga/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/ga/ReportManagerFormatter',{});
},
'Sage/UI/nls/ga/OwnerType':function(){
define('Sage/UI/nls/ga/OwnerType',{});
},
'Sage/MainView/JobMgr/templates/nls/ga/JobDefinitionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ga/JobDefinitionsListSummary',{});
},
'Sage/TaskPane/nls/ga/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/ga/LeadTasksTasklet',{});
},
'Sage/MainView/ReportMgr/templates/nls/ga/ReportDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ga/ReportDetailSummary',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ga/_ParameterEditorBase':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ga/_ParameterEditorBase',{});
},
'Sage/MailMerge/nls/ga/Service':function(){
define('Sage/MailMerge/nls/ga/Service',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ga/ConfirmationListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ga/ConfirmationListSummary',{});
},
'Sage/MainView/ActivityMgr/nls/ga/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/ga/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/ga/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ga/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ga/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ga/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ga/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ga/InvoiceRTDV',{});
},
'Sage/UI/nls/ga/SDataLookup':function(){
define('Sage/UI/nls/ga/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/ga/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/ga/RowDesigner',{});
},
'Sage/Groups/nls/ga/GroupLookup':function(){
define('Sage/Groups/nls/ga/GroupLookup',{});
},
'Sage/TaskPane/nls/ga/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/ga/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/ga/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/ga/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/ga/LibraryDocument':function(){
define('Sage/Utility/File/nls/ga/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ga/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ga/SpeedSearchLookup',{});
},
'Sage/UI/nls/ga/ConditionManager':function(){
define('Sage/UI/nls/ga/ConditionManager',{});
},
'Sage/MainView/JobMgr/templates/nls/ga/SchedulesListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ga/SchedulesListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ga/UserActivityListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ga/UserActivityListSummary',{});
},
'Sage/UI/Dashboard/nls/ga/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/ga/WidgetDefinition',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ga/AllOpenListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ga/AllOpenListSummary',{});
},
'Sage/UI/nls/ga/SearchConditionWidget':function(){
define('Sage/UI/nls/ga/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/ga/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ga/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ga/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/ga/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ga/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ga/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/ga/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/ga/DataSourcePanel',{});
},
'Sage/MainView/ReportMgr/templates/nls/ga/SchedulesListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ga/SchedulesListSummary',{});
},
'Sage/Library/nls/ga/Manager':function(){
define('Sage/Library/nls/ga/Manager',{});
},
'Sage/UI/nls/ga/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/ga/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/ga/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/ga/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/ga/Name':function(){
define('Sage/UI/Controls/nls/ga/Name',{});
},
'Sage/MainView/JobMgr/nls/ga/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ga/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ga/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ga/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/ga/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/ga/UpdateLeads',{});
},
'Sage/Library/nls/ga/FileHandler':function(){
define('Sage/Library/nls/ga/FileHandler',{});
},
'Sage/UI/nls/ga/ListPanel':function(){
define('Sage/UI/nls/ga/ListPanel',{});
},
'Sage/Utility/nls/ga/Sql':function(){
define('Sage/Utility/nls/ga/Sql',{});
},
'Sage/UI/Filters/nls/ga/EditFilters':function(){
define('Sage/UI/Filters/nls/ga/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/ga/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ga/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/ga/DurationSelect':function(){
define('Sage/UI/Controls/nls/ga/DurationSelect',{});
},
'Sage/UI/Alarms/nls/ga/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/ga/AlarmCountDown',{});
},
'Sage/UI/nls/ga/AttachmentList':function(){
define('Sage/UI/nls/ga/AttachmentList',{});
},
'Sage/MailMerge/nls/ga/Lookup':function(){
define('Sage/MailMerge/nls/ga/Lookup',{});
},
'Sage/QuickForms/Design/Editors/nls/ga/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ga/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ga/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/ga/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/ga/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ga/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ga/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ga/EditableGridControlDesigner',{});
},
'Sage/MainView/Options/nls/ga/OptionsDialog':function(){
define('Sage/MainView/Options/nls/ga/OptionsDialog',{});
},
'Sage/QuickForms/Design/nls/ga/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ga/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/ga/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/ga/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/ga/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ga/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/ga/Dialogs':function(){
define('Sage/UI/nls/ga/Dialogs',{});
},
'Sage/MainView/IntegrationContract/nls/ga/SyncResultsHistory':function(){
define('Sage/MainView/IntegrationContract/nls/ga/SyncResultsHistory',{});
},
'Sage/TaskPane/nls/ga/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/ga/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/ga/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/ga/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/ga/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ga/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/ga/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ga/UserControlDesigner',{});
},
'Sage/Groups/nls/ga/GroupNavigator':function(){
define('Sage/Groups/nls/ga/GroupNavigator',{});
},
'Sage/Utility/File/nls/ga/AddURLAttachment':function(){
define('Sage/Utility/File/nls/ga/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/ga/EditFilterItems':function(){
define('Sage/UI/Filters/nls/ga/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ga/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ga/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/ga/DragDropWatcher':function(){
define('Sage/Utility/File/nls/ga/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/ga/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/ga/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/ga/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ga/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ga/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ga/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ga/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ga/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ga/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ga/AllOpenListPanelConfig',{});
},
'Sage/MainView/nls/ga/FormManager':function(){
define('Sage/MainView/nls/ga/FormManager',{});
},
'Sage/UI/nls/ga/ActivityScheduler':function(){
define('Sage/UI/nls/ga/ActivityScheduler',{});
},
'Sage/MainView/nls/ga/SecurityManager':function(){
define('Sage/MainView/nls/ga/SecurityManager',{});
},
'Sage/TaskPane/nls/ga/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/ga/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/ga/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/ga/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/ga/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/ga/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ga/AllOpenDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ga/AllOpenDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/ga/ReportsListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ga/ReportsListSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/ga/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/ga/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/templates/nls/ga/ScheduleDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ga/ScheduleDetailSummary',{});
},
'Sage/MainView/Opportunity/nls/ga/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/ga/UpdateOpportunities',{});
},
'Sage/UI/nls/ga/EditCalendarUsers':function(){
define('Sage/UI/nls/ga/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ga/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ga/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/ga/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ga/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/ga/HelpMenu':function(){
define('Sage/UI/Controls/nls/ga/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/ga/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ga/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/ga/UserTasklet':function(){
define('Sage/TaskPane/nls/ga/UserTasklet',{});
},
'Sage/UI/Alarms/nls/ga/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/ga/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/ga/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/ga/OpportunityStatistics',{});
},
'Sage/TaskPane/nls/ga/GroupListTasklet':function(){
define('Sage/TaskPane/nls/ga/GroupListTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ga/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ga/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ga/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/ga/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/ga/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/ga/ColumnDesigner',{});
},
'Sage/MainView/JobMgr/templates/nls/ga/JobDefinitionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ga/JobDefinitionDetailSummary',{});
},
'Sage/UI/nls/ga/SearchMenuItem':function(){
define('Sage/UI/nls/ga/SearchMenuItem',{});
},
'Sage/Library/nls/ga/DocumentProperties':function(){
define('Sage/Library/nls/ga/DocumentProperties',{});
},
'Sage/UI/nls/ga/NotesHistoryList':function(){
define('Sage/UI/nls/ga/NotesHistoryList',{});
},
'Sage/Utility/nls/ga/File':function(){
define('Sage/Utility/nls/ga/File',{});
},
'Sage/MainView/ReportMgr/nls/ga/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ga/HistoryListPanelConfig',{});
},
'Sage/MainView/JobMgr/templates/nls/ga/ScheduleDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ga/ScheduleDetailSummary',{});
},
'Sage/QuickForms/Design/nls/ga/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ga/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/ga/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/ga/ContactTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ga/EventSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ga/EventSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/ga/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/ga/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/ga/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ga/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/ga/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/ga/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/ga/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ga/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/ga/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ga/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ga/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ga/HistoryEditor',{});
},
'Sage/Groups/nls/ga/GroupManager':function(){
define('Sage/Groups/nls/ga/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/ga/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ga/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ga/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ga/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ga/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ga/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/ga/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/ga/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ga/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ga/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/ga/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ga/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ga/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ga/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ga/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ga/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/ga/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ga/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ga/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ga/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ga/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ga/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ga/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ga/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ga/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ga/PickListControlDesigner',{});
},
'Sage/MainView/ActivityMgr/templates/nls/ga/LitRequestSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/ga/LitRequestSummary',{});
},
'Sage/QuickForms/Design/Editors/nls/ga/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ga/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/ga/FolderHandler':function(){
define('Sage/Library/nls/ga/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/ga/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ga/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/ga/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/ga/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/ga/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ga/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/ga/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/ga/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/ga/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ga/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ga/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ga/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/ga/EditableGrid':function(){
define('Sage/UI/nls/ga/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/ga/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ga/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/ga/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/ga/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/ga/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/ga/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/ga/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ga/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ga/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/ga/ReportManagerUtility',{});
},
'Sage/UI/nls/ga/SpeedSearch':function(){
define('Sage/UI/nls/ga/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/ga/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ga/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/ga/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ga/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/ga/SLXPreviewGrid':function(){
define('Sage/UI/nls/ga/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/ga/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/ga/UnconfirmedPane',{});
},
'Sage/Utility/nls/ga/Utility':function(){
define('Sage/Utility/nls/ga/Utility',{});
},
'Sage/QuickForms/Design/nls/ga/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ga/ControlDesigner',{});
},
'Sage/UI/Controls/nls/ga/Address':function(){
define('Sage/UI/Controls/nls/ga/Address',{});
},
'Sage/MainView/JobMgr/nls/ga/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/ga/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/ga/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ga/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ga/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ga/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/ga/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ga/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/ga/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ga/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/ga/UserType':function(){
define('Sage/UI/nls/ga/UserType',{});
},
'Sage/MainView/ReportMgr/templates/nls/ga/HistoryDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ga/HistoryDetailSummary',{});
},
'Sage/QuickForms/Design/nls/ga/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/ga/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/ga/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/ga/ActivityCalendar',{});
},
'Sage/Utility/nls/ga/Jobs':function(){
define('Sage/Utility/nls/ga/Jobs',{});
},
'Sage/UI/Controls/nls/ga/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/ga/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/ga/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ga/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/ga/ActivityList':function(){
define('Sage/UI/nls/ga/ActivityList',{});
},
'Sage/UI/Alarms/nls/ga/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/ga/JobNotificationPopup',{});
},
'Sage/MainView/JobMgr/templates/nls/ga/ExecutionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ga/ExecutionsListSummary',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ga/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ga/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/ga/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ga/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ga/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ga/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/ga/CalendarUsersListPane':function(){
define('Sage/UI/nls/ga/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/ga/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ga/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ga/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ga/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/templates/nls/ga/ExecutionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/ga/ExecutionDetailSummary',{});
},
'Sage/MainView/ReportMgr/nls/ga/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/ga/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/ga/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/ga/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ga/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ga/FormBasicPropertyEditor',{});
},
'Sage/UI/Alarms/nls/ga/AlarmButton':function(){
define('Sage/UI/Alarms/nls/ga/AlarmButton',{});
},
'Sage/MainView/ActivityMgr/nls/ga/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/ga/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/ga/Attachment':function(){
define('Sage/Utility/File/nls/ga/Attachment',{});
},
'Sage/QuickForms/Design/nls/ga/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ga/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ga/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/ga/PropertyEditorContainer',{});
},
'Sage/Services/nls/ga/ReportingService':function(){
define('Sage/Services/nls/ga/ReportingService',{});
},
'Sage/MailMerge/nls/ga/Helper':function(){
define('Sage/MailMerge/nls/ga/Helper',{});
},
'Sage/UI/Dashboard/nls/ga/Dashboard':function(){
define('Sage/UI/Dashboard/nls/ga/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/ga/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ga/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/ga/PickList':function(){
define('Sage/UI/Controls/nls/ga/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/ga/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ga/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/ga/Email':function(){
define('Sage/Utility/nls/ga/Email',{});
},
'Sage/TaskPane/nls/ga/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ga/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/ga/TimeZoneItem':function(){
define('Sage/UI/nls/ga/TimeZoneItem',{});
},
'Sage/MainView/ReportMgr/templates/nls/ga/HistoryListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/ga/HistoryListSummary',{});
},
'Sage/UI/Columns/nls/ga/SlxEdit':function(){
define('Sage/UI/Columns/nls/ga/SlxEdit',{});
},
'Sage/Reporting/nls/ga/Enumerations':function(){
define('Sage/Reporting/nls/ga/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/ga/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ga/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ga/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ga/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ga/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ga/ActivityListPanelConfig',{});
},
'Sage/UI/nls/ga/JobSchedulingWidget':function(){
define('Sage/UI/nls/ga/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/ga/LogOffButton':function(){
define('Sage/UI/Controls/nls/ga/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/ga/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ga/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ga/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ga/EditEventEditor',{});
},
'Sage/MailMerge/nls/ga/Loader':function(){
define('Sage/MailMerge/nls/ga/Loader',{});
},
'Sage/UI/Controls/nls/ga/DateTimePicker':function(){
define('Sage/UI/Controls/nls/ga/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/ga/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/ga/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/ga/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/ga/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/ga/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/ga/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ga/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ga/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ga/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ga/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ga/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ga/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ga/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ga/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/ga/Lookup':function(){
define('Sage/UI/Controls/nls/ga/Lookup',{});
},
'Sage/Utility/File/nls/ga/DescriptionsForm':function(){
define('Sage/Utility/File/nls/ga/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/ga/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ga/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/ga/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/ga/CommonTasksTasklet',{});
},
'Sage/Utility/nls/ga/Dashboard':function(){
define('Sage/Utility/nls/ga/Dashboard',{});
}}});
define("Sage/nls/Sage_ga", [], 1);
