require({cache:{
'Sage/Utility/File/nls/es/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/es/FallbackFilePicker',{});
},
'Sage/Utility/File/nls/es-mx/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/es-mx/FallbackFilePicker',{});
},
'Sage/UI/nls/es/Boolean':function(){
define('Sage/UI/nls/es/Boolean',{});
},
'Sage/UI/nls/es-mx/Boolean':function(){
define('Sage/UI/nls/es-mx/Boolean',{});
},
'Sage/Services/nls/es/ActivityService':function(){
define('Sage/Services/nls/es/ActivityService',{});
},
'Sage/Services/nls/es-mx/ActivityService':function(){
define('Sage/Services/nls/es-mx/ActivityService',{});
},
'Sage/UI/Controls/nls/es/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/es/CopyToClipboard',{});
},
'Sage/UI/Controls/nls/es-mx/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/es-mx/CopyToClipboard',{});
},
'Sage/Utility/nls/es/Activity':function(){
define('Sage/Utility/nls/es/Activity',{});
},
'Sage/Utility/nls/es-mx/Activity':function(){
define('Sage/Utility/nls/es-mx/Activity',{});
},
'Sage/QuickForms/Design/nls/es/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/es/DesignPanel',{});
},
'Sage/QuickForms/Design/nls/es-mx/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/es-mx/DesignPanel',{});
},
'Sage/UI/nls/es/TimelessActivitiesPane':function(){
define('Sage/UI/nls/es/TimelessActivitiesPane',{});
},
'Sage/UI/nls/es-mx/TimelessActivitiesPane':function(){
define('Sage/UI/nls/es-mx/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-mx/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-mx/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/es/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/es/ContactUserAssociationEditor',{});
},
'Sage/TaskPane/User/nls/es-mx/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/es-mx/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/es/ActivityManager':function(){
define('Sage/MainView/nls/es/ActivityManager',{});
},
'Sage/MainView/nls/es-mx/ActivityManager':function(){
define('Sage/MainView/nls/es-mx/ActivityManager',{});
},
'Sage/Services/nls/es/JobService':function(){
define('Sage/Services/nls/es/JobService',{});
},
'Sage/Services/nls/es-mx/JobService':function(){
define('Sage/Services/nls/es-mx/JobService',{});
},
'Sage/QuickForms/Design/nls/es/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-mx/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-mx/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/es/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/_PropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-mx/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-mx/_PropertyEditor',{});
},
'Sage/Services/nls/es/ActivityActionProcessor':function(){
define('Sage/Services/nls/es/ActivityActionProcessor',{});
},
'Sage/Services/nls/es-mx/ActivityActionProcessor':function(){
define('Sage/Services/nls/es-mx/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/TextBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-mx/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-mx/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-mx/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-mx/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es/UserActivityDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es/UserActivityDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es-mx/UserActivityDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es-mx/UserActivityDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es/ConfirmationDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es/ConfirmationDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es-mx/ConfirmationDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es-mx/ConfirmationDetailSummary',{});
},
'Sage/Utility/File/nls/es/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/es/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/es-mx/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/es-mx/DefaultDropHandler',{});
},
'Sage/UI/nls/es/TransferBoxWidget':function(){
define('Sage/UI/nls/es/TransferBoxWidget',{});
},
'Sage/UI/nls/es-mx/TransferBoxWidget':function(){
define('Sage/UI/nls/es-mx/TransferBoxWidget',{});
},
'Sage/Utility/File/nls/es/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/es/AttachmentPropertiesEditForm',{});
},
'Sage/Utility/File/nls/es-mx/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/es-mx/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/es/AlarmPane':function(){
define('Sage/UI/Alarms/nls/es/AlarmPane',{});
},
'Sage/UI/Alarms/nls/es-mx/AlarmPane':function(){
define('Sage/UI/Alarms/nls/es-mx/AlarmPane',{});
},
'Sage/TaskPane/nls/es/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/es/LiteratureManagementTasks',{});
},
'Sage/TaskPane/nls/es-mx/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/es-mx/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/es/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/es/DashboardWidget',{});
},
'Sage/UI/Dashboard/nls/es-mx/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/es-mx/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/es/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/NumericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-mx/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-mx/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/es/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es/CustomerPaymentsRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/es-mx/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es-mx/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/es/FilterPanel':function(){
define('Sage/UI/Filters/nls/es/FilterPanel',{});
},
'Sage/UI/Filters/nls/es-mx/FilterPanel':function(){
define('Sage/UI/Filters/nls/es-mx/FilterPanel',{});
},
'Sage/TaskPane/nls/es/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/es/_BaseTaskPaneTasklet',{});
},
'Sage/TaskPane/nls/es-mx/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/es-mx/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportManagerFormatter',{});
},
'Sage/MainView/ReportMgr/nls/es-mx/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/es-mx/ReportManagerFormatter',{});
},
'Sage/UI/nls/es/OwnerType':function(){
define('Sage/UI/nls/es/OwnerType',{});
},
'Sage/UI/nls/es-mx/OwnerType':function(){
define('Sage/UI/nls/es-mx/OwnerType',{});
},
'Sage/MainView/JobMgr/templates/nls/es/JobDefinitionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/es/JobDefinitionsListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/es-mx/JobDefinitionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/es-mx/JobDefinitionsListSummary',{});
},
'Sage/TaskPane/nls/es/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/es/LeadTasksTasklet',{});
},
'Sage/TaskPane/nls/es-mx/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/es-mx/LeadTasksTasklet',{});
},
'Sage/MainView/ReportMgr/templates/nls/es/ReportDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/es/ReportDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/es-mx/ReportDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/es-mx/ReportDetailSummary',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/_ParameterEditorBase':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/_ParameterEditorBase',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-mx/_ParameterEditorBase':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-mx/_ParameterEditorBase',{});
},
'Sage/MailMerge/nls/es/Service':function(){
define('Sage/MailMerge/nls/es/Service',{});
},
'Sage/MailMerge/nls/es-mx/Service':function(){
define('Sage/MailMerge/nls/es-mx/Service',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es/ConfirmationListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es/ConfirmationListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es-mx/ConfirmationListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es-mx/ConfirmationListSummary',{});
},
'Sage/MainView/ActivityMgr/nls/es/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/es/SnoozeOptions',{});
},
'Sage/MainView/ActivityMgr/nls/es-mx/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/es-mx/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/es/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-mx/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-mx/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-mx/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-mx/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/es/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es/InvoiceRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/es-mx/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es-mx/InvoiceRTDV',{});
},
'Sage/UI/nls/es/SDataLookup':function(){
define('Sage/UI/nls/es/SDataLookup',{});
},
'Sage/UI/nls/es-mx/SDataLookup':function(){
define('Sage/UI/nls/es-mx/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/es/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/es/RowDesigner',{});
},
'Sage/QuickForms/Design/nls/es-mx/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/es-mx/RowDesigner',{});
},
'Sage/Groups/nls/es/GroupLookup':function(){
define('Sage/Groups/nls/es/GroupLookup',{});
},
'Sage/Groups/nls/es-mx/GroupLookup':function(){
define('Sage/Groups/nls/es-mx/GroupLookup',{});
},
'Sage/TaskPane/nls/es/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/es/OpportunityTasksTasklet',{});
},
'Sage/TaskPane/nls/es-mx/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/es-mx/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/es/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/es/CheckBoxFilter',{});
},
'Sage/UI/Filters/nls/es-mx/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/es-mx/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/es/LibraryDocument':function(){
define('Sage/Utility/File/nls/es/LibraryDocument',{});
},
'Sage/Utility/File/nls/es-mx/LibraryDocument':function(){
define('Sage/Utility/File/nls/es-mx/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/SpeedSearchLookup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-mx/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-mx/SpeedSearchLookup',{});
},
'Sage/UI/nls/es/ConditionManager':function(){
define('Sage/UI/nls/es/ConditionManager',{});
},
'Sage/UI/nls/es-mx/ConditionManager':function(){
define('Sage/UI/nls/es-mx/ConditionManager',{});
},
'Sage/MainView/JobMgr/templates/nls/es/SchedulesListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/es/SchedulesListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/es-mx/SchedulesListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/es-mx/SchedulesListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es/UserActivityListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es/UserActivityListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es-mx/UserActivityListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es-mx/UserActivityListSummary',{});
},
'Sage/UI/Dashboard/nls/es/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/es/WidgetDefinition',{});
},
'Sage/UI/Dashboard/nls/es-mx/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/es-mx/WidgetDefinition',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es/AllOpenListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es/AllOpenListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es-mx/AllOpenListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es-mx/AllOpenListSummary',{});
},
'Sage/UI/nls/es/SearchConditionWidget':function(){
define('Sage/UI/nls/es/SearchConditionWidget',{});
},
'Sage/UI/nls/es-mx/SearchConditionWidget':function(){
define('Sage/UI/nls/es-mx/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/es/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-mx/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-mx/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/es/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/es/JobManagerActions',{});
},
'Sage/MainView/JobMgr/nls/es-mx/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/es-mx/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/ContactLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-mx/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-mx/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/es/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/es/DataSourcePanel',{});
},
'Sage/QuickForms/Design/nls/es-mx/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/es-mx/DataSourcePanel',{});
},
'Sage/MainView/ReportMgr/templates/nls/es/SchedulesListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/es/SchedulesListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/es-mx/SchedulesListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/es-mx/SchedulesListSummary',{});
},
'Sage/Library/nls/es/Manager':function(){
define('Sage/Library/nls/es/Manager',{});
},
'Sage/Library/nls/es-mx/Manager':function(){
define('Sage/Library/nls/es-mx/Manager',{});
},
'Sage/UI/nls/es/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/es/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/nls/es-mx/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/es-mx/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/es/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/es/NonVisibleControlContainer',{});
},
'Sage/QuickForms/Design/nls/es-mx/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/es-mx/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/es/Name':function(){
define('Sage/UI/Controls/nls/es/Name',{});
},
'Sage/UI/Controls/nls/es-mx/Name':function(){
define('Sage/UI/Controls/nls/es-mx/Name',{});
},
'Sage/MainView/JobMgr/nls/es/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es/ExecutionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/es-mx/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es-mx/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/es/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/PhoneControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-mx/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-mx/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/es/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/es/UpdateLeads',{});
},
'Sage/MainView/Lead/nls/es-mx/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/es-mx/UpdateLeads',{});
},
'Sage/Library/nls/es/FileHandler':function(){
define('Sage/Library/nls/es/FileHandler',{});
},
'Sage/Library/nls/es-mx/FileHandler':function(){
define('Sage/Library/nls/es-mx/FileHandler',{});
},
'Sage/UI/nls/es/ListPanel':function(){
define('Sage/UI/nls/es/ListPanel',{});
},
'Sage/UI/nls/es-mx/ListPanel':function(){
define('Sage/UI/nls/es-mx/ListPanel',{});
},
'Sage/Utility/nls/es/Sql':function(){
define('Sage/Utility/nls/es/Sql',{});
},
'Sage/Utility/nls/es-mx/Sql':function(){
define('Sage/Utility/nls/es-mx/Sql',{});
},
'Sage/UI/Filters/nls/es/EditFilters':function(){
define('Sage/UI/Filters/nls/es/EditFilters',{});
},
'Sage/UI/Filters/nls/es-mx/EditFilters':function(){
define('Sage/UI/Filters/nls/es-mx/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/es/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/FormUsagesPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-mx/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-mx/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/es/DurationSelect':function(){
define('Sage/UI/Controls/nls/es/DurationSelect',{});
},
'Sage/UI/Controls/nls/es-mx/DurationSelect':function(){
define('Sage/UI/Controls/nls/es-mx/DurationSelect',{});
},
'Sage/UI/Alarms/nls/es/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/es/AlarmCountDown',{});
},
'Sage/UI/Alarms/nls/es-mx/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/es-mx/AlarmCountDown',{});
},
'Sage/UI/nls/es/AttachmentList':function(){
define('Sage/UI/nls/es/AttachmentList',{});
},
'Sage/UI/nls/es-mx/AttachmentList':function(){
define('Sage/UI/nls/es-mx/AttachmentList',{});
},
'Sage/MailMerge/nls/es/Lookup':function(){
define('Sage/MailMerge/nls/es/Lookup',{});
},
'Sage/MailMerge/nls/es-mx/Lookup':function(){
define('Sage/MailMerge/nls/es-mx/Lookup',{});
},
'Sage/QuickForms/Design/Editors/nls/es/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-mx/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-mx/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/es/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/es/RunJobDialog',{});
},
'Sage/MainView/JobMgr/nls/es-mx/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/es-mx/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/es/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-mx/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-mx/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-mx/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-mx/EditableGridControlDesigner',{});
},
'Sage/MainView/Options/nls/es/OptionsDialog':function(){
define('Sage/MainView/Options/nls/es/OptionsDialog',{});
},
'Sage/MainView/Options/nls/es-mx/OptionsDialog':function(){
define('Sage/MainView/Options/nls/es-mx/OptionsDialog',{});
},
'Sage/QuickForms/Design/nls/es/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/HiddenControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-mx/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-mx/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/es/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/es/DashboardWidgetCell',{});
},
'Sage/UI/Dashboard/nls/es-mx/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/es-mx/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/es/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/UserBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-mx/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-mx/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/es/Dialogs':function(){
define('Sage/UI/nls/es/Dialogs',{});
},
'Sage/UI/nls/es-mx/Dialogs':function(){
define('Sage/UI/nls/es-mx/Dialogs',{});
},
'Sage/MainView/IntegrationContract/nls/es/SyncResultsHistory':function(){
define('Sage/MainView/IntegrationContract/nls/es/SyncResultsHistory',{});
},
'Sage/MainView/IntegrationContract/nls/es-mx/SyncResultsHistory':function(){
define('Sage/MainView/IntegrationContract/nls/es-mx/SyncResultsHistory',{});
},
'Sage/TaskPane/nls/es/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/es/SecuredActionTasklet',{});
},
'Sage/TaskPane/nls/es-mx/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/es-mx/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/es/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/es/DashboardTabController',{});
},
'Sage/UI/Dashboard/nls/es-mx/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/es-mx/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/es/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es/SalesOrderRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/es-mx/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es-mx/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/es/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/UserControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-mx/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-mx/UserControlDesigner',{});
},
'Sage/Groups/nls/es/GroupNavigator':function(){
define('Sage/Groups/nls/es/GroupNavigator',{});
},
'Sage/Groups/nls/es-mx/GroupNavigator':function(){
define('Sage/Groups/nls/es-mx/GroupNavigator',{});
},
'Sage/Utility/File/nls/es/AddURLAttachment':function(){
define('Sage/Utility/File/nls/es/AddURLAttachment',{});
},
'Sage/Utility/File/nls/es-mx/AddURLAttachment':function(){
define('Sage/Utility/File/nls/es-mx/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/es/EditFilterItems':function(){
define('Sage/UI/Filters/nls/es/EditFilterItems',{});
},
'Sage/UI/Filters/nls/es-mx/EditFilterItems':function(){
define('Sage/UI/Filters/nls/es-mx/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportsFormatter',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-mx/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-mx/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/es/DragDropWatcher':function(){
define('Sage/Utility/File/nls/es/DragDropWatcher',{});
},
'Sage/Utility/File/nls/es-mx/DragDropWatcher':function(){
define('Sage/Utility/File/nls/es-mx/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/es/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/es/DesignSurface',{});
},
'Sage/QuickForms/Design/nls/es-mx/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/es-mx/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/es/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-mx/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-mx/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/es/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/FormAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-mx/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-mx/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/EventListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-mx/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-mx/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/es/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/es/AllOpenListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/es-mx/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/es-mx/AllOpenListPanelConfig',{});
},
'Sage/MainView/nls/es/FormManager':function(){
define('Sage/MainView/nls/es/FormManager',{});
},
'Sage/MainView/nls/es-mx/FormManager':function(){
define('Sage/MainView/nls/es-mx/FormManager',{});
},
'Sage/UI/nls/es/ActivityScheduler':function(){
define('Sage/UI/nls/es/ActivityScheduler',{});
},
'Sage/UI/nls/es-mx/ActivityScheduler':function(){
define('Sage/UI/nls/es-mx/ActivityScheduler',{});
},
'Sage/MainView/nls/es/SecurityManager':function(){
define('Sage/MainView/nls/es/SecurityManager',{});
},
'Sage/MainView/nls/es-mx/SecurityManager':function(){
define('Sage/MainView/nls/es-mx/SecurityManager',{});
},
'Sage/TaskPane/nls/es/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/es/ActivityTaskConfigurationProvider',{});
},
'Sage/TaskPane/nls/es-mx/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/es-mx/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/es/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/es/EntityInfoToolTip',{});
},
'Sage/UI/Controls/nls/es-mx/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/es-mx/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/es-mx/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/es-mx/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es/AllOpenDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es/AllOpenDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es-mx/AllOpenDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es-mx/AllOpenDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/es/ReportsListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/es/ReportsListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/es-mx/ReportsListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/es-mx/ReportsListSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/es/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/es/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/Common/nls/es-mx/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/es-mx/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/templates/nls/es/ScheduleDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/es/ScheduleDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/es-mx/ScheduleDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/es-mx/ScheduleDetailSummary',{});
},
'Sage/MainView/Opportunity/nls/es/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/es/UpdateOpportunities',{});
},
'Sage/MainView/Opportunity/nls/es-mx/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/es-mx/UpdateOpportunities',{});
},
'Sage/UI/nls/es/EditCalendarUsers':function(){
define('Sage/UI/nls/es/EditCalendarUsers',{});
},
'Sage/UI/nls/es-mx/EditCalendarUsers':function(){
define('Sage/UI/nls/es-mx/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportParametersDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-mx/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-mx/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/es/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/DateTimePickerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-mx/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-mx/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/es/HelpMenu':function(){
define('Sage/UI/Controls/nls/es/HelpMenu',{});
},
'Sage/UI/Controls/nls/es-mx/HelpMenu':function(){
define('Sage/UI/Controls/nls/es-mx/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/es/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/LayoutPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-mx/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-mx/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/es/UserTasklet':function(){
define('Sage/TaskPane/nls/es/UserTasklet',{});
},
'Sage/TaskPane/nls/es-mx/UserTasklet':function(){
define('Sage/TaskPane/nls/es-mx/UserTasklet',{});
},
'Sage/UI/Alarms/nls/es/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/es/ActivityAlarm',{});
},
'Sage/UI/Alarms/nls/es-mx/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/es-mx/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/es/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/es/OpportunityStatistics',{});
},
'Sage/MainView/Opportunity/nls/es-mx/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/es-mx/OpportunityStatistics',{});
},
'Sage/TaskPane/nls/es/GroupListTasklet':function(){
define('Sage/TaskPane/nls/es/GroupListTasklet',{});
},
'Sage/TaskPane/nls/es-mx/GroupListTasklet':function(){
define('Sage/TaskPane/nls/es-mx/GroupListTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportConditionEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-mx/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-mx/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/es/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/es/AdvancedSearchOptions',{});
},
'Sage/MainView/IntegrationContract/nls/es-mx/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/es-mx/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/es/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/es/ColumnDesigner',{});
},
'Sage/QuickForms/Design/nls/es-mx/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/es-mx/ColumnDesigner',{});
},
'Sage/MainView/JobMgr/templates/nls/es/JobDefinitionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/es/JobDefinitionDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/es-mx/JobDefinitionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/es-mx/JobDefinitionDetailSummary',{});
},
'Sage/UI/nls/es/SearchMenuItem':function(){
define('Sage/UI/nls/es/SearchMenuItem',{});
},
'Sage/UI/nls/es-mx/SearchMenuItem':function(){
define('Sage/UI/nls/es-mx/SearchMenuItem',{});
},
'Sage/Library/nls/es/DocumentProperties':function(){
define('Sage/Library/nls/es/DocumentProperties',{});
},
'Sage/Library/nls/es-mx/DocumentProperties':function(){
define('Sage/Library/nls/es-mx/DocumentProperties',{});
},
'Sage/UI/nls/es/NotesHistoryList':function(){
define('Sage/UI/nls/es/NotesHistoryList',{});
},
'Sage/UI/nls/es-mx/NotesHistoryList':function(){
define('Sage/UI/nls/es-mx/NotesHistoryList',{});
},
'Sage/Utility/nls/es/File':function(){
define('Sage/Utility/nls/es/File',{});
},
'Sage/Utility/nls/es-mx/File':function(){
define('Sage/Utility/nls/es-mx/File',{});
},
'Sage/MainView/ReportMgr/nls/es/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/es-mx/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es-mx/HistoryListPanelConfig',{});
},
'Sage/MainView/JobMgr/templates/nls/es/ScheduleDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/es/ScheduleDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/es-mx/ScheduleDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/es-mx/ScheduleDetailSummary',{});
},
'Sage/QuickForms/Design/nls/es/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/UrlControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-mx/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-mx/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/es/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/es/ContactTasksTasklet',{});
},
'Sage/TaskPane/nls/es-mx/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/es-mx/ContactTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es/EventSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es/EventSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es-mx/EventSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es-mx/EventSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/es/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/es/_WizardDialogBase',{});
},
'Sage/MainView/ReportMgr/Common/nls/es-mx/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/es-mx/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/es/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es/SchedulesListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/es-mx/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es-mx/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/es/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/es/GoogleDocPicker',{});
},
'Sage/Utility/File/nls/es-mx/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/es-mx/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/es/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/ComboBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-mx/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-mx/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/es/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-mx/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-mx/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/HistoryEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-mx/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-mx/HistoryEditor',{});
},
'Sage/Groups/nls/es/GroupManager':function(){
define('Sage/Groups/nls/es/GroupManager',{});
},
'Sage/Groups/nls/es-mx/GroupManager':function(){
define('Sage/Groups/nls/es-mx/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/es/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-mx/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-mx/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/ComboBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-mx/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-mx/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportsListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/es-mx/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es-mx/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/es/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/es/JobNotificationButton',{});
},
'Sage/UI/Alarms/nls/es-mx/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/es-mx/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportWizardController',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-mx/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-mx/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/es/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/es-mx/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es-mx/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/RecurringEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-mx/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-mx/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportsUtility',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-mx/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-mx/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/es/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-mx/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-mx/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/es/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/es-mx/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es-mx/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/es/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-mx/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-mx/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-mx/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-mx/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-mx/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-mx/PickListControlDesigner',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es/LitRequestSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es/LitRequestSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/es-mx/LitRequestSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/es-mx/LitRequestSummary',{});
},
'Sage/QuickForms/Design/Editors/nls/es/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-mx/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-mx/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/es/FolderHandler':function(){
define('Sage/Library/nls/es/FolderHandler',{});
},
'Sage/Library/nls/es-mx/FolderHandler':function(){
define('Sage/Library/nls/es-mx/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/es/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-mx/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-mx/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/es/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/es/ContactSearchForDuplicates',{});
},
'Sage/MainView/Contact/nls/es-mx/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/es-mx/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/es/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/DateTimePickerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-mx/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-mx/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/es/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/es/AccountingTasksTasklet',{});
},
'Sage/TaskPane/nls/es-mx/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/es-mx/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/es/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-mx/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-mx/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/CurrencyBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-mx/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-mx/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/es/EditableGrid':function(){
define('Sage/UI/nls/es/EditableGrid',{});
},
'Sage/UI/nls/es-mx/EditableGrid':function(){
define('Sage/UI/nls/es-mx/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/es/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es/SalesQuoteRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/es-mx/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es-mx/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/es/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/es/SecurityProfile',{});
},
'Sage/MainView/SecurityMgr/nls/es-mx/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/es-mx/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportWizardController',{});
},
'Sage/MainView/ReportMgr/nls/es-mx/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/es-mx/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/es/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/UserAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-mx/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-mx/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportManagerUtility',{});
},
'Sage/MainView/ReportMgr/nls/es-mx/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/es-mx/ReportManagerUtility',{});
},
'Sage/UI/nls/es/SpeedSearch':function(){
define('Sage/UI/nls/es/SpeedSearch',{});
},
'Sage/UI/nls/es-mx/SpeedSearch':function(){
define('Sage/UI/nls/es-mx/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/es/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/CurrencyAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-mx/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-mx/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/es/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es/ReportManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/es-mx/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es-mx/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/es/SLXPreviewGrid':function(){
define('Sage/UI/nls/es/SLXPreviewGrid',{});
},
'Sage/UI/nls/es-mx/SLXPreviewGrid':function(){
define('Sage/UI/nls/es-mx/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/es/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/es/UnconfirmedPane',{});
},
'Sage/UI/Alarms/nls/es-mx/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/es-mx/UnconfirmedPane',{});
},
'Sage/Utility/nls/es/Utility':function(){
define('Sage/Utility/nls/es/Utility',{});
},
'Sage/Utility/nls/es-mx/Utility':function(){
define('Sage/Utility/nls/es-mx/Utility',{});
},
'Sage/QuickForms/Design/nls/es/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/ControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-mx/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-mx/ControlDesigner',{});
},
'Sage/UI/Controls/nls/es/Address':function(){
define('Sage/UI/Controls/nls/es/Address',{});
},
'Sage/UI/Controls/nls/es-mx/Address':function(){
define('Sage/UI/Controls/nls/es-mx/Address',{});
},
'Sage/MainView/JobMgr/nls/es/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/es/JobManagerGroupContextService',{});
},
'Sage/MainView/JobMgr/nls/es-mx/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/es-mx/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/es/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/BaseListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-mx/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-mx/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/es/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/OwnerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-mx/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-mx/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/es/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es/JobManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/es-mx/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es-mx/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/es-mx/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/es-mx/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/es/UserType':function(){
define('Sage/UI/nls/es/UserType',{});
},
'Sage/UI/nls/es-mx/UserType':function(){
define('Sage/UI/nls/es-mx/UserType',{});
},
'Sage/MainView/ReportMgr/templates/nls/es/HistoryDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/es/HistoryDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/es-mx/HistoryDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/es-mx/HistoryDetailSummary',{});
},
'Sage/QuickForms/Design/nls/es/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/es/FormDesigner',{});
},
'Sage/QuickForms/Design/nls/es-mx/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/es-mx/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityCalendar',{});
},
'Sage/MainView/ActivityMgr/nls/es-mx/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/es-mx/ActivityCalendar',{});
},
'Sage/Utility/nls/es/Jobs':function(){
define('Sage/Utility/nls/es/Jobs',{});
},
'Sage/Utility/nls/es-mx/Jobs':function(){
define('Sage/Utility/nls/es-mx/Jobs',{});
},
'Sage/UI/Controls/nls/es/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/es/_DialogHelpIconMixin',{});
},
'Sage/UI/Controls/nls/es-mx/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/es-mx/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/es/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/PickListAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-mx/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-mx/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/es/ActivityList':function(){
define('Sage/UI/nls/es/ActivityList',{});
},
'Sage/UI/nls/es-mx/ActivityList':function(){
define('Sage/UI/nls/es-mx/ActivityList',{});
},
'Sage/UI/Alarms/nls/es/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/es/JobNotificationPopup',{});
},
'Sage/UI/Alarms/nls/es-mx/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/es-mx/JobNotificationPopup',{});
},
'Sage/MainView/JobMgr/templates/nls/es/ExecutionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/es/ExecutionsListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/es-mx/ExecutionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/es-mx/ExecutionsListSummary',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/LeadLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-mx/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-mx/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/es/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es/SchedulesListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/es-mx/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es-mx/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/es/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/GenericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-mx/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-mx/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/es/CalendarUsersListPane':function(){
define('Sage/UI/nls/es/CalendarUsersListPane',{});
},
'Sage/UI/nls/es-mx/CalendarUsersListPane':function(){
define('Sage/UI/nls/es-mx/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/es/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-mx/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-mx/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/ColumnBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-mx/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-mx/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/templates/nls/es/ExecutionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/es/ExecutionDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/es-mx/ExecutionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/es-mx/ExecutionDetailSummary',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportManagerGroupContextService',{});
},
'Sage/MainView/ReportMgr/nls/es-mx/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/es-mx/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/es/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/es/MatchingOptionsConfig',{});
},
'Sage/MainView/IntegrationContract/nls/es-mx/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/es-mx/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/es/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/FormBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-mx/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-mx/FormBasicPropertyEditor',{});
},
'Sage/UI/Alarms/nls/es/AlarmButton':function(){
define('Sage/UI/Alarms/nls/es/AlarmButton',{});
},
'Sage/UI/Alarms/nls/es-mx/AlarmButton':function(){
define('Sage/UI/Alarms/nls/es-mx/AlarmButton',{});
},
'Sage/MainView/ActivityMgr/nls/es/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/es/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/MainView/ActivityMgr/nls/es-mx/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/es-mx/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/es/Attachment':function(){
define('Sage/Utility/File/nls/es/Attachment',{});
},
'Sage/Utility/File/nls/es-mx/Attachment':function(){
define('Sage/Utility/File/nls/es-mx/Attachment',{});
},
'Sage/QuickForms/Design/nls/es/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-mx/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-mx/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/es/PropertyEditorContainer',{});
},
'Sage/QuickForms/Design/nls/es-mx/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/es-mx/PropertyEditorContainer',{});
},
'Sage/Services/nls/es/ReportingService':function(){
define('Sage/Services/nls/es/ReportingService',{});
},
'Sage/Services/nls/es-mx/ReportingService':function(){
define('Sage/Services/nls/es-mx/ReportingService',{});
},
'Sage/MailMerge/nls/es/Helper':function(){
define('Sage/MailMerge/nls/es/Helper',{});
},
'Sage/MailMerge/nls/es-mx/Helper':function(){
define('Sage/MailMerge/nls/es-mx/Helper',{});
},
'Sage/UI/Dashboard/nls/es/Dashboard':function(){
define('Sage/UI/Dashboard/nls/es/Dashboard',{});
},
'Sage/UI/Dashboard/nls/es-mx/Dashboard':function(){
define('Sage/UI/Dashboard/nls/es-mx/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-mx/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-mx/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/es/PickList':function(){
define('Sage/UI/Controls/nls/es/PickList',{});
},
'Sage/UI/Controls/nls/es-mx/PickList':function(){
define('Sage/UI/Controls/nls/es-mx/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/es/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/es/HistoryEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/es-mx/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/es-mx/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/es/Email':function(){
define('Sage/Utility/nls/es/Email',{});
},
'Sage/Utility/nls/es-mx/Email':function(){
define('Sage/Utility/nls/es-mx/Email',{});
},
'Sage/TaskPane/nls/es/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es/SecurityManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/es-mx/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es-mx/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/es/TimeZoneItem':function(){
define('Sage/UI/nls/es/TimeZoneItem',{});
},
'Sage/UI/nls/es-mx/TimeZoneItem':function(){
define('Sage/UI/nls/es-mx/TimeZoneItem',{});
},
'Sage/MainView/ReportMgr/templates/nls/es/HistoryListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/es/HistoryListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/es-mx/HistoryListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/es-mx/HistoryListSummary',{});
},
'Sage/UI/Columns/nls/es/SlxEdit':function(){
define('Sage/UI/Columns/nls/es/SlxEdit',{});
},
'Sage/UI/Columns/nls/es-mx/SlxEdit':function(){
define('Sage/UI/Columns/nls/es-mx/SlxEdit',{});
},
'Sage/Reporting/nls/es/Enumerations':function(){
define('Sage/Reporting/nls/es/Enumerations',{});
},
'Sage/Reporting/nls/es-mx/Enumerations':function(){
define('Sage/Reporting/nls/es-mx/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/es/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-mx/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-mx/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportConditionsDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-mx/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-mx/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/es/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/es/ActivityListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/es-mx/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/es-mx/ActivityListPanelConfig',{});
},
'Sage/UI/nls/es/JobSchedulingWidget':function(){
define('Sage/UI/nls/es/JobSchedulingWidget',{});
},
'Sage/UI/nls/es-mx/JobSchedulingWidget':function(){
define('Sage/UI/nls/es-mx/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/es/LogOffButton':function(){
define('Sage/UI/Controls/nls/es/LogOffButton',{});
},
'Sage/UI/Controls/nls/es-mx/LogOffButton':function(){
define('Sage/UI/Controls/nls/es-mx/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/es/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/TextBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-mx/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-mx/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/EditEventEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-mx/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-mx/EditEventEditor',{});
},
'Sage/MailMerge/nls/es/Loader':function(){
define('Sage/MailMerge/nls/es/Loader',{});
},
'Sage/MailMerge/nls/es-mx/Loader':function(){
define('Sage/MailMerge/nls/es-mx/Loader',{});
},
'Sage/UI/Controls/nls/es/DateTimePicker':function(){
define('Sage/UI/Controls/nls/es/DateTimePicker',{});
},
'Sage/UI/Controls/nls/es-mx/DateTimePicker':function(){
define('Sage/UI/Controls/nls/es-mx/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportManagerActions',{});
},
'Sage/MainView/ReportMgr/nls/es-mx/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/es-mx/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/es/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/es/AlarmPopup',{});
},
'Sage/UI/Alarms/nls/es-mx/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/es-mx/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/es/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/es/ContactUserAssociationEditor',{});
},
'Sage/MainView/Contact/nls/es-mx/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/es-mx/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-mx/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-mx/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/es/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es/BaseListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/es-mx/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es-mx/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/es/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-mx/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-mx/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/EmailControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-mx/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-mx/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/es/Lookup':function(){
define('Sage/UI/Controls/nls/es/Lookup',{});
},
'Sage/UI/Controls/nls/es-mx/Lookup':function(){
define('Sage/UI/Controls/nls/es-mx/Lookup',{});
},
'Sage/Utility/File/nls/es/DescriptionsForm':function(){
define('Sage/Utility/File/nls/es/DescriptionsForm',{});
},
'Sage/Utility/File/nls/es-mx/DescriptionsForm':function(){
define('Sage/Utility/File/nls/es-mx/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/es/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/NumericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-mx/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-mx/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/es/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/es/CommonTasksTasklet',{});
},
'Sage/TaskPane/nls/es-mx/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/es-mx/CommonTasksTasklet',{});
},
'Sage/Utility/nls/es/Dashboard':function(){
define('Sage/Utility/nls/es/Dashboard',{});
},
'Sage/Utility/nls/es-mx/Dashboard':function(){
define('Sage/Utility/nls/es-mx/Dashboard',{});
}}});
define("Sage/nls/Sage_es-mx", [], 1);
