require({cache:{
'Sage/Utility/File/nls/az/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/az/FallbackFilePicker',{});
},
'Sage/Utility/File/nls/az-az/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/az-az/FallbackFilePicker',{});
},
'Sage/UI/nls/az/Boolean':function(){
define('Sage/UI/nls/az/Boolean',{});
},
'Sage/UI/nls/az-az/Boolean':function(){
define('Sage/UI/nls/az-az/Boolean',{});
},
'Sage/Services/nls/az/ActivityService':function(){
define('Sage/Services/nls/az/ActivityService',{});
},
'Sage/Services/nls/az-az/ActivityService':function(){
define('Sage/Services/nls/az-az/ActivityService',{});
},
'Sage/UI/Controls/nls/az/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/az/CopyToClipboard',{});
},
'Sage/UI/Controls/nls/az-az/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/az-az/CopyToClipboard',{});
},
'Sage/Utility/nls/az/Activity':function(){
define('Sage/Utility/nls/az/Activity',{});
},
'Sage/Utility/nls/az-az/Activity':function(){
define('Sage/Utility/nls/az-az/Activity',{});
},
'Sage/QuickForms/Design/nls/az/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/az/DesignPanel',{});
},
'Sage/QuickForms/Design/nls/az-az/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/az-az/DesignPanel',{});
},
'Sage/UI/nls/az/TimelessActivitiesPane':function(){
define('Sage/UI/nls/az/TimelessActivitiesPane',{});
},
'Sage/UI/nls/az-az/TimelessActivitiesPane':function(){
define('Sage/UI/nls/az-az/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/az/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/az/ActivityEditor',{});
},
'Sage/MainView/ActivityMgr/nls/az-az/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/az-az/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/az/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/az/ContactUserAssociationEditor',{});
},
'Sage/TaskPane/User/nls/az-az/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/az-az/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/az/ActivityManager':function(){
define('Sage/MainView/nls/az/ActivityManager',{});
},
'Sage/MainView/nls/az-az/ActivityManager':function(){
define('Sage/MainView/nls/az-az/ActivityManager',{});
},
'Sage/Services/nls/az/JobService':function(){
define('Sage/Services/nls/az/JobService',{});
},
'Sage/Services/nls/az-az/JobService':function(){
define('Sage/Services/nls/az-az/JobService',{});
},
'Sage/QuickForms/Design/nls/az/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/az-az/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az-az/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/az/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/_PropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/az-az/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az-az/_PropertyEditor',{});
},
'Sage/Services/nls/az/ActivityActionProcessor':function(){
define('Sage/Services/nls/az/ActivityActionProcessor',{});
},
'Sage/Services/nls/az-az/ActivityActionProcessor':function(){
define('Sage/Services/nls/az-az/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/az/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/TextBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/az-az/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az-az/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/az/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/az/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/nls/az-az/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/az-az/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/templates/nls/az/UserActivityDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/az/UserActivityDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/az-az/UserActivityDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/az-az/UserActivityDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/az/ConfirmationDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/az/ConfirmationDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/az-az/ConfirmationDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/az-az/ConfirmationDetailSummary',{});
},
'Sage/Utility/File/nls/az/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/az/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/az-az/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/az-az/DefaultDropHandler',{});
},
'Sage/UI/nls/az/TransferBoxWidget':function(){
define('Sage/UI/nls/az/TransferBoxWidget',{});
},
'Sage/UI/nls/az-az/TransferBoxWidget':function(){
define('Sage/UI/nls/az-az/TransferBoxWidget',{});
},
'Sage/Utility/File/nls/az/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/az/AttachmentPropertiesEditForm',{});
},
'Sage/Utility/File/nls/az-az/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/az-az/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/az/AlarmPane':function(){
define('Sage/UI/Alarms/nls/az/AlarmPane',{});
},
'Sage/UI/Alarms/nls/az-az/AlarmPane':function(){
define('Sage/UI/Alarms/nls/az-az/AlarmPane',{});
},
'Sage/TaskPane/nls/az/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/az/LiteratureManagementTasks',{});
},
'Sage/TaskPane/nls/az-az/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/az-az/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/az/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/az/DashboardWidget',{});
},
'Sage/UI/Dashboard/nls/az-az/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/az-az/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/az/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/NumericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/az-az/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az-az/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/az/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/az/CustomerPaymentsRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/az-az/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/az-az/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/az/FilterPanel':function(){
define('Sage/UI/Filters/nls/az/FilterPanel',{});
},
'Sage/UI/Filters/nls/az-az/FilterPanel':function(){
define('Sage/UI/Filters/nls/az-az/FilterPanel',{});
},
'Sage/TaskPane/nls/az/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/az/_BaseTaskPaneTasklet',{});
},
'Sage/TaskPane/nls/az-az/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/az-az/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/az/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/az/ReportManagerFormatter',{});
},
'Sage/MainView/ReportMgr/nls/az-az/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/az-az/ReportManagerFormatter',{});
},
'Sage/UI/nls/az/OwnerType':function(){
define('Sage/UI/nls/az/OwnerType',{});
},
'Sage/UI/nls/az-az/OwnerType':function(){
define('Sage/UI/nls/az-az/OwnerType',{});
},
'Sage/MainView/JobMgr/templates/nls/az/JobDefinitionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/az/JobDefinitionsListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/az-az/JobDefinitionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/az-az/JobDefinitionsListSummary',{});
},
'Sage/TaskPane/nls/az/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/az/LeadTasksTasklet',{});
},
'Sage/TaskPane/nls/az-az/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/az-az/LeadTasksTasklet',{});
},
'Sage/MainView/ReportMgr/templates/nls/az/ReportDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/az/ReportDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/az-az/ReportDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/az-az/ReportDetailSummary',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/az/_ParameterEditorBase':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/az/_ParameterEditorBase',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/az-az/_ParameterEditorBase':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/az-az/_ParameterEditorBase',{});
},
'Sage/MailMerge/nls/az/Service':function(){
define('Sage/MailMerge/nls/az/Service',{});
},
'Sage/MailMerge/nls/az-az/Service':function(){
define('Sage/MailMerge/nls/az-az/Service',{});
},
'Sage/MainView/ActivityMgr/templates/nls/az/ConfirmationListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/az/ConfirmationListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/az-az/ConfirmationListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/az-az/ConfirmationListSummary',{});
},
'Sage/MainView/ActivityMgr/nls/az/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/az/SnoozeOptions',{});
},
'Sage/MainView/ActivityMgr/nls/az-az/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/az-az/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/az/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/az-az/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az-az/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/az/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/az-az/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az-az/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/az/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/az/InvoiceRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/az-az/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/az-az/InvoiceRTDV',{});
},
'Sage/UI/nls/az/SDataLookup':function(){
define('Sage/UI/nls/az/SDataLookup',{});
},
'Sage/UI/nls/az-az/SDataLookup':function(){
define('Sage/UI/nls/az-az/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/az/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/az/RowDesigner',{});
},
'Sage/QuickForms/Design/nls/az-az/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/az-az/RowDesigner',{});
},
'Sage/Groups/nls/az/GroupLookup':function(){
define('Sage/Groups/nls/az/GroupLookup',{});
},
'Sage/Groups/nls/az-az/GroupLookup':function(){
define('Sage/Groups/nls/az-az/GroupLookup',{});
},
'Sage/TaskPane/nls/az/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/az/OpportunityTasksTasklet',{});
},
'Sage/TaskPane/nls/az-az/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/az-az/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/az/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/az/CheckBoxFilter',{});
},
'Sage/UI/Filters/nls/az-az/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/az-az/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/az/LibraryDocument':function(){
define('Sage/Utility/File/nls/az/LibraryDocument',{});
},
'Sage/Utility/File/nls/az-az/LibraryDocument':function(){
define('Sage/Utility/File/nls/az-az/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/az/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/az/SpeedSearchLookup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/az-az/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/az-az/SpeedSearchLookup',{});
},
'Sage/UI/nls/az/ConditionManager':function(){
define('Sage/UI/nls/az/ConditionManager',{});
},
'Sage/UI/nls/az-az/ConditionManager':function(){
define('Sage/UI/nls/az-az/ConditionManager',{});
},
'Sage/MainView/JobMgr/templates/nls/az/SchedulesListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/az/SchedulesListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/az-az/SchedulesListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/az-az/SchedulesListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/az/UserActivityListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/az/UserActivityListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/az-az/UserActivityListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/az-az/UserActivityListSummary',{});
},
'Sage/UI/Dashboard/nls/az/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/az/WidgetDefinition',{});
},
'Sage/UI/Dashboard/nls/az-az/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/az-az/WidgetDefinition',{});
},
'Sage/MainView/ActivityMgr/templates/nls/az/AllOpenListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/az/AllOpenListSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/az-az/AllOpenListSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/az-az/AllOpenListSummary',{});
},
'Sage/UI/nls/az/SearchConditionWidget':function(){
define('Sage/UI/nls/az/SearchConditionWidget',{});
},
'Sage/UI/nls/az-az/SearchConditionWidget':function(){
define('Sage/UI/nls/az-az/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/az/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/az-az/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az-az/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/az/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/az/JobManagerActions',{});
},
'Sage/MainView/JobMgr/nls/az-az/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/az-az/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/az/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/az/ContactLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/az-az/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/az-az/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/az/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/az/DataSourcePanel',{});
},
'Sage/QuickForms/Design/nls/az-az/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/az-az/DataSourcePanel',{});
},
'Sage/MainView/ReportMgr/templates/nls/az/SchedulesListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/az/SchedulesListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/az-az/SchedulesListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/az-az/SchedulesListSummary',{});
},
'Sage/Library/nls/az/Manager':function(){
define('Sage/Library/nls/az/Manager',{});
},
'Sage/Library/nls/az-az/Manager':function(){
define('Sage/Library/nls/az-az/Manager',{});
},
'Sage/UI/nls/az/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/az/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/nls/az-az/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/az-az/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/az/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/az/NonVisibleControlContainer',{});
},
'Sage/QuickForms/Design/nls/az-az/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/az-az/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/az/Name':function(){
define('Sage/UI/Controls/nls/az/Name',{});
},
'Sage/UI/Controls/nls/az-az/Name':function(){
define('Sage/UI/Controls/nls/az-az/Name',{});
},
'Sage/MainView/JobMgr/nls/az/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/az/ExecutionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/az-az/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/az-az/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/az/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az/PhoneControlDesigner',{});
},
'Sage/QuickForms/Design/nls/az-az/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az-az/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/az/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/az/UpdateLeads',{});
},
'Sage/MainView/Lead/nls/az-az/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/az-az/UpdateLeads',{});
},
'Sage/Library/nls/az/FileHandler':function(){
define('Sage/Library/nls/az/FileHandler',{});
},
'Sage/Library/nls/az-az/FileHandler':function(){
define('Sage/Library/nls/az-az/FileHandler',{});
},
'Sage/UI/nls/az/ListPanel':function(){
define('Sage/UI/nls/az/ListPanel',{});
},
'Sage/UI/nls/az-az/ListPanel':function(){
define('Sage/UI/nls/az-az/ListPanel',{});
},
'Sage/Utility/nls/az/Sql':function(){
define('Sage/Utility/nls/az/Sql',{});
},
'Sage/Utility/nls/az-az/Sql':function(){
define('Sage/Utility/nls/az-az/Sql',{});
},
'Sage/UI/Filters/nls/az/EditFilters':function(){
define('Sage/UI/Filters/nls/az/EditFilters',{});
},
'Sage/UI/Filters/nls/az-az/EditFilters':function(){
define('Sage/UI/Filters/nls/az-az/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/az/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/FormUsagesPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/az-az/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az-az/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/az/DurationSelect':function(){
define('Sage/UI/Controls/nls/az/DurationSelect',{});
},
'Sage/UI/Controls/nls/az-az/DurationSelect':function(){
define('Sage/UI/Controls/nls/az-az/DurationSelect',{});
},
'Sage/UI/Alarms/nls/az/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/az/AlarmCountDown',{});
},
'Sage/UI/Alarms/nls/az-az/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/az-az/AlarmCountDown',{});
},
'Sage/UI/nls/az/AttachmentList':function(){
define('Sage/UI/nls/az/AttachmentList',{});
},
'Sage/UI/nls/az-az/AttachmentList':function(){
define('Sage/UI/nls/az-az/AttachmentList',{});
},
'Sage/MailMerge/nls/az/Lookup':function(){
define('Sage/MailMerge/nls/az/Lookup',{});
},
'Sage/MailMerge/nls/az-az/Lookup':function(){
define('Sage/MailMerge/nls/az-az/Lookup',{});
},
'Sage/QuickForms/Design/Editors/nls/az/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/az-az/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az-az/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/az/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/az/RunJobDialog',{});
},
'Sage/MainView/JobMgr/nls/az-az/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/az-az/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/az/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/az-az/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az-az/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/az/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/az-az/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az-az/EditableGridControlDesigner',{});
},
'Sage/MainView/Options/nls/az/OptionsDialog':function(){
define('Sage/MainView/Options/nls/az/OptionsDialog',{});
},
'Sage/MainView/Options/nls/az-az/OptionsDialog':function(){
define('Sage/MainView/Options/nls/az-az/OptionsDialog',{});
},
'Sage/QuickForms/Design/nls/az/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az/HiddenControlDesigner',{});
},
'Sage/QuickForms/Design/nls/az-az/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az-az/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/az/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/az/DashboardWidgetCell',{});
},
'Sage/UI/Dashboard/nls/az-az/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/az-az/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/az/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/UserBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/az-az/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az-az/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/az/Dialogs':function(){
define('Sage/UI/nls/az/Dialogs',{});
},
'Sage/UI/nls/az-az/Dialogs':function(){
define('Sage/UI/nls/az-az/Dialogs',{});
},
'Sage/MainView/IntegrationContract/nls/az/SyncResultsHistory':function(){
define('Sage/MainView/IntegrationContract/nls/az/SyncResultsHistory',{});
},
'Sage/MainView/IntegrationContract/nls/az-az/SyncResultsHistory':function(){
define('Sage/MainView/IntegrationContract/nls/az-az/SyncResultsHistory',{});
},
'Sage/TaskPane/nls/az/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/az/SecuredActionTasklet',{});
},
'Sage/TaskPane/nls/az-az/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/az-az/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/az/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/az/DashboardTabController',{});
},
'Sage/UI/Dashboard/nls/az-az/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/az-az/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/az/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/az/SalesOrderRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/az-az/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/az-az/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/az/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az/UserControlDesigner',{});
},
'Sage/QuickForms/Design/nls/az-az/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az-az/UserControlDesigner',{});
},
'Sage/Groups/nls/az/GroupNavigator':function(){
define('Sage/Groups/nls/az/GroupNavigator',{});
},
'Sage/Groups/nls/az-az/GroupNavigator':function(){
define('Sage/Groups/nls/az-az/GroupNavigator',{});
},
'Sage/Utility/File/nls/az/AddURLAttachment':function(){
define('Sage/Utility/File/nls/az/AddURLAttachment',{});
},
'Sage/Utility/File/nls/az-az/AddURLAttachment':function(){
define('Sage/Utility/File/nls/az-az/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/az/EditFilterItems':function(){
define('Sage/UI/Filters/nls/az/EditFilterItems',{});
},
'Sage/UI/Filters/nls/az-az/EditFilterItems':function(){
define('Sage/UI/Filters/nls/az-az/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/az/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/az/CrystalReportsFormatter',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/az-az/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/az-az/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/az/DragDropWatcher':function(){
define('Sage/Utility/File/nls/az/DragDropWatcher',{});
},
'Sage/Utility/File/nls/az-az/DragDropWatcher':function(){
define('Sage/Utility/File/nls/az-az/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/az/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/az/DesignSurface',{});
},
'Sage/QuickForms/Design/nls/az-az/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/az-az/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/az/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/az/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/az-az/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/az-az/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/az/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/FormAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/az-az/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az-az/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/az/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/az/EventListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/az-az/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/az-az/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/az/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/az/AllOpenListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/az-az/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/az-az/AllOpenListPanelConfig',{});
},
'Sage/MainView/nls/az/FormManager':function(){
define('Sage/MainView/nls/az/FormManager',{});
},
'Sage/MainView/nls/az-az/FormManager':function(){
define('Sage/MainView/nls/az-az/FormManager',{});
},
'Sage/UI/nls/az/ActivityScheduler':function(){
define('Sage/UI/nls/az/ActivityScheduler',{});
},
'Sage/UI/nls/az-az/ActivityScheduler':function(){
define('Sage/UI/nls/az-az/ActivityScheduler',{});
},
'Sage/MainView/nls/az/SecurityManager':function(){
define('Sage/MainView/nls/az/SecurityManager',{});
},
'Sage/MainView/nls/az-az/SecurityManager':function(){
define('Sage/MainView/nls/az-az/SecurityManager',{});
},
'Sage/TaskPane/nls/az/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/az/ActivityTaskConfigurationProvider',{});
},
'Sage/TaskPane/nls/az-az/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/az-az/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/az/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/az/EntityInfoToolTip',{});
},
'Sage/UI/Controls/nls/az-az/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/az-az/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/az/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/az/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/az-az/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/az-az/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/templates/nls/az/AllOpenDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/az/AllOpenDetailSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/az-az/AllOpenDetailSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/az-az/AllOpenDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/az/ReportsListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/az/ReportsListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/az-az/ReportsListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/az-az/ReportsListSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/az/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/az/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/Common/nls/az-az/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/az-az/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/templates/nls/az/ScheduleDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/az/ScheduleDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/az-az/ScheduleDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/az-az/ScheduleDetailSummary',{});
},
'Sage/MainView/Opportunity/nls/az/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/az/UpdateOpportunities',{});
},
'Sage/MainView/Opportunity/nls/az-az/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/az-az/UpdateOpportunities',{});
},
'Sage/UI/nls/az/EditCalendarUsers':function(){
define('Sage/UI/nls/az/EditCalendarUsers',{});
},
'Sage/UI/nls/az-az/EditCalendarUsers':function(){
define('Sage/UI/nls/az-az/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/az/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/az/CrystalReportParametersDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/az-az/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/az-az/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/az/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az/DateTimePickerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/az-az/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az-az/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/az/HelpMenu':function(){
define('Sage/UI/Controls/nls/az/HelpMenu',{});
},
'Sage/UI/Controls/nls/az-az/HelpMenu':function(){
define('Sage/UI/Controls/nls/az-az/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/az/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/LayoutPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/az-az/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az-az/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/az/UserTasklet':function(){
define('Sage/TaskPane/nls/az/UserTasklet',{});
},
'Sage/TaskPane/nls/az-az/UserTasklet':function(){
define('Sage/TaskPane/nls/az-az/UserTasklet',{});
},
'Sage/UI/Alarms/nls/az/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/az/ActivityAlarm',{});
},
'Sage/UI/Alarms/nls/az-az/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/az-az/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/az/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/az/OpportunityStatistics',{});
},
'Sage/MainView/Opportunity/nls/az-az/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/az-az/OpportunityStatistics',{});
},
'Sage/TaskPane/nls/az/GroupListTasklet':function(){
define('Sage/TaskPane/nls/az/GroupListTasklet',{});
},
'Sage/TaskPane/nls/az-az/GroupListTasklet':function(){
define('Sage/TaskPane/nls/az-az/GroupListTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/az/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/az/CrystalReportConditionEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/az-az/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/az-az/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/az/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/az/AdvancedSearchOptions',{});
},
'Sage/MainView/IntegrationContract/nls/az-az/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/az-az/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/az/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/az/ColumnDesigner',{});
},
'Sage/QuickForms/Design/nls/az-az/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/az-az/ColumnDesigner',{});
},
'Sage/MainView/JobMgr/templates/nls/az/JobDefinitionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/az/JobDefinitionDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/az-az/JobDefinitionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/az-az/JobDefinitionDetailSummary',{});
},
'Sage/UI/nls/az/SearchMenuItem':function(){
define('Sage/UI/nls/az/SearchMenuItem',{});
},
'Sage/UI/nls/az-az/SearchMenuItem':function(){
define('Sage/UI/nls/az-az/SearchMenuItem',{});
},
'Sage/Library/nls/az/DocumentProperties':function(){
define('Sage/Library/nls/az/DocumentProperties',{});
},
'Sage/Library/nls/az-az/DocumentProperties':function(){
define('Sage/Library/nls/az-az/DocumentProperties',{});
},
'Sage/UI/nls/az/NotesHistoryList':function(){
define('Sage/UI/nls/az/NotesHistoryList',{});
},
'Sage/UI/nls/az-az/NotesHistoryList':function(){
define('Sage/UI/nls/az-az/NotesHistoryList',{});
},
'Sage/Utility/nls/az/File':function(){
define('Sage/Utility/nls/az/File',{});
},
'Sage/Utility/nls/az-az/File':function(){
define('Sage/Utility/nls/az-az/File',{});
},
'Sage/MainView/ReportMgr/nls/az/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/az/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/az-az/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/az-az/HistoryListPanelConfig',{});
},
'Sage/MainView/JobMgr/templates/nls/az/ScheduleDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/az/ScheduleDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/az-az/ScheduleDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/az-az/ScheduleDetailSummary',{});
},
'Sage/QuickForms/Design/nls/az/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az/UrlControlDesigner',{});
},
'Sage/QuickForms/Design/nls/az-az/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az-az/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/az/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/az/ContactTasksTasklet',{});
},
'Sage/TaskPane/nls/az-az/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/az-az/ContactTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/templates/nls/az/EventSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/az/EventSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/az-az/EventSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/az-az/EventSummary',{});
},
'Sage/MainView/ReportMgr/Common/nls/az/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/az/_WizardDialogBase',{});
},
'Sage/MainView/ReportMgr/Common/nls/az-az/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/az-az/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/az/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/az/SchedulesListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/az-az/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/az-az/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/az/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/az/GoogleDocPicker',{});
},
'Sage/Utility/File/nls/az-az/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/az-az/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/az/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az/ComboBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/az-az/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az-az/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/az/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/az/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/az-az/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/az-az/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/az/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/az/HistoryEditor',{});
},
'Sage/MainView/ActivityMgr/nls/az-az/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/az-az/HistoryEditor',{});
},
'Sage/Groups/nls/az/GroupManager':function(){
define('Sage/Groups/nls/az/GroupManager',{});
},
'Sage/Groups/nls/az-az/GroupManager':function(){
define('Sage/Groups/nls/az-az/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/az/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/az-az/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az-az/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/az/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/ComboBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/az-az/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az-az/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/az/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/az/ReportsListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/az-az/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/az-az/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/az/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/az/JobNotificationButton',{});
},
'Sage/UI/Alarms/nls/az-az/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/az-az/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/az/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/az/CrystalReportWizardController',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/az-az/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/az-az/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/az/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/az/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/az-az/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/az-az/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/az/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/az/RecurringEditor',{});
},
'Sage/MainView/ActivityMgr/nls/az-az/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/az-az/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/az/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/az/CrystalReportsUtility',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/az-az/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/az-az/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/az/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/az-az/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az-az/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/az/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/az/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/az-az/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/az-az/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/az/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/az-az/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az-az/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/az/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/az-az/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az-az/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/az/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/nls/az-az/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az-az/PickListControlDesigner',{});
},
'Sage/MainView/ActivityMgr/templates/nls/az/LitRequestSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/az/LitRequestSummary',{});
},
'Sage/MainView/ActivityMgr/templates/nls/az-az/LitRequestSummary':function(){
define('Sage/MainView/ActivityMgr/templates/nls/az-az/LitRequestSummary',{});
},
'Sage/QuickForms/Design/Editors/nls/az/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/az-az/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az-az/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/az/FolderHandler':function(){
define('Sage/Library/nls/az/FolderHandler',{});
},
'Sage/Library/nls/az-az/FolderHandler':function(){
define('Sage/Library/nls/az-az/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/az/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/az-az/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az-az/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/az/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/az/ContactSearchForDuplicates',{});
},
'Sage/MainView/Contact/nls/az-az/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/az-az/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/az/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/DateTimePickerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/az-az/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az-az/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/az/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/az/AccountingTasksTasklet',{});
},
'Sage/TaskPane/nls/az-az/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/az-az/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/az/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/az-az/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az-az/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/az/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/CurrencyBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/az-az/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az-az/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/az/EditableGrid':function(){
define('Sage/UI/nls/az/EditableGrid',{});
},
'Sage/UI/nls/az-az/EditableGrid':function(){
define('Sage/UI/nls/az-az/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/az/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/az/SalesQuoteRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/az-az/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/az-az/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/az/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/az/SecurityProfile',{});
},
'Sage/MainView/SecurityMgr/nls/az-az/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/az-az/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/az/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/az/ReportWizardController',{});
},
'Sage/MainView/ReportMgr/nls/az-az/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/az-az/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/az/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/UserAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/az-az/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az-az/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/az/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/az/ReportManagerUtility',{});
},
'Sage/MainView/ReportMgr/nls/az-az/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/az-az/ReportManagerUtility',{});
},
'Sage/UI/nls/az/SpeedSearch':function(){
define('Sage/UI/nls/az/SpeedSearch',{});
},
'Sage/UI/nls/az-az/SpeedSearch':function(){
define('Sage/UI/nls/az-az/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/az/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/CurrencyAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/az-az/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az-az/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/az/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/az/ReportManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/az-az/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/az-az/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/az/SLXPreviewGrid':function(){
define('Sage/UI/nls/az/SLXPreviewGrid',{});
},
'Sage/UI/nls/az-az/SLXPreviewGrid':function(){
define('Sage/UI/nls/az-az/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/az/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/az/UnconfirmedPane',{});
},
'Sage/UI/Alarms/nls/az-az/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/az-az/UnconfirmedPane',{});
},
'Sage/Utility/nls/az/Utility':function(){
define('Sage/Utility/nls/az/Utility',{});
},
'Sage/Utility/nls/az-az/Utility':function(){
define('Sage/Utility/nls/az-az/Utility',{});
},
'Sage/QuickForms/Design/nls/az/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az/ControlDesigner',{});
},
'Sage/QuickForms/Design/nls/az-az/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az-az/ControlDesigner',{});
},
'Sage/UI/Controls/nls/az/Address':function(){
define('Sage/UI/Controls/nls/az/Address',{});
},
'Sage/UI/Controls/nls/az-az/Address':function(){
define('Sage/UI/Controls/nls/az-az/Address',{});
},
'Sage/MainView/JobMgr/nls/az/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/az/JobManagerGroupContextService',{});
},
'Sage/MainView/JobMgr/nls/az-az/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/az-az/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/az/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/az/BaseListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/az-az/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/az-az/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/az/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az/OwnerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/az-az/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az-az/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/az/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/az/JobManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/az-az/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/az-az/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/az/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/az/ActivityEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/az-az/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/az-az/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/az/UserType':function(){
define('Sage/UI/nls/az/UserType',{});
},
'Sage/UI/nls/az-az/UserType':function(){
define('Sage/UI/nls/az-az/UserType',{});
},
'Sage/MainView/ReportMgr/templates/nls/az/HistoryDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/az/HistoryDetailSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/az-az/HistoryDetailSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/az-az/HistoryDetailSummary',{});
},
'Sage/QuickForms/Design/nls/az/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/az/FormDesigner',{});
},
'Sage/QuickForms/Design/nls/az-az/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/az-az/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/az/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/az/ActivityCalendar',{});
},
'Sage/MainView/ActivityMgr/nls/az-az/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/az-az/ActivityCalendar',{});
},
'Sage/Utility/nls/az/Jobs':function(){
define('Sage/Utility/nls/az/Jobs',{});
},
'Sage/Utility/nls/az-az/Jobs':function(){
define('Sage/Utility/nls/az-az/Jobs',{});
},
'Sage/UI/Controls/nls/az/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/az/_DialogHelpIconMixin',{});
},
'Sage/UI/Controls/nls/az-az/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/az-az/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/az/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/PickListAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/az-az/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az-az/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/az/ActivityList':function(){
define('Sage/UI/nls/az/ActivityList',{});
},
'Sage/UI/nls/az-az/ActivityList':function(){
define('Sage/UI/nls/az-az/ActivityList',{});
},
'Sage/UI/Alarms/nls/az/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/az/JobNotificationPopup',{});
},
'Sage/UI/Alarms/nls/az-az/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/az-az/JobNotificationPopup',{});
},
'Sage/MainView/JobMgr/templates/nls/az/ExecutionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/az/ExecutionsListSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/az-az/ExecutionsListSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/az-az/ExecutionsListSummary',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/az/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/az/LeadLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/az-az/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/az-az/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/az/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/az/SchedulesListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/az-az/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/az-az/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/az/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/GenericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/az-az/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az-az/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/az/CalendarUsersListPane':function(){
define('Sage/UI/nls/az/CalendarUsersListPane',{});
},
'Sage/UI/nls/az-az/CalendarUsersListPane':function(){
define('Sage/UI/nls/az-az/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/az/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/az-az/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az-az/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/az/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/ColumnBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/az-az/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az-az/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/templates/nls/az/ExecutionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/az/ExecutionDetailSummary',{});
},
'Sage/MainView/JobMgr/templates/nls/az-az/ExecutionDetailSummary':function(){
define('Sage/MainView/JobMgr/templates/nls/az-az/ExecutionDetailSummary',{});
},
'Sage/MainView/ReportMgr/nls/az/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/az/ReportManagerGroupContextService',{});
},
'Sage/MainView/ReportMgr/nls/az-az/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/az-az/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/az/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/az/MatchingOptionsConfig',{});
},
'Sage/MainView/IntegrationContract/nls/az-az/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/az-az/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/az/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/FormBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/az-az/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az-az/FormBasicPropertyEditor',{});
},
'Sage/UI/Alarms/nls/az/AlarmButton':function(){
define('Sage/UI/Alarms/nls/az/AlarmButton',{});
},
'Sage/UI/Alarms/nls/az-az/AlarmButton':function(){
define('Sage/UI/Alarms/nls/az-az/AlarmButton',{});
},
'Sage/MainView/ActivityMgr/nls/az/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/az/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/MainView/ActivityMgr/nls/az-az/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/az-az/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/az/Attachment':function(){
define('Sage/Utility/File/nls/az/Attachment',{});
},
'Sage/Utility/File/nls/az-az/Attachment':function(){
define('Sage/Utility/File/nls/az-az/Attachment',{});
},
'Sage/QuickForms/Design/nls/az/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/az-az/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az-az/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/az/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/az/PropertyEditorContainer',{});
},
'Sage/QuickForms/Design/nls/az-az/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/az-az/PropertyEditorContainer',{});
},
'Sage/Services/nls/az/ReportingService':function(){
define('Sage/Services/nls/az/ReportingService',{});
},
'Sage/Services/nls/az-az/ReportingService':function(){
define('Sage/Services/nls/az-az/ReportingService',{});
},
'Sage/MailMerge/nls/az/Helper':function(){
define('Sage/MailMerge/nls/az/Helper',{});
},
'Sage/MailMerge/nls/az-az/Helper':function(){
define('Sage/MailMerge/nls/az-az/Helper',{});
},
'Sage/UI/Dashboard/nls/az/Dashboard':function(){
define('Sage/UI/Dashboard/nls/az/Dashboard',{});
},
'Sage/UI/Dashboard/nls/az-az/Dashboard':function(){
define('Sage/UI/Dashboard/nls/az-az/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/az/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/az/ActivityListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/az-az/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/az-az/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/az/PickList':function(){
define('Sage/UI/Controls/nls/az/PickList',{});
},
'Sage/UI/Controls/nls/az-az/PickList':function(){
define('Sage/UI/Controls/nls/az-az/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/az/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/az/HistoryEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/az-az/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/az-az/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/az/Email':function(){
define('Sage/Utility/nls/az/Email',{});
},
'Sage/Utility/nls/az-az/Email':function(){
define('Sage/Utility/nls/az-az/Email',{});
},
'Sage/TaskPane/nls/az/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/az/SecurityManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/az-az/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/az-az/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/az/TimeZoneItem':function(){
define('Sage/UI/nls/az/TimeZoneItem',{});
},
'Sage/UI/nls/az-az/TimeZoneItem':function(){
define('Sage/UI/nls/az-az/TimeZoneItem',{});
},
'Sage/MainView/ReportMgr/templates/nls/az/HistoryListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/az/HistoryListSummary',{});
},
'Sage/MainView/ReportMgr/templates/nls/az-az/HistoryListSummary':function(){
define('Sage/MainView/ReportMgr/templates/nls/az-az/HistoryListSummary',{});
},
'Sage/UI/Columns/nls/az/SlxEdit':function(){
define('Sage/UI/Columns/nls/az/SlxEdit',{});
},
'Sage/UI/Columns/nls/az-az/SlxEdit':function(){
define('Sage/UI/Columns/nls/az-az/SlxEdit',{});
},
'Sage/Reporting/nls/az/Enumerations':function(){
define('Sage/Reporting/nls/az/Enumerations',{});
},
'Sage/Reporting/nls/az-az/Enumerations':function(){
define('Sage/Reporting/nls/az-az/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/az/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/az-az/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az-az/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/az/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/az/CrystalReportConditionsDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/az-az/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/az-az/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/az/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/az/ActivityListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/az-az/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/az-az/ActivityListPanelConfig',{});
},
'Sage/UI/nls/az/JobSchedulingWidget':function(){
define('Sage/UI/nls/az/JobSchedulingWidget',{});
},
'Sage/UI/nls/az-az/JobSchedulingWidget':function(){
define('Sage/UI/nls/az-az/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/az/LogOffButton':function(){
define('Sage/UI/Controls/nls/az/LogOffButton',{});
},
'Sage/UI/Controls/nls/az-az/LogOffButton':function(){
define('Sage/UI/Controls/nls/az-az/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/az/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/TextBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/az-az/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az-az/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/az/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/az/EditEventEditor',{});
},
'Sage/MainView/ActivityMgr/nls/az-az/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/az-az/EditEventEditor',{});
},
'Sage/MailMerge/nls/az/Loader':function(){
define('Sage/MailMerge/nls/az/Loader',{});
},
'Sage/MailMerge/nls/az-az/Loader':function(){
define('Sage/MailMerge/nls/az-az/Loader',{});
},
'Sage/UI/Controls/nls/az/DateTimePicker':function(){
define('Sage/UI/Controls/nls/az/DateTimePicker',{});
},
'Sage/UI/Controls/nls/az-az/DateTimePicker':function(){
define('Sage/UI/Controls/nls/az-az/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/az/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/az/ReportManagerActions',{});
},
'Sage/MainView/ReportMgr/nls/az-az/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/az-az/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/az/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/az/AlarmPopup',{});
},
'Sage/UI/Alarms/nls/az-az/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/az-az/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/az/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/az/ContactUserAssociationEditor',{});
},
'Sage/MainView/Contact/nls/az-az/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/az-az/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/az/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/az-az/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az-az/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/az/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/az/BaseListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/az-az/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/az-az/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/az/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/az-az/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az-az/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/az/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az/EmailControlDesigner',{});
},
'Sage/QuickForms/Design/nls/az-az/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az-az/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/az/Lookup':function(){
define('Sage/UI/Controls/nls/az/Lookup',{});
},
'Sage/UI/Controls/nls/az-az/Lookup':function(){
define('Sage/UI/Controls/nls/az-az/Lookup',{});
},
'Sage/Utility/File/nls/az/DescriptionsForm':function(){
define('Sage/Utility/File/nls/az/DescriptionsForm',{});
},
'Sage/Utility/File/nls/az-az/DescriptionsForm':function(){
define('Sage/Utility/File/nls/az-az/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/az/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/NumericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/az-az/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az-az/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/az/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/az/CommonTasksTasklet',{});
},
'Sage/TaskPane/nls/az-az/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/az-az/CommonTasksTasklet',{});
},
'Sage/Utility/nls/az/Dashboard':function(){
define('Sage/Utility/nls/az/Dashboard',{});
},
'Sage/Utility/nls/az-az/Dashboard':function(){
define('Sage/Utility/nls/az-az/Dashboard',{});
}}});
define("Sage/nls/Sage_az-az", [], 1);
